[General]
UnitType=LandUnit
LandUnitSubType=MobileUnit

DefaultCameraDistance=1.5
MinCameraDistanceForeAft=0.4
MinCameraDistanceBroadside=0.4
CameraPivotHeight=0.03

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

Length=9.0                     // in meters
Beam=3.37                       // in meters
Range=202                      // in miles

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Moderate
DamagePoints=11  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Physics]
HorsePower=780
Mass=36.2                      // in tons

MaxForwardVelocity=32.4        // in knots
MaxBackwardVelocity=2.7        // in knots
Braking=10                     // knots/sec
TurnRate=20                    // in degrees per second

[AI]

MissilesToSaturate=1

UnitScoreValue=1              // value for calculation of mission score
Role=Gun

[ControlSystem]
Collider=coll_hitbox  // makes unit destroyable
Integrity=12

[SensorData]
#Visual
VisualIdentificationRange=2.5  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=3
#---------- Visual ----------
[SensorSystem1] #AdvancedOptics
Type=Visual
SystemName=AdvancedOptics
MountPosition=0,0.03,0

[SensorSystem2] #IRSight
Type=Infrared
SystemName=IRSight
MountPosition=0,0.03,0

[SensorSystem3] #APS Radar
Type=Radar
SystemName=Drozd_Radar
Mount=Dummy
ModuleType=Sensor


[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=6

[WeaponSystem1]  #100mm_D-10
Type=Gun
SystemName=100mm_D-10	//2A46
#Sensors
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
ContainerBase=Gun
NumberOfGuns=1
Gun1=Barrel
AreContainersRotatable=True
#Angles
ElevationArc=-4,18
RestAngles=0
EngageOnlyInsideArc=True
#Loading
AssociatedMagazine=WeaponMagazineGun
#Effects
#Other
MaxReactiontime=2.5
MaxVelocityToFire=5
VIDIncrease=5  // In miles. Flat base VID increace when firing.
SharesMountWith=WeaponSystem3

[WeaponSystem2]  #Dshk
Type=CIWS
SystemName=Dshk
#Sensors
#Animations
#Mount
Mount=Turret2
IsMountRotatable=True
#Containers
ContainerBase=gun
Gun=gun
AreContainersRotatable=True
#Angles
ElevationArc=-5,75
RestAngles=0,-20
#Loading
AssociatedMagazine=WeaponMagazineDshk
#Effects
#Other
MaxReactiontime=2.5
MaxVelocityToFire=50
WorksStandalone=True
VIDIncrease=2.5  // In miles. Flat base VID increace when firing.
TargetAcquisitionTime=0.7

#[WeaponSystem3]  #APS Left Down
#Type=CIWS
#SystemName=Drozd
#Sensors
#Animations
#Mount
#Mount=aps_left_down
#IsMountRotatable=True
#Containers
#ContainerBase=aps_left_gun
#Gun=aps_left_gun
#AreContainersRotatable=True
#Angles
#FiringArcs=-40,10
#ElevationArc=-6,20
#Loading
#AssociatedMagazine=WeaponMagazineDrozd
#Effects
#Other
#MaxVelocityToFire=50
#WorksStandalone=True
#VIDIncrease=3  // In miles. Flat base VID increace when firing.

#[WeaponSystem4]  #APS Right Down
#Type=CIWS
#SystemName=Drozd
#Sensors
#Animations
#Mount
#Mount=aps_right_down
#IsMountRotatable=True
#Containers
#ContainerBase=aps_right_gun
#Gun=aps_right_gun
#AreContainersRotatable=True
#Angles
#FiringArcs=-40,10
#ElevationArc=-6,20
#Loading
#AssociatedMagazine=WeaponMagazineDrozd
#Effects
#Other
#MaxVelocityToFire=50
#WorksStandalone=True
#VIDIncrease=3  // In miles. Flat base VID increace when firing.

[WeaponSystem3]  
Type=Missile
SystemName=D-10T_9M117
#Sensors
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
ContainerBase=Gun
NumberOfContainers=1
Container1=Gun
AreContainersRotatable=True
#Angles
FixVerticalLaunchAngle=5
ElevationArc=-4,15              // Min,Max
RestAngles=0                   //Horizontal, Vertical   or  Horizontal only definitions
#Loading
Ammunition=wp_9m117
#AssociatedMagazine=WeaponMagazine9M117
#PreloadAmmunition=True           // REQUIRED!!! for non-unloading launchers with magazine, like MK29 and ASROC
#Effects
#Other
MaxReactiontime=2.5
MaxVelocityToFire=3
SharesMountWith=WeaponSystem1
VIDIncrease=6  // In miles. Flat base VID increace when firing.

[WeaponSystem4] #Chaff
Type=Chaff
SystemName=Smoke
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=0,0,0.4
#Containers
ContainerBase=Dummy
#Angles
#Loading
Ammunition=wp_aircraft_chaff
#Effects
NumberOfEffects=2
DelayBetweenLaunches=0.1
EffectOffset=0,0,30
#Other
MaxReactiontime=2.5
WorksStandalone=True

[---------- WeaponMagazines ----------]
[WeaponMagazineGun]
NumberOfAmmunitionTypes=2
Ammunition1=wp_cal_3bm25
Ammunition1_Count=25
Ammunition1=wp_cal_of412
Ammunition1_Count=10

[WeaponMagazineDshk]
NumberOfAmmunitionTypes=1
Ammunition1=wp_cal_12.7mm
Ammunition1_Count=450
ModuleType=SmallMagazine

[WeaponMagazine9M117]
NumberOfAmmunitionTypes=1
Ammunition1=wp_9m117
Ammunition1_Count=2

#[WeaponMagazineDrozd]
#NumberOfAmmunitionTypes=1
#Ammunition1=wp_aps_drozd
#Ammunition1_Count=600
#ModuleType=SmallMagazine

[Models]
############################################################
# Internal Resources folder related
############################################################

ResourcesFolder=assets/models/land_units/t55amd-1/
ResourcesRoot=t55amd-1.obj
ResourcesMesh=wp_t-55amd-1_hull
ResourcesMaterialFolder=ground objects/wp_t-55/
ResourcesMaterial=wp_t-55_mat
############################################################

[Submodels]
Turret=Turret
Gun=Gun
Barrel=Barrel
Turret2=Turret2
Gun2=gun
Submodel1=aps_radar
#Submodel2=aps_right_down
#Submodel3=aps_right_gun
#Submodel4=aps_left_down
#Submodel5=aps_left_gun
Submodel2=APS


[Turret]
Mesh=wp_t-55_turret
ResourcesMaterialFolder=ground objects/wp_t-55/
Material=wp_t-55_mat
Position=0,0.0203,-0.0029

[Gun]
Mesh=wp_t-55_gun
ResourcesMaterialFolder=ground objects/wp_t-55/
Material=wp_t-55_mat
Parent=Turret
Position=0,0.0034,0.0131

[Barrel]
Mesh=wp_t-55_barrel
ResourcesMaterialFolder=ground objects/wp_t-55/
Material=wp_t-55_mat
Parent=Gun
Position=0,0,0

[Turret2]
Mesh=wp_t-55_turret2
ResourcesMaterialFolder=ground objects/wp_t-55/
Material=wp_t-55_mat
Parent=Turret
Position=0.006197,0.009577,-0.004968

[gun]
Mesh=wp_t72_dshk_gun
ResourcesMaterialFolder=ground objects/wp_t-55/
Material=wp_t-55_mat
Parent=Turret2
Position=0,0.000779,0.005863

[aps_radar]
Mesh=aps_radar
ResourcesMaterialFolder=ground objects/wp_t-55/
Material=wp_t-55_mat
Parent=Turret
Position=0,0.00013,-0.00011

#[aps_right_down]
Mesh=aps_right_down
ResourcesMaterialFolder=ground objects/wp_t-55/
Material=wp_t-55_mat
Parent=Turret
Position=0.019373,0.00392,-0.000728

#[aps_right_gun]
Mesh=aps_right_gun
ResourcesMaterialFolder=ground objects/wp_t-55/
Material=wp_t-55_mat
Parent=aps_right_down
Position=0,0,0
Rotation=0,0,0

#[aps_left_down]
Mesh=aps_left_down
ResourcesMaterialFolder=ground objects/wp_t-55/
Material=wp_t-55_mat
Parent=Turret
Position=-0.019373,0.00392,-0.000728

#[aps_left_gun]
Mesh=aps_left_gun
ResourcesMaterialFolder=ground objects/wp_t-55/
Material=wp_t-55_mat
Parent=aps_left_down
Position=0,0,0
Rotation=0,0,0

[APS]
Mesh=wp_t-55_aps
ResourcesMaterialFolder=ground objects/wp_t-55/
Material=wp_t-55_mat
Parent=Turret
Position=0,0,0

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Small
AmbientAudioPosition=0,0,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

DustEffect=effects/land units/emitters/vehicle_movement_dust
DustEffectPosition=0,0,0

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=2

Collider1=coll_hitbox
Collider2=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.0152,-0.01
Rotation=0,0,0
Scale=0.045,0.03,0.09

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default
