#!alias ammunition/usn_rim-66e.ini
# ver. 20260906
#
[General]
# SM-1MR Block VIB (1987) - Versión para la Armada Española - F80s

Type=Missile							// Can be Projectile, Missile, Torpedo
TargetType=AAW							// Can be AAW, ASuW, ASW
SecondaryTargetType=ASuW
LandAttackCapability=ShoreTargetsOnly	// Can be  All, Installation, Mobile, ShoreTargetsOnly

AmmoPoints=1705							// For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

#Determines if this weapon has "early service" with low availability, must be earlier than 'FOCDate' and is usually the first production year (LRIP) or first year this weapon was deployed in service, specify ONLY this date in the case of prototype systems that never became fully operable
IOCDate=1991							// Year, shows in Unit Reference. If set, defines if the weapon is able to be used in combat before it is fully operational (before FOCDate)

#Specifies the first year this weapon is widely deployed, and when it becomes fully operational without serious availability/operability concerns
FOCDate=1993							// Year, shows in Unit Reference, defines first year this weapon is commonly available to be selected. Default/unset: always available

FrontalArea=0.1031
SideArea=1.67
BottomArea=1.67

[WarheadData]
WarheadType=0							// Blast Fragmentation
Power=32

FuzeProximityDistance=10.0				// For proximity fuze: distance to target in meter. Also indicates that Fuze Type = Proximity Fuze
KillProbability=0.85					// Base chance to hit0
InterceptOutOfAltitudePenalty=0.28		// Base value used for out-of-altitude calculations, 0.20 is excellent, 0.30 is good, 0.40 is average, 0.50 is poor

[Guidance]
MinAttackAltitude=10					// Minimum altitude of a target, in feet. Outside Min/Max altitude missile deviation is greatly increaced

#ECCM
AntiJammerBonus=0.3						// This value substracted from probability of being jammed  (0...1)
