#!extend language_en/ammunition_names.ini, language_de/ammunition_names.ini, language_cn/ammunition_names.ini

# Alternative names used when "Use native weapon names" is enabled.
[AmmunitionNames_Native]
wp_ss-n-26=P-800,Oniks
wp_ss-n-26a=P-800,Oniks
rfn_3m55=P-800,Oniks
wp_ss-n-26b=P-800,Oniks-M
