[AmmunitionNames]
wp_40h6e=40H6E

wp_9m39=9M39

wp_48n6e2=48N6E2

wp_tochka=9M123F Missile

wp_3bv3=3BV3

wp_3m-25=3M-25 Meteorite

wp_r-500=9M278

wp_9k720_he=9K720 HE 

wp_9k720_clu=9K720 CLU

wp_9k720_nuke=9K720 NUKE

wp_5v55r=5V55R

wp_ss-n-25=KH-35

wp_rs26=RS-26

wp_r-29rmu=R-29RMU

rfn_3m24ud=KH-35
rfn_9m311m=9M311M
rfn_cal_30mm=30MM

###############FLANKER####################
su_r27r=R-27R,,AAM,,The Vympel R-27R (AA-10A Alamo) is a Soviet semi-active radar-guided medium-range air-to-air missile that innovatively uses an inverted trapezoidal wing to enhance the missile's maneuverability.
su_r27t=R-27T,,AAM,,The Vympel R-27T (AA-10B Alamo) is a Soviet semi-active radar-guided medium-range air-to-air missile with an infrared seeker and a shorter range than the R-27R.
su_r27er=R-27ER,,AAM,,The Vympel R-27ER (AA-10C Alamo) is a Soviet semi-active radar-guided medium-range air-to-air missile. It is an improved version of the R-27R, which has been extended to increase the range of the missile.
su_r-27et=R-27ET,,AAM,,The Vympel R-27ET (AA-10D Alamo) is a Soviet semi-active radar-guided medium-range air-to-air missile with an infrared seeker and a shorter range than the R-27ER.
su_r77=R-77,,AAM,The Vympel R-77（AA-12 Adder）It is Russia's active radar-guided medium-range air-to-air missile. The research and development work began in the Soviet era, but it was not completed until after the disintegration of the Soviet Union. The missile uses a unique grid-wing aerodynamic layout, which brings excellent high-speed performance to the missile, but also increases the resistance at low speed.
su_r-77-1=R-77-1,,AAM,The Vympel R-77-1（AA-12 Adder）It is Russia's active radar-guided medium-range air-to-air missile, an improvement on the R-77 with a longer range.
su_r-77m=R-77M,,AAM,The Vympel R-77M（AA-12 Adder）It is Russia's active radar-guided long-range air-to-air missile,This missile employs a more powerful active phased array seeker and a dual-pulse engine, resulting in a significant performance improvement.
su_r37=R-37M,,AAM,The Vympel R-37M（AA-13 Axehead）It is Russia's active radar-guided ultra-long-range air-to-air missile with high speed and long range, and is used to perform interception missions.
su_kh31a=KH-31A,,ASM,Tactical Missiles Corporation Kh-31A（AS-17 Krypton）It is a Soviet supersonic anti-radiation missile, similar to the P-270 in many aspects. It looks like a smaller version of the P-270. There are reportedly plans to convert it into a long-range air-to-air missile.
su_kab-1500kr=KAB-1500KR,,AGM,Tactical Missiles Corporation KAB-1500KR is a Russian TV-guided bomb, similar to the American GBU-8/15 guided bomb, but the KAB-1500KR has better performance.
su_kh31p=KH-31P,,ARM,Tactical Missiles Corporation Kh-31P（AS-17 Krypton）It is a Soviet supersonic anti-radiation missile, similar to the P-270 in many aspects. It looks like a smaller version of the P-270. There are reportedly plans to convert it into a long-range air-to-air missile.
su_kh35=Kh-35,,AGM,Zvezda Kh-35 (AS-20 Kayak) It is a Russian subsonic anti-ship missile. Because its appearance and performance are similar to those of the American Harpoon missile, it is nicknamed "Harpoonski". It is designed to attack ships under 5,000 tons.It can also be used to attack ground targets.
su_l004=L-004,,ECM Pod,
#####################################
wp_p-1000=P-1000