########S-400########
[wp_mzkt_bigbird]
Type=S-400 SYSTEM
Default=91N6E Big Bird,91N6E Big Bird
Variant1=91N6E Big Bird,91N6E Big Bird
DefaultDescription=Russian long range early warning radar for S-300/S-400 complex.

[wp_baz_tel]
Type=S-400 SYSTEM
Default=5P90S TEL,5P90S TEL
Variant1=5P90S TEL,5P90S TEL
DefaultDescription=TEL for S-400 complex with data link ability(10nm range from FCR radar).

[wp_mzkt_96l6]
Type=S-400 SYSTEM
Default=96L6E,96L6E
Variant1=96L6E,96L6E
DefaultDescription=Battery aqusition radar for S-400 complex

[wp_mzkt_gravestone]
Type=S-400 SYSTEM
Default=92N6E Grave Stone,92N6E Grave Stone
Variant1=92N6E Grave Stone,92N6E Grave Stone
DefaultDescription=FCR radar for S-400 complex

[wp_5p85te2_s400]
Type=S-400 SYSTEM
Default=5P85TE2 S-400,5P85TE2 S-400
Variant1=5P85TE2 S-400,5P85TE2 S-400
DefaultDescription=TEL for S-400 complex without datalink ability (0.5nm range from FCR radar).
######S-300################
[wp_big_bird]
Type=S-300PM/U2 BATTERY
Default=64N6E Big Bird,64N6E Big Bird
Variant1=64N6E Big Bird,64N6E Big Bird
DefaultDescription=Russian long range early warning radar for S-300/S-400 complex.

[wp_kraz_tel]
Type=S-300PM/U2 BATTERY
Default=5P85TE TEL,5P85TE TEL
Variant1=5P85TE TEL,5P85TE TEL
DefaultDescription=TEL for S-300PMU2 based on KRAZ heavy duty truck.

[wp_5p85te2]
Type=S-300PM/U2 BATTERY
Default=5P85TE2 TEL(S-300),5P85TE2 TEL(S-300) 
Variant1=5P85TE2 TEL(S-300),5P85TE2 TEL(S-300)
DefaultDescription=TEL for S-300 complex without datalink ability (0.5nm range from FCR radar).

[wp_96l6e]
Type=S-300PM/U2 BATTERY
Default=96L6E,96L6E
Variant1=96L6E,96L6E
DefaultDescription=Battery aqusition radar for S-300 complex

[wp_tombstone]
Type=S-300PM/U2 BATTERY
Default=30N6E2 Tomb Stone,30N6E2 Tomb Stone
Variant1=30N6E2 Tomb Stone,30N6E2 Tomb Stone
DefaultDescription=FCR radar for S-300PMU2

####IGLA####
[wp_9k38_launcher]
Type=MANPADS
Default=9K38 Igla,9K38 Igla
Variant1=9K38 Igla,9K38 Igla
DefaultDescription=Soviet MANPADS with all aspect capabilities introduced in 1981.
#########TOCHKA###
[wp_tochka]
Type=SRBM
Default=OTR-21«Точка»,SRBM
Variant1=OTR-21«Точка»,SRBM
DefaultDescription=Soviet SRBM introduced in 1976 as succesor to scud missile system can carry variety of warheads.
######D-20###########
[wp_d-20]
Type=D-20
Default=D-20,D-20
Variant1=D-20,D-20
DefaultDescription=The 152 mm gun-howitzer M1955, also known as the D-20, (Russian: 152-мм пушка-гаубица Д-20 обр. 1955 г.) is a manually loaded, towed 152 mm gun-howitzer artillery piece, manufactured in the Soviet Union during the 1950s. It was first observed by the West in 1955, at which time it was designated the M1955.
#########ISKANDER-K##########
[wp_iskander]
Type=GLCM
Default=ИСКАНДЕР-К,Iskander Complex
Variant1=ИСКАНДЕР-К,Iskander Complex
DefaultDescription=Cruise missiles variant of Iskander SRBM, with 500km range and decoys.
##########R-330 EW##########
[wp_r-330zh]
Type=EW
Default=R-330ZH,R-330ZH
Variant1=R-330ZH,R-330ZH
DefaultDescription=Soviet/Russian Electronic warfare vehicle capable of jamming GPS and radio signals.
#########SATCOM########
[wp_sattelite_center]
Type=Installation
Default=SATCOM,SATCOM
Variant1=SATCOM,SATCOM
DefaultDescription=Military center of sattelite communication.
#########ISKANDER############
[wp_iskander_m]
Type=ISKANDER SRBM 
Default=ИСКАНДЕР-M,ISKANDER SRBM
Variant1=ИСКАНДЕР-M,ISKANDER SRBM
DefaultDescription=First Russian ballistic missile made after fall of soviet union, with range of 500km and decoys.

[wp_iskander_m_clu]
Type=ISKANDER SRBM
Default=ИСКАНДЕР-M CLU,ISKANDER SRBM
Variant1=ИСКАНДЕР-M CLU,ISKANDER SRBM
DefaultDescription=First Russian ballistic missile made after fall of soviet union, with range of 500km and decoys.

[wp_iskander_m_nuke]
Type=ISKANDER SRBM 
Default=ИСКАНДЕР-M NUKE,ISKANDER SRBM
Variant1=ИСКАНДЕР-M NUKE,ISKANDER SRBM
DefaultDescription=First Russian ballistic missile made after fall of soviet union, with range of 500km and decoys.

#############NEWA##############
[wp_newa]
Type=NEWA-SC
Default=NEWA-SC,NEWA-SC
Variant1=NEWA-SC,NEWA-SC
DefaultDescription=In 2001, Poland began offering an upgrade to the S-125 known as the Newa SC. This replaced many analogue components with digital ones for improved reliability and accuracy. This upgrade also involves mounting the missile launcher on a WZT-1 tank chassis (a TEL), greatly improving mobility and also adds IFF capability and data links. Radar is mounted on an 8-wheeled heavy truck chassis (formerly used for Scud launchers).

[wp_newa_fcr]
Type=NEWA-SC
Default=NEWA-SC FCR,NEWA-SC FCR
Variant1=NEWA-SC FCR,NEWA-SC FCR
DefaultDescription=In 2001, Poland began offering an upgrade to the S-125 known as the Newa SC. This replaced many analogue components with digital ones for improved reliability and accuracy. This upgrade also involves mounting the missile launcher on a WZT-1 tank chassis (a TEL), greatly improving mobility and also adds IFF capability and data links. Radar is mounted on an 8-wheeled heavy truck chassis (formerly used for Scud launchers).
#####################S-300SITE######
[wp_sam_site_s-300ps]
Type=S-300PS SITE
Default=S-300PS SITE,S-300PS SITE
Variant1=S-300PS SITE,S-300PS SITE
DefaultDescription=Reworked S-300 site with its dedicated radars and fixed flaplid radar.
###########KRASHUKHA-2####################
[wp_1l269_kra]
Type=EW
Default=1L269 Krasukha-2,1L269 Krasukha-2
Variant1=1L269 Krasukha-2,1L269 Krasukha-2
DefaultDescription=The Krasukha (Russian: Красуха English: Belladonna or Deadly Nightshade) is a Russian mobile, ground-based, electronic warfare (EW) system. This system is produced by the KRET corporation on different wheeled platforms.The Krasukha's primary targets are airborne radio-electronics (such as UAVs) and airborne systems guided by radar. The Krasukha has multiple applications in the Russian Armed Forces,has been deployed beyond Russian borders, and supplied to additional armed forces, such as those of Iran.
###########RS26#####################
[wp_rs26]
Type=IRBM
Default=RS-26,RS-26
Variant1=RS-26,RS-26
DefaultDescription=RS-26 new Russian ballistic missile used in combat in Ukraine.
############S-500#################
[wp_s-500tel]
Type=ABM
Default=S-500,S-500
Variant1=S-500,S-500
DefaultDescription=
#########3K60#############
[wp_3k60]
Type=ASM Launcher 
Default=3K60 Bal,3K60 Bal
Variant1=3K60 Bal,3K60 Bal
DefaultDescription=3K60 Bal