#[wp_ssn_sierra1]
Type=SSN,Attack Submarine
Default=Sierra Class,Sierra
DefaultDescription=The project 947 Akula is a class of submarines built from 1984 to 1991 by the Soviet Union and Russia. It was smaller and cheaper than the Victor-IIIK, sacrificing 650mm capability. It incorporated various quieting improvements and the MGK-540 sonar. Its purpose was initially limited to ASW patrols, however despite lack of heavy torpedoes it often replaced the Victor in its mission
Variant1=K-284 Akula,Akula
Variant2=K-263 Barnaul,Barnaul
Variant3=K-480 Ak Bars,Ak Bars
Variant4=K-322 Kashalot,Kashalot
Variant5=K-391 Bratsk,Bratsk
Variant6=K-317 Pantera,Pantera
Variant7=K-461 Volk,Volk
Variant8=K-328 Leopard,Leopard
Variant9=K-154 Tigr,Tigr

[wp_ss_kilo_877v]
Type=SS,Patrol Submarine
Default=Kilo 877V-class,Kilo 877V
DefaultDescription=Water pump jet variant of standard kilo,modernized in 90s projekt 877V
Variant1=B-871 Alrosa,Alrosa

[wp_projekt61m]
Type=BPK,Destroyer
Default=Projekt 01090-Class,Smetlivy
DefaultDescription=Ordered by the Soviet Union in the early 1960s, Smetlivy was laid down in July 1966 and commissioned into the Soviet Black Sea Fleet in 1969. In 1990 the ship was laid up for repairs and modification. She became part of the Russian Navy after the collapse of the Soviet Union in 1991. The ship returned to service in 1995, now armed with the more modern SS-N-25 Switchblade missile system.
Variant1=Smetlivy,Smetlivy

[wp_provorny]
Type=BPK,Destroyer
Default=Projekt 61E-class,Provoryn
DefaultDescription=Modified Kashin class destroyer with SA-N-1 launchers replaced by SA-N-7, and MR-500 radar.
Variant1=Provoryn,Provoryn

[wp_bpk_karaL]
Type=BPK,Missile Cruiser
Default=Kara-class,Kerch
DefaultDescription=Known in Russian as the Golden Eagle (Project 1134B) the Kara-class focus on anti-submarine warfare, though they also have heavy air-defences. The basic hull is a development of the Kresta II-class but introduces gas turbine engines.
Variant1=Kerch BPK-708,Kerch

[wp_rkr_slavaLU]
Type=RKR,Missile Cruiser
Default=Projekt 1164 Atlant(Late),Projekt 1164
DefaultDescription=Modernized Slava Class cruiser with new radar suit and improved sonar and sattelite systems. 
Variant1=Marshal Ustinov RKR-088,Ustinov

[wp_rkr_slavaLV]
Type=RKR,Missile Cruiser
Default=Projekt 1164 Atlant(Late),Projekt 1164
DefaultDescription=Modernized Slava Class cruiser with Top Plate radar.
Variant1=Varyag RKR-011,Varyag 

[wp_ssbn_delta4]
Type=SSBN,Ballistic Missile Submarine
Default=Project 667BDRM Class,Delta IV
DefaultDescription=Seven Project 667BDRM Delfin/Delta IV-class submarines were built, which were yet another iterative improvement of the Delta-class. All were retained and operated by the Russian Navy. The submarines, based at the Sayda Guba Naval Base, operate in the Northern Fleet. The Severodvinsk Shipyard built these vessels between 1981 and 1992. The last vessel completed was K-407 Novomoskovsk. 
Variant1=K-51
Variant2=K-84
Variant3=K-114
Variant4=K-117
Variant5=K-18
Variant6=K-407

[wp_ptg_tarantul_r71]
#aka Tarantul IV
Type=PTG,Missile Boat
Default=Projekt 12417 Molniya,Molniya
DefaultDescription=This corvette was built specifically for testing a 3M87 Kortik gun-and-missiles module.Missile Corvette R-71 laid down 12 August 1981 at the Sredne-Nevskiy Shipyard, Pontonny (yard No.201), launched 14 September 1983, commissioned 10 June 1985. 
Variant1=R-71

[wp_ptg_tarantul_r60]
#aka Tarantul IV
Type=PTG,Missile Boat
Default=Projekt 12411 Molniya,Molniya
DefaultDescription=Missile Corvette R-60 laid down 10 December 1985 at the Sredne-Nevskiy Shipyard, Pontonny (yard No.207), launched 30 December 1986, commissioned 12 December 1987.Missile Corvette R-60 was further modernized in 2005, having the 2 AK-630M CIWS removed, and replaced with Palash CIWS.
Variant1=R-60

[wp_mrk_nanuchka_3]
Type=MRK,Missile Boat
Default=Projekt 12341 Ovod,Nanuchka III
DefaultDescription=Known to the Soviets as the Ovod (Project 1234) the Nanuchka-class are corvettes intended to provide anti-surface cover to coastal waters. In Soviet hands they are generally armed with the SS-N-9 Siren.
Variant1=Smerch MRK,Smerch

[wp_mrk_nanuchka_4]
Type=MRK,Missile Boat
Default=Projekt 12347 Ovod,Nanuchka IV
DefaultDescription=Known to the Soviets as the Ovod (Project 1234) the Nanuchka-class are corvettes intended to provide anti-surface cover to coastal waters. In Soviet hands they are generally armed with the SS-N-9 Siren.
Variant1=Nakat MRK,Nakat

[wp_ptg_tarantul_mr]
#Proj 12411T aka Tarantul II
Type=PTG,Missile Boat
Default=Projekt 1241.1M Molniya,Tarantul III 
DefaultDescription=The superstructures were redesigned and the angled mast of the previous projects has been replaced by a narrow, straight lattice. The sensor position remained almost the same as the Project 1241.1. The "Pechera" navigation radar was off the roof of the bridge, with the MR-123 "Vympel" fire control radar installed. Two jamming system (NATO: "Wine Glass") were installed on both sides at the foot of the mast. The reason for this was the installation of four SS-N-22 'Sunburn' supersonic ship-to-ship missiles with a range of at least 100 km. The associated radar system is the L-band 'Band Stand' radar, with a 120 km active and 500 km (310 mi) passive range and the capability to track 15 different targets. The missiles can also receive third party guidance through the 'Light Bulb' uplink (from other ships, helicopters or long range patrol aircraft). Cannon armament is retained, as were the PK-16 launchers, although Soviet Navy ships benefited from the improved SA-N-8 quadruple MANPADS launcher. At least one ship had an SA-N-11 Kashtan gun and missile CIWS installed instead of the AK-630s.The Tarantul-III, built from 1987 on, received an improved electronic countermeasures suite, consisting of two 'Half Hat' and two 'Foot Ball' jamming systems, coupled to four improved PK-10 decoy launchers. At least 24 of these ships were built for the Soviet Navy before production ended in 1992.
Variant1=Р-2 «Чувашия»
Variant2=Р-5
Variant3=Р-11
Variant4=Р-14
Variant5=Р-18
Variant6=Р-19
Variant7=Р-20
Variant8=Р-24
Variant9=Р-29
Variant10=Р-46
Variant11=Р-47
Variant12=Р-66
Variant13=Р-76
Variant14=Р-83
Variant15=Р-85
Variant16=Р-103
Variant17=Р-109
Variant18=Р-113
Variant19=Р-158
Variant20=Р-187 «Заречный»
Variant21=Р-229
Variant22=Р-230
Variant23=Р-239 «Набережные челны»
Variant24=Р-442
Variant25=Р-240
Variant26=Р-261
Variant27=Р-271
Variant28=Р-291 «Димитровград»
Variant29=Р-293 «Моршанск»
Variant30=Р-297
Variant31=Р-298
Variant32=Р-334 «Ивановец»

[wp_mpk_grisha_mu]
Type=MPK,Frigate
Default=Prj.1124 MU «Albatros»,Albatros
NatoDefault=Grisha V-class,Grisha V
DefaultDescription=These corvettes, known in Russian as Al'batros (Project 1124) are intended for coastal defence, primarily in the ASW role. They are generally lightly armed but are equipped with effective self-defence SAMs.
Variant1=МПК-202
Variant2=МПК-221 «Приморский комсомолец»
Variant3=МПК-69
Variant4=МПК-113
Variant5=МПК-89
Variant6=МПК-207 «Поворино»
Variant7=МПК-222 «Кореец»
Variant8=МПК-217 «Ейск»
Variant9=МПК-194 «Брест»
Variant10=МПК-196
Variant11=МПК-125
Variant12=МПК-28
Variant13=МПК-197
Variant14=МПК-64 «Метель»
Variant15=МПК-107 «Иркутский комсомолец»
Variant16=МПК-203 «Юнга»
Variant17=МПК-130
Variant18=МПК-56
Variant19=МПК-7 «Онега»
Variant20=МПК-82
Variant21=МПК-17 «Усть-Илимск»
Variant22=МПК-10
Variant23=МПК-20
Variant24=МПК-59 «Снежногорск»
Variant25=МПК-14 «Мончегорск»
Variant26=U205 «Луцк»
Variant27=U209

[wp_bpk_udaloy2]
Type=BPK,Destroyer
Default=Project 1155.1 Fregat-M ,Fregat-M 
NatoDefault=Udaloy II-class,Udaloy II 
DefaultDescription=Known in Russian as the Fregat (Project 1155) the Udaloy is the most modern class of large anti-submarine ship in service with the Soviet Navy. These ships are heavily specialized, very modern ASW combatants with their 'Polinom' sonar suite and high-performance 'Kinzhal' point defense missiles, at the cost of any area air defense capability.\nThese ships were built in roughly three "batches" due to delays with the Kinzhal (SA-N-9 Gauntlet) missile system, with the earliest ships never receiving SAMs whatsoever, and the later ships being being extremely competent at missile defense with the full Kinzhal system installed.
Variant1=Admiral Chabanenko BPK-650,Chabanenko

