[Animations]
NumberOfAnimations=28
Animation1=Tube_Door_Port_C_Open
Animation2=Tube_Door_Port_D_Open
Animation3=Tube_Door_Port_U_Open
Animation4=Tube_Door_Stbd_C_Open
Animation5=Tube_Door_Stbd_D_Open
Animation6=Tube_Door_Stbd_U_Open

Animation7=Tube_Door_Port_C_Close
Animation8=Tube_Door_Port_D_Close
Animation9=Tube_Door_Port_U_Close
Animation10=Tube_Door_Stbd_C_Close
Animation11=Tube_Door_Stbd_D_Close
Animation12=Tube_Door_Stbd_U_Close

Animation13=RaisePeriscope
Animation14=LowerPeriscope
Animation15=RaiseESM
Animation16=LowerESM
Animation17=RaiseESM_1
Animation18=LowerESM_1
Animation19=RaiseESM_2
Animation20=LowerESM_2
Animation21=RaiseRadar
Animation22=LowerRadar
Animation23=RaiseSnorkel
Animation24=LowerSnorkel


[Tube_Door_Port_C_Open]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Port_C_Open_Sequence
Sequence1_Model=Door_Port_C

[Tube_Door_Port_D_Open]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Port_D_Open_Sequence
Sequence1_Model=Door_Port_D

[Tube_Door_Port_U_Open]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Port_U_Open_Sequence
Sequence1_Model=Door_Port_U

[Tube_Door_Stbd_C_Open]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Stbd_C_Open_Sequence
Sequence1_Model=Door_Stbd_C

[Tube_Door_Stbd_D_Open]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Stbd_D_Open_Sequence
Sequence1_Model=Door_Stbd_D

[Tube_Door_Stbd_U_Open]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Stbd_U_Open_Sequence
Sequence1_Model=Door_Stbd_U



#closing tubes anims
[Tube_Door_Port_C_Close]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Port_C_Close_Sequence
Sequence1_Model=Door_Port_C

[Tube_Door_Port_D_Close]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Port_D_Close_Sequence
Sequence1_Model=Door_Port_D

[Tube_Door_Port_U_Close]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Port_U_Close_Sequence
Sequence1_Model=Door_Port_U

[Tube_Door_Stbd_C_Close]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Stbd_C_Close_Sequence
Sequence1_Model=Door_Stbd_C

[Tube_Door_Stbd_D_Close]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Stbd_D_Close_Sequence
Sequence1_Model=Door_Stbd_D

[Tube_Door_Stbd_U_Close]
NumberOfSequencesToPlay=1
Sequence1=Tube_Door_Stbd_U_Close_Sequence
Sequence1_Model=Door_Stbd_U

# Masts animations

[RaisePeriscope]
NumberOfSequencesToPlay=2
Sequence1=RaisePeriscope_Sequence
Sequence1_Model=Periscope
Sequence2=RaisePeriscope2_Sequence
Sequence2_Model=Periscope2

[LowerPeriscope]
NumberOfSequencesToPlay=2
Sequence1=LowerPeriscope_Sequence
Sequence1_Model=Periscope
Sequence2=LowerPeriscope2_Sequence
Sequence2_Model=Periscope2

[RaiseESM]
NumberOfSequencesToPlay=3
Sequence1=RaiseESM_1_Sequence_1
Sequence1_Model=ESM1Mast
Sequence2=RaiseESM_1_Sequence_2
Sequence2_Model=ESM1
Sequence3=RaiseESM_2_Sequence
Sequence3_Model=ESM2

[LowerESM]
NumberOfSequencesToPlay=3
Sequence1=LowerESM_1_Sequence_1
Sequence1_Model=ESM1Mast
Sequence2=LowerESM_1_Sequence_2
Sequence2_Model=ESM1
Sequence3=LowerESM_2_Sequence
Sequence3_Model=ESM2

[RaiseESM_1]
NumberOfSequencesToPlay=2
Sequence1=RaiseESM_1_Sequence_1
Sequence1_Model=ESM1Mast
Sequence2=RaiseESM_1_Sequence_2
Sequence2_Model=ESM1

[LowerESM_1]
NumberOfSequencesToPlay=2
Sequence1=LowerESM_1_Sequence_1
Sequence1_Model=ESM1Mast
Sequence2=LowerESM_1_Sequence_2
Sequence2_Model=ESM1


[RaiseESM_2]
NumberOfSequencesToPlay=1
Sequence1=RaiseESM_2_Sequence
Sequence1_Model=ESM2

[LowerESM_2]
NumberOfSequencesToPlay=1
Sequence1=LowerESM_2_Sequence
Sequence1_Model=ESM2

[RaiseRadar]
NumberOfSequencesToPlay=1
Sequence1=RaiseRadar_Sequence
Sequence1_Model=RadarMast

[LowerRadar]
NumberOfSequencesToPlay=1
Sequence1=LowerRadar_Sequence
Sequence1_Model=RadarMast

[RaiseSnorkel]
NumberOfSequencesToPlay=1
Sequence1=RaiseSnorkel_Sequence
Sequence1_Model=Snorkel

[LowerSnorkel]
NumberOfSequencesToPlay=1
Sequence1=LowerSnorkel_Sequence
Sequence1_Model=Snorkel
#---------------------------------------------------------------------------------------------
#Tube_Door_Port_C
[Tube_Door_Port_C_Open_Sequence]
NumberOfSteps=2
Step1=0|-0.022054,0.020213 ,0.468172|0,0,0|EaseInOut
Step2=5|-0.032567,0.020213,0.442847|0,-33.7567,0|EaseInOut

[Tube_Door_Port_C_Close_Sequence]
NumberOfSteps=2
Step1=0|-0.032567,0.020213,0.442847|0,-33.7567,0|EaseInOut
Step2=5|-0.022054,0.020213 ,0.468172|0,0,0|EaseInOut

#---------------------------------
#Tube_Door_Port_D
[Tube_Door_Port_D_Open_Sequence]
NumberOfSteps=2
Step1=0|-0.010354,0.008974,0.481758|0,0,0|EaseInOut
Step2=5|-0.028391,0.007053 ,0.462891|0,-33.8508,0|EaseInOut

[Tube_Door_Port_D_Close_Sequence]
NumberOfSteps=2
Step1=0|-0.028391,0.007053 ,0.462891|0,-33.8508,0|EaseInOut
Step2=5|-0.010354,0.008974,0.481758|0,0,0|EaseInOut

#---------------------------------
#Tube_Door_Port_U
[Tube_Door_Port_U_Open_Sequence]
NumberOfSteps=2
Step1=0|-0.008332,0.030635,0.470007|0,0,0|EaseInOut
Step2=5|-0.022056,0.035637,0.448134|0,-26.9767,0|EaseInOut

[Tube_Door_Port_U_Close_Sequence]
NumberOfSteps=2
Step1=0|-0.022056,0.035637,0.448134|0,-26.9767,0|EaseInOut
Step2=5|-0.008332,0.030635,0.470007|0,0,0|EaseInOut

#---------------------------------
#Tube_Door_Stbd_C
[Tube_Door_Stbd_C_Open_Sequence]
NumberOfSteps=2
Step1=0|0.022059,0.020213 ,0.468172|0,0,0|EaseInOut
Step2=5|0.032567,0.020213,0.442847|0,33.7567,0|EaseInOut

[Tube_Door_Stbd_C_Close_Sequence]
NumberOfSteps=2
Step1=0|0.032567,0.020213,0.442847|0,33.7567,0|EaseInOut
Step2=5|0.022059,0.020213 ,0.468172|0,0,0|EaseInOut
#---------------------------------
#Tube_Door_Stbd_D
[Tube_Door_Stbd_D_Open_Sequence]
NumberOfSteps=2
Step1=0|0.010364,0.008976 ,0.481754|0,0,0|EaseInOut
Step2=5|0.028391,0.007053 ,0.462891|0,33.8508,0|EaseInOut

[Tube_Door_Stbd_D_Close_Sequence]
NumberOfSteps=2
Step1=0|0.028391,0.007053 ,0.462891|0,33.8508,0|EaseInOut
Step2=5|0.010364,0.008976 ,0.481754|0,0,0|EaseInOut

#---------------------------------
#Tube_Door_Stbd_U
[Tube_Door_Stbd_U_Open_Sequence]
NumberOfSteps=2
Step1=0|0.008439,0.03064,0.469952|0,0,0|EaseInOut
Step2=5|0.022056,0.035637,0.448134|0,26.9767,0|EaseInOut

[Tube_Door_Stbd_U_Close_Sequence]
NumberOfSteps=2
Step1=0|0.022056,0.035637,0.448134|0,26.9767,0|EaseInOut
Step2=5|0.008439,0.03064,0.469952|0,0,0|EaseInOut

#---------------------------------
#Periscope

[RaisePeriscope_Sequence]
NumberOfSteps=2
Step1=0|x,0,z|x,y,z|EaseInOut
Step2=5|x,0.056748,z|x,y,z|EaseInOut

[LowerPeriscope_Sequence]
NumberOfSteps=2
Step1=0|x,0.056748,z|x,y,z|EaseInOut
Step2=5|x,0,z|x,y,z|EaseInOut

#---------------------------------
#Periscope 2

[RaisePeriscope2_Sequence]
NumberOfSteps=2
Step1=0|x,0,z|x,y,z|EaseInOut
Step2=5|x,0.049035,z|x,y,z|EaseInOut

[LowerPeriscope2_Sequence]
NumberOfSteps=2
Step1=0|x,0.049035,z|x,y,z|EaseInOut
Step2=5|x,0,z|x,y,z|EaseInOut

#---------------------------------
#ESM

[RaiseESM_1_Sequence_1]
NumberOfSteps=2
Step1=0|x,0,z|x,y,z|EaseInOut
Step2=5|x,0.051136,z|x,y,z|EaseInOut

[RaiseESM_1_Sequence_2]
NumberOfSteps=2
Step1=0|x,0,z|x,y,z|EaseInOut
Step2=5|x,0.020615,z|x,y,z|EaseInOut

[LowerESM_1_Sequence_1]
NumberOfSteps=2
Step1=0|x,0.051136,z|x,y,z|EaseInOut
Step2=5|x,0,z|x,y,z|EaseInOut

[LowerESM_1_Sequence_2]
NumberOfSteps=2
Step1=0|x,0.020615,z|x,y,z|EaseInOut
Step2=5|x,0,z|x,y,z|EaseInOut


#---------------------------------
# ESM 2

[RaiseESM_2_Sequence]
NumberOfSteps=2
Step1=0|x,0,z|x,y,z|EaseInOut
Step2=5|x,0.049035,z|x,y,z|EaseInOut

[LowerESM_2_Sequence]
NumberOfSteps=2
Step1=0|x,0.049035,z|x,y,z|EaseInOut
Step2=5|x,0,z|x,y,z|EaseInOut

#---------------------------------
# Radar

[RaiseRadar_Sequence]
NumberOfSteps=2
Step1=0|x,0,z|x,y,z|EaseInOut
Step2=5|x,0.049035,z|x,y,z|EaseInOut

[LowerRadar_Sequence]
NumberOfSteps=2
Step1=0|x,0.049035,z|x,y,z|EaseInOut
Step2=5|x,0,z|x,y,z|EaseInOut

#---------------------------------
# Snorkel

[RaiseSnorkel_Sequence]
NumberOfSteps=2
Step1=0|x,0,z|x,y,z|EaseInOut
Step2=5|x,0.058092,z|x,y,z|EaseInOut

[LowerSnorkel_Sequence]
NumberOfSteps=2
Step1=0|x,0.058092,z|x,y,z|EaseInOut
Step2=5|x,0,z|x,y,z|EaseInOut