<<<<<<< Updated upstream
[LoadoutNames]
#------------------------------------------ New system ------------------------------------------
AA=Anti-Air
MST=MST
AABF=Anti-Air Battle Flag
MSTBF=MST Battle Flag
ASWBF=ASW Battle Flag
# - LongRange means operating range of aircraft, not the weapons range
# ---------- Mandatory loadouts ----------
Default=Default                            // Usually most common loadout for this plane
Ferry=Ferry                                // Maximum fueltanks, no weapons, except guns and chaff
Empty=Empty                                // No fueltanks, no weapons, except guns and chaff

#----------- Murder Hornet ---------------
MurderHornetCAP=MH CAP 174				   // F/A-18E/F Specific
MH_CAP_120=MH CAP 120						// F/A-18E/F Specific
MH_CAP_120EF=MH CAP 120-EF	// F/A-18E/F Specific
MurderHornetInterceptor=MH Interceptor		// F/A-18E/F Specific
MurderHornetPenetrator=MH Penetrator		// F/A-18E/F Specific
MurderHornetGunSlinger=MH Gunslinger  		// F/A-18E Specific
MurderHornetFistFight=MH Fist Fight			// F/A-18E Specific
MurderHornetStrikeLight=MH Strike Light			// F/A-18E/F Specific
MurderHornetStrikeHeavy=MH GBU-10		// F/A-18E Specific
MurderHornetCAS=MH CAS			// F/A-18E/F Specific
MurderHornetCASAGM=MH CAS AGM			// F/A-18F Specific
MH_CASAGMEF=MH CAS AGM-EF			// F/A-18F Specific
MurderHornetCASSDB=MH CAS SDB			// F/A-18F Specific
MH_CASSDBEF=MH CAS SDB-EF			// F/A-18F Specific
MurderHornetSEAD=MH SEAD			// F/A-18E/F Specific
MurderHornetAntiShip=MH Anti-Ship			// F/A-18E/F Specific
MH_AntiShipEF=MH Anti-Ship-EF			// F/A-18E/F Specific
MH_LRASM=MH LRASM			// F/A-18E/F Specific
#MH_GBU-12=MH GBU-12			// F/A-18E/F Specific
#MH_GBU-31=MH GBU-31			// F/A-18E/F Specific
MH_GBU-75=MH GBU-75			// F/A-18E/F Specific
MH_AGM-154JSOW=MH JSOW			// F/A-18E/F Specific
MH_AGM-154EF=MH JSOW-EF			// F/A-18E/F Specific
MH_AGM-154JSOWclus=MH JSOW Cluster			// F/A-18E/F Specific
MH_AGM-154clusEF=MH JSOW Cluster-EF			// F/A-18E/F Specific
MurderHornetStrikeJDAM=MH JDAM Land			// F/A-18E/F Specific
MH_GBU-31EF=MH JDAM Land-EF			// F/A-18E/F Specific
MurderHornetStrikeGBU=MH GBU 24			// F/A-18E/F Specific
MH_GBU-24EF=MH GBU 24-EF			// F/A-18E/F Specific
MH_QCSK31=MH Quicksink GBU-31
MH_QCSK31EF=MH Quicksink GBU-31-EF
MH_QCSK38=MH Quicksink GBU-38
MH_QCSK38EF=MH Quicksink GBU-38-EF
MurderHornetSEADHeavy=MH SEAD
MurderHornetSEADHeavyTanks=MH SEAD+Extra Fuel Tanks
MurderHornetLightsOut=MH SEAD Full
=======
[LoadoutNames]
# - LongRange means operating range of aircraft, not the weapons range
# ---------- Mandatory loadouts ----------
Default=Default                            // Usually most common loadout for this plane
Ferry=Ferry                                // Maximum fueltanks, no weapons, except guns and chaff
Empty=Empty                                // No fueltanks, no weapons, except guns and chaff

#----------- Murder Hornet ---------------
MurderHornetCAP=MH CAP 174				   // F/A-18E/F Specific
MH_CAP_424=MH CAP 424						// F/A-18E/F Specific
MH_CAP_120=MH CAP 120						// F/A-18E/F Specific
MH_CAP_120EF=MH CAP 120-EF	// F/A-18E/F Specific
MurderHornetInterceptor=MH Interceptor 174		// F/A-18E/F Specific
MH_LRAAM=MH Interceptor 424					// F/A-18E/F Specific
MurderHornetPenetrator=MH Penetrator 174		// F/A-18E/F Specific
MH_PenetratorLRAAM=MH Penetrator 424		// F/A-18E/F Specific
MurderHornetGunSlinger=MH Gunslinger  		// F/A-18E Specific
MurderHornetFistFight=MH Fist Fight			// F/A-18E Specific
MurderHornetStrikeLight=MH Strike Light			// F/A-18E/F Specific
MurderHornetStrikeHeavy=MH GBU-10		// F/A-18E Specific
MurderHornetCAS=MH CAS			// F/A-18E/F Specific
MurderHornetCASAGM=MH CAS AGM			// F/A-18F Specific
MH_CASAGMEF=MH CAS AGM-EF			// F/A-18F Specific
MurderHornetCASSDB=MH CAS SDB			// F/A-18F Specific
MH_CASSDBEF=MH CAS SDB-EF			// F/A-18F Specific
MurderHornetSEAD=MH SEAD			// F/A-18E/F Specific
MurderHornetAntiShip=MH Anti-Ship			// F/A-18E/F Specific
MH_AntiShipEF=MH Anti-Ship-EF			// F/A-18E/F Specific
MH_LRASM=MH LRASM			// F/A-18E/F Specific
MH_JASSM=MH JASSM			// F/A-18E/F Specific
#MH_GBU-12=MH GBU-12			// F/A-18E/F Specific
#MH_GBU-31=MH GBU-31			// F/A-18E/F Specific
MH_GBU-75=MH GBU-75			// F/A-18E/F Specific
MH_AGM-154JSOW=MH JSOW			// F/A-18E/F Specific
MH_AGM-154EF=MH JSOW-EF			// F/A-18E/F Specific
MH_AGM-154JSOWclus=MH JSOW Cluster			// F/A-18E/F Specific
MH_AGM-154clusEF=MH JSOW Cluster-EF			// F/A-18E/F Specific
MurderHornetStrikeJDAM=MH JDAM Land			// F/A-18E/F Specific
MH_GBU-31EF=MH JDAM Land-EF			// F/A-18E/F Specific
MurderHornetStrikeGBU=MH GBU 24			// F/A-18E/F Specific
MH_GBU-24EF=MH GBU 24-EF			// F/A-18E/F Specific
MH_QCSK31=MH Quicksink GBU-31
MH_QCSK31EF=MH Quicksink GBU-31-EF
MH_QCSK38=MH Quicksink GBU-38
MH_QCSK38EF=MH Quicksink GBU-38-EF
MurderHornetSEADHeavy=MH SEAD
MurderHornetSEADHeavyTanks=MH SEAD+Extra Fuel Tanks
MurderHornetLightsOut=MH SEAD Full

#------------------------------------------------------------------------------------
AA=Anti-Air
MST=MST
AABF=Anti-Air Battle Flag
MSTBF=MST Battle Flag
ASWBF=ASW Battle Flag
# ---
≥051_AA==051 Anti-Air
≥051_MST==051 MST
≥051_ASW==051 ASW
≥051_AABF==051 Anti-Air Battle Flag
≥051_MSTBF==051 MST Battle Flag
≥051_ASWBF==051 ASW Battle Flag
# ---
≥051sR_AA==051 SeaRAM Anti-Air
≥051sR_MST==051 SeaRAM MST
≥051sR_ASW==051 SeaRAM ASW
≥051sR_AABF==051 SeaRAM Anti-Air Battle Flag
≥051sR_MSTBF==051 SeaRAM MST Battle Flag
≥051sR_ASWBF==051 SeaRAM ASW Battle Flag
# ---
≥052_AA=≥052 Anti-Air
≥052_MST=≥052 MST
≥052_ASW=≥052 ASW
≥052_AABF=≥052 Anti-Air Battle Flag
≥052_MSTBF=≥052 MST Battle Flag
≥052_ASWBF=≥052 ASW Battle Flag
# ---
≥052sR_AA=≥052 SeaRAM Anti-Air
≥052sR_MST=≥052 SeaRAM MST
≥052sR_ASW=≥052 SeaRAM ASW
≥052sR_AABF=≥052 SeaRAM Anti-Air Battle Flag
≥052sR_MSTBF=≥052 SeaRAM MST Battle Flag
≥052sR_ASWBF=≥052 SeaRAM ASW Battle Flag
# ---
≥062_AA==062 Anti-Air
≥062_MST==062 MST
≥062_ASW==062 ASW
≥062_AABF==062 Anti-Air Battle Flag
≥062_MSTBF==062 MST Battle Flag
≥062_ASWBF==062 ASW Battle Flag
# ---
≥068_AA=≥068 Anti-Air
≥068_MST=≥068 MST
≥068_ASW=≥068 ASW
≥068_AABF=≥068 Anti-Air Battle Flag
≥068_MSTBF=≥068 MST Battle Flag
≥068_ASWBF=≥068 ASW Battle Flag
# ---
≥068sR_AA=≥068 SeaRAM Anti-Air
≥068sR_MST=≥068 SeaRAM MST
≥068sR_ASW=≥068 SeaRAM ASW
≥068sR_AABF=≥068 SeaRAM Anti-Air Battle Flag
≥068sR_MSTBF=≥068 SeaRAM MST Battle Flag
≥068sR_ASWBF=≥068 SeaRAM ASW Battle Flag
# ---
≥072_AA=≥072 Anti-Air
≥072_MST=≥072 MST
≥072_ASW=≥072 ASW
≥072_AABF=≥072 Anti-Air Battle Flag
≥072_MSTBF=≥072 MST Battle Flag
≥072_ASWBF=≥072 ASW Battle Flag
# ---
≥072sR_AA=≥072 SeaRAM Anti-Air
≥072sR_MST=≥072 SeaRAM MST
≥072sR_ASW=≥072 SeaRAM ASW
≥072sR_AABF=≥072 SeaRAM Anti-Air Battle Flag
≥072sR_MSTBF=≥072 SeaRAM MST Battle Flag
≥072sR_ASWBF=≥072 SeaRAM ASW Battle Flag
# ---
≥079_AA==79 Anti-Air
≥079_MST==79 MST
≥079_ASW==79 ASW
≥079_AABF==79 Anti-Air Battle Flag
≥079_MSTBF==79 MST Battle Flag
≥079_ASWBF==79 ASW Battle Flag
# ---
≥080_AA==80 Anti-Air
≥080_MST==80 MST
≥080_ASW==80 ASW
≥080_AABF==80 Anti-Air Battle Flag
≥080_MSTBF==80 MST Battle Flag
≥080_ASWBF==80 ASW Battle Flag
# ---
≥081_AA=≥81 Anti-Air
≥081_MST=≥81 MST
≥081_ASW=≥81 ASW
≥081_AABF=≥81 Anti-Air Battle Flag
≥081_MSTBF=≥81 MST Battle Flag
≥081_ASWBF=≥81 ASW Battle Flag
# ---
≥085_AA=≥85 Anti-Air
≥085_MST=≥85 MST
≥085_ASW=≥85 ASW
≥085_AABF=≥85 Anti-Air Battle Flag
≥085_MSTBF=≥85 MST Battle Flag
≥085_ASWBF=≥85 ASW Battle Flag
# ---
≥088_AA==88 Anti-Air
≥088_MST==88 MST
≥088_ASW==88 ASW
≥088_AABF==88 Anti-Air Battle Flag
≥088_MSTBF==88 MST Battle Flag
≥088_ASWBF==88 ASW Battle Flag
# ---
≥089_AA=≥89 Anti-Air
≥089_MST=≥89 MST
≥089_ASW=≥89 ASW
≥089_AABF=≥89 Anti-Air Battle Flag
≥089_MSTBF=≥89 MST Battle Flag
≥089_ASWBF=≥89 ASW Battle Flag
# ---
≥091_AA=≥91 Anti-Air
≥091_MST=≥91 MST
≥091_ASW=≥91 ASW
≥091_AABF=≥91 Anti-Air Battle Flag
≥091_MSTBF=≥91 MST Battle Flag
≥091_ASWBF=≥91 ASW Battle Flag
# ---
≥092_AA=≥92 Anti-Air
≥092_MST=≥92 MST
≥092_ASW=≥92 ASW
≥092_AABF=≥92 Anti-Air Battle Flag
≥092_MSTBF=≥92 MST Battle Flag
≥092_ASWBF=≥92 ASW Battle Flag
# ---
≥097_AA==097 Anti-Air
≥097_MST==097 MST
≥097_ASW==097 ASW
≥097_AABF==097 Anti-Air Battle Flag
≥097_MSTBF==097 MST Battle Flag
≥097_ASWBF==097 ASW Battle Flag
# ---
≥098_AA=≥098 Anti-Air
≥098_MST=≥098 MST
≥098_ASW=≥098 ASW
≥098_AABF=≥098 Anti-Air Battle Flag
≥098_MSTBF=≥098 MST Battle Flag
≥098_ASWBF=≥098 ASW Battle Flag
# ---
≥100_AA==100 Kidd Anti-Air
≥100_MST==100 Kidd MST
≥100_ASW==100 Kidd ASW
≥100_AABF==100 Kidd Anti-Air Battle Flag
≥100_MSTBF==100 Kidd MST Battle Flag
≥100_ASWBF==100 Kidd ASW Battle Flag
# ---
≥108_AA=≥108 Anti-Air
≥108_MST=≥108 MST
≥108_ASW=≥108 ASW
≥108_AABF=≥108 Anti-Air Battle Flag
≥108_MSTBF=≥108 MST Battle Flag
≥108_ASWBF=≥108 ASW Battle Flag
# ---
≥113_AA=≥113 Anti-Air
≥113_MST=≥113 MST
≥113_ASW=≥113 ASW
≥113_AABF=≥113 Anti-Air Battle Flag
≥113_MSTBF=≥113 MST Battle Flag
≥113_ASWBF=≥113 ASW Battle Flag
# ---
≥117_AA==117 Anti-Air
≥117_MST==117 MST
≥117_ASW==117 ASW
≥117_AABF==117 Anti-Air Battle Flag
≥117_MSTBF==117 MST Battle Flag
≥117_ASWBF==117 ASW Battle Flag
# ---
≥119_AA=≥119 Anti-Air
≥119_MST=≥119 MST
≥119_ASW=≥119 ASW
≥119_AABF=≥119 Anti-Air Battle Flag
≥119_MSTBF=≥119 MST Battle Flag
≥119_ASWBF=≥119 ASW Battle Flag
# ---
≥125_AA=≥125 Anti-Air
≥125_MST=≥125 MST
≥125_ASW=≥125 ASW
≥125_AABF=≥125 Anti-Air Battle Flag
≥125_MSTBF=≥125 MST Battle Flag
≥125_ASWBF=≥125 ASW Battle Flag
# ---
≥125SEWIP_AA=≥125 SEWIP Anti-Air
≥125SEWIP_MST=≥125 SEWIP MST
≥125SEWIP_ASW=≥125 SEWIP ASW
≥125SEWIP_AABF=≥125 SEWIP Anti-Air Battle Flag
≥125SEWIP_MSTBF=≥125 SEWIP MST Battle Flag
≥125SEWIP_ASWBF=≥125 SEWIP ASW Battle Flag
# ---
# ---
>>>>>>> Stashed changes
