[Shader]
Path=Marmoset/Occlusion/Bumped Specular IBL

#[Properties]
_Color=Color,{*}808080ff
_SpecColor=Color,{*}ffffffff
_SpecInt=Float,1.0
_Shininess=Float,6.5
_Fresnel=Float,0.75

[Textures]
_MainTex=aircraft/AH1G/Aussie_CobraAH1G.png
_SpecTex=aircraft/AH1G/Aussie_CobraAH1G_spec.png
_BumpMap=aircraft/AH1G/Aussie_CobraAH1G_normal.png
