[General]
# FAPDS - Frangible armour-piercing discarding-sabot projectile.
Type=Projectile            // can be Projectile, Missile, Torpedo
TargetType=ASuW             // can be AAW, ASuW, ASW
SecondaryTargetType=AAW

Mass=0.26                             // in kg. Used for aircraft
AmmoPoints=0.26                       // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DecalClass=GunImpacts      // referenced in effects/decals.ini

[Physics]
MuzzleVelocity=1100         // meter per second
MaxRange=6000              // in m
CircularErrorProbable=8   // radius in meters at max range for shells to impact

[---------- Warhead Data ----------]
[WarheadData]
WarheadType=1
Power=0.4
ArmorPen=4
FuzeMode=Impact
FuzeProximityDistance=0
ImpactSize=Tiny            // Impact size, can be small, medium, large, verylarge
Penetration=Heavy         // can be minor, moderate, heavy, always

[---------- Effects ----------]
[Particles]
TrailEffect=
HitShipExplosion=effects/Particle Emitters/impact_small_shell_multi
HitAirExplosionClass=SmallFlakExplosions
HitWaterSplashClass=TinyWaterSplashes