[General]
# ABM - Programmable airburst ammunition.
Type=Projectile            // can be Projectile, Missile, Torpedo
TargetType=AAW             // can be AAW, ASuW, ASW
SecondaryTargetType=ASuW
Mass=0.36
AmmoPoints=1.0

DecalClass=GunImpacts      // referenced in effects/decals.ini

[Physics]
MuzzleVelocity=1100         // meter per second
MaxRange=4000              // in m
CircularErrorProbable=1   // radius in meters at max range for shells to impact

[---------- Warhead Data ----------]
[WarheadData]
WarheadType=0
Power=1.5
ArmorPen=0.2
ImpactSize=Tiny           // Impact size, can be small, medium, large, verylarge
Penetration=Minor         // can be minor, moderate, heavy, always

[---------- Effects ----------]
[Particles]
TrailEffect=
HitShipExplosion=effects/Particle Emitters/impact_small_shell_multi
HitAirExplosionClass=SmallFlakExplosions
HitWaterSplashClass=TinyWaterSplashes