#!extend ammunition/usn_rim-66g.ini

# SM-2MR Block II

[---------- Mesh definitions----------]
[Models]
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/europack/models/
ResourcesRoot=weapons.obj
ResourcesMesh=eu_missile_SM-2M-2
ResourcesMaterialFolder=assets/europack/materials/RIM-66/
ResourcesMaterial=RIM-66G_mat.ini
;ResourcesMeshSwitchTime=0.5  // time in seconds after launch to switch from launch mesh to main mesh
############################################################
[---------- Launchers ----------]
# References to the launchers are just used for positioning relative to the launcher of the missile
[Launchers]
NumberOfLaunchers=3
Launcher1=MK13
Launcher2=MK22
Launcher3=MK26

[MK13]
LoadedPosition=0,0,0.009
UnloadedPosition=0,0,-0.086
LoadedRotation=0,0,0
UnloadedRotation=0,0,0

[MK22]
LoadedPosition=0,0,0.006
UnloadedPosition=0,0,-0.086
LoadedRotation=0,0,0
UnloadedRotation=0,0,0

[MK26]
LoadedPosition=0,0,0.006
UnloadedPosition=0,0,-0.086
LoadedRotation=0,0,0
UnloadedRotation=0,0,0
[---------- Effects ----------]

[Particles]
BoosterEffect=
BoosterEffectPosition=0,0,-0.035

InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,-0.035
InFlightEffectStartTime=3.0  // in seconds, after that the Inflight Effect will be played if available

SustainerEffect=effects/weapons/emitters/sam_medium_effect //missile_sustainer_small_effect
SustainerEffectPosition=0,0,-0.035
SustainerEffectStartTime=0.2