#!alias ammunition/usn_ugm-84c.ini

# UGM-84G Block 1G «Harpoon»

[General]
IOCDate=1997
FOCDate=1997

[SensorData]
TransientBaseNoise=180                 // In db

RCS=0.5
[---------- Guidance ----------]
[Guidance]
#========================================= Launch stats ============================================================
MinDepth=50
AntiJammerBonus=0.45                   // This value substracted from probability of being jammed (0...1)
AntiCountermeasuresBonus=0.50           // This value substracted from probability of spoofing by countermeasures (0...1)

