#=========================================================================================================================================================
#                                                  REQUIRES STATS REVISION
#=========================================================================================================================================================

#!alias ammunition/wp_sa-21a.ini
# 48N6DM

[General]
IOCDate=
FOCDate=2007
