#=========================================================================================================================================================
#                                                  REQUIRES STATS REVISION
#=========================================================================================================================================================

#!alias ammunition/wp_sa-n-20.ini
# 48N6M - Fort-M extended-range

[General]
IOCDate=1995                              // Year, shows in Unit Reference. If set, defines if the weapon is able to be used in combat before it is fully operational (before FOCDate)
FOCDate=                              // Year, shows in Unit Reference, defines first year this weapon is commonly available to be selected. Default/unset: always available

[Guidance]
AntiCountermeasuresBonus=0.50         // This value substracted from probability of spoofing by countermeasures (0...1)
AntiJammerBonus=0.45                  // This value substracted from probability of being jammed  (0...1)

MaxLoftAlt=82021.0                     // in feet. Maximum altitude for lofting
MaxFlightTime=210               // How long until missile entirely fails, acts as a hard limit based on batteries, etc. Default: unlimited

MaxVelocity=4082.0                     // Maximum speed in knots
MaxTurnRate=20                       // Maximum turnrate in degrees per second
MaxTurnG=25                       // Maximum G-limit of missile turns
LaunchTurnRate=120                     // Missiles like S-300 rapidly orient themselves after launch. in degrees per second
AccelerationTime=1.0                  // Burn time for initial booster burn
Acceleration=10                      // Gs of acceleration in initial burn
SustainerAccelerationTime=12            // Time of sustainer burn. -1 if there is no sustainer burn
SustainerAcceleration=22.8               // Acceleration of sustainer burn. -1 if there is no sustainer
#========================================= Launch stats ============================================================
MinLaunchRange=3.5                     // Minimum launch range in nautical miles
MaxLaunchRange=108.0                    // Maximum launch range in nautical miles
MinAttackAltitude=23.0                   // Minimum altitude of a target, in feet. Outside Min/Max altitude missile deviation is greatly increaced
MaxAttackAltitude=88582.7                // Maximum altitude of target, in feet
