[Language_en]
Name=F-15J Peace Eagle
Description=The F-15J Peace Eagle is a single-seat all-weather air-superiority fighter, based on the McDonnell Douglas F-15 Eagle, built under licence by Mitsubishi Heavy Industries and in use by the Japan Air Self-Defense Force. The F-15Js are identical to the F-15Cs except for some electronic equipments which are produced in Japan. 

[Language_cn]
Name=F-15J 和平鷹
Description=F-15J和平鷹式戰鬥機是一款單座全天候制空戰鬥機，以麥道F-15鷹式戰鬥機為基礎，由三菱重工業公司取得授權生產，現役於日本航空自衛隊。除部分日本本土生產的電子設備外，F-15J與F-15C型號完全相同。 

[Language_fr]
Name=F-15J Peace Eagle
Description=Le F-15J Peace Eagle est un chasseur monoplace tout temps destiné à assurer la supériorité aérienne, basé sur le McDonnell Douglas F-15 Eagle, construit sous licence par Mitsubishi Heavy Industries et utilisé par la Force aérienne d'autodéfense japonaise. Les F-15J sont identiques aux F-15C, à l'exception de certains équipements électroniques qui sont produits au Japon. 

[Language_es]
Name=F-15J Peace Eagle
Description=El F-15J Peace Eagle es un caza monoplaza de superioridad aérea para todo tipo de condiciones meteorológicas, basado en el McDonnell Douglas F-15 Eagle, fabricado bajo licencia por Mitsubishi Heavy Industries y utilizado por la Fuerza Aérea de Autodefensa de Japón. Los F-15J son idénticos a los F-15C, salvo por algunos equipos electrónicos que se fabrican en Japón. 

[Language_de]
Name=F-15J Peace Eagle
Description=Die F-15J Peace Eagle ist ein einsitziger Allwetter-Luftüberlegenheitsjäger, der auf der McDonnell Douglas F-15 Eagle basiert, von Mitsubishi Heavy Industries in Lizenz gebaut wird und von der japanischen Luftselbstverteidigungsstreitkraft eingesetzt wird. Die F-15Js sind mit Ausnahme einiger in Japan hergestellter elektronischer Ausrüstungen identisch mit den F-15Cs.  

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.8.0
