[---------- General Data ----------]
[General]
UnitType=Aircraft
CarrierCapable=True

DefaultCameraDistance=1
MinCameraDistanceForeAft=0.38
MinCameraDistanceBroadside=0.38

#Taxi values
GroundedPitchAngle=-0.4        // this angle is the pitch (x) angle at ground with gears down
GroundPivot=0,-0.0327,0        // defines the relative location of the landing gear
LandingPivot=0,-0.027,-0.086   // defines the relative location of the arrestor hook
OnDeckPositionOffset=0,0,-0.06
LaunchPointOffset=0.04

ForwardsTaxiVelocity=25
BackwardsTaxiVelocity=-5

Pilot=usn_pilot_s-3a
PilotPositions=-0.0083,-0.0073,0.047|0.0083,-0.0073,0.047|-0.0083,-0.0073,0.0736|0.0083,-0.0073,0.0736
EjectChance=0.6

[AI]
Role=MPA,ESM

[SensorData]
#Visual
VisualIdentificationRange=6       // Biggest range in nm at which this unit can be visually identified
IRSignature=SemiSmall
# Radar related (RCS => radar cross section)
RCS=SemiSmall

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_usn_s-3a

[---------- Flight Model ----------]
[Engine]
EngineIntakeArea=1.39

[FlightModel]
PitchGain=0.8                         // Vertical manuverability
VelocityGain=0.1136                   // Acceleration
HeadingGain=2                         // Horizontal manuverability
YawRateLimit=130                      // in degrees per second

BankGain=0.8                            // Roll change speed
MaxRollForHeading=45.0                // bank limit in normal flight
MaxRollRate=80.0                     // in degrees per second

ThrustGain=0.325                      // Thrust change speed
SpeedBrakeFractionGain=10            // Speed brakes deploy speed

SpeedDeltaPerAltitudeChange=0.0885

[Performance]
#Dimensions
WingSpan=20.93                        //meters
#Parameters
MaxG=6.0                              // Mostly for horizontal turns

MaxClimbRate=26                       //Meters per second
EmptyMass=12057.0                     // in kg
MaxFuel=5856.0                        // in kg

PerEngineMaxThrust=41250              //Newtons
EngineCount=2

Ceiling=40900.0                       // ceiling in feet
CruiseAltitude= ????                  //in feet
#"Engine" efficiency at 0ft, 37000 ft, 65000 ft. Always 1 for cruise altitude
AltitudeEfficiency=0.5,0.5,0.25       // Defines fuel consumption with altitude

#Governing of max speed
MaxSpeedAtSeaLevel=440                //in knots, Defines max speed at altitude curve
StallSpeed=97.0                       //in knots
MachLimit=0.785                       //for 37000ft, Defines max speed at altitude curve

#SpeedAndRange   MachNumbers or knots, Specified units or multiplier (except Cruise range)
RangeUnits=Miles                      // Can be: Km. Any other value = nmi. Defines measurment units of ranges of SpeedAndRange values

SpeedAndRange_Landing=0.2,0.4         // Landing
SpeedAndRange_Loiter=0.35,0.6         // Loiter
SpeedAndRange_Cruise=0.612,2765       // Cruise
SpeedAndRange_Max=0.785 ,0.8          // Attack/Fast/High/Max without AB

Altitudes=50,500,1000,3000,6000,10000,20000  // in feet

[---------- Main Systems ----------]
[FlightControls]
NumberOfAilerons=2
Aileron1_Model=Left_Aileron
Aileron1_MinAngle=-45.0
Aileron1_MaxAngle=45.0
Aileron1_BaseAngle=0.0

Aileron2_Model=Right_Aileron
Aileron2_MinAngle=-45.0
Aileron2_MaxAngle=45.0
Aileron2_BaseAngle=0.0

NumberOfElevators=2
Elevator1_Model=Left_Elevator
Elevator1_MinAngle=-20.0
Elevator1_MaxAngle=20.0
Elevator1_BaseAngle=0.0

Elevator2_Model=Right_Elevator
Elevator2_MinAngle=-20.0
Elevator2_MaxAngle=20.0
Elevator2_BaseAngle=0.0

NumberOfSpoilerons=4
Spoileron1_Model=Left_Outer_Spoiler
Spoileron1_MinAngle=0.0
Spoileron1_MaxAngle=-45.0
Spoileron1_BaseAngle=0.0

Spoileron2_Model=Left_Spoiler
Spoileron2_MinAngle=0.0
Spoileron2_MaxAngle=-45.0
Spoileron2_BaseAngle=0.0

Spoileron3_Model=Right_Outer_Spoiler
Spoileron3_MinAngle=0.0
Spoileron3_MaxAngle=-45.0
Spoileron3_BaseAngle=0.0

Spoileron4_Model=Right_Spoiler
Spoileron4_MinAngle=0.0
Spoileron4_MaxAngle=-45.0
Spoileron4_BaseAngle=0.0

NumberOfRudders=1
Rudder1_Model=Rudder
Rudder1_MinAngle=-30.0
Rudder1_MaxAngle=30.0
Rudder1_BaseAngle=0.0

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=6

[SensorSystem1] #Cockpit
# Cockpit
Type=Visual
SystemName=Optics
Mount=Dummy
ViewArcs=-150,150|-25,91
ModuleType=Sensor

[SensorSystem2] #AN/APS-137
Type=Radar
SystemName=AN/APS-137
Mount=Dummy
ModuleType=Sensor

[SensorSystem3] #FLIR
# FLIR
Type=Infrared
SystemName=OR-236
Mount=Dummy
ViewArcs=-150,150|-25,91
ModuleType=Sensor

#---------- ESM ----------
[SensorSystem4] #RWR
Type=ESM
SystemName=AircraftRWR
Mount=Dummy
ModuleType=Sensor

[SensorSystem5] #ELINT
Type=ESM
SystemName=AN/ALR-81
Mount=Dummy
ModuleType=Sensor

[SensorSystem6] #ELINT
Type=ESM
SystemName=AN/ALR-82
Mount=Dummy
ModuleType=Sensor

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=1
AvailableLoadouts=Recon

[WeaponSystem1] #Chaff
Type=Chaff
SystemName=US_AIR_CHAFF_DISP
#Sensors
#Animations
#Mount
Mount=Dummy
#MountPosition=0,-0.01,-0.016
#Containers
ContainerBase=Dummy
#Angles
#Loading
AssociatedMagazine=WeaponMagazineChaff
#Effects
NumberOfEffects=4
DelayBetweenLaunches=0.1
#Other
WorksStandalone=True
ModuleType=Weapon

[--------------------------- Loadouts ---------------------------]
[WeaponSystem1Empty]
#Nothing except two 300 USG external fuel tanks, approx range 6180 km
ReadyUpTime=30               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=60             // in minutes. Time that plane will spend in maintenance after landing.
Fuel=1817

[WeaponSystem1Recon]
ReadyUpTime=30               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=60             // in minutes. Time that plane will spend in maintenance after landing.
Fuel=1817

[---------- WeaponMagazines ----------]
[WeaponMagazineChaff]
NumberOfAmmunitionTypes=1
Ammunition1_Count=25
Ammunition1=wp_aircraft_chaff
ModuleType=WeaponMagazine

[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_s-3a
AssetBundleDamagedMesh=usn_s-3a_d
AssetBundleMaterial=usn_es-3a_mat.ini
AssetBundleMeshHullCollider=usn_s-3a_coll_hull
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=aircraft/usn_s-3a/
ResourcesRoot=usn_s-3a
ResourcesMesh=usn_s-3a
ResourcesMaterial=usn_es-3a_mat.ini

NumberOfDamageModels=3
DamageModel1=usn_s-3a_d1
DamageModelMaterial1=usn_es-3a_mat.ini
DamageModelLostWingSide1=Right
DamageModel2=usn_s-3a_d2
DamageModelMaterial2=usn_es-3a_mat.ini
DamageModelLostWingSide2=Left
DamageModel3=usn_s-3a_d3
DamageModelMaterial3=usn_es-3a_mat.ini
DamageModelLostWingSide3=Tail
############################################################
NumberOfSubModels=51

SubModel1=Cockpit
SubModel2=Canopyglass
SubModel3=Crew
SubModel4=WheelWells
SubModel5=Left_Spoiler
SubModel6=Left_Flap
SubModel7=Left_Outer_Wing
SubModel8=Left_Slat
SubModel9=Left_Outer_Spoiler
SubModel10=Left_Outer_Flap
SubModel11=Left_Aileron
SubModel12=Right_Spoiler
SubModel13=Right_Flap
SubModel14=Right_Outer_Wing
SubModel15=Right_Slat
SubModel16=Right_Outer_Spoiler
SubModel17=Right_Outer_Flap
SubModel18=Right_Aileron
SubModel19=Tailfin
SubModel20=Rudder
SubModel21=Left_Elevator
SubModel22=Right_Elevator
SubModel23=Nose_Gear
SubModel24=Nose_Gear_Strut
SubModel25=Nose_Gear_Launchbar
SubModel26=Nose_Gear_Door_L
SubModel27=Nose_Gear_Door_R
SubModel28=Left_Gear
SubModel29=Left_Gear_Door_1
SubModel30=Left_Gear_Door_2
SubModel31=Left_Gear_Door_3
SubModel32=Right_Gear
SubModel33=Right_Gear_Door_1
SubModel34=Right_Gear_Door_2
SubModel35=Right_Gear_Door_3
SubModel36=Arrester_Hook
SubModel37=Weapons_Bay
SubModel38=Bay_Door_L1
SubModel39=Bay_Door_L2
SubModel40=Bay_Door_L3
SubModel41=Bay_Door_R1
SubModel42=Bay_Door_R2
SubModel43=Bay_Door_R3
SubModel44=MAD
SubModel45=Fuel_Tank
SubModel46=Modex
Submodel47=Rudder_Modex
SubModel48=Left_Flap_Modex
SubModel49=Right_Flap_Modex
SubModel50=CarrierName
SubModel51=Top_Sensor

############################################################
# Fuselage
############################################################
[Cockpit]
Mesh=usn_s-3a_cockpit
Material=usn_es-3a_mat.ini

[Canopyglass]
Mesh=usn_s-3a_glass
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass

[Crew]
Mesh=usn_s-3a_crew
ResourcesMaterialFolder=characters/materials/
Material=usn_pilot_b_mat

[WheelWells]
Mesh=usn_s-3a_wheel_wells
Material=usn_s-3a_wheel_wells_mat

[Top_Sensor]
ResourcesMeshFolder=weapons/usaf_alq-119/
RootMesh=usaf_alq-119
Mesh=usaf_alq-119
ResourcesMaterialFolder=weapons/usn_pods/
Material=usn_es-3a_pod_mat.ini
Position=0,0.014,0.0097
Rotation=-1,0,180
Scale=2.35,1.2,1

############################################################
# Left Wing
############################################################

[Left_Spoiler]
Mesh=usn_s-3a_left_spoiler
Material=usn_es-3a_mat.ini
Position=-0.05,0.01092,-0.0056
Rotation=3.5,-90,0

[Left_Flap]
Mesh=usn_s-3a_left_flap
Material=usn_es-3a_mat.ini
Position=-0.07,0.00615,-0.01265
Rotation=0,-96,0

[Left_Outer_Wing]
Mesh=usn_s-3a_left_outer_wing
Material=usn_es-3a_mat.ini
Position=-0.06115,0.01086,0
Rotation=0,8,0

[Left_Slat]
Mesh=usn_s-3a_left_slat
Material=usn_es-3a_mat.ini
Parent=Left_Outer_Wing
Position=-0.0388,-0.00646,0.00027
Rotation=0,-117.5,0

[Left_Outer_Spoiler]
Mesh=usn_s-3a_left_outer_spoiler
Material=usn_es-3a_mat.ini
Parent=Left_Outer_Wing
Position=-0.01693,-0.00116,-0.01126
Rotation=1.5,-108.5,0

[Left_Outer_Flap]
Mesh=usn_s-3a_left_outer_flap
Material=usn_es-3a_mat.ini
Parent=Left_Outer_Wing
Position=-0.007,-0.0047,-0.01376
Rotation=0,-104,0

[Left_Aileron]
Mesh=usn_s-3a_left_aileron
//MeshType=ROLL_CONTROL
Material=usn_es-3a_mat.ini
Parent=Left_Outer_Wing
Position=-0.06532,-0.004,-0.0298
Rotation=0,-105,0

[Right_Spoiler]
Mesh=usn_s-3a_right_spoiler
Material=usn_es-3a_mat.ini
Position=0.05,0.01092,-0.0056
Rotation=-3.5,-90,0

[Right_Flap]
Mesh=usn_s-3a_right_flap
Material=usn_es-3a_mat.ini
Position=0.07,0.00615,-0.01265
Rotation=0,-84,0

[Right_Outer_Wing]
Mesh=usn_s-3a_right_outer_wing
Material=usn_es-3a_mat.ini
Position=0.06115,0.01086,0
Rotation=0,8,0

[Right_Slat]
Mesh=usn_s-3a_right_slat
Material=usn_es-3a_mat.ini
Parent=Right_Outer_Wing
Position=0.03725,-0.00647,0.0109
Rotation=0,-78.5,0

[Right_Outer_Spoiler]
Mesh=usn_s-3a_right_outer_spoiler
Material=usn_es-3a_mat.ini
Parent=Right_Outer_Wing
Position=0.01939,-0.00116,-0.00616
Rotation=-1.5,-87.5,0

[Right_Outer_Flap]
Mesh=usn_s-3a_right_outer_flap
Material=usn_es-3a_mat.ini
Parent=Right_Outer_Wing
Position=0.01052,-0.0047,-0.0113
Rotation=0,-92,0

[Right_Aileron]
Mesh=usn_s-3a_right_aileron
Material=usn_es-3a_mat.ini
Parent=Right_Outer_Wing
Position=0.07102,-0.00399,-0.01066
Rotation=0,-91,0

############################################################
# Tail Section
############################################################

[Tailfin]
Mesh=usn_s-3a_tailfin
//MeshType=YAW_CONTROL
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=-0.00155,0.03,-0.077
Rotation=-20,0,0

[Rudder]
Mesh=usn_s-3a_rudder
//MeshType=YAW_CONTROL
Material=usn_es-3a_mat.ini
Parent=Tailfin
Position=0.00155,0.02564,-0.0178
Rotation=80,0,0

[Left_Elevator]
Mesh=usn_s-3a_left_elevator
//MeshType=PITCH_CONTROL
Material=usn_es-3a_mat.ini
Position=-0.03,0.01033,-0.0938
Rotation=0,-9.5,-4.5

[Right_Elevator]
Mesh=usn_s-3a_right_elevator
//MeshType=PITCH_CONTROL
Material=usn_es-3a_mat.ini
Position=0.03,0.01033,-0.0938
Rotation=0,9.5,4.5

############################################################
# Landing Gear
############################################################

[Nose_Gear]
Mesh=usn_s-3a_nose_gear
Material=usn_es-3a_mat.ini
Parent=WheelWells
Position=0,-0.01422,0.08931
Rotation=0,0,0

[Nose_Gear_Strut]
Mesh=usn_s-3a_nose_gear_strut
Material=usn_es-3a_mat.ini
Parent=Nose_Gear
Position=0,-0.0089,-0.00213
Rotation=0,-90,0

[Nose_Gear_Launchbar]
Mesh=usn_s-3a_launch_bar
Material=usn_es-3a_mat.ini
Parent=Nose_Gear
Position=0,-0.0094,0.00137
Rotation=0,-90,0

[Nose_Gear_Door_L]
Mesh=usn_s-3a_nose_gear_door_L
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=-0.0035,-0.01867,0.07801
Rotation=-1,0,0

[Nose_Gear_Door_R]
Mesh=usn_s-3a_nose_gear_door_R
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=0.0035,-0.01867,0.07801
Rotation=-1,0,0

//----------------------------------------------------------

[Left_Gear]
Mesh=usn_s-3a_left_gear
Material=usn_es-3a_mat.ini
Parent=WheelWells
Position=-0.00624,-0.01604,-0.00222
Rotation=-51,-90,90

[Left_Gear_Door_1]
Mesh=usn_s-3a_left_gear_door_1
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=-0.01605,-0.00745,-0.02
Rotation=0,-2,0

[Left_Gear_Door_2]
Mesh=usn_s-3a_left_gear_door_2
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=-0.00457,-0.01868,-0.00591
Rotation=3,0,0

[Left_Gear_Door_3]
Mesh=usn_s-3a_left_gear_door_3
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=-0.00457,-0.01752,-0.02231
Rotation=4.5,0,0

//----------------------------------------------------------

[Right_Gear]
Mesh=usn_s-3a_right_gear
Material=usn_es-3a_mat.ini
Parent=WheelWells
Position=0.00624,-0.01604,-0.00222
Rotation=-51,90,-90

[Right_Gear_Door_1]
Mesh=usn_s-3a_right_gear_door_1
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=0.01605,-0.00745,-0.02
Rotation=0,-2,0

[Right_Gear_Door_2]
Mesh=usn_s-3a_right_gear_door_2
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=0.00457,-0.01868,-0.00591
Rotation=3,0,0

[Right_Gear_Door_3]
Mesh=usn_s-3a_right_gear_door_3
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=0.00457,-0.01752,-0.02231
Rotation=4.5,0,0

//----------------------------------------------------------

[Arrester_Hook]
Mesh=usn_s-3a_arrester_hook
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=0,-0.00986,-0.06875
Rotation=15,0,0

//----------------------------------------------------------

[Weapons_Bay]
Mesh=usn_s-3a_weaponsbay
Material=usn_s-3a_wheel_wells_mat
Parent=Anim_Controller
Position=0,0,0
Rotation=0,0,0

[Bay_Door_L1]
Mesh=usn_s-3a_bay_door_L1
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=-0.00457,-0.01934,0.025
Rotation=0,0,0

[Bay_Door_L2]
Mesh=usn_s-3a_bay_door_L2
Material=usn_es-3a_mat.ini
Parent=Bay_Door_L1
Position=-0.005,0.00095,0
Rotation=0,0,0

[Bay_Door_L3]
Mesh=usn_s-3a_bay_door_L3
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=-0.01685,-0.01046,0.025
Rotation=0,-1,0

[Bay_Door_R1]
Mesh=usn_s-3a_bay_door_R1
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=0.00457,-0.01934,0.025
Rotation=0,0,0

[Bay_Door_R2]
Mesh=usn_s-3a_bay_door_R2
Material=usn_es-3a_mat.ini
Parent=Bay_Door_R1
Position=0.005,0.00095,0
Rotation=0,0,0

[Bay_Door_R3]
Mesh=usn_s-3a_bay_door_R3
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=0.01685,-0.01046,0.025
Rotation=0,-1,0

[MAD]
Mesh=usn_s-3a_MAD
Material=usn_es-3a_mat.ini
Parent=Anim_Controller
Position=0,0,0.072
Rotation=0,0,0

[Fuel_Tank]
Mesh=usn_s-3a_fueltank
//MeshType=DROP_TANK
Material=usn_es-3a_mat.ini
Position=0,0,0
Rotation=0,0,0

[Modex]
Mesh=usn_s-3a_modex
ResourcesMaterialFolder=aircraft/materials/numbers/
Material=numbers

[Rudder_Modex]
Mesh=usn_s-3a_rudder_modex
ResourcesMaterialFolder=aircraft/materials/numbers/
Material=numbers
Parent=Rudder

[Left_Flap_Modex]
Mesh=usn_s-3a_left_flap_modex
ResourcesMaterialFolder=aircraft/materials/numbers/
Material=numbers
Parent=Left_Flap

[Right_Flap_Modex]
Mesh=usn_s-3a_right_flap_modex
ResourcesMaterialFolder=aircraft/materials/numbers/
Material=numbers
Parent=Right_Flap

[CarrierName]
Mesh=usn_s-3a_carrier_name
ResourcesMaterialFolder=aircraft/materials/emblem/
Material=emblem

[---------- Effects ----------]
[Particles]
ShotDownFireEffect=effects/aircraft_kill_effects/usn_s-3a_kill
ShotDownFireEffectPosition=0,0,0
HitWaterEffect=effects/splashes/emitters/splash_bomb
HitGroundEffect=effects/explosions/emitters/aircraft_hit_ground
HitAirEffectClass=LargeMissileExplosions
ExhaustSmoke=aircraft/particles/usn_s-3a_smokeemitter
#Contrail=aircraft/particles/usn_f-14a_contrail
TipVortexPosition=0.1463,0.0065,-0.027
TipVortex=effects/aircraft/emitters/tipvortex
#LeftWingVortexPosition=X,Y,Z
#LeftWingVortex=effects/aircraft/emitters/f-14_wingvortex
#RightWingVortexPosition=X,Y,Z
#RightWingVortex=effects/aircraft/emitters/f-14_wingvortex
ShockConePosition=0,0,0
ShockCone=effects/aircraft/emitters/shockcone
NoseGearParticlesParent=Nose_Gear
NoseGearParticlesPosition=0,-0.022,0

[Sounds]
############################################################
# Sounds
############################################################
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=3
# Front
EngineAudioClip=audio/aircraft/TF34
EngineAudioPosition=0,0,0
EngineAudioRollOff=Logarithmic
EngineAudioDistance=1,20
EngineAudioPitchRange=0.6,1.2
EngineAudioVolumeRange=0.1,0.5
# Rear
ExhaustAudioClip=audio/aircraft/jet_rear_2
ExhaustAudioPosition=0,0,0
ExhaustAudioRollOff=Logarithmic
ExhaustAudioDistance=1,20
ExhaustAudioPitchRange=1.0,1.0
ExhaustAudioVolumeRange=1.0,2.0
# Far
FarAudioClip=audio/aircraft/jet_far_2
FarAudioPosition=0,0,0
FarAudioRollOff=Logarithmic
FarAudioDistance=5,20
FarAudioPitch=1.0
FarAudioVolume=1.0
FarAudioFadeRange=0.0,0.25	      // nautical miles min/max

# Gears
#GearsAudioClip=audio/aircraft/gears
GearsAudioClip=audio/aircraft/LandingGearRetraction_v1
GearsAudioPosition=0,0,0
GearsAudioRollOff=Logarithmic
GearsAudioDistance=1,20
GearsAudioPitch=1.0
GearsAudioVolume=1.0
# Flaps
#FlapsAudioClip=audio/aircraft/flaps
FlapsAudioClip=audio/aircraft/LandingGearRetraction_v1
FlapsAudioPosition=0,0,0
FlapsAudioRollOff=Logarithmic
FlapsAudioDistance=1,20
FlapsAudioPitch=1.0
FlapsAudioVolume=1.0

//Front Sound = audio/aircraft/JE_Front_3 v=0.25, p=1.2
//Rear	Sound = audio/aircraft/JE_Burner_2
//Far	Sound = audio/aircraft/JetExhaustLoop p=0.75
//Afterburner = audio/aircraft/AfterburnerLarge_v1 p=0.75

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
NumberOfColliders=2
Collider1=col_body
Collider2=col_wings

[col_body]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.024,0.03,0.2

[col_wings]
Collider=Box
Position=0.0023,0.008,-0.0045
Rotation=0,0,0
Scale=0.28,0.006,0.058