[Language_en]
Name=Etendard Family Jets
Description=Adds the Etendard family of jets. This include the IVM, IVP, IVPM, Super Etendard and Super Etendard Modernisé Version 4.

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.7.0