[Shader]
Path=Marmoset/Transparent/Cutout/Diffuse IBL

#[Properties]
_Color=Color,{}808080ff
_SpecColor=Color,{}ffffffff
_SpecInt=Float,1.0
_Shininess=Float,6.5
_Fresnel=Float,0.75

[Textures]
_MainTex=assets/models/radars/DRBV20/textures/DRBV-20_diffuse2.png
_SpecTex=assets/models/radars/DRBV20/textures/DRBV-20_spec.png
_BumpMap=assets/models/radars/DRBV20/textures/DRBV-20_normal.png