#=========================================================================================================================================================
#                                                  REQUIRES STATS REVISION
#=========================================================================================================================================================
[General]
# TLAM
Type=Missile                           // can be Projectile, Missile, Torpedo
TargetType=ASuW                        // can be AAW, ASuW, ASW
LandAttackCapability=All // can be  All, Installation, Mobile, ShoreTargetsOnly

Mass=1450                              // in kg. Used for aircraft
AmmoPoints=4350                        // For Supply System. Defines "price" of ammunition based on mass, volume, 
complexity and availability


CIWSDefenceBonus=30                     // Less chance to be intercepted by CIWS because of anti-interception maneuvers
MissileDefenceBonus=0.30                     // Less chance to be intercepted by SAM because of anti-interception maneuvers
#Armored warhead & Deceptive Maneuver

DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=Standard  // referenced in effects/decals.ini

[SensorData]
#Visual
VisualIdentificationRange=6  // at what range in nm this unit can be visually identified
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=VerySmall
# Sonar related
# Transient
TransientRCS=Meager                    // Transient visibility on the radar
TransientVisualIdentificationRange=15  // Transient can be visually detected at this distance in nmi
TransientBaseNoise=220                 // In db

[---------- Warhead Data ----------]
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

# Fuze Types:
# 0 = Impact Fuze
# 1 = Proximity Fuze

[WarheadData]
WarheadType=0
Power=500
ImpactSize=VeryLarge                   // Impact size, can be small, medium, large, verylarge
Penetration=always                   // can be minor, moderate, heavy, always
FuzeType=0

[---------- Guidance ----------]
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing
[Guidance]
GuidanceType=0
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided
InitialFlightPhaseDuration=5         // time in seconds where the missile moves straight on without guiding
#======================================== Flight Profile ===========================================================
#flight phase 1: loft-----------------------------------------------------------------------------------------------------------------
#1st stage of missile flight - high altitude
MaxLoftAngle=80.0                      // Climb angle for initial loft
MaxLoftAlt=200000.0                     // in feet. Maximum altitude for lofting
#flight phase 2: sea skimming---------------------------------------------------------------------------------------------------------
#2nd stage of missile flight - low altitude
#flight phase 3: final flight phase (e.g. terminal popup)------------------------------------------------------------------------------
#Pop-Up. Missile climbs to higher altitude before activating the seeker. Or in some cases going even lower
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
TerminalApproachDist=5     //5         // in N. miles. Recommended to set this distance slightly less than the seeker range
TerminalDiveDistance=5     //5           // in N. miles.
SupportsBanking=True                   // if the missile will bank when turning
IgnoreHeightDifferenceForTargetDist=True  // useful for hight loft alt missiles to ignore the height for distance calculation

#========================================= Launch stats ============================================================
ApplyKinematics=False                   // 
MaxVelocity=3333                    // Stall at 500 knots   // Maximum speed in knots
#for acceleration, instead of calculating acceleration time based on the max velocity. MaxVelocity is still used, since missile stalls at 1/4 max velocity or 500 knots, whichever is less
AccelerationTime=8                  // 
Acceleration=15                    //
SustainerAccelerationTime=10            // 
SustainerAcceleration=10               // 
#---- Total Δv ≈ 2921 ≈ 8.6Ma

TypicalLaunchVelocity=0 
TypicalFiringAlt=0                    //TypicalTargetVelocity=0 
TypicalTargetAlt=0                     //
//It should have significant drag at low altitudes
//I can only shoot this way by setting it up


DragCoefficient=-1               // 

MaxTurnRate=180                       // Maximum turnrate in degrees per second                 
MinLaunchRange=8.0                     // Minimum launch range in nautical miles
MaxLaunchRange=37.79                    // Maximum launch range in nautical miles
LaunchReliability=98                   // The lower the value, the greater risk of misfire or accident (0...100)

#========================================     Seeker     ===========================================================
CircularErrorRadiusInstallation=150    // Circular error vs 'Installation' land units
#Homing
#N/A
#ECCM
AntiCountermeasuresBonus=0.40          // This value substracted from probability of spoofing by countermeasures (0...1)
AntiJammerBonus=0.30                   // This value substracted from probability of being jammed  (0...1)
#SelfDestruct
SelfDestructAfterTargetGone=False      // in case the target is destroyed and therefor lost, shall the missile be destroyed too?
SelfDestructDelay=5.0                  // delay in seconds for self destruction

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/wp_sa-n-3/
ResourcesRoot=wp_sa-n-3
ResourcesMesh=wp_sa-n-3
ResourcesMaterialFolder=materials/ships/
ResourcesMaterial=army_green_mat.ini
############################################################

[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
BoosterEffect=effects/weapons/emitters/sam_medium_effect
BoosterEffectPosition=0,0,-0.06
InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,-0.06
InFlightEffectStartTime=4.0  // in seconds, after that the Inflight Effect will be played if available

HitShipExplosion=VeryLargeGroundHitExplosions
HitShipExplosionRotation=0,25,0
HitAirExplosionClass=LargeMissileExplosions
HitAirExplosionRotation=0,25,0
HitWaterSplashClass=VeryLargeGroundHitExplosions
HitWaterSplashRotation=0,25,0
HitDefaultExplosion=VeryLargeGroundHitExplosions
HitDefaultExplosionRotation=0,25,0
HitGroundExplosionClass=VeryLargeGroundHitExplosions
HitGroundExplosionRotation=0,25,0
[---------- Colliders ----------]
[Colliders]
# creates the hit box for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.008,0.007,0.08