[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=89                                   // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini

[Ammunition]
Ammunition=usn_ssq-41

NumberOfAttachments=2
AttachmentPosition1=-0.0073,-0.025,0.02
AttachmentPosition2=0.0073,-0.025,0.02
SalvoFireAmount=1                       // number of shots fired

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################
############################################################
# Internal Resources folder related
############################################################

