[General]
SerialnumberReferences=Serial
EmblemReference=
NationFlagReference=Flag1
NumberOfSquadrons=2

[Default]
ResourcesLiveryFolder=aircraft/paf_mirage_iii/textures/
LiveryTexture=paf_mirage_iii_tx.png
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparent
Nation=Pakistan
ServiceDate=1970

[Squadron1]  #Squadron 7 (Early)- Haider, Pakistan
ResourcesSerialnumberFolder=aircraft/fr_mirage_iii/3sqn_raaf/serial/
SerialNumberPrefix=
SerialnumberTextures=21,31,84,100
ResourcesEmblemFolder=aircraft/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/paf_mirage_iii/textures/
LiveryTexture=paf_mirage_iii_tx.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Pakistan
ServiceDate=1970|2005