[AmmunitionNames]
# ------------------ AAM ------------------
fr_r-530=R.530,,AAM,French short to medium range semi active radar homing air to air missile.
rn_red_top=Red Top,,AAM,British short range limited all aspect IR guided missile, designed primarily to engage bombers at medium or high altitude.
rn_firestreak=Firestreak,,AAM,British first generation short range IR guided missile.
rn_skyflash=Skyflash,AAM,,A british medium range semi-active radar homing missile derived from the US AIM-7 Sparrow.

# ------------------ SAM ------------------
rn_seaslug_2=GWS.2,Seaslug MK.2,SAM,The GWS.2 Seaslug was a British first generation, beam riding, ship-launched surface-to-air missile. First employed in 1961, they were seen to have questionable effectiveness as they came into service. The GWS.2 variant slightly improved on the guidance and performance of the missile, but it (and the County-class Destroyers which used it) would be replaced by the more capable Sea Dart system in the 1980s.
rn_seaslug=GWS.1,Seaslug MK.1,SAM,The GWS.2 Seaslug was a British first generation, beam riding, ship-launched surface-to-air missile. First employed in 1961, they were seen to have questionable effectiveness as they came into service.
rn_seawolf_westminster=GWS.25,Sea Wolf,SAM,British point defence surface to air missile. Intended to provide an automated last line of defence against anti ship missiles and low flying aircraft. This is the conventionally launched variant. 
rn_seadart=GWS.30,Sea Dart,SAM,British medium range fleet defence surface to air missile. Designed as a replacement for the Sea Slug the Sea Dart is ramjet powered and has a semi-active radar seeker allowing it to engage supersonic aircraft. 
rn_seadart_mod2=GWS.30 Mod.2,Sea Dart,SAM,British medium range fleet defence surface to air missile. Designed as a replacement for the Sea Slug the Sea Dart is ramjet powered and has a semi-active radar seeker allowing it to engage supersonic aircraft.This is the improved Mod.2 version with better performance.
# ---------- Anti-radar Missiles ---------
rn_sea_eagle_arm=AS.37,Martel,ARM,The AS.37 Martel is an Anglo-French passive radar homing anti-radiation missile. The AS.37 features a selectable multi band radar seeker, allowing it to engage multiple types of radar sets.
# ---------- Anti-ship Missiles ----------
rn_sea_skua=Sea Skua,,ASM,The Sea Skua is a British lightweight short range air to surface missile.
rn_sea_eagle_asm=P.3T,Sea Eagle,ASM,The BAe dynamics P.3T Sea Eagle is a British anti-ship missile developed from the AS.37 Martel with a longer body, larger wings, more powerful engine, and redesigned avionics. Equipped with an active radar seeker the Sea Eagle is designed to be completely autonomous after firing, using a low flying sea skimming attack profile to avoid enemy detection and interception.
rn_sea_eagle_tv=AJ.168,Martel,ARM,The AJ.168 is functionally the same missile as the AS.37 anti-radiation missile but with the passive radar seeker replaced by a TV guidance module. Although jointly developed by Britain and France, the AJ.168 variant of the Martel was only used by the British. 
rn_as11=AS.11,,AGM,The AS-11 is a French made Air to Ground wire guided missile designed to engage armoured targets.
usn_agm-12b=AGM-12B,Bullpup,AGM,The AGM-12B is an American made anti surface missile guided via radio commands.
#-----------Land Strike only missiles---------

# ---------- Anti-sub Missiles ----------
rn_ikara=Ikara,,ASW,The Ikara missile is an Australian made anti submarine missile that carries a lightweight air dropped torpedo.
# ------------------ Depth Charges ------------------
rn_mk_11=Mk 11,250LB,Depth Charge,A British 250lb depth charge designed for use by aircraft.
depth_charge=Mk 7,50LB,Depth Charge,A British 50lb depth charge designed for use by aircraft.
# --------------- Torpedoes ---------------
rn_stingray_air=Sting Ray,Mod 0,ASW Torpedo,The Sting Ray Mod 0 is the Royal Navy's acoustic homing lightweight torpedo. Designed to attack modern Soviet high-performance submarines this variant is air dropped.
rn_stingray=Sting Ray,Mod 0,ASW Torpedo,The Sting Ray Mod 0 is the Royal Navy's acoustic homing lightweight torpedo. Designed to attack modern Soviet high-performance submarines this variant is ship launched.
rn_mk23=Mk 23,Grog,Torpedo,The Grog Mark 23 is a wire guided version of the Royal Navy's Mark 20 heavy weight electric torpedo.These torpedoes are wire guided and capable of being retargeted from the launch platform.
rn_mk24=Tigerfish,Mk 24-Mod-2,Torpedo,The Mark 24 is a British electric heavyweight torpedo. These torpedoes are wire guided and capable of being retargeted from the launch platform.
rn_mark8_mod4=Mk VIII,Mod 4,Torpedo,The Mark VIII was originally designed in 1925 and was the main submarine launched torpedo for the Royal Navy during WW2. This is the updated 1965, and final, Mod 4 version, which was in use until the 1990's.
rn_mk30_air=Mk 30,Mod 1,Torpedo,The Mark 30 is a British electric lightweight air dropped torpedo.These torpedoes are designed to engage submarines with passive sonar detection.
rn_mk44_air=Mk 44,Mod 1,Torpedo,The Mark 44 is a British electric lightweight air dropped torpedo.These torpedoes are designed to engage submarines with passive sonar detection.
# ------------------ Bombs -----------------
rn_gp_500=GP-500LB,,Bomb,A 500lb general purpose British made bomb.
rn_gp_1000=GP-1000LB,,Bomb,A 1000lb general purpose British made bomb.
# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------
rn_2inch=2-Inch RP,RP-2,FFAR,The 2-Inch Rocket was a replacement for the SNEB in royal navy service for concerns that radars onboard ships would set off the SNEB rockets.
rn_rp_3_ap=3.5-Inch AP,RP-3,FFAR,The 3-Inch Rocket was a World War 2 rocket capable of being fitted with a variety of warheads.
rn_rp_3_sap=3.5-Inch SAP,RP-3,FFAR,The 3-Inch Rocket was a World War 2 rocket capable of being fitted with a variety of warheads.
# ------------------ MLRS -----------------

# ------------------ Guns -----------------
rn_cal_84mm=84mm
rn_cal_120mm=120mm
# ------------------ CIWS -----------------
usn_cal_03in=0.30 inch
usn_cal_7.62mm=7.62mm
# ----------- Noisemakers/Chaff -----------
rn_jezebel=Jezebel,DIFAR,Sonobuoy,The Dowty Mini-Jezebel is a Directional Frequency Analysis and Recording (DIFAR) type sonobuoy.
# ----------------- Decoys ----------------

# ----------------- Special ----------------

# ----------------- Fueltanks ----------------
rn_tank_230_sea_harrier=230 Gallon Fuel Tank
rn_tank_100_as_4=100 Gallon Fuel Tank
rn_tank_300_s1=300 Gallon Fuel Tank


