[****************************** All nations ******************************]

[ -------------------- Land Targets Industrial: Fueltanks ----------------]

[ -------------------- Land Targets Industrial: Offshore Oil Platforms ----]

[ -------------------- Land Targets Industrial: Refineries ----------------]
[Oil_pump]
Type=Установка
DefaultDescription=Один масляный насос, используемый сотнями на нефтяных месторождениях
Default=Нефтяной насос,Насос
Variant1=Желтый нефтяной насос,Насос

[Oil_refinery]
Type=Установка
DefaultDescription=Обычный нефтеперерабатывающий завод
Default=Нефтеперерабатывающий завод,Переработка

[ -------------------- Land Targets Ports ----------------]
[ -------------------- Airbases, airfields ----------------]

[ -------------------- Radars -------------------- ]
[ -------------------- Radios and Comms -------------------- ]

[ -------------------- SAM Sites -------------------- ]
[ -------------------- AShM Sites -------------------- ]
[ -------------------- Artillery Sites -------------------- ]
[ -------------------- Vehicles -------------------- ]
[--------------------Bunkers----------------------]
[Ammo_Bunker]
Type=Бункер
DefaultDescription=Бетонный Бункер Для Хранения Боеприпасов
Default=Бункер для боеприпасов, Бункер для боеприпасов

[Bunker_2]
Type=Бункер
DefaultDescription=Бетонный бункер с двумя бойницами для стрельбы
Default=Бункер Тип 2, Бункер

[TBunkerTrench]
Type=Бункер
DefaultDescription=Высокий бетонный бункер с небольшими траншеями слева, справа и сзади.
Default=Бункер с траншеей,Т-Бункер
Variant1=Пустынный Т-бункер,Т-Бункер
[--------------------Bases------------------------]
[FOB]
Type=Военная база
DefaultDescription=Передовая оперативная база, достаточно большая для нескольких отрядов солдат вблизи линии фронта
Default=Передовая оперативная база,FOB
Variant1=Пустынная передовая оперативная база,FOB

[US_Missile]
Type=Ракетная база
DefaultDescription=База с десятью ракетами МБР
Default=Ракетная база, Ракетная база
[---------------------------------Trenches---------------]
[Omega_trench]
Type=Траншея
DefaultDescription=Траншея в форме символа Омега
Default=Омега-траншея,U-траншея
Variant1=Пустынная Омега-траншея,U-траншея

[------------------Targets--------------------]
#[50M_target]this is currently bugged
#Type=Installation
#Default=50 Metre Diameter Target, 50M Target

[4tentgroup]
Type=Палатка
DefaultDescription=Четыре палатки с бочками
Default=4 Палатки,Палатки
Variant1=4 Зеленые палатки,Палатки

[****************************** China ***********************************]
[ -------------------- Land Targets Industrial ----------------]
[ -------------------- Land Targets Ports ----------------]
[ -------------------- Airbases, airfields ----------------]
[ -------------------- Radars -------------------- ]
[ -------------------- SAM Sites -------------------- ]
[ -------------------- AShM Sites -------------------- ]
[ -------------------- Artillery Sites -------------------- ]

[ -------------------- Vehicles -------------------- ]

[****************************** Iceland ***********************************]
[ -------------------- Land Targets Industrial ----------------]
[ -------------------- Land Targets Ports ----------------]
[ -------------------- Airbases, airfields ----------------]

[ -------------------- Radars -------------------- ]
[ -------------------- SAM Sites -------------------- ]
[ -------------------- AShM Sites -------------------- ]
[ -------------------- Artillery Sites -------------------- ]
[ -------------------- Vehicles -------------------- ]

[****************************** Iraq ***********************************]
[ -------------------- Land Targets Industrial ----------------]
[ -------------------- Land Targets Ports ----------------]
[ -------------------- Airbases, airfields ----------------]
[ -------------------- Radars -------------------- ]
[ -------------------- SAM Sites -------------------- ]
[ -------------------- AShM Sites -------------------- ]
[ -------------------- Artillery Sites -------------------- ]
[ -------------------- Vehicles -------------------- ]

[****************************** Israel ******************************]
[ -------------------- Land Targets Industrial ----------------]
[ -------------------- Land Targets Ports ----------------]
[ -------------------- Airbases, airfields ----------------]
[ -------------------- Radars -------------------- ]
[ -------------------- SAM Sites -------------------- ]
[idf_dsws]
Type=Позиция ПВО
Default="Праща Давида" ТПУ,"Праща Давида"
Variant1="Праща Давида" ТПУ,"Праща Давида"

[idf_dsws_radar]
Type=Radar
Default="Праща Давида" Радар,"Праща Давида" Радар
Variant1="Праща Давида" Радар,"Праща Давида" Радар

[ -------------------- AShM Sites -------------------- ]
[ -------------------- Artillery Sites -------------------- ]
[ -------------------- Vehicles -------------------- ]

[****************************** Japan ***********************************]
[ -------------------- Land Targets Industrial ----------------]
[ -------------------- Land Targets Ports ----------------]
[ -------------------- Airbases, airfields ----------------]
[ -------------------- Radars -------------------- ]
[ -------------------- SAM Sites -------------------- ]

[ -------------------- AShM Sites -------------------- ]
[ -------------------- Artillery Sites -------------------- ]
[ -------------------- Vehicles -------------------- ]

[****************************** US NATO ***********************************]
[ -------------------- Land Targets Industrial ----------------]
[ -------------------- Land Targets Ports ----------------]
[ -------------------- Airbases, airfields ----------------]


[ -------------------- SAM Sites -------------------- ]

[ -------------------- AShM Sites -------------------- ]
[ -------------------- Artillery Sites -------------------- ]

[ -------------------- Vehicles -------------------- ]


[****************************** Finland ***********************************]
[ -------------------- Artillery Sites -------------------- ]

[****************************** Soviet Union ******************************]
[ -------------------- Land Targets Industrial ----------------]
[ -------------------- Land Targets Ports ----------------]
[ -------------------- Airbases, airfields ----------------]

[ -------------------- Radars -------------------- ]


[ -------------------- SAM Sites -------------------- ]

[ -------------------- AShM Sites -------------------- ]

[ -------------------- Artillery Sites -------------------- ]


[ -------------------- Vehicles -------------------- ]


[****************************** North Vietnam ******************************]
[ -------------------- Land Targets Industrial ----------------]


[ -------------------- Airbases, airfields ----------------]
[ -------------------- Radars -------------------- ]

[ -------------------- SAM Sites -------------------- ]
[ -------------------- AShM Sites -------------------- ]
[ -------------------- Artillery Sites -------------------- ]


[ -------------------- Ports -------------------- ]

[shahed_tel_white]
Type=Мобильная система запуска
Default=Герань-136-белая,Герань-136-белая
DefaultDescription=Передвижная пусковая платформа, предназначенная для запуска спец боеприпасов. Она может быстро перемещаться и позволяет гибко и недорого поражать неподвижные или слабо защищенные цели с помощью автономных или дистанционно управляемых беспилотных летательных аппаратов-камикадзе.
Variant1=Герань-136-белая,Герань-136-белая


[shahed_tel_black]
Type=Мобильная система запуска
Default=Герань-136-черная,Герань-136-черная
DefaultDescription=Передвижная пусковая платформа, предназначенная для запуска спец боеприпасов. Она может быстро перемещаться и позволяет гибко и недорого поражать неподвижные или слабо защищенные цели с помощью автономных или дистанционно управляемых беспилотных летательных аппаратов-камикадзе.
Variant1=Герань-136-черная,Герань-136-черная

[wp_ss-26_tel]
Type=ОТРК "Искандер"
Default=ОТРК "Искандер",ОТРК "Искандер"
Variant1=ОТРК "Искандер",ОТРК "Искандер"

[dronesquad705_1]
Type=Взвод БПЛА
Default=Полевая группа БПЛА, Полевая группа БПЛА
Variant1=Полевая группа БПЛА, Полевая группа БПЛА
Variant2=Полевая группа БПЛА, Полевая группа БПЛА

__________________________________________________________

[usa_airbase_6thGEN]
Type=Авиабаза
Default=Авиабаза США (6th Gen),Авиабаза
Variant1=Авиабаза ВМФ,АБ ВМФ
Variant2=Авиабаза,АБ

__________________________________________________________

[se_airbase_JAS_39]
Type=Авиабаза
Default=JAS_39Airbase,Авиабаза
Variant1=JAS_39Airbase,Авиабаза

____________________________________________________________

[****************************** All nations ******************************]

[usa_mbt_m1a1hc]
Type=ОБТ
Default=M1A1HC Abrams,M1A1HC
Variant1=M1A1HC Abrams,M1A1HC
Variant2=M1A1HC Abrams (Пустынный),M1A1HC

[wp_mbt_t-72b-1989]
Type=MBT
Default=T-72Б Вып.1989,T-72Б
Variant1=T-72Б Вып.1989,T-72Б
Variant2=T-72Б Вып.1989,T-72Б
Variant3=T-72Б Вып.1989,T-72Б
Variant4=T-72Б Вып.1989,T-72Б
Variant5=T-72Б Вып.1989,T-72Б
Variant6=T-72Б Вып.1989,T-72Б

[wp_mbt_t-72m1]
Type=ОБТ
Default=T-72M1,T-72M1
Variant1=T-72M1,T-72M1
Variant2=T-72M1,T-72M1
Variant3=T-72M1,T-72M1
Variant4=T-72M1,T-72M1
Variant5=T-72M1,T-72M1
Variant6=T-72M1,T-72M1

[wp_mbt_t-55amd-1]
Type=ОБТ
Default=T-55АМД-1,T-55АМД
Variant1=T-55АМД-1,T-55АМД
Variant2=T-55АМД-1,T-55АМД
Variant3=T-55АМД-1,T-55АМД
Variant4=T-55АМД-1,T-55АМД
Variant5=T-55АМД-1,T-55АМД
Variant6=T-55АМД-1,T-55АМД
Variant7=T-55АМД-1,T-55АМД

[uk_mbt_fv4030_4]
Type=ОБТ
Default=FV4030/4 Challenger 1,FV4030/4
Variant1=FV4030/4 Challenger 1,FV4030/4
Variant2=FV4030/4 Challenger 1（Песочный）,FV4030/4
Variant3=FV4030/4 Challenger 1（Зимний）,FV4030/4

[wp_td_2s25]
Type=ПТ
Default=2S25 Спрут-СД,2С25
Variant1=2S25 Спрут-СД,2С25

[pla_mbt_ztz-96]
Type=ОБТ
Default=ZTZ-96,ZTZ-96
Variant1=ZTZ-96,ZTZ-96

[pla_td_ptz-89]
Type=ПТ
Default=PTZ-89,PTZ-89
Variant1=PTZ-89,PTZ-89

[brd_mbt_leo2a4]
Type=ОБТ
Default=Leopord 2A4,Leo2A4
Variant1=Leopord 2A4,Leo2A4

[wp_ifv_bmp-1]
Type=БМП
Default=БМП-1,БМП-1
Variant1=БМП-1,БМП-1
Variant2=БМП-1,БМП-1
Variant3=БМП-1,БМП-1
Variant4=БМП-1,БМП-1
Variant5=БМП-1,БМП-1
Variant6=БМП-1,БМП-1

[wp_ifv_bmp-2]
Type=БМП
Default=БМП-2,БМП-2
Variant1=БМП-2,БМП-2
Variant2=БМП-2,БМП-2
Variant3=БМП-2,БМП-2
Variant4=БМП-2,БМП-2
Variant5=БМП-2,БМП-2
Variant6=БМП-2,БМП-2

[uk_ifv_fv510]
Type=БМП
Default=FV510,FV510
Variant1=FV510,FV510
Variant2=FV510（Песчаный）,FV510
Variant3=FV510（Зимний）,FV510
Variant4=FV510（ООН）,FV510

[uk_ifv_fv510ua]
Type=БМП
Default=FV510UA,FV510UA
Variant1=FV510UA,FV510UA
Variant2=FV510UA（Песчаный）,FV510UA
Variant3=FV510UA（Зимний）,FV510UA

[brd_ifv_marder_1a3]
Type=БМП
Default=Marder 1A3,Marder 1A3
Variant1=Marder 1A3,Marder 1A3

[usa_slm_tads_hmmwv]
Type=РЛС
Default=SLM TADS,БКС
Variant1=SLM TADS,БКС

[usa_slm_tel_hmmwv]
Type=ЗРК
Default=SLM TEL,SLM TEL
Variant1=SLM TEL,SLM TEL

[usa_spaa_adats]
Type=ЗСУ
Default=ADATS,ADATS
Variant1=ADATS,ADATS

[wp_spaa_mt-lb_zu-23]
Type=ЗСУ
Default=МТЛБ ЗУ-23,МТЛБ ЗУ-23
Variant1=МТЛБ ЗУ-23,МТЛБ ЗУ-23
Variant2=МТЛБ ЗУ-23,МТЛБ ЗУ-23
Variant3=МТЛБ ЗУ-23,МТЛБ ЗУ-23
Variant4=МТЛБ ЗУ-23,МТЛБ ЗУ-23

[wp_spaa_mt-lb_2m-3]
Type=ЗСУ
Default=МТЛБ 2M-3,МТЛБ 2M-3
Variant1=МТЛБ 2M-3,МТЛБ 2M-3
Variant2=МТЛБ 2M-3,МТЛБ 2M-3
Variant3=МТЛБ 2M-3,МТЛБ 2M-3
Variant4=МТЛБ 2M-3,МТЛБ 2M-3

[wp_spaa_mt-lb_s-60]
Type=ЗСУ
Default=МТЛБ С-60,МТЛБ С-60
Variant1=МТЛБ С-60,МТЛБ С-60
Variant2=МТЛБ С-60,МТЛБ С-60
Variant3=МТЛБ С-60,МТЛБ С-60
Variant4=МТЛБ С-60,МТЛБ С-60

[ru_spaa_mt-lb_sosna]
Type=ЗРК
Default=МТЛБ "Сосна",МТЛБ "Сосна"
Variant1=МТЛБ "Сосна",МТЛБ "Сосна"

[pla_spaa_pgz-09]
Type=ЗСУ
Default=PGZ-09,PGZ-09
Variant1=PGZ-09,PGZ-09

[brd_spaa_flarakpz_1]
Type=ЗРК
Default=Roland IFV,Roland
Variant1=Roland IFV,Roland
Variant2=Roland IFV,Roland

[usa_spaa_m247]
Type=ЗСУ
Default=M247 Sergeant York,M247
Variant1=M247 Sergeant York,M247

[it_spaa_sidam_25]
Type=ЗСУ
Default=SIDAM 25,SIDAM 25
Variant1=SIDAM 25,SIDAM 25

[swe_spaa_ito_90m]
Type=ЗРК
Default=ITO 90M,ITO 90M
Variant1=ITO 90M,ITO 90M
Variant1=ITO 90M,ITO 90M

[wp_spaa_sa-19]
Type=ЗСУ
Default=SA-19 Tunguska,SA-19
Variant1=SA-19 Tunguska,SA-19
Variant2=SA-19 Tunguska,SA-19

[wp_spaa_sa-19a]
Type=ЗСУ
Default=2С6М «Тунгуска-М»,2С6М
Variant1=2С6М «Тунгуска-М»,2С6М
Variant2=2С6М «Тунгуска-М»,2С6М

[brd_spaa_gepard]
Type=ЗСУ
Default=Gepard,Gepard
Variant1=Gepard,Gepard
Variant2=Gepard,Gepard

[brd_spaa_gepard1a2]
Type=ЗСУ
Default=Gepard 1A2,Gepard
Variant1=Gepard 1A2,Gepard
Variant2=Gepard 1A2,Gepard

[kr_k9]
Type=SPA
Default=K9 САУ, K9 САУ
Variant1=K9 САУ,K9 САУ
Variant2=K9 САУ,K9 САУ
Variant3=K9 САУ,K9 САУ
Variant4=K9 САУ,K9 САУ

[de_pzh2000]
Type=САУ
Default=PZH-2000 САУ,PZH-2000 САУ
Variant1=PZH-2000 САУ,PZH-2000 САУ
Variant2=PZH-2000 САУ, PZH-2000 САУ
Variant3=PZH-2000 САУ, PZH-2000 САУ
Variant4=PZH-2000 САУ, PZH-2000 САУ