[General]
SerialnumberReferences=Modex
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=5

[Default]
ResourcesLiveryFolder=aircraft/fr_as_532/textures/liveries/AS332F1_SuperPuma/
LiveryTexture=BRA_AS332F1_1.png
# nations are referenced in the layout.ini file:
Nation=Brazil

[Squadron1] # AS332F1 2º Esquadrão de Helicópteros de Emprego Geral – HU-2 (2nd Utility Helicopter Squadron),AS332F1
ResourcesSerialnumberFolder=aircraft/fr_as_532/hullnumbers/BRA/
SerialNumberPrefix=
SerialnumberTextures=7077.png,7070.png,7071.png,7072.png,7073.png,7074.png,7075.png,7076.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_as_532/textures/liveries/AS332F1_SuperPuma/
LiveryTexture=BRA_AS332F1_1.png
# nations are referenced in the layout.ini file:
Nation=Brazil
