[General]
SerialnumberReferences=Modex
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=2

[Default]
ResourcesLiveryFolder=aircraft/fr_ec_725/textures/liveries/
LiveryTexture=BRA_UH15_1.png
# nations are referenced in the layout.ini file:
Nation=Brazil

[Squadron1] # H225M (AH-15B) 2º Esquadrão de Helicópteros de Emprego Geral – HU-2 (“Pegasus”)(2nd Utility Helicopter Squadron),H225M
ResourcesSerialnumberFolder=aircraft/fr_ec_725/hullnumbers/BRA/
SerialNumberPrefix=
SerialnumberTextures=4101.png,4102.png,4103.png,4104.png
ResourcesEmblemFolder=aircraft/fr_ec_725/emblem/
EmblemTexture=
ResourcesLiveryFolder=aircraft/fr_ec_725/textures/liveries/
LiveryTexture=BRA_UH15_1.png
# nations are referenced in the layout.ini file:
Nation=Brazil


