#!extend ammunition/ger_IRIS-T_SLX.ini

[Guidance]
AutoAttackBelowMinAltitude=True
AutoAttackAboveMaxAltitude=False
OptimalTargetDist=15,40

MaxLoftAngle=80.0                      // Climb angle for initial loft

[Models]
InFlightSound=audio/environment/Missile-InFlight_WindOnly_Loop.wav
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/europack/models/
ResourcesRoot=weapons.obj
ResourcesMesh=eu_missile_IRIS-T_SLX
ResourcesMaterialFolder=assets/europack/materials/IRIS-T/
ResourcesMaterial=IRIS-T_SLX_mat.ini
ResourcesMeshForLaunch=
ResourcesMeshCanister=
ResourcesMeshSwitchTime=  // time in seconds after launch to switch from launch mesh to main mesh
############################################################

NumberOfStages=1

Stage1Mesh=eu_missile_IRIS-T_SLX
Stage1FlightEffect=effects/weapons/emitters/solidrocket_small/rocketmotor_solid_small_boost.ini
Stage1FlightEffectPosition=0,0,-0.023
Stage1BurnTime=16.5
Stage1AudioClip=audio/weapons/Missile-Medium_MotorLoop.wav


[---------- Effects ----------]

[Particles]
BoosterEffect=
BoosterEffectPosition=0,0,0
InFlightEffectClass=
InFlightEffectPosition=0,0,0
InFlightEffectStartTime=1  // in seconds, after that the Inflight Effect will be played if available

SustainerEffect=
SustainerEffectPosition=0,0,0
SustainerEffectStartTime=0.2

HitDefaultExplosionClass=MediumMissileExplosions
HitShipExplosionClass=MediumShipHitExplosion
HitAirExplosionClass=MediumMissileExplosions

HitWaterSplashClass=SmallWaterSplashes
HitGroundExplosionClass=RocketGroundHitExplosion