#!extend ammunition/usn_pac3_mse.ini

[Guidance]
AutoAttackBelowMinAltitude=True
AutoAttackAboveMaxAltitude=False
OptimalTargetDist=10,30

[Models]
InFlightSound=audio/environment/Missile-InFlight_WindOnly_Loop.wav
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/europack/models/
ResourcesRoot=weapons.obj
ResourcesMesh=eu_missile_PAC-3_MSE
ResourcesMaterialFolder=assets/europack/materials/PAC-3_MSE/
ResourcesMaterial=PAC-3_MSE_mat.ini
ResourcesMeshForLaunch=
ResourcesMeshCanister=
ResourcesMeshSwitchTime=  // time in seconds after launch to switch from launch mesh to main mesh
############################################################

NumberOfSubModels=2
SubModel1=ControlFinPair1
SubModel2=ControlFinPair2
ControlSurfaceMaxAngle=20
ControlSurfaceFullDeflectionRate=30
ControlSurfaceResponseTime=0.08

NumberOfStages=2

Stage1Mesh=eu_launch_PAC-3_MSE
Stage1SeparationTime=0.1
Stage1FlightEffect=effects/weapons/emitters/solidrocket_small/rocketmotor_solid_small_boost.ini
Stage1FlightEffectPosition=0,0,-0.035
Stage1BurnTime=0.1
Stage1AudioClip=audio/weapons/Missile-Large_MotorLoop.wav

Stage2Mesh=eu_missile_PAC-3_MSE_body
Stage2FlightEffect=effects/weapons/emitters/solidrocket_small/rocketmotor_solid_small_boost.ini
Stage2FlightEffectPosition=0,0,-0.035
Stage2BurnTime=9.0
Stage2AudioClip=audio/weapons/Missile-Medium_MotorLoop.wav


[ControlFinPair1]
Type=None
Mesh=eu_missile_PAC-3_MSE_fin_1
// Mesh contains two opposite fins; its origin is the centre of their hinge axis.
Position=0,0,-0.031473
Rotation=0,0,45
ControlSurface=True
ControlStages=2

[ControlFinPair2]
Type=None
Mesh=eu_missile_PAC-3_MSE_fin_2
Position=0,0,-0.031473
Rotation=0,0,-45
ControlSurface=True
ControlStages=2


[---------- Effects ----------]

[Particles]
BoosterEffect=
BoosterEffectPosition=0,0,0
InFlightEffect=
InFlightEffectPosition=0,0,0
InFlightEffectStartTime=1  // in seconds, after that the Inflight Effect will be played if available

SustainerEffect=
SustainerEffectPosition=0,0,0
SustainerEffectStartTime=0.2

HitDefaultExplosionClass=MediumMissileExplosions
HitShipExplosionClass=MediumShipHitExplosion
HitAirExplosionClass=MediumMissileExplosions

HitWaterSplashClass=SmallWaterSplashes
HitGroundExplosionClass=RocketGroundHitExplosion
