#!extend ammunition/usn_aim-9l.ini

[General]
DefaultCameraDistance=0.3
MinCameraDistanceForeAft=0.14
MinCameraDistanceBroadside=0.12
CameraPivotHeight=0.0

[---------- Mesh definitions----------]

[Models]
ResourcesFolder=assets/models/ammunition/aim-9/
ResourcesRoot=usn_aim-9l.obj
ResourcesMesh=aim-9l
ResourcesMaterial=usn_aim-9l_mat.ini
ResourcesMeshSwitchTime=0.2  // time in seconds after launch to switch from launch mesh to main mesh

NumberOfSubModels=3

SubModel1=ControlFinPair1
SubModel2=ControlFinPair2
SubModel3=Glas

ControlSurfaceMaxAngle=20
ControlSurfaceFullDeflectionRate=30
ControlSurfaceResponseTime=0.08

NumberOfStages=1

Stage1Mesh=aim-9l_body
Stage1MeshPosition=0,0,0
Stage1MeshRotation=0,0,0
Stage1FlightEffect=effects/weapons/emitters/solidrocket_aam_small/rocketmotor_solid_aam_small.ini
Stage1FlightEffectPosition=0,0,-0.021077
Stage1BurnTime=5.23
Stage1AudioClip=audio/weapons/Missile-Small_MotorLoop.wav

InFlightSound=audio/environment/Missile-InFlight_WindOnly_Loop.wav


[Glas]
Mesh=Glas
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass

[ControlFinPair1]
Type=None
Mesh=aim-9l_fin
Position=0,0,0.014161
Rotation=0,0,45
ControlSurface=True
ControlDirection=Reversed

[ControlFinPair2]
Type=None
Mesh=aim-9l_fin
Position=0,0,0.014161
Rotation=0,0,-45
ControlSurface=True
ControlDirection=Reversed

[---------- Effects ----------]
[Particles]
BoosterEffect=
BoosterEffectPosition=0,0,-0.022

InFlightEffectClass=
InFlightEffectPosition=0,0,-0.022
InFlightEffectStartTime=7.75  // in seconds, after that the Inflight Effect will be played if available

SustainerEffect=
SustainerEffectPosition=0,0,-0.02 
SustainerEffectStartTime=4.0

HitShipExplosionClass=MediumMissileExplosions
HitAirExplosionClass=MediumMissileExplosions
HitDefaultExplosionClass=MediumMissileExplosions
HitWaterSplashClass=SmallWaterSplashes
