[General]
SerialnumberReferences=Modex
EmblemReference=Emblem
NationFlagReference=Flag19
NumberOfSquadrons=2

[Default]
Nation=South_Korea

[Squadron1] #627 Helicopter Flight Squadron
ResourcesSerialnumberFolder=aircraft/rok_mk99/Serials/
SerialNumberPrefix=
SerialnumberTextures=rok_701.png,rok_702.png,rok_703.png,rok_704.png,rok_705.png,rok_706.png,rok_707.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=South_Korea
ServiceDate=1993|2000

[Squadron1] #629 Helicopter Flight Squadron
ResourcesSerialnumberFolder=aircraft/rok_mk99/Serials/
SerialNumberPrefix=
SerialnumberTextures=rok_708.png,rok_709.png,rok_710.png,rok_711.png,rok_712.png,rok_713.png
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=South_Korea
ServiceDate=1993|2000