[AmmunitionNames]
# ------------------ AAM ------------------
# ------------------ SAM ------------------


# ---------- Anti-radar Missiles ---------
# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------
# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------
# --------------- Torpedoes ---------------

u
# ------------------ Bombs -----------------
# ---------------- Sonobuoys ---------------
# ------------------ MLRS -----------------

# ------------------ Guns -----------------
wp_cal_100mm_d10_naval=100mm (HE),,,100mm HE shells for T-55 turrets converted into naval guns onboard armed merchants. The range is limited by the elevation limits of the turret.

# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------


# ----------------- Decoys ----------------


# ----------------- Special ----------------

# ----------------- Fueltanks ----------------
