
[LanguageResources]
Unknown=Unknown Group
#---------- Movement&Control----------
#---------- Sensors ----------
#---------- Weapons ----------

#---------- Magasines ----------

#---------- Decoys&Other ----------

#---------- Land Unit hit zones ------------

[SystemNames]
# ***********************************************************************************************
#                                          Main SYSTEMS
# ***********************************************************************************************
# ***********************************************************************************************
#                                          Sensor SYSTEMS
# ***********************************************************************************************
#======================================== Generic ========================================
#---------------------------------------- Visual ----------------------------------------



#---------------------------------------- Radar ----------------------------------------

#---------- Surface ships ----------
#---Air/Air&Surface---


#---Surface only---

#---Fire Control---
#SAM
#Guns

#---------- Submarines ----------
#---------------------------------------- Aircraft radar ----------------------------------------


#---------- Containers ----------

#---------------------------------------- Sonar ----------------------------------------
FishFinderSonar=Fish Finder Sonar|Generic civilian sonar used by fishing vessels to locate underwater objects, such as fish, wrecks, or foolish submarine captains.
NavSonar=Navigation Sonar|Generic civilian sonar used for navigation purposes.
MineDetectorSonar=Mine Detection Sonar|Generic high-frequency sonar made for finding naval mines first and foremost.


#Towed
#Dipping
#---------------------------------------- ESM ----------------------------------------
#---------------------------------------- ECM ----------------------------------------

#---------------------------------------- MAD ----------------------------------------
ASWTrawlerMAD=ASW Trawler MAD|Magnetic Anomaly Detector (MAD) for surface ships.

#---------------------------------------- Laser Designator ---------------------------

#============================================ France ===========================================
#---------------------------------------- Radar ----------------------------------------

#---------------------------------------- Sonar ----------------------------------------

#---------------------------------------- ESM ----------------------------------------

#---------------------------------------- ECM ----------------------------------------

#============================================ Israel ===========================================
#---------------------------------------- Radar ----------------------------------------
#---------- Surface ships ----------
#---Air/Air&Surface---

#---Surface only---
#---Fire Control---

#---------------------------------------- ESM ----------------------------------------
#---------------------------------------- ECM ----------------------------------------

#======================================== United States ========================================
#---------------------------------------- Visual ----------------------------------------

#---------------------------------------- Radar ----------------------------------------
#---------- Surface ships ----------
#---Air/Air&Surface---


#---Surface only---


#---Fire Control---
#SAM
#Guns


#---------- Submarines ----------


#---------------------------------------- Aircraft radar ----------------------------------------


#---------------------------------------- Land units radar ----------------------------------------
#---Air/Air&Surface---

#---Surface only---

#---Fire Control---

#---------------------------------------- Sonar ----------------------------------------

#---------- Submarines ----------

#---------------------------------------- ESM ----------------------------------------

#---------------------------------------- ECM ----------------------------------------
#---------------------------------------- MAD ----------------------------------------

#---------------------------------------- Laser Designator ---------------------------

#======================================== Soviet Union ========================================
#---------------------------------------- Radar ----------------------------------------
#---------- Surface ships ----------]
#---Air/Air&Surface---
#---Surface only---

#---Fire Control---
#SAM
#ASM

#Guns

#CIWS

#---------- Submarines ----------
#---------- Land Units ----------

#---------------------------------------- Aircraft Radar ----------------------------------------
#Air/Air&Surface

#Surface only

### Sonar
#---------------------------------------- Sonar ----------------------------------------
#---------- Surface ships ----------
#----- Towed/VDS -----


#---------- Submarines ----------

#----- Towed/VDS -----


#---------- Aircraft ----------


#---------- Sonobuoys ----------


#---------------------------------------- Visual/Infared ----------------------------------------


#---------------------------------------- ESM ----------------------------------------

#---------------------------------------- ECM ----------------------------------------

#---------------------------------------- MAD ----------------------------------------


#---------------------------------------- Laser Designator ---------------------------


#======================================== Royal Navy ========================================
#---------------------------------------- Radar ----------------------------------------

#---------------------------------------- ESM ----------------------------------------

#---------------------------------------- ECM ----------------------------------------

#---------------------------------------- Aircraft Radar ----------------------------------------
#Air/Air&Surface

#---------------------------------------- Sonar ----------------------------------------
#---------- Surface ships ----------


# ***********************************************************************************************
#                                          WEAPON SYSTEMS
# ***********************************************************************************************

#======================================== France ========================================

#======================================== Sweden ========================================

#======================================== United Kingdom ========================================

#======================================== United States ========================================
#---------------------------------------- Missile Launchers ----------------------------------------

#---------------------------------------- Torpedo Launchers ----------------------------------------
#********** Ships **********

#********** Submarines **********

#---------------------------------------- Land Guns ----------------------------------------

#---------------------------------------- Naval Guns ----------------------------------------

#---------------------------------------- CIWS ----------------------------------------

#---------------------------------------- Aircraft Guns ----------------------------------------

#---------------------------------------- Chaff ----------------------------------------

#---------------------------------------- Noisemaker ----------------------------------------

#======================================== Soviet Union ========================================
#---------------------------------------- Missile Launchers ----------------------------------------

#---------------------------------------- Torpedo Launchers ----------------------------------------
#********** Ships **********

#********** Submarines **********

#---------------------------------------- RBU ----------------------------------------

#---------------------------------------- Land Guns ----------------------------------------

#---------------------------------------- Naval Guns ----------------------------------------


#---------------------------------------- CIWS ----------------------------------------
#---------------------------------------- Aircraft Guns ----------------------------------------
#---------------------------------------- Chaff ----------------------------------------
#---------------------------------------- Noisemaker ----------------------------------------


# ***********************************************************************************************
#                                          Magazine SYSTEMS
# ***********************************************************************************************
# ------------------ SAM ------------------
# ---------- Anti-ship Missilies ----------
# ---------- Anti-sub  Missilies ----------
# ------------------ RBU ------------------
# --------------- Torpedoes ---------------


# ------------------ Guns -----------------
# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------


# ***********************************************************************************************
#                                          OTHER SYSTEMS
# ***********************************************************************************************
