[ ====================================== United Kingdom =================================== ]
[SeaWolf]
# Sea Wolf SAM launcher
HorizontalDegreesPerSecond=120   // rotation speed horizontally
VerticalDegreesPerSecond=120     // rotation speed vertically
ReloadTime=300.0           // time in seconds after firing until launcher is reloaded
MoveToRestPositionTime=10.0      // time in seconds the weapon goes back to rest position if not used
Warmup=False
ModuleType=SmallLauncher
SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,0
NumberOfAttachments=6

[MK12]
#Colt Mk 12
MissileInterceptChance=20       // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=45      // For CIWS. Chance to intercept missile with 0 defense rating
HorizontalDegreesPerSecond=100  // rotation speed horizontally
VerticalDegreesPerSecond=100    // rotation speed vertically
FireRate=1000                   // rounds per minute
BurstTime=1.5                   // the length of a single burst in time
RoundsLoaded=0                  // number of rounds loaded
RoundsMax=10000                 // number of rounds could be loaded into gun. Must not be less than 'RoundsLoaded'
ReloadTime=0                    // magazine reload time in seconds
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_m39_burst
EffectPosition=0,0,0
SpawnPosition=0,0,0.0

[Bofors_L/60_dual]
# Bofors L/60 dual 40mm Autocannon
#Users:rn_dd_battle, rn_dd_c-class
HorizontalDegreesPerSecond=40  // rotation speed horizontally
VerticalDegreesPerSecond=60    // rotation speed vertically
FireRate=240                  	// rounds per minute
RoundsLoaded=8              	// number of rounds in magazine, took higher number
ReloadTime=1                  // magazine reload time in seconds
RecoilTime=0.25                 // time in seconds for the recoil
RecoilStrength=0.00025           // amplitude of recoil
MoveToRestPositionTime=30.0      // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/AK725_fire_emitter //57mm_fire_emitter	//5inch_fire_emitter2	//wp_25mm_burst
EffectPosition=0,0,0.055
SpawnPosition=0,0,0.08
FireSequential=True
ModuleType=OpenMount

[Bofors_L/60_single]
# Bofors L/60 dual 40mm Autocannon
#Users:rn_dd_battle, rn_dd_c-class
HorizontalDegreesPerSecond=50  // rotation speed horizontally
VerticalDegreesPerSecond=60    // rotation speed vertically
FireRate=120                  	// rounds per minute
RoundsLoaded=4              	// number of rounds in magazine, took higher number
ReloadTime=1                  // magazine reload time in seconds
RecoilTime=0.25                 // time in seconds for the recoil
RecoilStrength=0.00025           // amplitude of recoil
MoveToRestPositionTime=30.0      // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/AK725_fire_emitter //57mm_fire_emitter	//5inch_fire_emitter2	//wp_25mm_burst
EffectPosition=0,0,0.068
SpawnPosition=0,0,0.08
ModuleType=OpenMount

[GSW-30]
# GSW-30 missile launcher
NumberOfAttachments=2
AttachmentPosition1=-0.012,-0.0075,0.002
AttachmentPosition2=0.012,-0.0075,0.002
HorizontalDegreesPerSecond=120   // rotation speed horizontally
VerticalDegreesPerSecond=120     // rotation speed vertically
ReloadTime=20.0           // time in seconds after firing until launcher is reloaded
MoveToRestPositionTime=30.0      // time in seconds the weapon goes back to rest position if not used
SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,0
PreLaunchDelay=1
ModuleType=SmallLauncher

[RN_SeacatQuad]
# Seacat SAM launcher
NumberOfAttachments=4
AttachmentPosition1=-0.013,-0.012,0.007
AttachmentPosition2=-0.013,0.012,0.007
AttachmentPosition3=0.013,0.012,0.007
AttachmentPosition4=0.013,-0.012,0.007
HorizontalDegreesPerSecond=120   // rotation speed horizontally
VerticalDegreesPerSecond=120     // rotation speed vertically
ReloadTime=30.0           // time in seconds after firing until launcher is reloaded
MoveToRestPositionTime=10.0      // time in seconds the weapon goes back to rest position if not used
Warmup=False
ModuleType=SmallLauncher

#SmokeEffect=effects/weapons/emitters/LauncherSmoke
#SmokeEffectPosition=0,0,0
PreLaunchDelay=1

[SeaslugLauncher]
NumberOfAttachments=2
AttachmentPosition1=-0.0185,0.0056,0
AttachmentPosition2=0.0185,0.0056,0
HorizontalDegreesPerSecond=90   // rotation speed horizontally
VerticalDegreesPerSecond=90     // rotation speed vertically
ReloadTime=45.0           // time in seconds after firing until launcher is reloaded
MoveToRestPositionTime=30.0      // time in seconds the weapon goes back to rest position if not used
SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,0
PreLaunchDelay=1
ModuleType=MediumLauncher

[Mark6]
# 4.5 inch Mark 8 naval gun in dual mk6 turret
#Users: ir_ffg_alvand
HorizontalDegreesPerSecond=20   // rotation speed horizontally
VerticalDegreesPerSecond=20     // rotation speed vertically
FireRate=40                     // rounds per minute
RoundsLoaded=16                // number of rounds loaded
ReloadTime=6                  // magazine reload time in seconds
RecoilTime=0.75                 // time in seconds for the recoil
RecoilStrength=0.00025           // amplitude of recoil
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/5inch_fire_emitter2
EffectPosition=0,0,0.08525
SpawnPosition=0,0,0.08525
ModuleType=MediumTurret
FireSequential=True

[Ikara]
# Ikara missile launcher
NumberOfAttachments=1
AttachmentPosition1=-0.0,0.009,0.018
HorizontalDegreesPerSecond=120   // rotation speed horizontally
VerticalDegreesPerSecond=120     // rotation speed vertically
ReloadTime=50.0           // time in seconds after firing until launcher is reloaded
MoveToRestPositionTime=30.0      // time in seconds the weapon goes back to rest position if not used
SmokeEffect=effects/weapons/emitters/LauncherSmoke
SmokeEffectPosition=0,0,0
PreLaunchDelay=1
ModuleType=SmallLauncher

[Oerlikon_20mm_v3]
# Oerlikon 20mm Autocannon
MissileInterceptChance=10      // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=25     // For CIWS. Chance to intercept aircraft with 0 defense rating
HorizontalDegreesPerSecond=50  // rotation speed horizontally
VerticalDegreesPerSecond=40    // rotation speed vertically
FireRate=250                   // rounds per minute
RoundsLoaded=60                // number of rounds in magazine
ReloadTime=5                   // magazine reload time in seconds
RecoilTime=0.55                 // time in seconds for the recoil
RecoilStrength=0.001           // amplitude of recoil
MoveToRestPositionTime=30.0    // time in seconds the weapon goes back to rest position if not used
#Effect=effects/weapons/emitters/usn_phalanx_burst
Effect=effects/weapons/emitters/usn_50cal_burst
EffectPosition=0,0,0
SpawnPosition=0,0,0.05
ModuleType=OpenMount

[QF20]
# QF 20 Pounder 84mm cannon
#Users: rn_mbt_mk5-1
HorizontalDegreesPerSecond=18   // rotation speed horizontally
VerticalDegreesPerSecond=18     // rotation speed vertically
FireRate=30                     // rounds per minute
RoundsLoaded=1                  // number of rounds loaded
ReloadTime=4.0                    // magazine reload time in seconds
RecoilTime=0.45                  // time in seconds for the recoil
RecoilStrength=0.00004          // amplitude of recoil
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/5inch_fire_emitter2
EffectPosition=0,0,0.082
SpawnPosition=0,0,0.126
ModuleType=MediumTurret

[L3A2]
# 7.62 mm (.30 in) Browning MG for Centurion Mk 5/1
MissileInterceptChance=-1      // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=5     // For CIWS. Chance to intercept aircraft with 0 defense rating
HorizontalDegreesPerSecond=55  // rotation speed horizontally
VerticalDegreesPerSecond=40    // rotation speed vertically
FireRate=600                   // rounds per minute
RoundsLoaded=200               // number of rounds in magazine
ReloadTime=8                  // magazine reload time in seconds
MoveToRestPositionTime=10.0    // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_50cal_burst
EffectPosition=0,-0.00043,-0.0008
SpawnPosition=0,0.00055,0.018
ModuleType=OpenMount

[L3A2_762]
# 7.62 mm Browning MG for Centurion Mk 13
MissileInterceptChance=-1      // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=5     // For CIWS. Chance to intercept aircraft with 0 defense rating
HorizontalDegreesPerSecond=55  // rotation speed horizontally
VerticalDegreesPerSecond=40    // rotation speed vertically
FireRate=600                   // rounds per minute
RoundsLoaded=200               // number of rounds in magazine
ReloadTime=8                  // magazine reload time in seconds
MoveToRestPositionTime=10.0    // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_50cal_burst
EffectPosition=0,-0.00043,-0.0008
SpawnPosition=0,0.00055,0.018
ModuleType=OpenMount

[L37A1]
# 7.62 mm MG
MissileInterceptChance=-1      // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=5     // For CIWS. Chance to intercept aircraft with 0 defense rating
HorizontalDegreesPerSecond=60  // rotation speed horizontally
VerticalDegreesPerSecond=35    // rotation speed vertically
FireRate=650                   // rounds per minute
RoundsLoaded=250               // number of rounds in magazine
ReloadTime=12                  // magazine reload time in seconds
MoveToRestPositionTime=6.0    // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/usn_50cal_burst
EffectPosition=0,-0.00043,-0.0008
SpawnPosition=0,0.00055,0.018
ModuleType=OpenMount

[L11A5]
# L11A5 120mm cannon
HorizontalDegreesPerSecond=16   // rotation speed horizontally
VerticalDegreesPerSecond=12     // rotation speed vertically
FireRate=12                     // rounds per minute
RoundsLoaded=1                  // number of rounds loaded
ReloadTime=7                    // magazine reload time in seconds
RecoilTime=0.55                  // time in seconds for the recoil
RecoilStrength=0.00008          // amplitude of recoil
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/5inch_fire_emitter2
EffectPosition=0,0,0.082
SpawnPosition=0,0,0.126
ModuleType=MediumTurret