[AmmunitionNames]

# ---------- Air To Air Missile ---------


# ---------- Anti-radar Missiles ---------
usn_mk234_nulka=Nulka,,Air Decoy,


-------------------------------------------------------------------------------------------