#CIC

[###-Generic-###]
[CIC_Carrier_Late]
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=140
EvaluationSlots=4

[CIC_Carrier_Modern]
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=170
EvaluationSlots=6

[AWACS]
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=400
EvaluationSlots=4

[###-SOVIET-###]
[TKS_2]
#Second-Gen Soviet Datalink
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=2
EvaluationSlots=2

[S_108]
#Late Russian Datalink
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=4
EvaluationSlots=2

[OSNOD]
#Modern Russian Datalink
ReactionTime=VeryFast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=6
EvaluationSlots=2

[Lesorub_M]
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=40
EvaluationSlots=4

[Sigma_22350]
ReactionTime=VeryFast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=120
EvaluationSlots=4

[Trebovaniye_M]
ReactionTime=VeryFast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=100
EvaluationSlots=4

[###-USA-###]
[Link_16]
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=6
EvaluationSlots=2

[AEGIS_Early]
# SPY-1 / 2000s
ReactionTime=VeryFast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=120
EvaluationSlots=4

[AEGIS_Late]
# SPY-1 / 2010s
ReactionTime=VeryFast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=160
EvaluationSlots=6

[AEGIS_Modern]
# SPY-6 / 2020s
ReactionTime=VeryFast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=200
EvaluationSlots=8

[ACDS]
# Carriers / 1990s
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=90
EvaluationSlots=3

[SSDS]
# Carriers / 2000s
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=180
EvaluationSlots=5

[###-CHINA-###]
[AEWC_KJ500]
ReactionTime=VeryFast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=1
CICSlots=100
EvaluationSlots=4

[AEWC_KJ600]
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=1
CICSlots=250
EvaluationSlots=3

[PLA_Datalink]
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=6
EvaluationSlots=2

[ZKJ_4A]
ReactionTime=Medium
DatalinkTier=4
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=48
EvaluationSlots=2

[ZKJ_5]
ReactionTime=Fast
DatalinkTier=4
DatalinkSource=True
SignalProcessingBonus=1
CICSlots=56
EvaluationSlots=3

[ZKJ_5A]
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=1
CICSlots=64
EvaluationSlots=3

[ZKJ_5B]
ReactionTime=Fast
DatalinkTier=4
DatalinkSource=True
SignalProcessingBonus=0
CICSlots=24
EvaluationSlots=2

[ZBJ_1]
ReactionTime=VeryFast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=1
CICSlots=80
EvaluationSlots=4

[ZBJ_1S]
ReactionTime=Fast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=1
CICSlots=64
EvaluationSlots=3

[ZBJ_1A]
ReactionTime=VeryFast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=1
CICSlots=100
EvaluationSlots=4

[ZBJ_1B]
ReactionTime=VeryFast
DatalinkTier=5
DatalinkSource=True
SignalProcessingBonus=1
CICSlots=180
EvaluationSlots=4