[Language_en]
Name=Bréguet Br.1050 Alizé
Description=Introduces the Bréguet Br.1050 Alizé for the French Navy and Indian Navy

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.6.0