#!/usr/bin/env python3
"""Build SEST_USN2027_Fixes: keep U.S. Navy 2027's Flight III Burke loadable.

U.S. Navy 2027 (3606774881) ships no hulls of its own. Every ship is a
`#!alias` patch over a Modern US Navy (3390330875) hull, and Modern US Navy
renames hulls almost daily. On 18 Sep 2026 its v567 retired
vessels/usn_ddg_burke_f3.ini (the Flight III became usn_ddg_burke_f3_125 and
usn_ddg_burke_f3_concept, both with a different weapon-slot layout), twelve
hours after 2027's last fix. 2027's usn_ddg_arleigh_flt3_2027 still aliases
the retired file, so at startup the loader fails to find the base, the
patch's own [FlightDeck] asks for an air group the base would have carried,
and the game dies with KeyNotFoundException 'AirGroup' - before any mission.

Re-pointing the alias at a new base is not a fix: the patch overwrites weapon
slots 2-9 as Mk 41 cells, and in the new layouts slot 2 is gone and slot 3 is
the Phalanx. What the game ran happily until the rename was OLD BASE + PATCH,
so that is what this pack ships, flattened: the retired base (vendored under
donors/, byte-faithful from the 2026-09-19 export of Modern US Navy pre-v567)
with the live 2027 patch merged over it the way the alias mechanism does -
section by section, key by key, patch wins - written as one standalone hull.
SEST_Integration sits above U.S. Navy 2027, so this file replaces the alias
and nothing depends on Modern US Navy's file names any more.

The same mod also deleted its ESSM Block 2 round (usn_rim-162e) without
editing the hulls that load it, so the flattened hull's Mk 41 cells are
re-pointed at Euromod's identical RIM-162H; see SUBSTITUTE_AMMO.

Guards (the builder exits non-zero, so build_all and git status notice):
  - the live patch must still alias usn_ddg_burke_f3.ini; once its author
    re-points it, this pack is redundant and must be retired
  - every substituted round must be genuinely gone and its replacement present
  - the donor base must carry [FlightDeck] and [AirGroup]
  - every non-loadout section the patch overrides must exist in the base
  - the flattened hull must carry [General], [FlightDeck], [AirGroup]

Meshes are not text and were not exported, so if Modern US Navy's mesh
cleanup (v566) dropped a part the old hull references, that part renders
missing in game; it does not crash the loader.

    python3 integration/usn-2027-fixes/build_pack.py
"""
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "integration" / "missions"))
from refine_civ_traffic import winning_file  # noqa: E402
OUT = HERE / "SEST_USN2027_Fixes"
PATCH = ROOT / "mods-source" / "3606774881" / "vessels" / "usn_ddg_arleigh_flt3_2027.ini"
PATCH_VARIANTS = PATCH.with_name("usn_ddg_arleigh_flt3_2027_variants.ini")
DONOR = HERE / "donors" / "usn_ddg_burke_f3.ini"
STALE_BASE = "vessels/usn_ddg_burke_f3.ini"

# Rounds the flattened hull loads that no enabled mod defines any more, and
# what to load instead. U.S. Navy 2027 deleted usn_rim-162e (its ESSM Block 2)
# on 15 Sep 2026 without editing the seventeen hulls that load it, so every
# 2027 Burke now carries a magazine of a round that does not exist - the game
# logs "could not find" and the cell never fires. Euromod's usn_rim-162h is
# the same missile (RIM-162H ESSM Block II), so the flattened hull loads that.
# Each substitute is checked against the load order below; drop an entry once
# upstream defines the original again.
SUBSTITUTE_AMMO = {"usn_rim-162e": "usn_rim-162h"}

INFO = """[Language_en]
Name=SEST USN 2027 Fixes
Description=Keeps U.S. Navy 2027's Flight III Arleigh Burke (usn_ddg_arleigh_flt3_2027) loadable after Modern US Navy retired the hull it was aliased to (v567, 18 Sep 2026). The alias patch is flattened onto the retired base so the ship no longer depends on Modern US Navy's file names. Without this the game dies at startup with KeyNotFoundException 'AirGroup'. Retire once U.S. Navy 2027 re-points its alias. Consolidated into SEST_Integration.

[Compatibility]
ApproximateVersion=0.8.2
"""

HEADER = """# SEST USN 2027 Fixes - usn_ddg_arleigh_flt3_2027, flattened.
# = Modern US Navy usn_ddg_burke_f3.ini (retired by v567, 18 Sep 2026; vendored copy)
#   + U.S. Navy 2027's usn_ddg_arleigh_flt3_2027 alias patch, merged section by
#   section and key by key with the patch winning, exactly as the alias would.
# Generated by integration/usn-2027-fixes/build_pack.py - do not edit by hand.
"""


def read(path):
    return path.read_text(encoding="utf-8-sig", errors="replace").replace("\r\n", "\n")


def name_of(header):
    """'[SensorSystem10]  #TB-37' and '[SensorSystem10] #SQR-19' are the same
    section: the game keys on the bracketed name, the comment is decoration."""
    return header[:header.index("]") + 1] if "]" in header else header


def sections(text):
    """[(header or None, [lines])] in file order; a header is the raw '[..]' line."""
    out, cur = [], (None, [])
    for line in text.split("\n"):
        if line.startswith("["):
            out.append(cur)
            cur = (line.strip(), [])
        else:
            cur[1].append(line)
    out.append(cur)
    return [s for s in out if s[0] is not None or any(l.strip() for l in s[1])]


def key_of(line):
    s = line.strip()
    if not s or s.startswith("#") or s.startswith("//") or "=" not in s:
        return None
    return s.split("=", 1)[0].strip()


def merge(base_secs, patch_secs):
    """Alias semantics: same section -> patch keys replace base keys (first
    occurrence), new keys append; unknown section -> appended whole."""
    index = {name_of(h): i for i, (h, _) in enumerate(base_secs) if h}
    out = [(h, list(lines)) for h, lines in base_secs]
    added, overridden = [], []
    for h, plines in patch_secs:
        if h is None:
            continue
        if name_of(h) in index:
            lines = out[index[name_of(h)]][1]
            for pl in plines:
                k = key_of(pl)
                if k is None:
                    if pl.strip():
                        lines.append(pl)
                    continue
                for i, bl in enumerate(lines):
                    if key_of(bl) == k:
                        lines[i] = pl
                        break
                else:
                    lines.append(pl)
            overridden.append(h)
        else:
            out.append((h, list(plines)))
            index[name_of(h)] = len(out) - 1
            added.append(h)
    return out, overridden, added


def main():
    if not PATCH.exists():
        sys.exit(f"donor patch missing (re-export mods-source?): {PATCH}")
    patch = read(PATCH)
    m = re.match(r"^#!alias\s+(\S+)", patch)
    if not m:
        sys.exit(f"{PATCH.name} no longer starts with #!alias - upstream restructured; re-check this pack")
    target = m.group(1).replace("\\", "/")
    if target != STALE_BASE:
        sys.exit(f"RETIRE THIS PACK: U.S. Navy 2027 now aliases {target}, not {STALE_BASE}. "
                 "Remove SEST_USN2027_Fixes from data/mod-catalog.json local_packs and delete "
                 "integration/usn-2027-fixes.")
    base = read(DONOR)
    if "[FlightDeck]" not in base or "[AirGroup]" not in base:
        sys.exit("vendored donor base lacks [FlightDeck]/[AirGroup] - wrong donor")

    base_secs = sections(base)
    patch_secs = sections(re.sub(r"^#!alias[^\n]*\n", "", patch, count=1))
    base_headers = {name_of(h) for h, _ in base_secs if h}
    # A PARTIAL system section (no Type= of its own) only makes sense on top of
    # a base section of the same number; a complete one (TLAM datalink, second
    # ESM set) is a legitimate addition and needs no base.
    for h, lines in patch_secs:
        if h and re.match(r"^\[(SensorSystem|WeaponSystem)\d+\]", h) and name_of(h) not in base_headers \
                and not any(key_of(l) == "Type" for l in lines):
            sys.exit(f"patch overrides {h} which the donor base does not define - layout drift")

    merged, overridden, added = merge(base_secs, patch_secs)
    text = HEADER + "\n".join(h + "\n" + "\n".join(lines) for h, lines in merged)
    text = re.sub(r"\n{3,}", "\n\n", text).rstrip("\n") + "\n"

    swapped = []
    for gone, live in SUBSTITUTE_AMMO.items():
        if not re.search(rf"^Ammunition\d+={re.escape(gone)}\s*$", text, re.M):
            continue
        if winning_file(f"ammunition/{gone}.ini") is not None:
            sys.exit(f"{gone} is defined again - drop it from SUBSTITUTE_AMMO and re-run")
        if winning_file(f"ammunition/{live}.ini") is None:
            sys.exit(f"substitute {live} for {gone} is not defined by any enabled mod either")
        text, n = re.subn(rf"^(Ammunition\d+=){re.escape(gone)}\s*$", rf"\g<1>{live}", text, flags=re.M)
        swapped.append(f"{gone} -> {live} x{n}")
    for must in ("[General]", "[FlightDeck]", "[AirGroup]", "[WeaponSystems]"):
        if must not in text:
            sys.exit(f"flattened hull lacks {must}")

    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "vessels").mkdir(parents=True)
    (OUT / "vessels" / PATCH.name).write_text(text, encoding="utf-8", newline="\n")
    # the patch's own variants file (hull numbers, names) travels with it unchanged
    shutil.copyfile(PATCH_VARIANTS, OUT / "vessels" / PATCH_VARIANTS.name)
    (OUT / "_info.ini").write_text(INFO, encoding="utf-8", newline="\n")
    print(f"{OUT.name}: {PATCH.name} flattened onto {DONOR.name}: "
          f"{len(overridden)} sections overridden, {len(added)} added, {text.count(chr(10))} lines")
    for s_ in swapped:
        print(f"  retired round substituted: {s_}")


if __name__ == "__main__":
    main()
