#!extend ammunition/pla_df-15b.ini

[Guidance]
InitialFlightPhaseDuration=1.0        // time in seconds where the missile moves straight on without guiding

[Models]
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/ammunition/df-15/
ResourcesRoot=df-15_ac.obj
ResourcesMesh=missile
ResourcesMaterial=df-15_mat.ini
ResourcesMeshForLaunch=
ResourcesMeshCanister=
ResourcesMeshSwitchTime=  // time in seconds after launch to switch from launch mesh to main mesh
############################################################

NumberOfStages=2

Stage1Mesh=missile
Stage1MeshPosition=0,0,0
Stage1MeshRotation=0,0,0
Stage1SeparationTime=54
Stage1FlightEffect=effects/weapons/emitters/sam_medium_effect
Stage1FlightEffectPosition=0,0,-0.035
Stage1BurnTime=53
Stage1SeparationEffect=effects/weapons/usn_rur-5_separation
Stage1SeparationEffectPosition=0,0,0
Stage1JettisonMesh=body
Stage1JettisonMeshPosition=0,0,0
Stage1JettisonMeshRotation=0,0,0

Stage2Mesh=warhead
Stage2MeshPosition=0,0,0
Stage2MeshRotation=0,0,0


[Particles]
BoosterEffect=
BoosterEffectPosition=0,0,-0.072

InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,-0.095
InFlightEffectStartTime=3  // in seconds, after that the Inflight Effect will be played if available

SustainerEffect=