#!extend ammunition/plaaf_pl-17.ini

[Guidance]

SecondThrustTime=1200|TerminalApproach

[Particles]
BoosterEffect=effects/weapons/new_motor_effects/aam_small_effect_new_boost_5s
BoosterEffectPosition=0,0,-0.024

InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,-0.03
InFlightEffectStartTime=0  // in seconds, after that the Inflight Effect will be played if available

SustainerEffect=

SecondThrustEffect=effects/weapons/new_motor_effects/aam_small_effect_new_sustain
SecondThrustEffectPosition=0,0,-0.03