#!extend ammunition/plaaf_pl-15.ini


[Guidance]

SecondThrustTime=1200|TerminalApproach+1

[Particles]
BoosterEffect=effects/weapons/emitters/aam_effect
BoosterEffectPosition=0,0,-0.008

InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,-0.022
InFlightEffectStartTime=3  // in seconds, after that the Inflight Effect will be played if available

SustainerEffect=

SecondThrustEffect=effects/weapons/emitters/aam_effect
SecondThrustEffectPosition=0,0,-0.008