#!extend ammunition/plan_hhq-9c.ini

[Guidance]
InitialFlightPhaseDuration=0.8         // time in seconds where the missile moves straight on without guiding

MinLaunchRange=2.0                     // Minimum launch range in nautical miles

[---------- Mesh definitions----------]

[Models]
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/ammunition/hhq-9c/
ResourcesRoot=hhq-9c_ac.obj
ResourcesMesh=hhq-9c
ResourcesMeshForLaunch=
ResourcesMeshSwitchTime=  // time in seconds after launch to switch from launch mesh to main mesh
ResourcesMaterial=hhq-9c_mat.ini
############################################################

NumberOfStages=2

Stage1Mesh=hhq-9c_s1
Stage1MeshPosition=0,0,0
Stage1MeshRotation=0,0,0
Stage1SeparationTime=8
Stage1FlightEffect=effects/weapons/emitters/sam_medium_effect
Stage1FlightEffectPosition=0,0,-0.035
Stage1BurnTime=8.0
Stage1SeparationEffect=effects/weapons/usn_rur-5_separation
Stage1SeparationEffectPosition=0,0,0
Stage1JettisonMesh=hhq-9c_s1d
Stage1JettisonMeshPosition=0,0,0
Stage1JettisonMeshRotation=0,0,0

Stage2Mesh=hhq-9c
Stage2MeshPosition=0,0,0
Stage2MeshRotation=0,0,0
Stage2FlightEffect=effects/weapons/emitters/sam_small_effect
Stage2FlightEffectPosition=0,0,-0.025
Stage2BurnTime=15.0



[Particles]
BoosterEffect=effects/weapons/emitters/LauncherSmoke
BoosterEffectPosition=0,0,-0.012
InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,-0.025
InFlightEffectStartTime=3  // in seconds, after that the Inflight Effect will be played if available

SustainerEffect=
SustainerEffectPosition=0,0,-0.021
SustainerEffectStartTime=6.0