#!extend ammunition/plan_yu-7_air.ini

[SubAmmunition]
SubAmmunitionType=Torpedo
SubAmmunitionName=plan_yu-7_ship
SubAmmunitionPosition=0,0,0|0,0,0
#SubAmmunitionRotation=0,0,0
SubAmmunitionDelayBetweenLaunches=0
SubAmmunitionTriggerMinTime=5
SubAmmunitionTriggerTime=12
SubAmmunitionEjectVelocity=3,8      // 弹出速度(knots)："min,max" 每枚随机；缺省=子弹药自带 EjectVelocity
SubAmmunitionEjectVelocityVector=0,90,0|0,-90,0
SubAmmunitionSpread=2000
SubAmmunitionSpreadAngle=120
SubAmmunitionInheritTarget=False
SubAmmunitionDisplayOnParent=True
MainAmmunitionDisappear=False
