[ -------------------- Guns -------------------- ]

[2A65_2S19]
# 155 mm howitzer used on the M109 Paladin SPH
# users: usa_spa_m109a2
HorizontalDegreesPerSecond=14   // rotation speed horizontally
VerticalDegreesPerSecond=12     // rotation speed vertically
FireRate=8                     // rounds per minute; Here it governs delay between barrels. Reload time influences an overall firerate of the turret.
RoundsLoaded=4                  // number of rounds loaded
ReloadTime=15                   // magazine reload time in seconds
RecoilTime=0.5                  // time in seconds for the recoil
RecoilStrength=0.0001           // amplitude of recoil
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/5inch_fire_emitter2
EffectPosition=-0.02042,0,0.010643        // From weapon system barrel
DustEffect=effects/weapons/emitters/medium_artillery_firing_dust
DustEffectPosition=0,0,0        // From weapon system mount
SpawnPosition=0,0,0.15
ModuleType=MediumTurret

[2A65_2S19_LASER]
# 155 mm howitzer used on the M109 Paladin SPH
# users: usa_spa_m109a2
HorizontalDegreesPerSecond=14   // rotation speed horizontally
VerticalDegreesPerSecond=12     // rotation speed vertically
FireRate=8                     // rounds per minute; Here it governs delay between barrels. Reload time influences an overall firerate of the turret.
RoundsLoaded=4                  // number of rounds loaded
ReloadTime=15                   // magazine reload time in seconds
RecoilTime=0.5                  // time in seconds for the recoil
RecoilStrength=0.0001           // amplitude of recoil
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/5inch_fire_emitter2
EffectPosition=-0.02042,0,0.010643        // From weapon system barrel
DustEffect=effects/weapons/emitters/medium_artillery_firing_dust
DustEffectPosition=0,0,0        // From weapon system mount
SpawnPosition=0,0,0.15
ModuleType=MediumTurret

[2A65_2S43]
# 155 mm howitzer used on the M109 Paladin SPH
# users: usa_spa_m109a2
HorizontalDegreesPerSecond=14   // rotation speed horizontally
VerticalDegreesPerSecond=12     // rotation speed vertically
FireRate=8                     // rounds per minute; Here it governs delay between barrels. Reload time influences an overall firerate of the turret.
RoundsLoaded=4                  // number of rounds loaded
ReloadTime=15                   // magazine reload time in seconds
RecoilTime=0.5                  // time in seconds for the recoil
RecoilStrength=0.0001           // amplitude of recoil
MoveToRestPositionTime=20.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/5inch_fire_emitter2
EffectPosition=0.01098,0.01363,0.011801        // From weapon system barrel
DustEffect=effects/weapons/emitters/medium_artillery_firing_dust
DustEffectPosition=0,0,0        // From weapon system mount
SpawnPosition=0,0,0.15
ModuleType=MediumTurret

[2A65_2S43_LASER]
# 155 mm howitzer used on the M109 Paladin SPH
# users: usa_spa_m109a2
HorizontalDegreesPerSecond=14   // rotation speed horizontally
VerticalDegreesPerSecond=12     // rotation speed vertically
FireRate=8                     // rounds per minute; Here it governs delay between barrels. Reload time influences an overall firerate of the turret.
RoundsLoaded=4                  // number of rounds loaded
ReloadTime=15                   // magazine reload time in seconds
RecoilTime=0.5                  // time in seconds for the recoil
RecoilStrength=0.0001           // amplitude of recoil
MoveToRestPositionTime=30.0     // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/5inch_fire_emitter2
EffectPosition=0.01098,0.01363,0.011801        // From weapon system barrel
DustEffect=effects/weapons/emitters/medium_artillery_firing_dust
DustEffectPosition=0,0,0        // From weapon system mount
SpawnPosition=0,0,0.15
ModuleType=MediumTurret