[Shader]
Path=Marmoset/Bumped Specular IBL

;[Properties]
;_Color=Color,White
;_SpecColor=Color,White
;_SpecInt=Float,1
;_Shininess=Float,6.5
;_Fresnel=Float,0.75

[Textures]
_MainTex=assets/europack/materials/SA-N-12/SA-N-12B_diff.png  
_SpecTex=assets/europack/materials/SA-N-12/SA-N-12B_spec.png  
_BumpMap=assets/europack/materials/SA-N-12/SA-N-12B_normal.png