[General]
SerialnumberReferences=Modex
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=1

[Default]
ResourcesLiveryFolder=aircraft/raaf_p-3c
LiveryTexture=raaf_p3c_old.png
Nation=Australia
ServiceDate=1978|2005

[Squadron1]  #VP-1 Screaming Eagles
ResourcesSerialnumberFolder=aircraft/usn_p-3c/vp-1/modex/
SerialNumberPrefix=
SerialnumberTextures=01,02,03,04,05,06,07,08,09
ResourcesEmblemFolder=
ResourcesLiveryFolder=aircraft/raaf_p-3c
LiveryTexture=raaf_p3c_old.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_australia
# nations are referenced in the layout.ini file:
Nation=Australia

