[AmmunitionNames]
# ------------------ AAM ------------------
fr_r511=R.511,Matra R.511,AAM,Le Matra R.511 était un missile air-air à guidage radar semi-actif, d'une portée de 7 kilomètres (4,3 milles nautiques) et doté d'un petit radar. Il fut utilisé dans les années 1960 par les forces aériennes françaises.

# ---------- Anti-ship Missiles ----------
fr_as_20=AS-20,Nord AS-20,Attaque au sol,Le Nord AS-20 était un missile air-sol radioguidé de première génération, dérivé du missile air-air Nord AA.20. Il était doté d'une ogive de 33 kg et fut principalement utilisé par les forces aériennes françaises, allemandes et italiennes dans les années 1960 et 1970.

# ------------------ FFAR -----------------
rn_rp_3_ap=3.5-Inch AP,RP-3,FFAR,La roquette de 3 pouces était une roquette britannique de la Seconde Guerre mondiale pouvant être équipée de diverses ogives.
rn_rp_3_sap=3.5-Inch SAP,RP-3,FFAR,La roquette de 3 pouces était une roquette britannique de la Seconde Guerre mondiale pouvant être équipée de diverses ogives.

# ------------------ Guns -----------------
rn_cal_20mm=20mm