[General]
NumberOfVariants=1

[Default]
Nation=Sweden

[Variant1]

CustomAirGroup=True
# ---------------------- Aircraft ---------------------
# ************************ USA ************************
#Fighters
#Fighters
se_jas-39=Squadron1,12
usaf_f-15a=Squadron1,8
usaf_f-4e=Squadron1,12

#Bombers
#Recon
usaf_e-3a=Default,2
usn_ra-5c=Default,6
#EW
usn_ea-6b=Default,4
#ASW
usn_p-3c=Squadron1,8
# -------------------- Helicopters --------------------]
usn_sh-2f=Default,0
usn_sh-3h=Default,0
usn_ch-46=Default,2

Nation=Sweden