[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag19
NumberOfSquadrons=2

[Default]
Nation=France

[Squadron1]#empty
ResourcesSerialnumberFolder=
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/gre_hu_16b/
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=flag_france
# nations are referenced in the layout.ini file:
Nation=France
[Squadron2]#empty
ResourcesSerialnumberFolder=
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/gre_hu_16b/
LiveryTexture=
ResourcesFlagFolder=
FlagTexture=flag_australia
# nations are referenced in the layout.ini file:
Nation=Australia