[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag9
AllVariantsAreOfSameNation=True //Speeds up nation sorting. Only needed if there is more then 1 nation variants. Default is 'true'
NumberOfSquadrons=3

[Default]
ResourcesSerialnumberFolder=aircraft/civ_707/acne/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_707/acne/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_707/acne/
LiveryTexture=civ_707_tx
SpecularTexture=civ_707_spec
NormalTexture=civ_707_nm
Nation=UK

[Squadron1]  42 Squadron
ResourcesSerialnumberFolder=aircraft/civ_707/acne/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_707/acne/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_707/acne/
LiveryTexture=civ_707_tx
SpecularTexture=civ_707_spec
NormalTexture=civ_707_nm
Nation=UK

[Squadron2]  51 Squadron
ResourcesSerialnumberFolder=aircraft/civ_707/acne/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_707/acne/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_707/acne/
LiveryTexture=civ_707_tx
SpecularTexture=civ_707_spec
NormalTexture=civ_707_nm
Nation=UK

[Squadron3]  120/201/206 Squadron 
ResourcesSerialnumberFolder=aircraft/civ_707/acne/serial/
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=aircraft/civ_707/acne/
EmblemTexture=
ResourcesLiveryFolder=aircraft/civ_707/acne/
LiveryTexture=civ_707_tx
SpecularTexture=civ_707_spec
NormalTexture=civ_707_nm
Nation=UK


#[Squadron4]  Air Carrier Network England
#ResourcesSerialnumberFolder=aircraft/civ_707/acne/serial/
#SerialNumberPrefix=
#SerialnumberTextures=
#ResourcesEmblemFolder=aircraft/civ_707/acne/
#EmblemTexture=
#ResourcesLiveryFolder=aircraft/civ_707/acne/
#LiveryTexture=civ_707_tx
#SpecularTexture=civ_707_spec
#NormalTexture=civ_707_nm
#Nation=UK
