[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=1

[Default]
ResourcesLiveryFolder=aircraft/usn_sh-3h/
LiveryTexture=rn_sh-3h_824.png
Nation=UK

[Squadron1] 
ResourcesSerialnumberFolder=textures/misc/
SerialNumberPrefix=
SerialnumberTextures=transparant
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparant
ResourcesLiveryFolder=aircraft/usn_sh-3h/
LiveryTexture=rn_sh-3h_824.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_rn
# nations are referenced in the layout.ini file:
Nation=UK
