[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=7

[Default]
ResourcesLiveryFolder=aircraft/usn_sh-3h/
LiveryTexture=rn_sh-3h_824.png
Nation=UK

[Squadron1] #810 NAS
ResourcesSerialnumberFolder=textures/misc/
SerialNumberPrefix=
SerialnumberTextures=transparant
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparant
ResourcesLiveryFolder=aircraft/usn_sh-3h/
LiveryTexture=rn_sh-3h_824.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_rn
# nations are referenced in the layout.ini file:
Nation=UK

[Squadron2] #814 NAS
ResourcesSerialnumberFolder=textures/misc/
SerialNumberPrefix=
SerialnumberTextures=transparant
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparant
ResourcesLiveryFolder=aircraft/usn_sh-3h/
LiveryTexture=rn_sh-3h_824.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_rn
# nations are referenced in the layout.ini file:
Nation=UK

[Squadron3] #819 NAS
ResourcesSerialnumberFolder=textures/misc/
SerialNumberPrefix=
SerialnumberTextures=transparant
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparant
ResourcesLiveryFolder=aircraft/usn_sh-3h/
LiveryTexture=rn_sh-3h_824.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_rn
# nations are referenced in the layout.ini file:
Nation=UK

[Squadron4] #820 NAS
ResourcesSerialnumberFolder=textures/misc/
SerialNumberPrefix=
SerialnumberTextures=transparant
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparant
ResourcesLiveryFolder=aircraft/usn_sh-3h/
LiveryTexture=rn_sh-3h_824.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_rn
# nations are referenced in the layout.ini file:
Nation=UK

[Squadron5] #824 NAS
ResourcesSerialnumberFolder=textures/misc/
SerialNumberPrefix=
SerialnumberTextures=transparant
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparant
ResourcesLiveryFolder=aircraft/usn_sh-3h/
LiveryTexture=rn_sh-3h_824.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_rn
# nations are referenced in the layout.ini file:
Nation=UK

[Squadron6] #826 NAS
ResourcesSerialnumberFolder=textures/misc/
SerialNumberPrefix=
SerialnumberTextures=transparant
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparant
ResourcesLiveryFolder=aircraft/usn_sh-3h/
LiveryTexture=rn_sh-3h_824.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_rn
# nations are referenced in the layout.ini file:
Nation=UK

[Squadron7] #846
ResourcesSerialnumberFolder=textures/misc/
SerialNumberPrefix=
SerialnumberTextures=transparant
ResourcesEmblemFolder=textures/Misc/
EmblemTexture=transparant
ResourcesLiveryFolder=aircraft/usn_sh-3h/
LiveryTexture=rn_sh-3h_845.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_rn
# nations are referenced in the layout.ini file:
Nation=UK