[---------- General Data ----------]
[General]
UnitType=Aircraft
CarrierCapable=True

DefaultCameraDistance=1
MinCameraDistanceForeAft=0.3
MinCameraDistanceBroadside=0.3
CameraPivotHeight=0.0

#Taxi values
GroundedPitchAngle=5          // this angle is the pitch (x) angle at ground with gears down
GroundPivot=0,-0.032,0.005      // defines the relative location of the landing gear
#LandingPivot=0,-0.027,-0.065    // defines the relative location of the arrestor hook
LandingPitch=6
OnDeckPositionOffset=0,0,-0.023

#Pilot=wp_pilot_k1m_a
#PilotPositions=0,-0.003,0.039
#EjectChance=0.6

[AI]
Role=Fighter,Bomber

[SensorData]
#Visual
VisualIdentificationRange=6.0  // Biggest range in nm at which this unit can be visually identified
IRSignature=SemiSmall
# Radar related (RCS => radar cross section)
RCS=SemiSmall

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_A4

[---------- Flight Model ----------]
[Engine]
EngineIntakeArea=2.8532

[FlightModel]
PitchGain=0.75                        // Vertical manuverability
VelocityGain=0.526                   // Acceleration
HeadingGain=3                         // Horizontal manuverability
YawRateLimit=130                      // in degrees per second

BankGain=2.3                          // Roll change speed
#MaxRollForHeading=55.0                // bank limit in normal flight
MaxRollRate=80.0                      // in degrees per second

ThrustGain=0.352                      // Thrust change speed
SpeedBrakeFractionGain=10            // Speed brakes deploy speed

SpeedDeltaPerAltitudeChange=0.0885

[Performance]
#Dimensions
WingSpan=8.382                         //meters
#Parameters
MaxG=8                                // Mostly for horizontal turns

MaxClimbRate=38.1                     //Meters per second
EmptyMass=4413.0                      // in kg, dry empty weight
MaxFuel=2767.0                       // in kg, internal

PerEngineMaxThrust=3600              //Newtons
PerEngineMaxAfterburnerThrust=3600   //Newtons
EngineCount=1

Ceiling=42250.0                       // ceiling in feet
CruiseAltitude=33000.0                  //in feet
#"Engine" efficiency at 0ft, 37000 ft, 65000 ft. Always 1 for cruise altitude
AltitudeEfficiency=0.5,0.5,0.25       // Defines fuel consumption with altitude

#Governing of max speed
MaxSpeedAtSeaLevel=564                //in knots, Defines max speed at altitude curve
StallSpeed=131.0                      //in knots
MachLimit=0.92                        //for 37000ft, Defines max speed at altitude curve

#SpeedAndRange   MachNumbers or knots, Specified units or multiplier (except Cruise range)
RangeUnits=Miles                      // Can be: Km. Any other value = nmi. Defines measurment units of ranges of SpeedAndRange values

SpeedAndRange_Landing=125,0.4         // Landing
SpeedAndRange_Loiter=200,0.6          // Loiter
SpeedAndRange_Cruise=432,1160         // Cruise
SpeedAndRange_Max=540,0.8             // Attack/Fast/High/Max without AB
#SpeedAndRange_Afterburner=580,0.2     // AB max

Altitudes=200,1000,3000,6000,10000,20000  // in feet

[---------- Main Systems ----------]
[FlightControls]
NumberOfAilerons=2
Aileron1_Model=Left_Aileron
Aileron1_MinAngle=-20.0
Aileron1_MaxAngle=30.0
Aileron1_BaseAngle=0.0
Aileron1_RotationAxis=X

Aileron2_Model=Right_Aileron
Aileron2_MinAngle=-20.0
Aileron2_MaxAngle=30.0
Aileron2_BaseAngle=0.0
Aileron2_RotationAxis=X

NumberOfElevators=1
Elevator1_Model=Left_Stabilator
Elevator1_MinAngle=-20.0
Elevator1_MaxAngle=20.0
Elevator1_BaseAngle=0.0
Elevator1_RotationAxis=X

Elevator2_Model=Right_Stabilator
Elevator2_MinAngle=20.0
Elevator2_MaxAngle=-20.0
Elevator2_BaseAngle=0.0
Elevator2_RotationAxis=Z

NumberOfRudders=1
Rudder1_Model=Rudder
Rudder1_MinAngle=-30.0
Rudder1_MaxAngle=30.0
Rudder1_RotationAxis=Y

AfterBurnerSubModel=Afterburner    // optional entry
MaxAfterBurnerIntensity=0.3
AfterBurnerFadeTime=0.5

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1

[SensorSystem1] #Cockpit
# Cockpit
Type=Visual
SystemName=Eyes 
Mount=Dummy
ViewArcs=-178,178|-25,91
ModuleType=Sensor

#Section TODO For PF/PFU variants
#[SensorSystem2] #AN/APQ-126 Radar
#Type=Radar
#SystemName=AN/APQ-126
#Mount=Dummy
#ModuleType=Sensor

#[SensorSystem3] #RWR
#Type=ESM
#SystemName=AircraftRWR
#Mount=Dummy
#ModuleType=Sensor

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=3
AvailableLoadouts=AirToAir,Strike

[WeaponSystem1]
Type=Hardpoint
SystemName=Hardpoint
AssociatedSensors=SensorSystem1

FiringArcs=-10,10

NumberOfStations=3

Station1=-0.03,-0.0162,-0.015         //Left Wing Station
Station2=0.03,-0.0162,-0.015          //Right Wing Station
Station3=0,-0.0162,-0.026              //Centerline Station

#Station3Rotation=

MEROffset=0,0.00146,0.02022 //0.011
MERPositions=0,-0.007790527,-0.01590017|0,-0.007790527,0.0173499|0.0045,-0.003790527,-0.01590017|0.0045,-0.003790527,0.0173499|-0.0045,-0.003790527,-0.01590017|-0.0045,-0.003790527,0.0173499
MERRotations=0,0,0|0,0,0|0,0,45|0,0,45|0,0,-45|0,0,-45

FTPositions=0,-0.003,0.02

# Guns 
[WeaponSystem2] #Gun 1: Colt Mk 12 20mm cannon
Type=CIWS
SystemName=M39
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=0.0097,-0.0111,0.026     //Placeholder
IsMountRotatable=True
#Containers
ContainerBase=Dummy
Gun=Dummy
AreContainersRotatable=True
#Angles
FiringArcs=-1,1
ElevationArc=-1,1
#Loading
#Ammunition=wp_cal_23mm
AssociatedMagazine=WeaponMagazine_Mk12_1
#Effects
#Other
IsOffensive=True
ModuleType=Weapon

[WeaponSystem3] #Gun 2: Colt Mk12 20mm cannon
Type=CIWS
SystemName=M39   //Placeholder
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=-0.0097,-0.0111,0.026     //Placeholder
IsMountRotatable=True
#Containers
ContainerBase=Dummy
Gun=Dummy
AreContainersRotatable=True
#Angles
FiringArcs=-1,1
ElevationArc=-1,1
#Loading
#Ammunition=wp_cal_23mm
AssociatedMagazine=WeaponMagazine_Mk12_2
#Effects
#Other
IsOffensive=True
ModuleType=Weapon

[--------------------------- Loadouts ---------------------------]
[WeaponSystem1Empty]
ReadyUpTime=5               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=120             // in minutes. Time that plane will spend in maintenance after landing.
SubModelsToHide=Pylon_Left,Pylon_Center,Pylon_Right,MER_Rack_Left,MER_Rack_Center,MER_Rack_Right
#Nothing

[WeaponSystem1Ferry]
ReadyUpTime=10           // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=120             // in minutes. Time that plane will spend in maintenance after landing.
SubModelsToHide=MER_Rack_Left,MER_Rack_Center,MER_Rack_Right
#Extended range recon configuration
#Station1=usn_tank_300_a-6|FT
#Station2=usn_tank_300_a-6|FT
Station3=usn_tank_300_a-6|FT

[WeaponSystem1Default]
ReadyUpTime=15               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=120             // in minutes. Time that plane will spend in maintenance after landing.
SubModelsToHide=MER_Rack_Left,MER_Rack_Right
Station1=usn_aim-9b
Station2=usn_aim-9b
Station3=usn_mk-82|MER

[WeaponSystem1AirToAir]
ReadyUpTime=15               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=120             // in minutes. Time that plane will spend in maintenance after landing.
SubModelsToHide=MER_Rack_Left,MER_Rack_Center,MER_Rack_Right
Station1=usn_aim-9b
Station2=usn_aim-9b

[WeaponSystem1Strike]
ReadyUpTime=15               // in minutes. Time that plane will spend refueling and rearming before takeoff.
CoolDownTime=120             // in minutes. Time that plane will spend in maintenance after landing.
SubModelsToHide=MER_Rack_Center
Station1=usn_mk-82|MER
Station2=usn_mk-82|MER
Station3=usn_tank_300_a-6|FT

[WeaponSystem1StrikeLongRange]
SubModelsToHide=

[WeaponSystem1CAS]
SubModelsToHide=

[---------- WeaponMagazines ----------]
############################################################
# Weapon Magazine Systems
############################################################
[WeaponMagazine_Mk12_1]
NumberOfAmmunitionTypes=1
Ammunition1_Count=100
Ammunition1=usn_cal_20mm
ModuleType=WeaponMagazine

[WeaponMagazine_Mk12_2]
NumberOfAmmunitionTypes=1
Ammunition1_Count=100
Ammunition1=usn_cal_20mm
ModuleType=WeaponMagazine


[--------------------------- Mesh definitions ---------------------------]
[Models]
LODLevels=2
LOD1Distance=0.5  // nautical miles
LOD2Distance=1.0  // nautical miles
############################################################
# AssetBundle related
############################################################

############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=aircraft/A4/
ResourcesRoot=A4_rigged.obj
ResourcesMesh=A4
ResourcesMaterial=A4_mat.ini

#NumberOfDamageModels=3
#DamageModel1=wp_mig-17_d_1
#DamageModelMaterial1=wp_mig-17_mat
#DamageModelLostWingSide1=Left
#DamageModel2=wp_mig-17_d_2
#DamageModelMaterial2=wp_mig-17_mat
#DamageModelLostWingSide2=Right
#DamageModel3=wp_mig-17_d_3
#DamageModelMaterial3=wp_mig-17_mat
#DamageModelLostWingSide3=Tail
############################################################
[Submodels]
SubModel1=window
#SubModel2=hump
SubModel3=rear_gear1
SubModel4=rear_gear
SubModel5=forward_gear
SubModel6=rear_gear_bay_door
SubModel7=rear_gear_bay_door1
SubModel8=rear_Gearbay
SubModel9=rear_Gearbay1
SubModel10=nose_gear_door
SubModel11=Left_slat
SubModel12=Left_Aileron
SubModel13=Left_Flap
SubModel14=Right_slat
SubModel15=Right_Aileron
SubModel16=Right_Flap
SubModel17=Rudder
SubModel18=Left_Stabilator
SubModel19=hook
SubModel20=Pylon_Left
SubModel21=Pylon_Center
SubModel22=Pylon_Right
SubModel23=MER_Rack_Left
SubModel24=MER_Rack_Center
SubModel25=MER_Rack_Right
############################################################
# Fuselage
############################################################
[window]
Mesh=window
Material=A4_mat.ini

[hump]
Mesh=hump
Material=A4_mat.ini

[rear_gear1]
Mesh=rear_gear
Material=A4_mat.ini
Position=0.01614303451270497,-0.012796244572902985,-0.01692198623259873
Rotation=0,0,0
Scale=0.95,1,1

[rear_gear]
Mesh=rear_gear
Material=A4_mat.ini
Position=-0.01614303451270497,-0.012796244572902985,-0.01692198623259873
Rotation=0,0,0
Scale=-0.95,1,1

[forward_gear]
Mesh=forward_gear
Material=A4_mat.ini
Position=0,-0.005454256246173517,0.03074993505834658
Rotation=0,0,0




[rear_gear_bay_door]
Mesh=rear_gear_bay_door_2
Material=A4_mat.ini
Position=0.017256725331754732,-0.01442828546961918,-0.014515225257146106
Rotation=3.369368308588984,-0.004348346805233303,0.019111943369902063

[rear_gear_bay_door1]
Mesh=rear_gear_bay_door_2
Material=A4_mat.ini
Position=-0.017256725331754732,-0.01442828546961918,-0.014515225257146106
Rotation=3.369368308588984,0.004348346805233303,-0.019111943369902063
Scale=-1,1,1

[rear_Gearbay]
Mesh=rear_gear_bay_door
Material=A4_mat.ini
Position=0.019930466448578904,-0.012806086388190745,-0.0000003039999242034422
Rotation=-0.004992934286514146,-0.0003805887519669216,0.0016257508602640336

[rear_Gearbay1]
Mesh=rear_gear_bay_door
Material=A4_mat.ini
Position=-0.019930466448578904,-0.012806086388190745,-0.0000003039999242034422
Rotation=-0.004992934286514146,0.0003805887519669216,-0.0016257508602640336
Scale=-1,1,1

[nose_gear_door]
Mesh=nose_gear_door
Material=A4_mat.ini
Position=-0.003,-0.01325,0.032999877729744206
Rotation=-2.0484,2.33415,0.08353
############################################################
# Left Wing
############################################################





[Left_slat]
Mesh=leading_slat
Material=A4_mat.ini
Scale=-1,1,1
Position=-0.03060315535982481,-0.010170456505288058,-0.0005050015992765027
Rotation=0.0007393488134047513,-40.937083447660164,-0.004253895440914399

[Left_Aileron]
Mesh=Alion
//MeshType=ROLL_CONTROL
Material=A4_mat.ini
Scale=-1,1,1
Position=-0.03456556688983675,-0.011192011029036698,-0.031528105148518185
Rotation=0.02285566995740826,0.002916336655247168,-0.013047600467842885

[Left_Flap]
Mesh=flap
Material=A4_mat.ini
Position=0.008194949160082819,-0.011639999056114509,-0.03452302931600127
Rotation=-0.0000035706109545556975,-0.00009119186241643502,-0.0000040224771032713196
############################################################
# Right Wing
############################################################
[Right_slat]
Mesh=leading_slat
Material=A4_mat.ini
Position=0.03060315535982481,-0.010170456505288058,-0.0005050015992765027
Rotation=0.0007393488134047513,40.937083447660164,0.004253895440914399

[Right_Aileron]
Mesh=Alion
//MeshType=ROLL_CONTROL
Material=A4_mat.ini
Position=0.03456556688983675,-0.011192011029036698,-0.031528105148518185
Rotation=0.02285566995740826,-0.002916336655247168,0.013047600467842885

[Right_Flap]
Mesh=flap
Material=A4_mat.ini
Scale=-1,1,1
Position=-0.008194949160082819,-0.011639999056114509,-0.03452302931600127
Rotation=-0.0000035706109545556975,0.00009119186241643502,0.0000040224771032713196
############################################################
# Tail Section
############################################################
[Rudder]
Mesh=rudder
//MeshType=YAW_CONTROL
Material=A4_mat.ini
Position=0,0.01597114592124539,-0.0845146503730956
Rotation=-11.5419682865699,0,0

[Left_Stabilator]
Mesh=elevator
//MeshType=PITCH_CONTROL
Material=A4_mat.ini
Position=-0.000000012302372176305755,0.010148490693837466,-0.08844882207263342
Rotation=0,0,0

[hook]
Mesh=hook
Material=A4_mat.ini
Position=0,-0.01095603703821626,-0.05392456971043859
Rotation=-0.000011675653043146144,0,0

############################################################
# Landing Gear
############################################################

# FUELTANK PYLONS ETC-------------------------------------------------------

[Pylon_Left]
Mesh=bomb_rack
Material=A4_mat.ini
Position=0.03,-0.0127,-0.015
Rotation=0,0,0

[Pylon_Center]
Mesh=bomb_rack
Material=A4_mat.ini
Position=0,-0.012757074458147263,0.000000006700221695825001
Rotation=0,0,0

[Pylon_Right]
Mesh=bomb_rack
Material=A4_mat.ini
Position=-0.03,-0.0127,-0.015
Rotation=0,0,0

[MER_Rack_Left]
ResourcesMeshFolder=weapons/usn_mer/
RootMesh=usn_mer
Mesh=usn_mer
ResourcesMaterialFolder=weapons/usn_mer/
Material=usn_mer_mat

Position=-0.03,-0.015,-0.015
Rotation=0,0,0
#IsVisible=False

[MER_Rack_Center]
ResourcesMeshFolder=weapons/usn_mer/
RootMesh=usn_mer
Mesh=usn_mer
ResourcesMaterialFolder=weapons/usn_mer/
Material=usn_mer_mat
Position=0,-0.015,-0.0055
Rotation=0,0,0

[MER_Rack_Right]
ResourcesMeshFolder=weapons/usn_mer/
RootMesh=usn_mer
Mesh=usn_mer
ResourcesMaterialFolder=weapons/usn_mer/
Material=usn_mer_mat

Position=0.03,-0.015,-0.015
Rotation=0,0,0
#----------------------------------------------------------

[---------- Effects ----------]
[Particles]
ShotDownFireEffect=effects/aircraft_kill_effects/wp_mig-17_kill
ShotDownFireEffectPosition=0,0,0
HitWaterEffect=effects/splashes/emitters/splash_bomb
HitGroundEffect=effects/explosions/emitters/aircraft_hit_ground
HitAirEffectClass=LargeMissileExplosions
ExhaustSmoke=aircraft/particles/wp_mig-17_smokeemitter

############################################################
# Sounds
############################################################
[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=3
# Front
EngineAudioClip=audio/aircraft/J79_Front
EngineAudioPosition=0,0,0
EngineAudioRollOff=Logarithmic
EngineAudioDistance=1,20
EngineAudioPitchRange=1.4,2.8
EngineAudioVolumeRange=0.1,0.5
# Rear
ExhaustAudioClip=audio/aircraft/jet_rear_2
ExhaustAudioPosition=0,0,0
ExhaustAudioRollOff=Logarithmic
ExhaustAudioDistance=1,20
ExhaustAudioPitchRange=0.6,1.0
ExhaustAudioVolumeRange=0.75,1.2
# Far
FarAudioClip=audio/aircraft/jet_far_1
FarAudioPosition=0,0,0
FarAudioRollOff=Logarithmic
FarAudioDistance=5,20
FarAudioPitch=1.0
FarAudioVolume=1.0
FarAudioFadeRange=0.0,0.15	      // nautical miles min/max
# Afterburner
AfterburnerAudioClip=audio/aircraft/afterburner_mig-29
AfterburnerAudioPosition=0,0,0
AfterburnerAudioRollOff=Logarithmic
AfterburnerAudioDistance=1,20
AfterburnerAudioPitch=1.0
AfterburnerAudioVolume=1.0
# Gears
#GearsAudioClip=audio/aircraft/gears
GearsAudioClip=audio/aircraft/LandingGearRetraction_v1
GearsAudioPosition=0,0,0
GearsAudioRollOff=Logarithmic
GearsAudioDistance=1,20
GearsAudioPitch=1.0
GearsAudioVolume=1.0
# Flaps
#FlapsAudioClip=audio/aircraft/flaps
FlapsAudioClip=audio/aircraft/LandingGearRetraction_v1
FlapsAudioPosition=0,0,0
FlapsAudioRollOff=Logarithmic
FlapsAudioDistance=1,20
FlapsAudioPitch=1.0
FlapsAudioVolume=1.0

//Front Sound = audio/aircraft/JE_Front_3 v=0.25, p=1.2
//Rear	Sound = audio/aircraft/JE_Burner_2
//Far	Sound = audio/aircraft/JetExhaustLoop p=0.75
//Afterburner = audio/aircraft/AfterburnerLarge_v1 p=0.75

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
# creates the hit boxes for this object
NumberOfColliders=2
Collider1=col_body
Collider2=col_wings

[col_body]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.02361928,0.02891341,0.1916716

[col_wings]
Collider=Box
Position=0.0023026,0.0051,-0.012915
Rotation=0,0,0
Scale=0.169098,0.006968998,0.05797473