[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=136                                    // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini

[Ammunition]
Ammunition=usn_zuni

NumberOfAttachments=2
AttachmentPosition1=0.0015,0,0.007
AttachmentPosition2=-0.0015,0,0.007


SalvoFireAmount=1                       // number of shots fired

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/ammunition/zuni_mount/
ResourcesRoot=zuni_mount.obj
ResourcesMesh=Zuni_mount
ResourcesMaterial=Zuni_mount_mat.ini
