#####################################################################

To add own sounds to your systems, use:

####################################################################



WeaponAudioClip_YourModname.ini

///////////////////////////////////////////////////////
#!extend systems/WeaponAudioClip_Mapping.ini

[Weaponsystem_Name]
WeaponAudioClip=audio/weapons/Audio-File.wav
WeaponAudioPosition=0,0,0
WeaponAudioRollOff=Logarithmic
WeaponAudioDistance=1,10
WeaponAudioVolume=1.2
WeaponAudioAudibility=Above

///////////////////////////////////////////////////////





TorpedoAudioClip_YourModname.ini

///////////////////////////////////////////////////////
#!extend systems/WeaponAudioClip_Mapping.ini

[Torpedo_Name]                                 
SonarAudioClip=audio/environment/Audio-File.wav
SonarAudioPosition=0,0,0                       
SonarAudioRollOff=Logarithmic                  
SonarAudioDistance=1,50                        
SonarAudioPitch=1                              
SonarAudioVolume=1                             
SonarAudioAudibility=Below  // layer of sound audibility: Above, Below, AboveAndBelow  

///////////////////////////////////////////////////////





SonarAudioClip_YourModname.ini

///////////////////////////////////////////////////////
#!extend systems/SonarAudioClip_Mapping.ini

[Sonar_Name]                                 
SonarAudioClip=audio/environment/Audio-File.wav
SonarAudioPosition=0,-0.07,0.6
SonarAudioRollOff=Logarithmic
SonarAudioDistance=1.8,55
SonarAudioPitch=1
SonarAudioVolume=1.6
SonarAudioAudibility=Below  // layer of sound audibility: Above, Below, AboveAndBelow                  

///////////////////////////////////////////////////////





NoisemakerAudioClip_YourModname.ini

///////////////////////////////////////////////////////
#!extend systems/NoisemakerAudioClip_Mapping.ini

[Noisemaker_Name]                                 
SonarAudioClip=audio/environment/Audio-File.wav
SonarAudioPosition=0,-0.07,0.6
SonarAudioRollOff=Logarithmic
SonarAudioDistance=1.8,55
SonarAudioPitch=1
SonarAudioVolume=1.6
SonarAudioAudibility=Below  // layer of sound audibility: Above, Below, AboveAndBelow                  

///////////////////////////////////////////////////////