[AmmunitionNames]
# ------------------ AAM ------------------

# ------------------ SAM ------------------
ins_barak_8= Barak_8, India sam

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------
ins_brahmos-er=brahmos Anti ship Missile
ins_brahmos=brahmos, India Anti ship Missile

#-----------Land Strike only missiles---------

# ---------- Anti-sub Missiles ----------

# ------------------ RBU ------------------

# ---------- Torpedoes ----------

# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# ------------------ Depth Charges ------------------

# ----------------- Fueltanks ----------------