[DRAA-10A]
#Users: fr_br1050
#Based on AN/APS-116
#https://www.radartutorial.eu/19.kartei/08.airborne/karte072.pt.html
Kind=Radar
Type=DirectedSearch    // Classes can be "DirectedSearch", "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=Surface           // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
RotationDirection=1    // -1 means left, 1 means right
RPM=6  
MinRange=0.2           // min range in km
MaxRange=240          // max range in km
MinAltitude=0          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=0          // max altitude in meters, relevant for air, unused for surface
RangeResolution=30.0   // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=1.1          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=43.3              // gain in dB on the sensor
Frequency=X-Band       // frequency band
PeakPower=500.0        // output peak power in kW
CanDetectPeriscope=True

[DRAA-2A]
#Users: fr_br1050
#Based on AN/APS-20
#https://www.radartutorial.eu/19.kartei/08.airborne/karte072.pt.html
Kind=Radar
Type=DirectedSearch    // Classes can be "DirectedSearch", "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=Surface           // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
RotationDirection=1    // -1 means left, 1 means right
RPM=6  
MinRange=0.2           // min range in km
MaxRange=180         // max range in km
MinAltitude=0          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=0          // max altitude in meters, relevant for air, unused for surface
RangeResolution=130.0   // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=1.1          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=35.3              // gain in dB on the sensor
Frequency=X-Band       // frequency band
PeakPower=400.0        // output peak power in kW
CanDetectPeriscope=True

[ARAR-11D] BR1050 Alizé ESM1
#Users:  BR1050 Alizé before ALM upgrad. Source on specs https://imagesdefense.gouv.fr/fr/contre-mesures-passives-a-bord-des-avions-asm.html
Kind=ESM
Gain=4                              // gain of sensor in dB
HasDataLink=True                    // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=13.0              // in degrees
Frequencies=S-Band,C-Band,X-Band	//radar frequency bands the ESM suite can detect
IdentificationRate=0.6              // Rate of identification, more = faster identification, default is 1
ModuleType=SmallSensor

[ARAR-10B] BR1150 Atlantic 1
#Users: BR1150 Atlantic 1 source on specs https://www.youtube.com/watch?v=yX8goubLkY4
Kind=ESM
Gain=10                              // gain of sensor in dB
HasDataLink=True                    // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=3.0              // in degrees
Frequencies=S-Band,C-Band,X-Band	//radar frequency bands the ESM suite can detect
IdentificationRate=0.6              // Rate of identification, more = faster identification, default is 1
ModuleType=SmallSensor

[ARAR-12] BR1050 Alizé ESM2
#Users: BR1050 Alizé after ALM upgrade. Source on specs https://www.forecastinternational.com/archive/disp_old_pdf.cfm?ARC_ID=1724
Kind=ESM
Gain=6                              // gain of sensor in dB
HasDataLink=True                    // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=10.0              // in degrees
Frequencies=L-Band,S-Band,C-Band,X-Band,Ku-Band,K-Band,Ka-Band	//radar frequency bands the ESM suite can detect
IdentificationRate=1              // Rate of identification, more = faster identification, default is 1
ModuleType=SmallSensor

[DSTV_4L_LOFAR_sonar] #TSM 8010
Kind=Sonar
HasDataLink=True
AngularResolution=8.0
RangeResolution=150.0
PassiveRange=8          // in km
Gain=35
Type=Hull                            //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
Baffles=0,0
SonarFrequency=LF

[DSTA_2_sonar] #Active range only
Kind=Sonar
IsActiveOnly=True 
HasDataLink=True
AngularResolution=8.0
RangeResolution=130.0
ActiveRange=2                        // in km
ActiveGain=20                        // in db, gain of the sensor
OutputPower=180                      // Active sensor output power in dB, unused for passive ones
Type=Hull                            //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
Baffles=0,0
SonarFrequency=MF

[SSQ-41_Jezebel_sonar] #Need setup
Kind=Sonar
HasDataLink=True
AngularResolution=15.0
RangeResolution=150.0
PassiveRange=6          // in km
Gain=28
Type=Hull                            //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
Baffles=0,0
SonarFrequency=LF

[Chlio_FLIR] #Thomson CSF Chlio FLIR
Kind=Visual
#Infrared
UseIRValues=True                 // Affects only Encyclopedia. For correct type display
VIDRangeMultiplier=1.5           // Target VID range multiplied by this for identification check. 0 means it cannot identify
MaxRangeMultiplier=1.5           // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=1.5             // Final VID/Detection range is multiplied by this in case when target observed on surface background