[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=205                                   // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini


[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=2

[SensorSystem1]
Type=LaserDesignator
SystemName=ASELPOD_Designator
Mount=Dummy
ModuleType=Sensor

[SensorSystem2]
Type=Visual
SystemName=ASELPOD
Mount=Dummy
ModuleType=Sensor

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/ammunition/aselpod/
ResourcesRoot=aselpod.obj
ResourcesMesh=pod
ResourcesMaterial=aselpod_mat.ini


