[AmmunitionNames]
# ------------------ AAM ------------------
fr_r511=R.511,Matra R.511,AAM,The Matra R.511 was a semi active radar homing early air to air missile with 7 kilometer range or 4.3 nautical miles and a limited radar. It saw service during the 60's with the French air forces.

# ---------- Anti-ship Missiles ----------
fr_as_20=AS-20,Nord AS-20,AGM,The Nord AS-20 was an early air to ground radio guided missile developed from the Nord air to air AA.20 missile. It had a 33kg warhead and it was used mainly by the French, German and Italian air forces in the 60's and 70's.

# ------------------ FFAR -----------------
rn_rp_3_ap=3.5-Inch AP,RP-3,FFAR,The 3-Inch Rocket was a World War 2 rocket capable of being fitted with a variety of warheads.
rn_rp_3_sap=3.5-Inch SAP,RP-3,FFAR,The 3-Inch Rocket was a World War 2 rocket capable of being fitted with a variety of warheads.

# ------------------ Guns -----------------
rn_cal_20mm=20mm