[General]
DefaultSquadronShortName=N/A

[plaaf_j-11]
Type=战斗机
Default=歼-11,歼-11
DefaultDescription=1991年起自俄罗斯整机进口，以及由俄罗斯进口散件并在中国组装的苏-27SK战斗机。使用俄罗斯进口的航电、发动机和武器。
Squadron1=歼-11（空16师"贺兰雄狮"）,歼-11
Squadron2=歼-11（空2师6旅）,歼-11
Callsigns=Squadron1,雄鹰|Squadron2,雄狮

[plaaf_j-11a]
Type=战斗机
Default=歼-11A,歼-11A
DefaultDescription=1991年起自俄罗斯整机进口，以及由俄罗斯进口散件并在中国组装的苏-27SK战斗机。使用俄罗斯进口的航电、发动机和武器。
Squadron1=歼-11A（空33师98团"雾都雄鹰"）,歼-11A
Squadron2=歼-11A（空16师"贺兰雄狮"）,歼-11A
Squadron3=歼-11A（"雾都雄鹰"金头盔座机40547）,歼-11A
Squadron4=歼-11A（空41旅）,歼-11A
Callsigns=Squadron1,雾都雄鹰|Squadron2,贺兰雄狮

[plaaf_j-11b]
Type=战斗机
Default=歼-11B,歼-11B
DefaultDescription=2000年起，在吸收苏-27SK战斗机生产技术的基础上，中国利用本国技术升级改造苏-27的机体，推出的本土化改型，实现机体、材料、发动机、航电系统和武器的全面国产化。歼-11B应用国产符合材料技术改进机体设计，减轻结构重量，增加机体使用寿命；换装国产涡扇-10B"太行"涡轮风扇发动机。在航电和传感器方面，歼-11B换装了国产数字综合航电武器系统，采用全玻璃化座舱、四余度数字式电传操纵系统、国产1493型平板缝隙天线火控雷达。歼-11B的主要对空武器是霹雳-12主动雷达制导空空导弹和霹雳-8B红外空空导弹，此外还可挂载精确制导对地弹药。
Squadron1=歼-11B（空16旅"贺兰雄狮"）,歼-11B
Squadron2=歼-11B（辽东雄鹰）,歼-11B
Squadron3=歼-11B（空1旅）,歼-11B
Callsigns=Squadron1,雄狮|Squadron2,雄鹰

[plaaf_j-11bh]
Type=战斗机
Default=歼-11BH,歼-11BH
DefaultDescription=2000年起，在吸收苏-27SK战斗机生产技术的基础上，中国利用本国技术升级改造苏-27的机体，推出的本土化改型，实现机体、材料、发动机、航电系统和武器的全面国产化。歼-11B应用国产符合材料技术改进机体设计，减轻结构重量，增加机体使用寿命；换装国产涡扇-10B"太行"涡轮风扇发动机。在航电和传感器方面，歼-11B换装了国产数字综合航电武器系统，采用全玻璃化座舱、四余度数字式电传操纵系统、国产1493型平板缝隙天线火控雷达。歼-11B的主要对空武器是霹雳-12主动雷达制导空空导弹和霹雳-8B红外空空导弹，此外还可挂载精确制导对地弹药，H代表海军航空兵
Squadron1=歼-11BH,歼-11BH
Callsigns=Squadron1,雄狮|Squadron2,雄鹰

[plaaf_j-11bg]
Type=战斗机
Default=歼-11BG,歼-11BG
DefaultDescription=2017年起歼-11B开始中期升级（MLU）和部分复产计划。飞机改装新一代综合航电和火控系统，换装有源相控阵（AESA）雷达，可挂载霹雳-15主动雷达制导空空导弹和霹雳-10红外空空导弹。
Squadron1=歼-11BG（空16旅"贺兰雄狮"）,歼-11BG
Squadron2=歼-11BG（辽东雄鹰）,歼-11BG
Callsigns=Squadron1,雄狮|Squadron2,雄鹰

[plaaf_j-11bgh]
Type=战斗机
Default=歼-11BGH,歼-11BGH
DefaultDescription=2017年起歼-11B开始中期升级（MLU）和部分复产计划。飞机改装新一代综合航电和火控系统，换装有源相控阵（AESA）雷达，可挂载霹雳-15主动雷达制导空空导弹和霹雳-10红外空空导弹，H代表海军航空兵
Squadron1=歼-11BGH（）,歼-11BGH
Callsigns=Squadron1,1
################################################

[plaaf_j-8b]
Type=战斗机
Default=歼-8B,歼-8B
DefaultDescription=歼-8B是歼-8II系列飞机的首个改型，于1988年开始研制，1995年服役。该机换装涡喷-13A发动机，装备衍射屏显，大气数据计算机，SL-5A单脉冲火控雷达。主要对空武器是自意大利引进的阿斯派德（Aspide）半主动雷达制导空空导弹，后改为国产的霹雳-11导弹，是中国首款初步具备超视距空战能力的战斗机，但并不具备下视下射能力。该机还可挂载霹雳-5和霹雳-8红外空空导弹和无制导对地弹药。
Squadron1=歼-8B（空1师）,歼-8B
Squadron2=歼-8B（海航9师）,歼-8B
Squadron3=歼-8B（81192）,歼-8B
Callsigns=Squadron1,雄鹰|Squadron2,雄狮|Squadron3,雄鹰

[plaaf_j-8e]
Type=战斗机
Default=歼-8E,歼-8E
DefaultDescription=1980年最初服役时，由于配套机载火控雷达研制进度滞后，无法按时装机，初期生产型的歼-8只能定型为"歼-8白天型"，不具备全天候作战能力。1985年装备中国第一型自主研发的机载火控雷达SL-4雷达的歼-8A型飞机定型生产，但由于SL-4雷达性能落后，飞机配套的霹雳-2乙红外空空导弹早已停产，歼-8A仅生产了31架。1992年，改装JL-7A雷达，新型火控计算机和导弹离轴发射控制装置，装备霹雳-5红外空空导弹的歼-8E首飞，这是歼-8基本型号的最后一个改型，也是作战能力最完备的改型。
Squadron1=歼-8E（空24师）,歼-8E
Callsigns=Squadron1,雄鹰

[plaaf_j-8f]
Type=战斗机
Default=歼-8F,歼-8F
DefaultDescription=1985年，中美达成合作协议（美方称"和平珍珠"项目，中方称"八二工程"），由中方出资，委托诺斯罗普·格鲁曼公司提供综合航电和雷达火控系统，对歼-8II飞机进行技术升级。1989年合作协议中止，格鲁曼公司依照合同于1992年交付中方两架改造完成的"八二工程"原型机。基于"八二工程"的技术合作成果，中国于1997年开始研制装备国产先进综合航电和脉冲多普勒雷达的歼-8F，并搭配国产的新一代主动雷达制导中程空空导弹。歼-8F于2000年首飞，2002年交付部队。该机换装涡喷-13B发动机，安装国产1492型脉冲多普勒机载雷达和数字综合火控设备，挂载霹雳-12主动雷达制导中程空空导弹，具备多目标超视距攻击能力，还可挂载精确对地制导武器用于对地攻击。
Squadron1=歼-8F（空1师）,歼-8F
Squadron2=歼-8F（空9师）,歼-8F
Callsigns=Squadron1,利剑|Squadron2,雄狮

[plaaf_jz-8f]
Type=战斗机,侦察机
Default=歼侦-8F,歼侦-8F
DefaultDescription=歼侦-8F是基于歼-8F发展出的战术侦察机。该机拆除了航炮，安装数字光学侦察照相设备，可在机腹挂载红外相机及合成孔径雷达吊舱。该机还可安装电子情报和信号情报侦察吊舱，使飞机具有一定的战略情报搜集功能。除执行侦察任务外，歼侦-8F飞机也可携带空空导弹，并可在夜间和复杂气象条件下执行侦察任务。歼侦-8F于2006年首飞，是中国人民解放军空军主要使用的高空高速战术侦察机。
Squadron1=歼侦-8F（空29师）,歼侦-8F
Callsigns=Squadron1,千里眼

####################################################

[plaaf_j-7ii]
Type=战斗机
Default=歼-7II,歼-7II
DefaultDescription=歼-7战斗机是由中国制造的第二代超音速喷气式战斗机。1961年，中国引进苏联米格-21F-13战斗机，此后在中苏交恶，苏联撤走全部技术协助的情况下于1966年成功试制国产化的米格-21战斗机，并定型为歼-7战斗机。1968年，中国航空工业成都飞机公司开始改进歼-7战斗机，并于1975年推出改进进气口，加装机炮的歼-7I战斗机。1979年，装新型弹射座椅，换装涡喷-7乙发动机，加大航程的歼-7II战斗机定型量产。
Squadron1=歼-7II（空1师）,歼-7II
Squadron2=歼-7II（空2师）,歼-7II
Squadron3=歼-7II（海航8师）,歼-7II
Callsigns=Squadron1,雄鹰|Squadron2,雄狮|Squadron3,英雄

[plaaf_j-7iiia]
Type=战斗机
Default=歼-7IIIA,歼-7IIIA
DefaultDescription=歼-7战斗机是由中国制造的第二代超音速喷气式战斗机。1961年，中国引进苏联米格-21F-13战斗机，此后在中苏交恶，苏联撤走全部技术协助的情况下于1966年成功试制国产化的米格-21战斗机，并定型为歼-7战斗机。1978年起，参照苏联米格-21MF全天候战斗机，中国开始研制具有全天候作战能力，装备机载搜索和火控雷达的歼-7III（歼-7C）战斗机，并于1984年成功首飞。1995年装备加大推力的涡喷-13F1发动机和改进机载武器航电设备的歼-7IIIA（歼-7D）定型生产。由于歼-7III/IIIA飞机定型时性能已经落后，仅生产了50架。
Squadron1=歼-7IIIA（空9师）,歼-7IIIA
Callsigns=Squadron1,雄鹰

[plaaf_j-7e]
Type=战斗机
Default=歼-7E,歼-7E
DefaultDescription=歼-7战斗机是由中国制造的第二代超音速喷气式战斗机。1961年，中国引进苏联米格-21F-13战斗机，此后在中苏交恶，苏联撤走全部技术协助的情况下于1966年成功试制国产化的米格-21战斗机，并定型为歼-7战斗机。1986年，中国航空工业成都飞机公司与西北工业大学合作改进歼-7II飞机，大翼采用双三角翼搭配前缘机动襟翼构型，极大提升了中低空亚音速和跨音速机动性，换装涡喷-13F1发动机，并改装更先进的航电设备。该机于1993年定型为歼-7E，共生产260架。
Squadron1=歼-7E（空1师）,歼-7E
Squadron2=歼-7EH（海航3师）,歼-7EH
Callsigns=Squadron1,雄鹰|Squadron2,雄狮

###################################################

[plaaf_j-10a]
Type=战斗机
Default=歼-10A,歼-10A
DefaultDescription=歼-10A是中国自主研制的第三代单发单座多用途战斗机，采用大三角翼加鸭式气动布局。该机换装国产脉冲多普勒火控雷达，具备中距拦射和近距格斗能力，可挂载霹雳-12主动雷达制导中程空空导弹和霹雳-8红外格斗导弹，同时具备对地精确打击能力。
Squadron1=歼-10A,歼-10A
Squadron2=歼-10A（八一飞行表演队）,歼-10A
Squadron3=歼-10A（实验涂装）,歼-10A
Squadron4=歼-10A（空131师"大红鹰"）,歼-10A
Squadron5=歼-10A（空26旅）,歼-10A
Squadron6=歼-10A（空61旅）,歼-10A
Squadron7=歼-10A（空80师）,歼-10A
Squadron8=歼-10A（空132旅）,歼-10A
Squadron9=歼-10A（空94旅）,歼-10A
Squadron10=歼-10A（空70旅）,歼-10A
Squadron11=歼-10A（空43旅）,歼-10A
Squadron12=歼-10A（飞训1团）,歼-10A
Squadron13=歼-10A（飞训2团）,歼-10A
Callsigns=Squadron1,飞鹰|Squadron4,红鹰

[plaaf_j-10c]
Type=战斗机
Default=歼-10C,歼-10C
DefaultDescription=歼-10C是歼-10A的改进型，采用DSI进气道和重新优化的机身设计，换装有源相控阵（AESA）雷达和先进综合航电系统。该机可挂载霹雳-15远程主动雷达制导空空导弹和霹雳-10高机动红外格斗导弹，具备强大的超视距空战和对地/对海精确打击能力。
Squadron1=歼-10C（空2旅）,歼-10C
Squadron2=歼-10C（八一飞行表演队）,歼-10C
Squadron3=歼-10C（实验涂装）,歼-10C
Squadron4=歼-10C（空131旅"大红鹰"）,歼-10C
Squadron5=歼-10C（空131旅"云岭红鹰"）,歼-10C
Squadron6=歼-10C（空130旅）,歼-10C
Squadron7=歼-10C（空124旅）,歼-10C
Squadron8=歼-10C（空72旅）,歼-10C
Squadron9=歼-10C（空66旅）,歼-10C
Squadron10=歼-10C（空34旅）,歼-10C
Squadron11=歼-10C（空25旅）,歼-10C
Squadron12=歼-10C（空18旅）,歼-10C
Squadron13=歼-10C（飞训1团）,歼-10C
Squadron14=歼-10C（新机试用团）,歼-10C
Callsigns=Squadron1,飞鹰|Squadron4,红鹰

###################################################

[plaaf_j-16d]
Type=电战机
Default=歼-16D,歼-16D
DefaultDescription=歼-16D是基于歼-16双座战斗轰炸机发展而来的专用电子战飞机，拆除了机炮和红外搜索跟踪系统，在翼尖安装电子情报吊舱，并在机翼下挂载电子干扰吊舱。该机可执行伴随电子干扰、防空压制和防区外电子攻击任务，是中国空军电子战能力的重要组成。
Squadron1=歼-16D,歼-16D

[plaaf_j-16]
Type=战斗轰炸机
Default=歼-16,歼-16
DefaultDescription=歼-16是中国自主研制的双座双发重型多用途战斗轰炸机，基于歼-11BS平台深度改进而来。该机换装有源相控阵（AESA）雷达和国产涡扇-10B"太行"发动机，具备强大的对空、对地和对海精确打击能力，可挂载霹雳-15、霹雳-10空空导弹以及各类精确制导对地/反舰弹药，是中国空军现役主力重型多用途战机。
Squadron1=歼-16,歼-16

[plaaf_h-6k]
Type=轰炸机
Default=轰-6K,轰-6K
DefaultDescription=轰-6是中国空军和海军航空兵装备的中型轰炸机，其源自1960年代中国自苏联引进的图-16中型轰炸机。其各种改进版本在60余年的时间中承担了中国空军和海军航空兵的中远程常规战术打击，战略核威慑，和远程海上侦察和反舰任务，是中国远程空中火力投送的绝对主力。轰-6K是2010年代初诞生的全面升级型号，部分机体结构重新设计，换装国产先进航电和传感器设备，换装国产涡扇-18发动机，可以挂载中国新一代远程空地巡航导弹、空地弹道导弹和远程反舰导弹，进一步加强了其防区外打击能力。
Squadron1=轰-6K,轰-6K

[plaaf_h-6k_early]
Type=轰炸机
Default=轰-6K（早期型）,轰-6K
DefaultDescription=轰-6是中国空军和海军航空兵装备的中型轰炸机，其源自1960年代中国自苏联引进的图-16中型轰炸机。其各种改进版本在60余年的时间中承担了中国空军和海军航空兵的中远程常规战术打击，战略核威慑，和远程海上侦察和反舰任务，是中国远程空中火力投送的绝对主力。轰-6K是2010年代初诞生的全面升级型号，部分机体结构重新设计，换装国产先进航电和传感器设备，换装国产涡扇-18发动机，可以挂载中国新一代远程空地巡航导弹、空地弹道导弹和远程反舰导弹，进一步加强了其防区外打击能力。
Squadron1=轰-6K,轰-6K

[plaaf_h-6k_late]
Type=轰炸机
Default=轰-6K（后期型）,轰-6K
DefaultDescription=轰-6是中国空军和海军航空兵装备的中型轰炸机，其源自1960年代中国自苏联引进的图-16中型轰炸机。其各种改进版本在60余年的时间中承担了中国空军和海军航空兵的中远程常规战术打击，战略核威慑，和远程海上侦察和反舰任务，是中国远程空中火力投送的绝对主力。轰-6K是2010年代初诞生的全面升级型号，部分机体结构重新设计，换装国产先进航电和传感器设备，换装国产涡扇-18发动机，可以挂载中国新一代远程空地巡航导弹、空地弹道导弹和远程反舰导弹，进一步加强了其防区外打击能力。
Squadron1=轰-6K,轰-6K

[plaaf_h-6j]
Type=轰炸机
Default=轰-6J,轰-6J
DefaultDescription=轰-6是中国空军和海军航空兵装备的中型轰炸机，其源自1960年代中国自苏联引进的图-16中型轰炸机。其各种改进版本在60余年的时间中承担了中国空军和海军航空兵的中远程常规战术打击，战略核威慑，和远程海上侦察和反舰任务，是中国远程空中火力投送的绝对主力。轰-6J是2018年服役的改进型号，主要装备海军航空兵，承担远海侦察和反舰打击任务。轰-6J在轰-6K的基础上升级航电设备，换装有源相控阵雷达，可携带远程被动电子侦察吊舱，通过定位敌方舰船电子辐射发动反舰打击。
Squadron1=轰-6J,轰-6J

[plaaf_h-6n]
Type=轰炸机,战略轰炸机
Default=轰-6N,轰-6N
DefaultDescription=轰-6是中国空军和海军航空兵装备的中型轰炸机，其源自1960年代中国自苏联引进的图-16中型轰炸机。其各种改进版本在60余年的时间中承担了中国空军和海军航空兵的中远程常规战术打击，战略核威慑，和远程海上侦察和反舰任务，是中国远程空中火力投送的绝对主力。轰-6N是2018年服役的改进型号，主要承担战略核威慑和空基核打击职责。轰-6N在轰-6K的基础上升级航电设备，换装有源相控阵雷达，增加空中受油能力，可挂载惊雷-1空基战略弹道导弹。在保留各种远程制导弹药挂载能力的基础上，该机还可携带无侦-8超音速无人侦察机执行远程高速侦察任务。
Squadron1=轰-6N,轰-6N