
[LanguageResources]

#####################################################
########### Visual/IR #####################


JZ-8_POD_EO=光电侦察吊舱|光电侦察吊舱
OLS-27=OLS-27 IRST|OLS-27是苏-27战斗机装备的红外/光电瞄准系统，可利用红外特征搜索空中目标，也可用于为R-27ET和R-73导弹提供火控参数。该系统为被动探测传感器，作用距离较短。
J-16_IRST=IRST|红外光电瞄准系统，可利用红外特征搜索空中目标，也可用于为导弹提供火控参数。该系统衍生自俄制OLS-27系列红外光电瞄准系统，为被动探测传感器，作用距离较短。
YINGS-IIIA=鹰隼IIIA瞄准吊舱|鹰隼IIIA是中国空军装备的红外/电视/激光通用复合瞄准吊舱，具备昼夜观测能力和武器制导能力。
YINGS-IIIA_Designator=鹰隼IIIA激光器|鹰隼IIIA瞄准吊舱激光器

########### Radar #####################
JL-7A=JL-7A雷达|歼雷-7雷达是歼-7III战斗机使用的单脉冲火控雷达，安装于机头进气锥内，采用抛物面天线。该雷达技术最初来源于越南战场被击落的F-105D战斗轰炸机R-14A雷达残骸，经过研仿后形成317型型雷达，作为海上搜索雷达装备于强-5乙鱼雷攻击机，后改为机载火控雷达。该雷达仅具备最基本的搜索和跟踪能力，作用距离短，不具备下视下射能力，可为霹雳-5和霹雳-8导弹提供离轴发射火控参数。

JL-7AG=JL-7AG雷达|歼雷-7雷达是歼-7III战斗机使用的单脉冲火控雷达，安装于机头进气锥内，采用抛物面天线。该雷达技术最初来源于越南战场被击落的F-105D战斗轰炸机R-14A雷达残骸，经过研仿后形成317型型雷达，作为海上搜索雷达装备于强-5乙鱼雷攻击机，后改为机载火控雷达。该雷达仅具备最基本的搜索和跟踪能力，作用距离短，不具备下视下射能力，可为霹雳-5和霹雳-8导弹提供离轴火控参数。该雷达在经过改进后装备歼-8E战斗机。

SL-5A=SL-5A雷达|射雷-5甲雷达是中国空军装备的第一型机载火控雷达，射雷-4雷达（也称204雷达）的改进产品，装备歼-8B战斗机。该型雷达仍采用单脉冲体制，在射雷-4雷达的基础上增加连续波照射器，以为当时计划中的霹雳-4半主动雷达制导空空导弹提供火控引导，但由于该雷达依然不具备下视下射能力，作用距离短，且霹雳-4导弹项目最终取消，歼-8B战斗机依然不具备中距拦射能力。雷达仅能作基础搜索使用，或为霹雳-5和霹雳-8导弹提供离轴发射火控参数。

Type_266=266型雷达测距仪|266型雷达测距器是歼-7战斗机为其红外导弹和机炮瞄准使用的简易雷达测距装置，不具备搜索和跟踪能力。

KLJ-92B=KLJ-92B雷达|KLJ-92雷达（又称1492雷达）是中国空军装备的第一款全波形数字脉冲多普勒战斗机雷达，主要装备歼-8F和歼-8DF战斗机，搭配国产霹雳-12主动雷达制导中距空空导弹，使得歼-8II战斗机第一次具备了真正的超视距空战能力。该雷达采用平板缝隙阵天线，具备出色的下视下射能力，能够同时处理并跟踪多个目标。

JZ-8_Pod_SAR_L=合成孔径雷达吊舱（左向）
JZ-8_Pod_SAR_R=合成孔径雷达吊舱（右向）

KLJ-73=KLJ-73雷达|KLJ-73雷达（又称1473雷达）是中国空军装备的一款数字脉冲多普勒雷达，装备歼-10A战斗机，其性能大致与美国F-16C/D战斗机的APG-88(V)相当。

KLJ-10A=KLJ-10A雷达|KLJ-10A雷达是歼-10C战斗机的机载雷达，采用主动有源相控阵（AESA）体制，其性能大致与美国F-35战斗机的APG-81雷达相当。

N001=N001雷达|N001雷达是苏联研制的机械扫描脉冲多普勒机载火控雷达，是苏-27系列战斗机的机载雷达，采用机械扫描倒置卡塞格伦天线，雷达对战斗机目标大约有100公里探测距离，可实现空对空搜索与半主动雷达制导导弹和红外导弹制导。

KLJ-93=KLJ-93雷达|KLJ-93雷达（又称1493雷达）是中国空军歼-11B/BS系列战斗机装备的一款全波形数字脉冲多普勒雷达，其性能大致与美国F-15C战斗机装备的APG-63雷达相当。

KLJ-11A=KLJ-11A雷达|KLJ-11A雷达是歼-11BG战斗机的机载雷达，采用主动有源相控阵（AESA）体制，其增强的探测能力和信息处理水平支持歼-11BG战斗机使用以霹雳-15和霹雳-10为代表的中国空军第三代空空导弹武器。

KLJ-16=KLJ-16雷达|KLJ-16雷达是歼-16战斗机的机载雷达，采用主动有源相控阵（AESA）体制，具有较强的远距离探测能力和目标处理能力。

KLC-6=KLC-6雷达|KLC-6雷达是轰-6K轰炸机的机载雷达，采用机械扫描平板天线，主要用于远距离对面搜索和为巡航导弹提供火控参数，可以发现和跟踪地面目标。

KLC-6A=KLC-6A雷达|KLC-6A雷达是轰-6J/N轰炸机的机载雷达，采用主动有源相控阵（AESA）体制，具有更高的搜索距离和更强的目标处理能力。

########### ESM #####################
KJ930-2_RWR=KJ930-2雷达告警接收机|KJ930机载电子对抗系统的雷达告警接收机（RWR）

KJ8602A_RWR=KJ8602A雷达告警接收机|KJ8602A机载电子对抗系统的雷达告警接收机（RWR）

RKL-800A_RWR=RKL-800雷达告警接收机|RKL-800机载电子对抗系统的雷达告警接收机（RWR）

KZ900_Pod_ESM=KZ-900战术电子情报侦察吊舱|歼侦-8F装备的先进的机载信号情报（SIGINT）与电子侦察系统。

RKL-10_RWR=RKL-10雷达告警接收机|RKL-10机载电子对抗系统的雷达告警接收机（RWR）

RKL-10A_RWR=RKL-10A雷达告警接收机|RKL-10A机载电子对抗系统的雷达告警接收机（RWR）

RKL-16_RWR=RKL-16雷达告警接收机|RKL-16机载电子对抗系统的雷达告警接收机（RWR）

RKL-700A_ESM=RKL-700A战术自卫电子战吊舱|中国空军装备的新一代战术自卫电子战吊舱，可用于定位和压制敌方雷达和防空系统，并实施自卫电子干扰。

RKL-6_RWR=RKL-6雷达告警接收机|RKL-6机载电子对抗系统的雷达告警接收机（RWR）

RKL-600_Pod_ESM=RKL-600电子侦察吊舱|RKL-600电子侦察吊舱是轰-6J搭载的远程被动电子侦察设备，可远距离探测并跟踪敌方舰艇雷达辐射并为反舰导弹提供火控参数。


RWR=雷达告警装置|

########### ECM #####################
RKZ-16_ECM=RKZ-16自卫电子战系统|歼-16系列战斗机内置机载综合电子战系统装备的自卫电子干扰措施。

RKZ-930_ECM=RKZ-930综合电子战吊舱|RKZ-930是中国空军装备的综合机载电子战吊舱，可实施进攻性电子干扰，定位和压制敌方雷达传感器和防空系统。

RKL-700A_ECM=RKL-700A战术自卫电子战吊舱|中国空军装备的新一代战术自卫电子战吊舱，可用于定位和压制敌方雷达和防空系统，并实施自卫电子干扰。

RKZ-6_ECM=RKZ-6自卫电子战系统|轰-6K轰炸机内置机载综合电子战系统装备的自卫电子干扰措施。

RKZ-6A_ECM=RKZ-6A自卫电子战系统|轰-6J/N轰炸机内置机载综合电子战系统装备的自卫电子干扰措施。

#######################################################


30-1=30-1型机炮|

#######################################################













