; Verylarge: broadened neutral smoke and distance-sorted transparent layers.
[Main]
Duration=10000
Loop=False
Prewarm=False
StartDelay=0
StartLifetime=0.06
StartSpeed=0
StartSize=2.8
StartRotation=0
StartColor=1,0.97,0.89,0.010
GravityModifier=0
SimulationSpace=Local
SimulationSpeed=1
ScalingMode=Shape
PlayOnAwake=True
EmitterVelocityMode=Custom
CustomVelocity=0,0,0
MaxParticles=4
StopAction=None
CullingMode=AlwaysSimulate

[Emission]
RateOverTime=40
RateOverDistance=0.0

[Shape]
ShapeType=Circle
Radius=0
Arc=360
ArcMode=Random
Position=0,0,0
Rotation=0,0,0
Scale=2.3,2.3,1
AlignToDirection=False

[VelocityOverLifetime]
X=0
Y=0
Z=0
Space=Local
SpeedModifier=1

[ColorOverLifetime]
Color=gradient(0:1,1,1,0/0.12:1,1,1,1/0.55:1,1,1,0.7/1:1,1,1,0)

[SizeOverLifetime]
Z=1.25
Y=3.22
X=3.22
SeparateAxes=True
Size=curve(0:1/1:1)

[Renderer]
RenderMode=Mesh
Material=effects/weapons/materials/solidrocket_white.ini
SortMode=Distance
SortingFudge=0
MinParticleSize=0
MaxParticleSize=1
Alignment=Local
ShadowCastingMode=Off
ReceiveShadows=False
LightProbeUsage=Off
ReflectionProbeUsage=Off
MeshCount=1
Mesh0=effects/weapons/emitters/solidrocket_verylarge/meshes/diamond_core.obj,diamond_core
SortingOrder=0

