[AmmunitionNames]
# ---------- Anti-ship Missiles ----------
pla_yj-18=鹰击-18,,反水面,鹰击-18是以俄罗斯3M-54（SS-N-27）为基础研制的远程反舰导弹，以亚音速巡航，末段以最高3马赫的超音速攻击。该弹专用于打击海上舰艇，可由飞机、水面舰艇和潜艇发射。

pla_yj-83=鹰击-83,,反水面,鹰击-83是中程反舰巡航导弹，大量装备于中国人民解放军的舰艇、潜艇和飞机。它以亚音速低空巡航，末段以1.4马赫的超音速攻击。

#-----------Land Strike only missiles---------
pla_jl-3=巨浪-3,,潜射弹道导弹,巨浪-3是中国第三代洲际射程潜射弹道导弹，装备094型潜艇，并预计将装备未来的096型潜艇。

pla_cj-10=长剑-10,,对地攻击,长剑-10是以俄罗斯Kh-55为基础研制的远程对地攻击导弹，可携带常规或核弹头，可由飞机、水面舰艇和潜艇发射。

# --------------- Torpedoes ---------------
pla_yu-6=鱼-6,,鱼雷,鱼-6是中国的533毫米两用重型鱼雷，采用线导，发射后可由发射平台重新引导。
