; Broad outer torus spreads, stalls vertically, then curls down around the rising centre.
[Main]
Duration=17
Loop=False
Prewarm=False
StartDelay=5.9
StartLifetime=64|88
StartSpeed=0
StartSize=5.0|8.4
StartRotation=-3.14159|3.14159
StartColor=1,1,1,1
GravityModifier=0
SimulationSpace=World
ScalingMode=Hierarchy
PlayOnAwake=True
EmitterVelocityMode=Custom
CustomVelocity=0,0,0
MaxParticles=289
StopAction=None
CullingMode=AlwaysSimulate
[Emission]
RateOverTime=9
RateOverDistance=0
Bursts=0:104:104:1:0.01
[Shape]
ShapeType=Sphere
Radius=4.4
Position=0,8.6,0
Rotation=0,0,0
Scale=1.38,0.45,1.38
[Renderer]
RenderMode=Billboard
Material=effects/weapons/emitters/solidrocket_verylarge/large_smoke_alpha.ini
SortMode=Distance
SortingFudge=0
SortingOrder=1
Alignment=View
MinParticleSize=0
MaxParticleSize=8
ShadowCastingMode=Off
ReceiveShadows=False
LightProbeUsage=Off
ReflectionProbeUsage=Off
[VelocityOverLifetime]
Space=World
X=-0.07|0.07
Y=curve(0:0.94/0.2:0.66/0.48:0.18/0.72:-0.1/1:-0.18)
Z=-0.07|0.07
Radial=curve(0:0.5/0.3:0.3/0.68:0.12/1:0.03)
[SizeOverLifetime]
SeparateAxes=False
Size=curve(0:0.09/0.07:0.54/0.23:0.98/0.56:1.34/1:1.68)
[ColorOverLifetime]
Color=gradient(0:0.98,0.91,0.86,0/0.04:0.98,0.91,0.86,0.62/0.27:0.94,0.88,0.85,0.7/0.66:0.84,0.85,0.88,0.48/1:0.94,0.96,1,0)
[Noise]
Strength=0.18
Frequency=0.24
OctaveCount=2
ScrollSpeed=0.065
Damping=True
Quality=High
[TextureSheetAnimation]
Mode=Grid
NumTilesX=8
NumTilesY=16
Animation=WholeSheet
RowMode=Custom
RowIndex=0
TimeMode=Lifetime
StartFrame=0.04|0.16
Cycles=1
FrameOverTime=curve(0:0.12/0.2:0.28/0.55:0.56/1:0.9)
