; Raised high poloidal circuit embedded in the crown.
[Main]
Duration=6
Loop=False
Prewarm=False
StartDelay=8.6
StartLifetime=14|16
StartSpeed=0
StartSize=2.4|4.0
StartRotation=-3.14159|3.14159
StartColor=0.78,0.73,0.7,0.46
GravityModifier=0
SimulationSpace=World
ScalingMode=Hierarchy
PlayOnAwake=True
EmitterVelocityMode=Custom
CustomVelocity=0,0,0
MaxParticles=120
StopAction=None
CullingMode=AlwaysSimulate
[Emission]
RateOverTime=5.0
RateOverDistance=0
Bursts=0:28:28:1:0.01
[Shape]
ShapeType=Circle
Radius=2.4
Position=0,11.6,0
Rotation=-90,0,0
Scale=1,1,1
[Renderer]
RenderMode=Billboard
Material=effects/weapons/emitters/solidrocket_verylarge/large_smoke_cooled.ini
SortMode=Distance
SortingFudge=0
SortingOrder=3
Alignment=View
MinParticleSize=0
MaxParticleSize=8
ShadowCastingMode=Off
ReceiveShadows=False
LightProbeUsage=Off
ReflectionProbeUsage=Off
[VelocityOverLifetime]
Space=World
X=-0.03|0.03
Y=curve(0:1.9/0.125:1.45/0.25:0.33/0.375:-0.8/0.5:-1.24/0.625:-0.8/0.75:0.33/0.875:1.45/1:1.9)
Z=-0.03|0.03
OrbitalX=0
OrbitalY=0
OrbitalZ=0
OrbitalOffsetX=0
OrbitalOffsetY=0
OrbitalOffsetZ=0
Radial=curve(0:0/0.125:1.5/0.25:2.1/0.375:1.5/0.5:0/0.625:-1.5/0.75:-2.1/0.875:-1.5/1:0)
SpeedModifier=1
[SizeOverLifetime]
SeparateAxes=False
Size=curve(0:0.3/0.08:0.68/0.28:1/0.55:1.16/0.78:0.86/0.94:0.34/1:0.03)
[ColorOverLifetime]
Color=gradient(0:0.98,0.86,0.72,0/0.05:0.98,0.86,0.72,0.5/0.22:0.86,0.78,0.72,0.58/0.5:0.7,0.7,0.73,0.48/0.76:0.62,0.66,0.72,0.34/0.94:0.68,0.72,0.78,0.1/1:0.74,0.8,0.88,0)
[Noise]
Strength=0.24
Frequency=0.24
OctaveCount=2
ScrollSpeed=0.07
Damping=True
Quality=High
[TextureSheetAnimation]
Mode=Grid
NumTilesX=8
NumTilesY=16
Animation=WholeSheet
RowMode=Custom
RowIndex=0
TimeMode=Lifetime
StartFrame=0.08|0.18
Cycles=1
FrameOverTime=curve(0:0.14/0.25:0.35/0.65:0.65/1:0.92)

