; 500 kt v2: column_cloudlets; world-space distributed cloud layer.
[Main]
Duration=24
Loop=False
Prewarm=False
StartDelay=2.5
StartLifetime=55|70
StartSpeed=0
StartSize=2.6|4.4
StartRotation=-3.14159|3.14159
StartColor=0.23,0.21,0.24,0.82
GravityModifier=0
SimulationSpace=World
ScalingMode=Hierarchy
PlayOnAwake=True
EmitterVelocityMode=Custom
CustomVelocity=0,0,0
MaxParticles=650
StopAction=None
CullingMode=AlwaysSimulate

[Emission]
RateOverTime=18
RateOverDistance=0
Bursts=0:100:100:1:0.01

[Shape]
ShapeType=Sphere
Radius=2.4
Position=0,3.1,0
Rotation=0,0,0
Scale=1,1,1

[Renderer]
RenderMode=Billboard
Material=effects/explosions/emitters/nuclear_500kt_surface_v2/nuclear_cloud_alpha.ini
SortMode=Distance
SortingFudge=0
SortingOrder=0
Alignment=View
MinParticleSize=0
MaxParticleSize=5
ShadowCastingMode=Off
ReceiveShadows=False
LightProbeUsage=Off
ReflectionProbeUsage=Off

[ColorOverLifetime]
Color=gradient(0:0.76,0.78,0.80,0/0.05:0.78,0.80,0.82,0.7/0.3:0.80,0.82,0.84,0.8/0.75:0.82,0.84,0.86,0.22/1:0.84,0.86,0.88,0)

[SizeOverLifetime]
SeparateAxes=False
Size=curve(0:0.16/0.15:0.65/0.5:1.3/1:1.9)

[VelocityOverLifetime]
Space=World
X=-0.04|0.04
Y=0.55|0.82
Z=-0.04|0.04

[Noise]
Strength=0.18
Frequency=0.3
OctaveCount=2
ScrollSpeed=0.08
Damping=True
Quality=High

[TextureSheetAnimation]
Mode=Grid
NumTilesX=8
NumTilesY=16
Animation=WholeSheet
RowMode=Custom
RowIndex=0
TimeMode=Lifetime
StartFrame=0
Cycles=1
FrameOverTime=curve(0:0.17/0.2:0.48/1:0.95)
