; A subdued 2-D core supplies cohesion; sparse surrounding particles provide volume.
[Main]
Duration=0.1
Loop=False
Prewarm=False
StartDelay=0.12
StartLifetime=8.2
StartSpeed=0
StartSize=25
StartRotation=0
StartColor=1,1,1,0.64
GravityModifier=0
SimulationSpace=World
ScalingMode=Hierarchy
PlayOnAwake=True
EmitterVelocityMode=Custom
CustomVelocity=0,0,0
MaxParticles=1
StopAction=None
CullingMode=AlwaysSimulate
[Emission]
RateOverTime=0
RateOverDistance=0
Bursts=0:1:1:1:0.01
[Shape]
ShapeType=Sphere
Radius=0
Position=0,4.8,0
Rotation=0,0,0
Scale=1,1,1
[Renderer]
RenderMode=Billboard
Material=effects/explosions/materials/fx_main_fireball_1
SortMode=Distance
SortingFudge=0
SortingOrder=-3
Alignment=View
MinParticleSize=0
MaxParticleSize=8
ShadowCastingMode=Off
ReceiveShadows=False
LightProbeUsage=Off
ReflectionProbeUsage=Off
[SizeOverLifetime]
SeparateAxes=False
Size=curve(0:0.08/0.07:0.72/0.2:1/0.48:1.08/0.75:1.02/1:0.94)
[ColorOverLifetime]
Color=gradient(0:1,1,1,0/0.03:1,1,1,0.78/0.2:1,0.97,0.8,0.72/0.5:1,0.7,0.36,0.6/0.82:0.86,0.43,0.18,0.4/0.95:0.56,0.4,0.32,0.18/1:0.5,0.5,0.5,0)
[VelocityOverLifetime]
Space=World
X=0
Y=curve(0:0.18/0.35:0.5/1:0.42)
Z=0
[TextureSheetAnimation]
Mode=Grid
NumTilesX=16
NumTilesY=16
Animation=WholeSheet
RowMode=Custom
RowIndex=0
TimeMode=Lifetime
StartFrame=0
Cycles=1
FrameOverTime=curve(0:0/0.18:0.1/0.45:0.25/0.72:0.47/1:0.7)


