; Darker alpha-blended cloud for 500 kt mushroom
[Shader]
Path=Legacy Shaders/Particles/Alpha Blended
[Properties]
_TintColor=Color,{*}FFFFFFFF
_InvFade=Float,1
[Textures]
_MainTex=effects/weapons/textures/fx_boostersmoke2_white
