#!extend campaigns/cities.ini
# ver. 20260905

[Málaga]
Location=36.7167, -4.4167
Nation=Spain
Ports=Port Málaga
ShowAs=Port
Airports=LEMG

[Fuengirola]
Location=36.5390, -4.6247
Nation=Spain

[Ferrol]
Location=43.4766, -8.2401
Nation=Spain
Ports=Port Ferrol
ShowAs=Port

[Cartagena]
Location=37.600, -0.987
Nation=Spain
Ports=Port Cartagena
ShowAs=Port

[Cadiz]
Location=36.535, -6.2975
Nation=Spain
Ports=none

[Rota]
Location=36.620763, -6.331558
Nation=Spain
Ports=Port Rota
ShowAs=Port

[Morón de la Frontera]
Location=37.1750, -5.6151
Nation=Spain
ShowAs=Airport

[Torrejón]
Location=40.4912, -3.4542
Nation=Spain
ShowAs=Airport

[Los Llanos]
Location=38.9554, -1.8601
Nation=Spain
ShowAs=Airport

[Zaragoza]
ShowAs=Airport

[Las Palmas]
ShowAs=Airport

[San Javier]
Location=37.7747, -0.8122
Nation=Spain
ShowAs=Airport

[Talavera la Real]
Location=38.8893, -6.8294
Nation=Spain
ShowAs=Airport

[Son Sant Joan]
Location=39.5487, 2.7235
Nation=Spain
ShowAs=Airport

[Barcelona]
ShowAs=Port

[Valencia]
ShowAs=Port

[Santa Cruz de Tenerife]
Location=28.472, -16.244
Nation=Spain

[Oviedo]
Location=43.3616, -5.8485
Nation=Spain

[León]
Location=42.5994, -5.5667
Nation=Spain

[Soria]
Location=41.7631, -2.4682
Nation=Spain

[La Coruña]
Location=43.3712, -8.3960
Nation=Spain

[Valladolid]
Location=41.6521, -4.7284
Nation=Spain

[Córdoba]
Location=37.8790, -4.7797
Nation=Spain

[Granada]
Location=37.1743, -3.6001
Nation=Spain

[Almería]
Location=36.8404, -2.4646
Nation=Spain

[Ceuta]
Location=35.8887, -5.3164
Nation=Spain

[Melilla]
Location=35.2922, -2.9381
Nation=Spain

[Isla de Alborán]
Location=35.9388, -3.0337
Nation=Spain

[Isla de Perejil]
Location=35.9135, -5.4180
Nation=Spain

[Algeciras]
Location=36.1305, -5.4418
Nation=Spain
Ports=Port Algeciras
ShowAs=Port

[Islas Chafarinas]
Location=35.1831, -2.4287
Nation=Spain

[Peñón de Vélez de la Gomera]
Location=35.1711, -4.2995
Nation=Spain

[Alhucemas]
Location=35.2215, -3.8887
Nation=Spain
