#!extend campaigns/ports.ini
# ver. 20260905

[Port Málaga]
Location=36.7167, -4.4167
Nation=Spain

[Port Ferrol]
Location=43.4766, -8.2401
Nation=Spain

[Port Cartagena]
Location=37.600, -0.987
Nation=Spain

[Port Rota]
Location=36.6208, -6.3316
Nation=Spain

[Port Algeciras]
Location=36.1305, -5.4418
Nation=Spain