#!/usr/bin/env python3
"""Build SEST Collection Fixes: the surgical overrides from the collection audit.

docs/collection-interop-audit.md examined every contested file across the 133
mods. Eleven of its findings were fixed by measured load-order moves (see
data/load-order.tokens.txt); the rest are value-level defects where no order
can win — the right stats are split across two mods, or every shipped copy has
the same bug. Those become overrides here, at the top of the order where the
SEST invariant guarantees they win.

Every file is a clone of one proven donor with the minimum deltas, each guarded
so an upstream change to the donor fails the build loudly instead of silently
shipping a stale merge. The audit cohort that justifies each fix is cited
inline — the full evidence (what each mod shipped, what was measured, what the
alternatives cost) lives in docs/collection-interop-audit.md.

Usage (repo root):  python3 integration/collection-fixes/build_patch.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MODS = ROOT / "mods-source"
OUT = Path(__file__).resolve().parent / "SEST_Collection_Fixes"

INFO_INI = """\
[Language_en]
Name=SEST Collection Fixes
Description=Value-level corrections from the collection-wide override audit: \
restores the vanilla-fidelity AGM-88 HARM the F-16 fleet was authored against, \
opens the GBU-53/B StormBreaker's 200-ft release window to 500-45000 ft, \
returns the GBU-12D and GBU-24 to conventional Paveway behaviour, gives the \
ESSM its only ECCM bonuses, re-unites the AC-130's 30mm definition with \
Euromod's ballistics, lifts the Hellfire's 2000-ft launch ceiling for the \
gunship, fixes AIM-9L/M impact size and speed-penalty keys, raises the \
AIM-9X turn rate, sharpens the GBU-39 SDB to its author's 1.5 m CEP, gives \
the KD-88 its 108 nm range and the AKF-98A its active-radar seeker, restores \
the eight Nimitz Expanded carriers with the CVN-70 typo fixed, keeps the \
Nimitz (2000s)'s type, class and hull names now that the retired mod that \
alone supplied them is gone, and repairs the MH-60R's dangling Penguin seat \
reference, gives the MH-60R an 816 \
Squadron RAN squadron under the Australian flag and returns the S-70B-2 to \
the Australian flag it only ever flew under, restores the loft angle the \
SM-3, SM-6 and PAC-3 MSE had commented out, and brings the SM-3's \
unreachable 220,000-ft target floor down to 150,000 ft, where the \
ballistic threats it exists to intercept actually fly. Generated by \
integration/collection-fixes/build_patch.py; must load above every workshop mod.

[Compatibility]
ApproximateVersion=0.8.2
"""


def read(mod, rel):
    src = MODS / mod / rel
    if not src.exists():
        sys.exit(f"donor missing (re-export {mod}?): {src}")
    return src.read_text(encoding="utf-8-sig", errors="replace")


def write(rel, text, header):
    dst = OUT / rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    banner = "".join(f"# {line}\n" for line in header.splitlines())
    dst.write_text(banner + text, encoding="utf-8")


def edit(text, pattern, repl, expect, ctx):
    """Regex-sub with an exact match-count guard (the SEAD260 lesson: never
    splice against a file you have not just re-verified)."""
    out, n = re.subn(pattern, repl, text, flags=re.M)
    if n != expect:
        sys.exit(f"{ctx}: pattern {pattern!r} matched {n} times, expected {expect} "
                 "- donor changed upstream, rebase this fix")
    return out


def main():
    built = []

    # ------------------------------------------------------------------ ammo
    # usn_agm-88 [audit: usn_agm-88 cohort]. Murder Hornet (3430135740) ships
    # an AGM-45 Shrike under this id and never fires it - its own airframes all
    # use usn_agm-88g. Every actual consumer is an F-16 from 3758320372 (plus
    # SEST F-16CM JATM), authored against this vanilla-fidelity HARM copy.
    # Shipped verbatim: the audit diffed it against vanilla usn_agm-88a.ini.
    t = read("3758320372", "ammunition/usn_agm-88.ini")
    if "AGM-88A HARM" not in t:
        sys.exit("usn_agm-88: donor no longer labelled AGM-88A HARM - re-verify")
    write("ammunition/usn_agm-88.ini", t,
          "SEST Collection Fixes - restores the AGM-88A HARM (3758320372's vanilla-\n"
          "fidelity copy). The prior winner was an AGM-45 Shrike under this id: 50 nm\n"
          "range, 25 nm seeker, no loft, which nothing in the collection ever fired.")
    built.append("usn_agm-88")

    # usn_aim-9l [audit: usn_aim-9l/9m cohort]. The winning copy carries
    # ImpactSize=5 - a numeric non-enum value used nowhere else (372x Medium /
    # 350x Large / 167x VerySmall repo-wide, zero numeric) - and drops
    # InterceptSpeedPenaltyMultiplier that vanilla carries. Everything else kept.
    #
    # DONOR REBASED 2026-09-20. The original donor was the deprecated Super
    # Hornet (3426791311), unsubscribed and pruned from the export. Re-measured
    # against what is left: US Naval Aviation (3737267013, rank 54) is now the
    # top provider and carries the IDENTICAL defect at the identical lines, so
    # the fix still earns its place - only the donor changes.
    #
    # usn_aim-9m is RETIRED from this pack: 3737267013's copy is already
    # ImpactSize=VerySmall with InterceptSpeedPenaltyMultiplier present, so
    # there is nothing left to correct. Shipping it would be an override that
    # changes nothing.
    ispm = ("InterceptSpeedPenaltyMultiplier=0.75                  "
            "// multiplier to the severity of the speed penalty, 0.75 for good, "
            "1.0 for average, 1.25 for poor")
    for name, kp in (("usn_aim-9l", "0.80"),):
        t = read("3737267013", f"ammunition/{name}.ini")
        t = edit(t, r"^ImpactSize=5(\s)", r"ImpactSize=VerySmall\1", 1, name)
        if "InterceptSpeedPenaltyMultiplier" in t:
            sys.exit(f"{name}: donor now defines InterceptSpeedPenaltyMultiplier - rebase")
        t = edit(t, rf"^(KillProbability={re.escape(kp)})", ispm + "\n\\1", 1, name)
        write(f"ammunition/{name}.ini", t,
              "SEST Collection Fixes - base: 3737267013's file. Two deltas back to\n"
              "vanilla convention: ImpactSize 5 (non-enum) -> VerySmall, and the\n"
              "dropped InterceptSpeedPenaltyMultiplier=0.75 restored.")
        built.append(name)

    # usn_aim-9x [audit: usn_aim-9x cohort]. The 2027-mod winner is the right
    # era anchor (full kinematics, 19.4 nm reach, best ECCM) but its
    # MaxTurnRate=45 is the lowest of five authors by a wide margin (70 / 80 /
    # 150 / 180 elsewhere) on a thrust-vectoring dogfight missile. Raised to
    # 70, matching the maintained US Naval Aviation value; everything else is
    # the winner's tuning untouched.
    t = read("3606774881", "ammunition/usn_aim-9x.ini")
    t = edit(t, r"^MaxTurnRate=45(\s)", r"MaxTurnRate=70\1", 1, "usn_aim-9x")
    write("ammunition/usn_aim-9x.ini", t,
          "SEST Collection Fixes - base: 3606774881's kinematic rewrite. One delta:\n"
          "MaxTurnRate 45 -> 70 deg/s (the other four authors wrote 70/80/150/180;\n"
          "45 was the outlier on a thrust-vectoring HOBS missile).")
    built.append("usn_aim-9x")

    # usn_gbu-39 [audit: usn_gbu-39 cohort]. USNA's winning SDB keeps the
    # correct glide kinematics but carries CircularErrorRadius=15 m - an order
    # of magnitude off the F-22 author's 1.5 m for a weapon whose entire point
    # is precision - plus the weaker warhead block. Audit call: winner's
    # kinematics + loser's CEP/Power/ImpactSize/TargetMemory.
    t = read("3737267013", "ammunition/usn_gbu-39.ini")
    t = edit(t, r"^Power=12$", "Power=27", 1, "usn_gbu-39")
    t = edit(t, r"^ImpactSize=Medium(\s)", r"ImpactSize=Large\1", 1, "usn_gbu-39")
    t = edit(t, r"^CircularErrorRadius=15(\s)", r"CircularErrorRadius=1.5\1", 1, "usn_gbu-39")
    if "TargetMemory" in t:
        sys.exit("usn_gbu-39: donor now defines TargetMemory - rebase")
    t = edit(t, r"^(CircularErrorRadius=1\.5.*)$", "\\1\n#Homing\nTargetMemory=True",
             1, "usn_gbu-39")
    write("ammunition/usn_gbu-39.ini", t,
          "SEST Collection Fixes - base: 3737267013's glide kinematics; CEP 15 ->\n"
          "1.5 m, Power 12 -> 27, ImpactSize Medium -> Large, TargetMemory=True\n"
          "taken from the F-22 author's copy (3418252667) per the audit.")
    built.append("usn_gbu-39")

    # usn_gbu-53 [audit: usn_f-35c/usn_gbu-53 cohort - the launch-envelope
    # trap]. The winning StormBreaker's release window is MinLaunchAltitude
    # 9900 / MaxLaunchAltitude 10100 - a 200-foot band that reads like a
    # hand-tuned test value. 34 mission F-35Cs and 24 Block IIIs carry it.
    # Seeker, ReattackMode, 47 nm reach and the 93 kg-appropriate warhead all
    # kept; only the envelope opens to the losers' 500-45000 ft.
    t = read("3607989779", "ammunition/usn_gbu-53.ini")
    t = edit(t, r"^MinLaunchAltitude=9900(\s)", r"MinLaunchAltitude=500\1", 1, "usn_gbu-53")
    t = edit(t, r"^MaxLaunchAltitude=10100(\s)", r"MaxLaunchAltitude=45000\1", 1, "usn_gbu-53")
    write("ammunition/usn_gbu-53.ini", t,
          "SEST Collection Fixes - base: 3607989779's radar-seeking StormBreaker.\n"
          "One fix: the 9900-10100 ft release window (a 200-ft band no aircraft\n"
          "holds) opened to 500-45000 ft. Warhead stays 13/Small/Moderate - the\n"
          "defensible figure for a 93 kg SDB II.")
    built.append("usn_gbu-53")

    # usn_gbu-12d [audit: usn_gbu-12d cohort]. The winner re-roled the GBU-12
    # as an armour-piercing penetrator with a 2000 ft floor, applied to every
    # carrier in the collection (mission Super Hornets included). The three
    # losers agree on the conventional blast-frag Paveway II; USNA's copy is
    # the maintained one. Its Mass=363 is a GBU-16 figure - the audit endorses
    # the winner's 275 kg for a 500 lb Paveway II, so that one value is kept.
    t = read("3737267013", "ammunition/usn_gbu-12d.ini")
    t = edit(t, r"^Mass=363(\s)", r"Mass=275\1", 1, "usn_gbu-12d")
    write("ammunition/usn_gbu-12d.ini", t,
          "SEST Collection Fixes - base: 3737267013's conventional Paveway II\n"
          "(blast-frag Power 32, 500 ft floor, vanilla 10 nm seeker convention).\n"
          "One delta: Mass 363 -> 275 kg, the accurate 500 lb figure.")
    built.append("usn_gbu-12d")

    # usn_gbu-24 [audit: usn_gbu-24 cohort]. The winning copy is a 363 kg
    # GBU-27 substituted under the GBU-24's id; the only consumer anywhere is
    # the vanilla A-6E. Vanilla body verbatim: guaranteed assets, and exactly
    # what that consumer was authored against.
    t = read("_vanilla/original", "ammunition/usn_gbu-24.ini")
    if "Mass=1050" not in t:
        sys.exit("usn_gbu-24: vanilla export changed - re-verify")
    write("ammunition/usn_gbu-24.ini", t,
          "SEST Collection Fixes - the vanilla GBU-24 Paveway III, verbatim. The\n"
          "prior winner shipped a 363 kg GBU-27 under this id; the only consumer\n"
          "(vanilla A-6E) expects this file.")
    built.append("usn_gbu-24")

    # usa_agm-114k [audit: usa_agm-114k cohort]. The French Helicopter
    # Package's winning Hellfire has the better kinematics (13 deg/s, 5.94 nm,
    # Power 21) but a 2000 ft launch ceiling - one tenth of the mission
    # AC-130J's cruise altitude, gating its only precision weapon. Ceiling
    # raised to 20000 ft; the AC-130 pack's supply cost restored.
    t = read("3567228449", "ammunition/usa_agm-114k.ini")
    t = edit(t, r"^MaxLaunchAltitude=2000(\s)", r"MaxLaunchAltitude=20000\1", 1, "usa_agm-114k")
    if "AmmoPoints" in t:
        sys.exit("usa_agm-114k: donor now defines AmmoPoints - rebase")
    t = edit(t, r"^(Mass=45\.7.*)$",
             "\\1\nAmmoPoints=65                          // For Supply System. "
             'Defines "price" of ammunition based on mass, volume, complexity and availability',
             1, "usa_agm-114k")
    write("ammunition/usa_agm-114k.ini", t,
          "SEST Collection Fixes - base: 3567228449's agile Hellfire (kept for the\n"
          "whole helicopter fleet). Two deltas: MaxLaunchAltitude 2000 -> 20000 ft\n"
          "so the AC-130J can fire from orbit altitude, and the AC-130 pack's\n"
          "AmmoPoints=65 supply cost restored.")
    built.append("usa_agm-114k")

    # usn_cal_30mm [audit: usn_cal_30mm cohort]. Euromod's winning definition
    # is a stripped file: no Mass/AmmoPoints, no GravityFactor, no proximity
    # fuze, no intercept probability, no [Models] block - all authored by the
    # AC-130 pack and silently dropped by the whole-file override. Composed:
    # Euromod's ballistics (1109 m/s, 4000 m, CEP 12) + the AC-130 pack's
    # missing keys and shell mesh. Live on the gunship's gun and the
    # Zumwalt's 30mm mount.
    euro = read("3629144864", "ammunition/usn_cal_30mm.ini")
    ac130 = read("3559495372", "ammunition/usn_cal_30mm.ini")
    for needle, where in (("MuzzleVelocity=1109", euro), ("CircularErrorProbable=12", euro),
                          ("FuzeProximityDistance=25", ac130), ("KillProbability=0.0002", ac130),
                          ("ResourcesRoot=shell_small", ac130), ("GravityFactor=4", ac130)):
        if needle not in where:
            sys.exit(f"usn_cal_30mm: donor lost {needle!r} - rebase this merge")
    write("ammunition/usn_cal_30mm.ini", COMPOSED_CAL_30MM,
          "SEST Collection Fixes - merge of both authors: Euromod's ballistics\n"
          "(1109 m/s, 4000 m, CEP 12) + the AC-130 pack's Mass/AmmoPoints,\n"
          "GravityFactor, 25 m proximity fuze, intercept KillProbability and\n"
          "shell-mesh [Models] block that the override was silently dropping.")
    built.append("usn_cal_30mm")

    # usn_rim-162 [audit: usn_rim-116/162 cohort]. Both shippers carry the
    # dead legacy ECCM pair (CounterMeasuresRejection - zero occurrences in
    # vanilla 0.8.2); only Mogami's losing copy adds the live keys. The
    # mission's entire air-defence line fires ESSM against dedicated PLA
    # jamming aircraft, so AntiJammerBonus is not cosmetic.
    t = read("3461044389", "ammunition/usn_rim-162.ini")
    if "AntiCountermeasuresBonus" in t:
        sys.exit("usn_rim-162: donor now defines AntiCountermeasuresBonus - rebase")
    t = edit(t, r"^(NoiseRejection=60.*)$",
             "\\1\n#ECCM\n"
             "AntiCountermeasuresBonus=0.4          // This value substracted from "
             "probability of spoofing by countermeasures (0...1)\n"
             "AntiJammerBonus=0.2                   // This value substracted from "
             "probability of being jammed  (0...1)",
             1, "usn_rim-162")
    write("ammunition/usn_rim-162.ini", t,
          "SEST Collection Fixes - base: 3461044389's ESSM. One addition, from the\n"
          "Mogami mod's copy: AntiCountermeasuresBonus=0.4 / AntiJammerBonus=0.2 -\n"
          "the only live-schema ECCM values any mod defines for RIM-162.")
    built.append("usn_rim-162")

    # plaaf_kd-88 [audit: plaaf_kd-88 cohort]. After the load-order move the
    # CV-18 mod's KD-88 wins: LandAttackCapability=All, sea-skimming terminal,
    # real KD-88 mesh - everything the audit wanted except the Fujian mod's
    # 108 nm range figure. This override is that merge, pinned above future
    # reorders.
    t = read("3663564190", "ammunition/plaaf_kd-88.ini")
    if "LandAttackCapability" not in t:
        sys.exit("plaaf_kd-88: donor lost LandAttackCapability - rebase")
    t = edit(t, r"^MaxLaunchRange=97(\s)", r"MaxLaunchRange=108\1", 1, "plaaf_kd-88")
    write("ammunition/plaaf_kd-88.ini", t,
          "SEST Collection Fixes - base: 3663564190's KD-88 (land attack, 200 ft\n"
          "sea-skimming, real mesh, supply cost). One delta: MaxLaunchRange 97 ->\n"
          "108 nm, the higher of the two carrier mods' figures per the audit.")
    built.append("plaaf_kd-88")

    # plaaf_akf-98a [audit: plaaf_akf-98a cohort]. The winning copy sets
    # GuidanceType=4 (anti-radiation) on a stat block written for an active
    # seeker: SeekerActiveRange=50, Ku-band, 35 kW, and a Secondary PASSIVE
    # guidance key whose own comment says it is for active/semi-active
    # seekers. =3 makes the file coherent and the 320 nm ASuW round able to
    # engage non-emitting targets.
    t = read("3663564190", "ammunition/plaaf_akf-98a.ini")
    t = edit(t, r"^GuidanceType=4$", "GuidanceType=3", 1, "plaaf_akf-98a")
    write("ammunition/plaaf_akf-98a.ini", t,
          "SEST Collection Fixes - base: 3663564190's AKF-98A. One delta:\n"
          "GuidanceType 4 -> 3 (active radar). The file's own seeker block\n"
          "(SeekerActiveRange=50, Ku-band 35 kW, SecondaryPassiveRadarGuidanceType)\n"
          "is written for an active seeker; as an ARM it could only ever engage\n"
          "emitting targets.")
    built.append("plaaf_akf-98a")

    # usn_rgm_184a [NSM investigation, secondary finding]. The RAN's NSM carries
    # MinAttackAltitude=55 - "minimum altitude of a TARGET, in feet. Outside
    # Min/Max altitude missile deviation is greatly increaced". Its targets are
    # ships, at ~0 ft, so every shot this round ever takes is outside its own
    # band. This is NOT why the Anzacs held fire (that was the missing
    # datalink provider, fixed in integration/ran-fleet/build_fleet.py) - the
    # key degrades accuracy, it does not veto launch, confirmed against the 74
    # vanilla files that carry it. But no ship-launched anti-ship round should
    # have it at all: all 74 vanilla carriers are AAW missiles, and none of the
    # three comparison NSMs (Euromod's knm_nsm_1a, the Type 23's rn_nsm,
    # vanilla's usn_rgm-84d Harpoon) declares an attack-altitude floor.
    # Deliberately NOT touched: TerminalApproachDist=25 against a 20 nm seeker.
    # It looks wrong, but it is Red Storm Arsenal's house style across its whole
    # arsenal (plan_yj18 19.5 vs 14, wp_ss_n_19a 30 vs 14) and vanilla ships the
    # same shape on the Charlie-I's SS-N-7, so it is proven not to break launch
    # or flight - and TargetMemory=True carries the round through the gap.
    t = read("3413868677", "ammunition/usn_rgm_184a.ini")
    t = edit(t, r"^MinAttackAltitude=55[^\n]*\n", "", 1, "usn_rgm_184a")
    write("ammunition/usn_rgm_184a.ini", t,
          "SEST Collection Fixes - base: 3413868677's NSM (RGM-184A), the round the\n"
          "RAN Anzacs and Hobarts fire. One delta: MinAttackAltitude=55 removed. It\n"
          "put every sea-level target outside the round's own engagement band, where\n"
          "the engine 'greatly increases' missile deviation; no vanilla anti-ship\n"
          "round declares the key and no other NSM in the collection does either.")
    built.append("usn_rgm_184a")

    # usn_rim-161b/c/d, usn_rim-174a/c, usn_pac3_mse [SM-3 investigation].
    # Reported in game: the SM-3 flies strangely and shows ~5% intercept
    # against everything (7% against supersonic-high).
    #
    # All six of these rounds declare MaxLoftAlt with their MaxLoftAngle
    # COMMENTED OUT - the author wrote the value, then disabled the line.
    # 527 missiles across the collection pair the two keys; 14 do not, and
    # every one of the 14 is either one of these six or lofts to 300 ft or
    # less, where a climb angle means nothing. So a missile told to reach
    # 300,000 ft is given no angle to climb at, and flies whatever the
    # engine defaults to instead of the near-vertical boost the number
    # describes. Same shape as the ARRW's missing MaxLoftAlt: a key left
    # off, silently costing the weapon its behaviour - except here the
    # intended value is sitting in the file, so nothing is invented.
    #
    # The two symptoms are one bug. An interceptor that never reaches its
    # band is out of altitude for the whole engagement, and the engine's
    # out-of-altitude term is what drives the Pk readout into the single
    # digits.
    #
    # Second defect, same family, and the one behind the rest of the report
    # (lock/unlock cycling, wandering off for minutes, ~5% intercept against
    # everything and 7% against supersonic-high): the three SM-3s gate at
    # MinAttackAltitude=220000, and outside a round's altitude band the
    # engine "greatly increases missile deviation" - its own comment. A
    # deviating missile loses and regains its track, which is the cycling,
    # and MaxFlightTime=300 is how it wanders for five minutes. The "high"
    # profile scoring 7% rather than 5% is the same term: less far below
    # the gate.
    #
    # 220,000 ft is unsatisfiable in practice. Of 589 missiles in the
    # collection only eleven threat rounds ever reach it - the Chinese
    # DF-21/DF-26/JL-1/YJ-17/YJ-20 family. Everything else an SM-3 exists to
    # shoot at peaks below: JL-3, R-39 and R-29RMU at 200,000, Kinzhal at
    # 200,000, YJ-21 at 180,000, SS-26 at 165,000. So nearly every
    # engagement the round can be given is an out-of-band one.
    #
    # 150,000 ft is a deliberate compromise, chosen by the user, and it is
    # worth being honest that it is not anchored the way the rest of this
    # file is. Three candidates were on the table:
    #
    #   220,000 (upstream)  the realistic PARAMETER. Real SM-3 intercepts
    #                       are exoatmospheric, 70-100 km up. But only 11 of
    #                       the collection's threats ever reach it, so the
    #                       round is inert and wanders - a far less
    #                       realistic OUTCOME than a working interceptor.
    #    99,000 (hq-19)     the anchored option: pla_hq-19, the collection's
    #                       only other exoatmospheric BMD interceptor, same
    #                       role and same CanNotAttackTypes, uses it. Covers
    #                       29 threats.
    #   150,000 (chosen)    leans back toward the real engagement regime
    #                       while still covering 18 threats - the whole
    #                       DF-21/DF-26/YJ-17/YJ-20/JL family, plus JL-3,
    #                       R-39, R-29RMU and Kinzhal at 200,000, YJ-21 at
    #                       180,000, SS-26 at 165,000 and PrSM at 160,000.
    #
    # What the choice costs, so it is on the record: the 99,000 ft tier goes
    # out of band - plan_yj21 and plaaf_cm401 (Chinese anti-ship hypersonics)
    # and usn_cps / usn_arrw. If those need intercepting, 99,000 is the
    # number and pla_hq-19 is the justification for it.
    #
    # Either way the round stays high-altitude: cruise missiles and
    # sea-skimmers are nowhere near the band, and aircraft are excluded
    # outright by upstream's CanNotAttackTypes=Aircraft,Helicopter, which is
    # correct - the SM-3's kill vehicle manoeuvres on thrusters in vacuum
    # and has no aerodynamic control surfaces.
    #
    # Precedent in this file: usn_rgm_184a above, where MinAttackAltitude=55
    # was removed for the same engine behaviour against sea-level targets.
    # Not removed here, because unlike the NSM this round really is a
    # high-altitude interceptor - the floor is wrong, not the idea of one.
    #
    # NOT touched: MaxAttackAltitude. An earlier revision of this comment
    # said the SM-3s do not declare it. They do - 1,640,000 ft on the B and
    # C, 3,000,000 on the D - and both are realistic, which is exactly why
    # the 300,000 ft MaxLoftAlt cap above is a defect rather than a choice.
    #
    # NOT touched: KillProbability. 0.85/0.85/0.90 against pla_hq-19's 0.95
    # looks like the same asymmetry, but it is not - the real SM-3 test
    # record is around 30 hits in 40 attempts, so these are honest numbers.
    # If anything the 0.95 is the generous one, and it belongs to another
    # author's mod.
    # MaxFlightTime sized to each block's own declared range at its own
    # MaxVelocity, with headroom for VelocityBleed=0.6: the B and C need
    # 300 s for 486 nm and get 600; the D needs 617 s for 1500 nm and gets
    # 900. Real SM-3 engagements at these ranges run ten minutes and up.
    SM3 = {"usn_rim-161b": 600, "usn_rim-161c": 600, "usn_rim-161d": 900}
    LOFT_ANGLE = {"usn_rim-161b": "85.0", "usn_rim-161c": "85.0",
                  "usn_rim-161d": "85.0", "usn_rim-174a": "80.0",
                  "usn_rim-174c": "80.0", "usn_pac3_mse": "65.0"}
    for name, angle in LOFT_ANGLE.items():
        t = read("3629144864", f"ammunition/{name}.ini")
        if re.search(r"^MaxLoftAngle=", t, re.M):
            sys.exit(f"{name}: upstream enabled MaxLoftAngle - drop this fix")
        t = edit(t, rf"^[;#]\s*MaxLoftAngle={angle}\b([^\n]*)$",
                 f"MaxLoftAngle={angle}\\1", 1, name)
        extra = ""
        if name in SM3:
            # ---- the SM-3 realism pass -----------------------------------
            # Benchmark is pla_hq-19: the collection's other dedicated
            # exoatmospheric BMD interceptor, a Chinese one, and the round
            # this has to be measured against if the two sides are to behave
            # like their real counterparts.
            #
            # 1. IT CANNOT CLIMB TO ITS OWN CEILING. MaxAttackAltitude is
            #    1,640,000 ft (500 km) on the B and C and 3,000,000 ft
            #    (914 km) on the D - realistic figures - but MaxLoftAlt caps
            #    the climb at 300,000 ft (91 km). So the round is cleared to
            #    engage through a band whose top 82-90% it physically cannot
            #    reach. The real Block IIA apogees far above that and
            #    intercepted an ICBM-class target in 2020. hq-19 has no such
            #    hole because it lofts to "Target" - a documented symbolic
            #    value meaning "climb to the altitude the target was at" -
            #    so it always reaches its mark. The SM-3 gets the same.
            t = edit(t, r"^MaxLoftAlt=300000\.0\b", "MaxLoftAlt=Target", 1, name)

            # 2. THE PROVEN INTERCEPTOR IS RATED THE WORST ONE. SM-3 is the
            #    most combat-proven BMD interceptor in service, and sits at
            #    0.50 - "poor" by the file's own scale - while pla_hq-19 and
            #    pla_hq-9 both get 0.10 and the SM-6 gets 0.15. The C is
            #    worse still at 1.10, the only value in 151 AAW rounds past
            #    the documented end of the scale. All three to hq-19's 0.10:
            #    its direct opposite number, same role, same collection.
            t = edit(t, r"^InterceptOutOfAltitudePenalty=(?:0\.50|1\.10)\b",
                     "InterceptOutOfAltitudePenalty=0.10", 1, name)

            # 3. IT DIES BEFORE ITS DECLARED RANGE. MaxFlightTime=300 s at
            #    MaxVelocity buys the B and C exactly their 486 nm with zero
            #    margin, and the D only 729 nm of its declared 1500 - it
            #    expires at the half-way point of a shot the file says it can
            #    take. VelocityBleed=0.6 makes both worse in practice. By
            #    contrast hq-19's 280 s covers its 175 nm two and a half
            #    times over, so the enemy round has the margin this one
            #    lacks. Sized to the declared range plus that bleed.
            t = edit(t, r"^MaxFlightTime=300\b", f"MaxFlightTime={SM3[name]}", 1, name)
            extra = (f"\nMaxLoftAlt 300000 -> Target, so it climbs to the target instead "
                     f"of\nstopping at 91 km inside a band that reaches 500-914 km.\n"
                     f"InterceptOutOfAltitudePenalty -> 0.10, the value its opposite "
                     f"number\npla_hq-19 carries; it had 0.50 ('poor'), and the C had an "
                     f"off-scale 1.10.\nMaxFlightTime 300 -> {SM3[name]} s, enough to "
                     f"actually fly its declared range.\nMinAttackAltitude 220000 -> "
                     f"150000, where the ballistic threats fly.")
            t = edit(t, r"^MinAttackAltitude=220000\b", "MinAttackAltitude=150000",
                     1, name)
        if name == "usn_rim-161d":
            # The D is the fastest and newest of the three and is penalised
            # 30x more than its older siblings for target speed, which is
            # backwards. Aligned to the B and C's value - in-family, and the
            # softest change in this block.
            t = edit(t, r"^InterceptSpeedPenaltyMultiplier=0\.3\b",
                     "InterceptSpeedPenaltyMultiplier=0.01", 1, name)
            extra += ("\nInterceptSpeedPenaltyMultiplier 0.3 -> 0.01, its own B and C "
                      "siblings'\nvalue: the fastest of the three was the worst at "
                      "catching fast targets.")
        write(f"ammunition/{name}.ini", t,
              f"SEST Collection Fixes - base: 3629144864's {name}. One delta:\n"
              f"MaxLoftAngle={angle} un-commented. The author wrote the value and then\n"
              "disabled the line, which left MaxLoftAlt with no climb angle: the round\n"
              "is told what altitude to reach and not how steeply to get there." + extra)
        built.append(name)

    # -------------------------------------------------------------- vessels
    # usn_cvn_nimitz_variants [audit: usn_cvn_nimitz_variants cohort]. Flight
    # Deck Ops' 2-variant file was discarding Nimitz Expanded's other eight
    # carriers (CVN-70..77, each with hull numbers and period air wings).
    # Shipping the 10-variant file here composes the two mods instead of
    # reordering 20 slots: FDO keeps the hull and all deck-ops animation.
    # One fix: Variant3's 'sn_s-3a' dangling id -> usn_s-3a, so Vinson's
    # Vikings actually spawn.
    t = read("3432592449", "vessels/usn_cvn_nimitz_variants.ini")
    if "NumberOfVariants=10" not in t:
        sys.exit("usn_cvn_nimitz_variants: donor no longer 10 variants - rebase")
    t = edit(t, r"^sn_s-3a=Squadron8,10$", "usn_s-3a=Squadron8,10", 1, "usn_cvn_nimitz_variants")
    write("vessels/usn_cvn_nimitz_variants.ini", t,
          "SEST Collection Fixes - base: 3432592449's 10-variant table (CVN-68..77\n"
          "with per-hull numbers, emblems and period air wings), which Flight Deck\n"
          "Ops' 2-variant file was overriding away. One delta: Variant3's dangling\n"
          "'sn_s-3a' corrected to usn_s-3a. The FDO hull and animations still win.")
    built.append("usn_cvn_nimitz_variants")

    # ------------------------------------------------------------- aircraft
    # usn_mh-60r [audit: usn_mh-60r cohorts] - RETIRED 2026-09-20.
    #
    # The fix removed a dangling '|MK46' seat from the AntiShip fit's Penguin.
    # In the 2026-09-20 export U.S. Navy 2027 has reworked the aircraft
    # outright: the AntiShip loadout is gone, replaced by Anti-shipEarly
    # (usn_agm-119_air) and Anti-shipLate (AGM-114 on TERAGM114), and the
    # string MK46 no longer appears anywhere in the file. There is nothing
    # left to correct, so the override is dropped rather than re-aimed.
    #
    # Checked before dropping, because retiring an override changes which file
    # the game reads: the active mission's MH-60R flies LoadoutVariant=Default,
    # and the four SEST RAAF base rosters name the unit without a loadout, so
    # nothing referenced the loadout key that disappeared.
    for stale in ("aircraft/usn_mh-60r.ini", "ammunition/usn_aim-9m.ini"):
        f = OUT / stale
        if f.exists():
            f.unlink()
            print(f"    removed {stale} (retired - upstream no longer carries the defect)")

    # usn_mh-60r_squadrons - the Royal Australian Navy's Seahawk.
    #
    # The campaign flies the MH-60R as the RAN's ship's flight, and every one
    # of the type's squadrons, in every mod, is a US Navy squadron with
    # Nation=US - the unit panel showed a foreign flag on HMAS Arafura's
    # helicopter. The squadron is what carries a nation for an aircraft (stock
    # usn_p-2h_squadrons.ini gives its RAAF squadron Nation=Australia and
    # flag_australia), so the fix is a squadron, not a new airframe.
    #
    # Donor: 3737267013's 19-squadron table. It is the one written for the
    # model the winning aircraft file draws - U.S. Navy 2027's usn_mh-60r
    # loads 3737267013's sh60 mesh with `Modex` and `Emblem` submodels, which
    # is what this table's SerialnumberReferences=Modex / EmblemReference=
    # Emblem decorate. The copy that won before (3590477166, three squadrons)
    # names a `number` submodel the model does not have. One delta: an 816
    # Squadron RAN entry appended as Squadron20, on the Default livery and
    # serials, with no US squadron badge.
    t = read("3737267013", "aircraft/usn_mh-60r_squadrons.ini").replace("\r\n", "\n")
    if "NumberOfSquadrons=19" not in t or "SerialnumberReferences=Modex" not in t:
        sys.exit("usn_mh-60r_squadrons: donor no longer the 19-squadron Modex table - rebase")
    t = edit(t, r"^NumberOfSquadrons=19$", "NumberOfSquadrons=20", 1, "usn_mh-60r_squadrons")
    default = re.search(r"^\[Default\]\n(.*?)(?=^\[)", t, re.S | re.M).group(1)
    serials = re.search(r"^SerialnumberTextures=(.+)$", default, re.M).group(1)
    livery = re.search(r"^LiveryTexture=(.+)$", default, re.M).group(1)
    t = t.rstrip("\n") + (
        "\n\n[Squadron20] #816 Squadron RAN - HMAS Albatross, Nowra\n"
        "ResourcesSerialnumberFolder=aircraft/materials/modex/\n"
        "SerialNumberPrefix=\n"
        f"SerialnumberTextures={serials}\n"
        "ResourcesEmblemFolder=\n"
        "ResourcesLiveryFolder=aircraft/usn_mh-60r/\n"
        f"LiveryTexture={livery}\n"
        "SpecularTexture=sh60_SpecTex.png\n"
        "ResourcesFlagFolder=ships/materials/textures/\n"
        "FlagTexture=flag_australia\n"
        "Nation=Australia\n")
    write("aircraft/usn_mh-60r_squadrons.ini", t,
          "SEST Collection Fixes - base: 3737267013's 19-squadron MH-60R table,\n"
          "the one written for the sh60 model U.S. Navy 2027's usn_mh-60r draws.\n"
          "One delta: Squadron20, 816 Squadron RAN, Nation=Australia with the\n"
          "Australian flag, for the Royal Australian Navy's ship's flights.")
    built.append("usn_mh-60r_squadrons")

    # S-70B-2_Seahawk_squadrons - the RAN's own Seahawk, flagged American.
    #
    # The S-70B-2 flew only with the Royal Australian Navy (816 Squadron, the
    # Tigers), and the mod's one squadron is named "S-70B-2 'Tiger'" - but
    # both its [Default] and [Squadron1] say Nation=US, so every one on an RAN
    # deck showed the US flag. One delta per section: Nation=Australia.
    t = read("3403661005", "aircraft/S-70B-2_Seahawk_squadrons.ini").replace("\r\n", "\n")
    if "NumberOfSquadrons=1" not in t:
        sys.exit("S-70B-2_Seahawk_squadrons: donor no longer one squadron - rebase")
    t = edit(t, r"^Nation=US$", "Nation=Australia", 2, "S-70B-2_Seahawk_squadrons")
    write("aircraft/S-70B-2_Seahawk_squadrons.ini", t,
          "SEST Collection Fixes - base: 3403661005's squadron table for the\n"
          "RAN's S-70B-2. One delta: Nation=US -> Australia in [Default] and\n"
          "[Squadron1], 816 Squadron's 'Tiger'.")
    built.append("S-70B-2_Seahawk_squadrons")

    build_mh60r_names()
    added = build_missing_sensors()
    named = build_missing_loadout_names()
    carried = build_carried_vessel_names()

    (OUT / "_info.ini").write_text(INFO_INI, encoding="utf-8")
    print(f"built {OUT.relative_to(ROOT)}: {len(built)} overrides - {', '.join(built)}")
    print(f"  + {len(added)} sensor definitions no mod supplied: {', '.join(added)}")
    print(f"  + {len(named)} loadout display names: {', '.join(named)}")
    print(f"  + {len(carried)} vessel name section(s) carried: {', '.join(carried)}")


# Sensor types that units mount but NO mod defines, so the sensor is inert.
# systems/ merges section-by-section, so supplying the missing definition adds
# capability without overriding anybody. Each is CLONED from the closest
# same-class, same-era definition rather than invented - donor named per entry.
#
#   new type          donor                       who mounts it (mission units)
MISSING_SENSORS = {
    "Side_Globe": ("_vanilla/original", "Start_ECM",
                   "Soviet shipboard defensive jammer. Donor is vanilla's own "
                   "Soviet ship ECM (Sovremenny, Udaloy, Krivak). Mounted by "
                   "ru_cv_varyag and wp_rkr_kirov_improved, both fielded."),
    "Rum_Tub": ("_vanilla/original", "Start_ESM",
                "Soviet shipboard ESM array, the receive half of the same suite "
                "as Side Globe. Mounted by wp_rkr_kirov_improved."),
    "J/OPS-20": ("3629144864", "eu_nav_radar",
                 "JMSDF navigation radar. Donor is Euromod's modern naval "
                 "navigation radar. Mounted by jmsdf_ddg_maya, fielded."),
    "pla_pod_kg-800": ("_vanilla/original", "Azaliya_OECM",
                       "PLAN escort jamming pod on the J-15D, the type's whole "
                       "reason to exist. Donor is vanilla's Soviet EW-aircraft "
                       "jammer at 5 kW - deliberately a fraction of the NGJ's "
                       "75 kW in SEST_Growler_NGJ_MALICE, so red gets a working "
                       "jammer rather than a Growler. 8 airframes fielded."),
    "4th_Gen_FLIR": ("_vanilla/original", "AdvancedOptics",
                     "EO/IR turret on the Z-9D. Donor is vanilla's advanced "
                     "optical sight."),
}


def build_missing_sensors():
    """Supply definitions for sensor types every mod references and none defines."""
    out, blocks = [], []
    for name, (donor_mod, donor_sec, why) in MISSING_SENSORS.items():
        # If anyone starts defining it, ours would shadow theirs - stop instead.
        for f in (ROOT / "mods-source").rglob("systems/sensors.ini"):
            if re.search(rf"^\[{re.escape(name)}\]", read_file(f), re.M):
                sys.exit(f"{name} is now defined by {f.parts[-3]} - drop it from "
                         "MISSING_SENSORS rather than shadowing upstream")
        src = read_file(MODS / donor_mod / "systems" / "sensors.ini")
        m = re.search(rf"^\[{re.escape(donor_sec)}\]\n(.*?)(?=^\[|\Z)", src, re.S | re.M)
        if not m:
            sys.exit(f"donor sensor [{donor_sec}] missing from {donor_mod} - rebase")
        body = "\n".join(l for l in m.group(1).strip().splitlines()
                         if not l.strip().startswith("#Users:"))
        blocks.append(f"# {name}: {why}\n"
                      f"# Cloned from [{donor_sec}] in {donor_mod}.\n"
                      f"[{name}]\n{body}\n")
        out.append(name)
    if blocks:
        (OUT / "systems").mkdir(parents=True, exist_ok=True)
        (OUT / "systems" / "sensors.ini").write_text(
            "# SEST Collection Fixes - sensor types that units mount but no mod\n"
            "# defines, so the sensor does nothing at all. systems/ files merge\n"
            "# section-by-section, so these ADD the missing definitions without\n"
            "# overriding anything. Every one is cloned from the closest\n"
            "# same-class, same-era definition; none is invented.\n\n"
            + "\n".join(blocks), encoding="utf-8")
    return out


# Loadout keys offered in a picker with no display name anywhere, so the UI
# shows the raw key. language_*/ merges key-by-key, so these are additive.
MISSING_LOADOUT_NAMES = {
    "Strike158": "Strike (AGM-158 JASSM)",
    "Strike86": "Strike (AGM-86 ALCM)",
    "StrikeNuke": "Strike (nuclear)",
    "CAS1": "Close Air Support (alt)",
    "StrikePrecision1": "Strike Precision (alt)",
    "StrikeLowAltitude": "Strike Low Altitude",
    # upstream typo: vanilla's key is AirToAirLongRange with a capital R, so the
    # Su-35's lowercase spelling matches nothing and shows raw in the picker
    "AirToAirLongrange": "Air To Air Long Range",
    # U.S. Navy 2027's MH-60R (the winning Seahawk, sold in Southern Watch
    # and flown in White Water's Ship's Flight) and the JMSDF SH-60K offer
    # these two and no mod names them - the picker read "MISSING TEXT -
    # [LoadoutNames]Anti-shipLate". Early hangs a Penguin with the Hellfires;
    # Late is Hellfires alone.
    "Anti-shipEarly": "Anti-ship (Penguin, Hellfire)",
    "Anti-shipLate": "Anti-ship (Hellfire)",
    # The Mi-24P's alternates, in the same (alt) style as the rows above.
    "DefaultAlt": "Default (alt)",
    "DefaultHeavy": "Default Heavy",
    "AntiArmorAlt": "AntiTank (alt)",
    "AntiArmorHeavy": "AntiTank Heavy",
    # J-36: YJ-91 and AKF-98 anti-radiation rounds with PL-15s.
    "AntiRadiation": "Anti-Radiation",
    # AS 332M Cougar: _1 dummies the .50 cal and keeps the 20 mm door gun,
    # _2 the reverse.
    "CASLight_1": "Close Air Support Light (20 mm)",
    "CASLight_2": "Close Air Support Light (.50 cal)",
    # Tu-95MA: an upstream typo for Default with no weapon section behind
    # it, so the fit carries nothing. Named for what it is rather than
    # disguised as the real Default.
    "Defaul": "Unarmed (mod typo)",
}


RAN_SEAHAWK = "Squadron20"


def build_mh60r_names():
    """[usn_mh-60r] display names for the composed squadron table.

    language_*/ merges key-by-key, and 3590477166 - which loads above
    3737267013 - names Squadron1-3 after ITS three squadrons (HSM-51/74/77),
    so over 3737267013's liveries (HSM-35/37/40) the names would be wrong.
    Squadron1-3 and the callsign list are copied from 3737267013's own file;
    Squadron20 and its callsign are the one addition.
    """
    src = read("3737267013", "language_en/aircraft_names.ini").replace("\r\n", "\n")
    sec = re.search(r"^\[usn_mh-60r\]\n(.*?)(?=^\[|\Z)", src, re.S | re.M)
    if not sec:
        sys.exit("3737267013 no longer names usn_mh-60r - rebase build_mh60r_names")
    keys = dict(re.findall(r"^(Squadron[123]|Callsigns)=(.+)$", sec.group(1), re.M))
    if set(keys) != {"Squadron1", "Squadron2", "Squadron3", "Callsigns"} or \
            "Squadron20" in keys["Callsigns"]:
        sys.exit(f"usn_mh-60r names changed upstream ({sorted(keys)}) - rebase")
    keys[RAN_SEAHAWK] = "MH-60R 816 Squadron RAN,MH-60R"
    keys["Callsigns"] += f"|{RAN_SEAHAWK},Tiger"
    order = ["Squadron1", "Squadron2", "Squadron3", RAN_SEAHAWK, "Callsigns"]
    body = ("# SEST Collection Fixes - names for the composed usn_mh-60r squadron\n"
            "# table: Squadron1-3 and Callsigns as 3737267013 wrote them (the\n"
            "# livery owner), plus the RAN squadron. Merges key-by-key.\n"
            "[usn_mh-60r]\n" + "".join(f"{k}={keys[k]}\n" for k in order))
    (OUT / "language_en").mkdir(parents=True, exist_ok=True)
    (OUT / "language_en" / "aircraft_names.ini").write_text(body, encoding="utf-8")


def build_missing_loadout_names():
    src = read_file(MODS / "_vanilla/original" / "language_en" / "loadout_names.ini")
    clash = [k for k in MISSING_LOADOUT_NAMES if re.search(rf"^{re.escape(k)}=", src, re.M)]
    if clash:
        sys.exit(f"vanilla now names these loadouts: {clash} - drop them here")
    body = ("# SEST Collection Fixes - display names for loadout keys that no mod\n"
            "# names, which the picker would otherwise show as the raw key.\n"
            "# language_*/ merges key-by-key, so nothing upstream is replaced.\n"
            "[LoadoutNames]\n"
            + "".join(f"{k}={v}\n" for k, v in MISSING_LOADOUT_NAMES.items()))
    (OUT / "language_en").mkdir(parents=True, exist_ok=True)
    (OUT / "language_en" / "loadout_names.ini").write_text(body, encoding="utf-8")
    return list(MISSING_LOADOUT_NAMES)


# Vessel name sections whose ONLY provider is a mod the collection is shedding.
#   unit id -> (mod that shipped the section, the section text verbatim)
# usn_cvn_nimitz_2000s: the hull is won by Murder Hornet (3430135740), which
# ships no language file at all. Its Type/class/hull names came solely from the
# DEPRECATED MyGo Super Hornet (3426791311) - the mod docs/setup-runbook.md
# tells the user to unsubscribe - and there they sat on line 1 behind a UTF-8
# BOM. Without them the picker files the carrier under "Missing Type" and
# labels it "MISSING: usn_cvn_nimitz_2000s name or squadron reference".
# language_*/ merges key-by-key, so carrying the section verbatim is a no-op
# while a provider is present and keeps the names when it goes.
#
# THE CARRY HOLDS THE TEXT, NOT A POINTER TO IT. Reading the section out of the
# donor at build time works only while the donor is still exported - which is
# exactly the case the carry exists to survive. MyGo was unsubscribed on
# 19 Sep 2026, the next export dropped the file, and the build then died on it
# instead of quietly keeping the names. The text below is the section as it
# stood in mods-source/3426791311/language_en/vessel_names.ini at 7a31060c, the
# last export that shipped it. While the donor IS present the build re-reads it
# and fails on any drift, so this copy cannot go stale unnoticed.
CARRIED_VESSEL_NAMES = {
    "usn_cvn_nimitz_2000s": ("3426791311", """\
Type=CVN,Aircraft Carrier
Default=Nimitz-class (2000s),Nimitz
DefaultDescription=The largest warships in USN service during the Cold War the Nimitz-class is a nuclear powered supercarrier displacing over 100000 tons. These ships are one of the most threatening ways that the USN has to project power away from the US coastline.
Variant1=Nimitz CVN-68,Nimitz
Variant2=Dwight D. Eisenhower CVN-69,Eisenhower
Variant3=Carl Vinson CVN-70,Vinson"""),
}


def build_carried_vessel_names():
    blocks, out = [], []
    for uid, (donor_mod, carried) in CARRIED_VESSEL_NAMES.items():
        donor = MODS / donor_mod / "language_en" / "vessel_names.ini"
        if donor.exists():
            m = re.search(rf"^\[{re.escape(uid)}\]\n(.*?)(?=^\[|\Z)",
                          read_file(donor), re.S | re.M)
            if not m:
                sys.exit(f"[{uid}] no longer in {donor_mod}'s vessel_names.ini - rebase")
            live = m.group(1).strip("\n")
            if live != carried:
                sys.exit(f"[{uid}] has drifted in {donor_mod}. Update "
                         f"CARRIED_VESSEL_NAMES to the live text:\n{live}")
        blocks.append(f"[{uid}]\n{carried}\n")
        out.append(uid)
    if blocks:
        (OUT / "language_en").mkdir(parents=True, exist_ok=True)
        (OUT / "language_en" / "vessel_names.ini").write_text(
            "# SEST Collection Fixes - vessel name sections carried verbatim from the\n"
            "# only mod that provides them, so the unit keeps its type, class and hull\n"
            "# names when that mod is unsubscribed. language_*/ merges key-by-key, so\n"
            "# nothing upstream is replaced. See CARRIED_VESSEL_NAMES in build_patch.py.\n\n"
            + "\n".join(blocks), encoding="utf-8")
    return out


def read_file(p):
    return Path(p).read_text(encoding="utf-8-sig", errors="replace")


COMPOSED_CAL_30MM = """\
[General]
#30mm HE / HEI
Type=Projectile            // can be Projectile, Missile, Torpedo
TargetType=AAW             // can be AAW, ASuW, ASW
SecondaryTargetType=ASuW

Mass=4.5                               // in kg. Used for aircraft
AmmoPoints=4.5                         // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

DecalClass=GunImpacts      // referenced in effects/decals.ini

[Physics]
MuzzleVelocity=1109         // meter per second
MaxRange=4000              // in m
GravityFactor=4
CircularErrorProbable=12   // radius in meters at max range for shells to impact

[---------- Warhead Data ----------]
[WarheadData]
Power=0.85
ImpactSize=Tiny           // Impact size, can be small, medium, large, verylarge
Penetration=Minor         // can be minor, moderate, heavy, always
FuzeProximityDistance=25              // In meters
KillProbability=0.0002                // Chance to intercept missile. Relevant for Guns, irrelevant for CIWS

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=weapons/shells/
ResourcesRoot=shell_small
ResourcesMesh=shell_small
ResourcesMaterial=shell_mat

[---------- Effects ----------]
[Particles]
TrailEffect=
HitShipExplosion=effects/Particle Emitters/impact_small_shell_multi
HitAirExplosionClass=SmallFlakExplosions
HitDefaultExplosion=effects/Particle Emitters/impact_small_shell
HitWaterSplashClass=TinyWaterSplashes
"""


if __name__ == "__main__":
    main()
