#=========================================================================================================================================================
#                                                  REQUIRES STATS REVISION
#=========================================================================================================================================================
[General]
# AIM-9X Sidewinder
#!alias ammunition/usn_aim-9x.ini

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_aim-9l
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_aim-9l_mat
AssetBundleMeshHullCollider=usn_aim-9l_coll
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/weapon/ammunition/aim-9/
ResourcesRoot=dts_aim-9x.obj
ResourcesMesh=aim-9x
ResourcesMaterialFolder=assets/models/weapon/ammunition/aim-9/textures
ResourcesMaterial=dts_aim-9x_mat.ini
############################################################
#NumberOfSubModels=0
[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
BoosterEffect=effects/weapons/emitters/aam_small_effect
BoosterEffectPosition=0,0,-0.015

InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,-0.015
InFlightEffectStartTime=2.0  // in seconds, after that the Inflight Effect will be played if available

HitShipExplosionClass=MediumMissileExplosions
HitAirExplosionClass=MediumMissileExplosions
HitDefaultExplosionClass=MediumMissileExplosions
HitWaterSplashClass=SmallWaterSplashes

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
# creates the hit boxes for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.005,0.005,0.043