#=========================================================================================================================================================
#                                                  REQUIRES STATS REVISION
#=========================================================================================================================================================
[General]
# AIM-9M Sidewinder
#!alias ammunition/usn_aim-9m.ini
