[CH53SA_FLIR]
Kind=Visual
#user: MH-60R
#Infrared
#3nd Gen Infrared
UseIRValues=True                 // Affects only Encyclopedia. For correct type display
VIDRangeMultiplier=3.0           // Target VID range multiplied by this for identification check. 0 means it cannot identify
MaxRangeMultiplier=3.0           // Target VID range multiplied by this for detection check. Can not be less then VID multiplier
LookDownMultiplier=1             // Final VID/Detection range is multiplied by this in case when target observed on surface background

[CH53SA_APS147]
#Users: MH-60R
Kind=Radar
Type=Search            // Classes can be "Search", "Targeting"
HasDataLink=True       // true means the sensor data will be used for the entire task force via data link, false local use only
Role=Surface           // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
RotationDirection=1    // -1 means left, 1 means right
TargetChannels=60       // if applicable number of targets it can track simultaneously
WeaponChannels=0       // if applicable number of weapons (missiles) it can guide simultaneously
RPM=6                 // revolutions per minute
MinRange=0.2           // min range in km
MaxRange=360.0         // max range in km
MinAltitude=0          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=0          // max altitude in meters, relevant for air, unused for surface
RangeResolution=80.0  // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=2.0          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=51.0              // gain in dB on the sensor
Frequency=X-Band       // frequency band
PeakPower=400.0         // output peak power in kW
CanDetectPeriscope=True

[CH53SA_AQS22]
#Users: MH-60R
Kind=Sonar
IsActiveOnly=False                   // True means no passive detection
HasDataLink=True                     // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=5.0                // TODO in degrees
RangeResolution=50.0                // TODO defines the minimum range where two targets behind can be recognized as two; in meters
Gain=40                              // in db, gain of the sensor
ActiveRange=25                       // in km
PassiveRange=24                      // in km
ActiveGain=20                        // in db, gain of the active sensor
OutputPower=220                      // Active sensor output power in dB, unused for passive ones
Type=Dipping                         //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF                    // TODO ????
SignalProcessing=7
MaxConvergenceZones=0				// maximum number of CZs this sonar can detect out to, 0 if incapable of using CZ/BB effects

[CH53SA_ESM]
#users: MH-60R 
Kind=ESM
Gain=12                              // gain of sensor in dB
HasDataLink=True                    // true means the sensor data will be used for the entire task force via data link, false local use only
IdentificationRate=1.2
AngularResolution=5.0              // in degrees
Frequencies=L-Band,S-Band,C-Band,X-Band,Ku-Band,Ka-Band                   // Frequencies that current ESM system can detect
ModuleType=SmallSensor

[CH53SA_RWR]
#users: MH-60R
Kind=ESM
Type=RWR
Gain=10                             // gain of sensor in dB
HasDataLink=False                   // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=10.0              // in degrees
Frequencies=S-Band,X-Band,Ku-Band,Ka-Band,K-Band                  // Frequencies that current ESM system can detect

[CH53SA_DECM]
#Users: lots
Kind=ECM
Frequencies=L-Band,S-Band,C-Band,X-Band,Ku-Band //radar frequency bands the ECM suite can jam
Type=Defensive                         // can be Defensive, Offensive, Universal
JamChannels=5                          // number of jamming channels. Defensive or Universal ECM need at least 1 free channel to protect the base platform
JamChance=0.70                          // For Defensive and Universal jammers. Base chance to jam the attacking weapon
CoverRange=8                           // in nmi, If within this range from attacked unit and within weapon seeker cone, jammer will add to combined chance to jam weapon.
