[General]
UnitType=LandUnit
LandUnitSubType=SAM


DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.3
MinCameraDistanceBroadside=0.3
CameraPivotHeight=0.03

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

Length=7.4                     // in meters
Beam=2.4                       // in meters
Range=405                      // in miles

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=None
DamagePoints=3  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

FrontalArea=5.94
SideArea=10.7
BottomArea=19.3
[Tacview]
Name=Truck
Tag=Ground+Vehicle+Artillery



[AI]
UnitScoreValue=0.5             // value for calculation of mission score
Role=Gun

[ControlSystem]
Collider=coll_hitbox  // makes unit destroyable
Integrity=3

[SensorData]
#Visual
VisualIdentificationRange=2.5  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1
#---------- Visual ----------
[SensorSystem1] #Optics
Type=Visual
SystemName=Optics
MountPosition=0,0.04,0

[---------- Weapon Systems ----------] 
[WeaponSystems]
NumberOfWeaponSystems=1

[WeaponSystem1] 
Type=Missile
SystemName=SA-N-6V2
#Sensors
#AssociatedSensors=SensorSystem2
ExternalGuidingSystems=30N6E2
ExternalGuidingSystemSearchRadius=0.5     // in nmi
#Animations
#Mount
Mount=Launchers
IsMountRotatable=False
#Containers
NumberOfContainers=4
Container1=Dummy
Container1_Position=-0.009,0.0265,0.032
Container2=Dummy
Container2_Position=0.009,0.0265,0.032
Container3=Dummy
Container3_Position=-0.0168,0.0105,0.032
Container4=Dummy
Container4_Position=0.0168,0.0105,0.032
AreContainersRotatable=False
#Angles
#Loading
Ammunition=wp_48n6e2
ReloadableWithoutMagazine=False
#Effects
#Other
WorksStandalone=False
AutoEnableSensor=True
VIDIncrease=15  // In miles. Flat base VID increace when firing.
[---------- WeaponMagazines ----------]
[WeaponMagazineLauncher] #Purely fictional to mitigate lack of reloading
NumberOfAmmunitionTypes=1
Ammunition1=wp_48n6e2
Ammunition1_Count=16 //40 on vehicle + 80 in reloading vehicle
ModuleType=SmallMagazine

[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
ResourcesFolder=ground objects/wp_bm-21/
ResourcesRoot=wp_bm-21
ResourcesMesh=wp_bm-21_chassis
ResourcesMaterialFolder=ground objects/wp_radars/
ResourcesMaterial=wp_urals_mat

[Submodels]
BASE=BASE
Launchers=Launchers
BARB=BARB
BASEEND=BASEEND
APU=APU
Wheels1=Wheels1
Wheels2=Wheels2
RADARSTICKF=RADARSTICKF




[Launchers]
ResourcesMeshFolder=ground objects/wp_sa-10/
RootMesh=wp_sa-10
Mesh=wp_sa-10_launchers
ResourcesMaterialFolder=materials/ships/
Material=kraz_tel_mat.ini 
Position=0,0.031,-0.14
Rotation=-90,0,0


[BARB]
ResourcesMeshFolder=weapons/usn_lau-68/
RootMesh=usn_lau-68
Mesh=usn_lau-68
ResourcesMaterialFolder=materials/ships/
Material=soviet_gray_mat.ini
Position=0,0.02,-0.029
Parent=
Scale=5,5,0.5
Rotation=90,0,0

[BASE]
ResourcesMeshFolder=ships/usn_dd_spruance/
RootMesh=usn_dd_spruance
Mesh=usn_dd_spruance_asroc_box_1
ResourcesMaterialFolder=ground objects/wp_sa-10/
Material=wp_sa-10_launchers_mat
Scale=2.8,0.5,1.05
Position=0,0.012,-0.115
Rotation=0,0,0

[BASEEND]
ResourcesMeshFolder=ships/usn_dd_spruance/
RootMesh=usn_dd_spruance
Mesh=usn_dd_spruance_asroc_box_1
ResourcesMaterialFolder=ground objects/wp_sa-10/
Material=wp_sa-10_launchers_mat
Scale=2.8,0.15,0.7
Position=0,0.0265,-0.05
Rotation=0,0,0

[APU]
ResourcesMeshFolder=ships/usn_dd_spruance/
RootMesh=usn_dd_spruance
Mesh=usn_dd_spruance_asroc_box_1
ResourcesMaterialFolder=materials/ships/
Material=army_green_mat.ini
Scale=2.6,0.4,0.2
Position=0,0.03,-0.025
Rotation=0,0,0

[Wheels1]
Mesh=nato_mim-23_CWAR_trailer
ResourcesMeshFolder=ground objects/nato_mim-23_hawk/
RootMesh=nato_mim-23_launcher
ResourcesMaterialFolder=materials/ships/
Material=all_tires_mat.ini
Position=0,0.0,-0.11
Scale=1.5,1.3,1.3
[Wheels2]
Mesh=nato_mim-23_CWAR_trailer
ResourcesMeshFolder=ground objects/nato_mim-23_hawk/
RootMesh=nato_mim-23_launcher
ResourcesMaterialFolder=materials/ships/
Material=all_tires_mat.ini
Position=0,0.0,-0.13
Scale=1.5,1.3,1.3

[RADARSTICKF]
ResourcesMeshFolder=ships/usn_dd_spruance/
RootMesh=usn_dd_spruance
Mesh=usn_dd_spruance_asroc_box_1
ResourcesMaterialFolder=materials/ships/
Material=army_green_mat.ini
Scale=0.2,0.1,0.75
Position=0.0,0.05,-0.154
Rotation=45,0,0






[---------- Effects ----------]
[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Small
AmbientAudioPosition=0,0,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

DustEffect=effects/land units/emitters/vehicle_movement_dust
DustEffectPosition=0,0,0

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=2

Collider1=coll_hitbox
Collider2=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.0197,0
Rotation=0,0,0
Scale=0.045,0.04,0.1

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default
