[General]
UnitType=LandUnit
LandUnitSubType=MobileUnit
IsMobile=True

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.3
MinCameraDistanceBroadside=0.3
CameraPivotHeight=0.03

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

Length=6.2                     // in meters
Beam=3.27                       // in meters
Range=202                      // in miles

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Moderate
DamagePoints=6  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

FrontalArea=3.69
SideArea=6.95
BottomArea=18.4
[Tacview]
Name=T-55
Tag=Ground+Vehicle+Armor+Tank

[Physics]
HorsePower=580
Mass=36                        // in tons

MaxForwardVelocity=27          // in knots
MaxBackwardVelocity=5          // in knots
Braking=10                     // knots/sec
TurnRate=20                    // in degrees per second

[AI]
UnitScoreValue=0.5             // value for calculation of mission score
Role=Gun

[ControlSystem]
Collider=coll_hitbox  // makes unit destroyable
Integrity=6
ArmorType=Moderate
IsCoveredByMainArmor=True

[SensorData]
#Visual
VisualIdentificationRange=2.5  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=1

#---------- Visual ----------
[SensorSystem1] #Optics
Type=Visual
SystemName=Optics
MountPosition=0,0.035,0

[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=1

[WeaponSystem1] #sa-3
Type=Missile
SystemName=SA-3
#Sensors
ExternalGuidingSystems=SNR-125
ExternalGuidingSystemSearchRadius=0.5     // in nmi
#Animations
#Mount
Mount=Launcher
IsMountRotatable=True
NumberOfContainers=1
ContainerBase=Rails
NumberOfContainers=1
Container1=Rails
AreContainersRotatable=True
Container1_Position=0,0,0
#0,0.0129,0.0605
Container1_Rotation=0,0,0
#Angles
ElevationArc=30,45
RestAngles=0,0
LoadAngles=0,0
#Loading
Ammunition=wp_sa-3
ReloadableWithoutMagazine=False
ForceMoveToLoadPosition=True
#Effects
#Other
DisplayWeaponsOnSystem=True
ModuleType=Weapon
Collider=coll_hitbox
Integrity=5
VIDIncrease=15  // In miles. Flat base VID increace when firing.

[---------- WeaponMagazines ----------]
[WeaponMagazineLauncher] #Purely fictional to mitigate lack of reloading
NumberOfAmmunitionTypes=1
Ammunition1=wp_sa-3
Ammunition1_Count=16 
ModuleType=SmallMagazine

[--------------------------- Mesh definitions ---------------------------]
[Models]
LODLevels=0
LOD1Distance=1  // nautical miles

ResourcesFolder=ground objects/wp_t-55/
ResourcesRoot=wp_t-55
ResourcesMesh=wp_t-55_hull
ResourcesMaterial=wp_t-55_mat
############################################################

[Submodels]
BARBDUMMY=BARBDUMMY
BARB=BARB


Launcher=Launcher
Rails=Rails

[BARBDUMMY]
Position=0,0,0

[BARB]
ResourcesMeshFolder=weapons/usn_lau-68/
RootMesh=usn_lau-68
Mesh=usn_lau-68
ResourcesMaterialFolder=materials/ships/
Material=soviet_gray_mat.ini
Position=0,0.02,0
Parent=BARBDUMMY
Scale=5,5,0.6
Rotation=90,0,0

[Launcher]
ResourcesMeshFolder=ground objects/wp_sa-3_goa/
RootMesh=wp_sa-3_goa
Mesh=wp_sa-3_launcher
ResourcesMaterialFolder=ground objects/wp_sa-3_goa/
Material=wp_sa-3_goa_mat
Parent=BARBDUMMY
Position=0,0.01,0

[Rails]
ResourcesMeshFolder=ground objects/wp_sa-3_goa/
RootMesh=wp_sa-3_goa
Mesh=wp_sa-3_rails
ResourcesMaterialFolder=ground objects/wp_sa-3_goa/
Material=wp_sa-3_goa_mat
Parent=Launcher
Position=0,0.0184,0.0266

[---------- Effects ----------]
[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

DustEffect=effects/land units/emitters/vehicle_movement_dust
DustEffectPosition=0,0,0

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Small
AmbientAudioPosition=0,0,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=2

Collider1=coll_hitbox
Collider2=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.0152,0.00068
Rotation=0,0,0
Scale=0.045,0.03,0.09

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default
