
[MK141_MANSUP]
# Mark 141 missile launcher (MANSUP) 2 tubes
NumberOfAttachments=2  // per container
AttachmentPosition1=0,0.00375,0
AttachmentPosition2=0,-0.00375,0
ReloadTime=0
MoveToRestPositionTime=30.0      // time in seconds the weapon goes back to rest position if not used
SmokeEffect=effects/weapons/emitters/MANSUP_launcher_effect.ini
SmokeEffectPosition=0,0.0,0.065
SmokeEffectDirectional=True
ModuleType=MediumLauncher

[SR-375A]
# Bofors 375mm B2 Double barrel Anti-Submarine Rocket Mortar
#Users:Niteroi-class
SalvoFireAmount=2                         // number of shots fired
SalvoFireTime=0.5                         // in seconds, Delay between the launches
SalvoFireTargetAreaCircleRadius=36.0      // in meters, circle radius for the target area where the single shots shall land

HorizontalDegreesPerSecond=30             // rotation speed horizontally
VerticalDegreesPerSecond=30               // rotation speed vertically
NumberOfAttachments=2                     // per container
AttachmentPosition1=0.0035,0,0.001
AttachmentPosition2=-0.0035,0,0.001

Effect=effects/weapons/emitters/RBUSmoke
EffectPosition=0,0,0.05
SpawnPosition=0,0,0
ReloadTime=20                             // time in seconds after firing until launcher is reloaded
MoveToRestPositionTime=50.0               // time in seconds the weapon goes back to rest position if not used
ModuleType=MediumLauncher

[Bofors_L/70_MkIII]
# Bofors L/70 40mm Autocannon on Mark III mount
#Users: bra_niteroi(2005)
MissileInterceptChance=50       // For CIWS. Chance to intercept missile with 0 defense rating
AircraftInterceptChance=70      // For CIWS. Chance to intercept missile with 0 defense rating
HorizontalDegreesPerSecond=92  // rotation speed horizontally
VerticalDegreesPerSecond=57    // rotation speed vertically
FireRate=330	             	// rounds per minute
RoundsLoaded=30              	// number of rounds in magazine, took higher number
ReloadTime=2                    // magazine reload time in seconds
RecoilTime=0.18                 // time in seconds for the recoil
RecoilStrength=0.00025           // amplitude of recoil
MoveToRestPositionTime=10      // time in seconds the weapon goes back to rest position if not used
Effect=effects/weapons/emitters/AK725_fire_emitter
EffectPosition=0,0,0.03484 
SpawnPosition=0,0,0.03484 
ModuleType=CIWS
