[Animations]
; Yes these were "reverse engineered" from the F-16 mod, for your information
Animation1=Canopy_Extend
Animation2=Canopy_Retract
;Animation3=Flaps_Takeoff
;Animation4=Flaps_Takeoff_Retract
;Animation5=Flaps_Landing
;Animation6=Flaps_Landing_Retract
Animation7=Gear_Extend
Animation8=Gear_Retract
;Animation9=Hook_Deploy
;Animation10=Hook_Retrieve

[Canopy_Extend]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Open
Sequence1_Model=Canopy_Frame_vz

[Canopy_Retract]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Close
Sequence1_Model=Canopy_Frame_vz


[Gear_Extend]
NumberOfSequencesToPlay=7
Sequence1=Nose_Gear_Down
Sequence1_Model=Nose_Gear
Sequence2=Nose_Gear_Down
Sequence2_Model=Nose_Dummy
Sequence3=Nose_Gear_Hatch_Down
Sequence3_Model=Nose_Gear_Door
Sequence4=Gear_Down_L
Sequence4_Model=Left_Gear
Sequence5=L_Gear_Door_Down
Sequence5_Model=Left_Gear_Door
Sequence6=Gear_Down_R
Sequence6_Model=Right_Gear
Sequence7=R_Gear_Door_Down
Sequence7_Model=Right_Gear_Door

[Gear_Retract]
NumberOfSequencesToPlay=7
Sequence1=Nose_Gear_Up
Sequence1_Model=Nose_Gear
Sequence2=Nose_Gear_Up
Sequence2_Model=Nose_Dummy
Sequence3=Nose_Gear_Hatch_Up
Sequence3_Model=Nose_Gear_Door
Sequence4=Gear_Up_L
Sequence4_Model=Left_Gear
Sequence5=L_Gear_Door_Up
Sequence5_Model=Left_Gear_Door
Sequence6=Gear_Up_R
Sequence6_Model=Right_Gear
Sequence7=R_Gear_Door_Up
Sequence7_Model=Right_Gear_Door

[Flaps_Takeoff]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff
Sequence1_Model=Left_Flaperon
Sequence2=Flap_Takeoff
Sequence2_Model=Right_Flaperon

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff_Retract
Sequence1_Model=Left_Flaperon
Sequence2=Flap_Takeoff_Retract
Sequence2_Model=Right_Flaperon

[Flaps_Landing]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing
Sequence1_Model=Left_Flaperon
Sequence2=Flap_Landing
Sequence2_Model=Right_Flaperon

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing_Retract
Sequence1_Model=Left_Flaperon
Sequence2=Flap_Landing_Retract
Sequence2_Model=Right_Flaperon

[Hook_Deploy]
NumberOfSequencesToPlay=1
Sequence1=Hook_Extend
Sequence1_Model=Tailhook_vz

[Hook_Retrieve]
NumberOfSequencesToPlay=1
Sequence1=Hook_Retract
Sequence1_Model=Tailhook_vz

[Hook_Extend]
NumberOfSteps=3
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=2 
RotationX2=0
Smoothness2=EaseInOut
Time3=5 
RotationX3=-75
Smoothness3=EaseInOut

[Hook_Retract]
NumberOfSteps=3
Time1=0 
RotationX1=-75
Smoothness1=EaseInOut
Time2=2 
RotationX2=-75
Smoothness2=EaseInOut
Time3=5 
RotationX3=0
Smoothness3=EaseInOut

[Flap_Takeoff]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=5 
RotationX2=-20
Smoothness2=EaseInOut

[Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-20
Smoothness1=EaseInOut
Time2=5 
RotationX2=0
Smoothness2=EaseInOut

[Flap_Landing]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=10 
RotationX2=-35
Smoothness2=EaseInOut

[Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-35
Smoothness1=EaseInOut
Time2=10 
RotationX2=0
Smoothness2=EaseInOut

[Canopy_Open]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=5 
RotationX2=-45
Smoothness2=EaseInOut

[Canopy_Close]
NumberOfSteps=2
Time1=0 
RotationX1=-45
Smoothness1=EaseInOut
Time2=5 
RotationX2=0
Smoothness2=EaseInOut

[Gear_Down_R]
NumberOfSteps=3
Time1=0 
RotationX1=-110
RotationY1=-40
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationX2=-110
RotationY2=-40
RotationZ2=0
Smoothness2=EaseInOut
Time3=8
RotationX3=0
RotationY3=0
RotationZ3=0
Smoothness3=EaseInOut

[Gear_Down_L]
NumberOfSteps=3
Time1=0 
RotationX1=-110
RotationY1=40
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationX2=-110
RotationY2=40
RotationZ2=0
Smoothness2=EaseInOut
Time3=8
RotationX3=0
RotationY3=0
RotationZ3=0
Smoothness3=EaseInOut

[Gear_Up_L]
NumberOfSteps=2
Time1=0 
RotationX1=0
RotationY1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationX2=-110
RotationY2=40
RotationZ2=0
Smoothness2=EaseInOut

[Gear_Up_R]
NumberOfSteps=2
Time1=0
RotationX1=0 
RotationY1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=5
RotationX2=-110
RotationY2=-40
RotationZ2=0
Smoothness2=EaseInOut

[Nose_Gear_Down]
NumberOfSteps=3
Time1=0 
RotationX1=57.5
Smoothness1=EaseInOut
Time2=5 
RotationX2=57.5
Smoothness2=EaseInOut
Time3=8 
RotationX3=0
Smoothness3=EaseInOut

[Nose_Gear_Up]
NumberOfSteps=3
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=5 
RotationX2=57.5
Smoothness2=EaseInOut
Time3=8 
RotationX3=57.5
Smoothness3=EaseInOut

[L_Gear_Door_Up]
NumberOfSteps=2
Time1=5 
RotationZ1=0
Smoothness1=EaseInOut
Time2=8 
RotationZ2=95
Smoothness2=EaseInOut

[L_Gear_Door_Down]
NumberOfSteps=2
Time1=0 
RotationZ1=95
Smoothness1=EaseInOut
Time2=3 
RotationZ2=0
Smoothness2=EaseInOut

[R_Gear_Door_Up]
NumberOfSteps=2
Time1=5 
RotationZ1=0
Smoothness1=EaseInOut
Time2=8 
RotationZ2=-95
Smoothness2=EaseInOut

[R_Gear_Door_Down]
NumberOfSteps=2
Time1=0  
RotationZ1=-95
Smoothness1=EaseInOut
Time2=3 
RotationZ2=0
Smoothness2=EaseInOut

[Nose_Gear_Hatch_Down]
NumberOfSteps=2
Time1=0 
RotationZ1=-80
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut

[Nose_Gear_Hatch_Up]
NumberOfSteps=2
Time1=3 
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=-80
Smoothness2=EaseInOut