[AmmunitionNames]
# ------------------ AAM ------------------
plaaf_pl-10=PL-10,,ИК РВВ,PL-10 оснащена современной тепловизионной ГСН, обеспечивающей всеракурсное применение. Ракета способна захватывать цель после пуска (LOAL) и получать целеуказание по линии передачи данных в полёте. Многоэлементная ГСН имеет углы визирования до ±90° и может работать с нашлемной системой целеуказания.
plaaf_pl-12=PL-12,,РВВ,PL-12 — китайская ракета «воздух-воздух» средней дальности с активной радиолокационной ГСН, сопоставимая с американской AIM-120 AMRAAM и российской Р-77.
plaaf_pl-15=PL-15,,РВВ,PL-15 — китайская ракета «воздух-воздух» большой дальности с активной радиолокационной ГСН.

# ------------------ SAM ------------------
pla_hq-10=HQ-10,,ЗУР,HQ-10 — китайская зенитная ракета малой дальности.

# ------------------ Anti-Ship ------------------
plaaf_yj-91a=YJ-91A,,ПКР,YJ-91A — противокорабельный вариант противорадиолокационной ракеты YJ-91, китайской лицензионной версии Х-31П.
pla_yj-83=YJ-83,,ПКР,YJ-83 — противокорабельная крылатая ракета средней дальности, состоящая на вооружении множества кораблей, подводных лодок и самолётов НОАК. Маршевый участок проходит на малой высоте с дозвуковой скоростью, на конечном участке ракета атакует со скоростью М=1,4.

#-----------Land Strike only missiles---------
pla_kd-88=KD-88,,Ракета воздух-поверхность,KD-88 — китайская ракета класса «воздух-поверхность» для ударов вне зоны ПВО, созданная на базе ПКР YJ-83, но с телевизионной ГСН. Вариант KD-88A оснащён тепловизионной ГСН.

# ---------- Anti-radar Missiles ---------
plaaf_yj-91=YJ-91,,ПРР,YJ-91 — китайская противорадиолокационная ракета, созданная на основе Х-31П с новой китайской ГСН.

# ------------------ Bombs -----------------
plaaf_500-Ⅱ=500-II,,Бомба,Китайская 500-кг авиабомба типа II с высоким аэродинамическим сопротивлением.
plaaf_500-Ⅲ=500-III,,Бомба,Китайская 500-кг авиабомба типа III с низким аэродинамическим сопротивлением.
pla_ls-6_500=LS-6 (500 кг),,Управляемая бомба,Планирующая бомба LS-6 с наведением по GPS представляет собой 500-кг фугасную бомбу с низким сопротивлением, оснащённую модулем планирования и наведения, что позволяет наносить высокоточные удары вне зоны ПВО.

# ------------------ FFAR -----------------
plaaf_hf-14=HF-14,,НАР,
plaaf_hf-6=HF-6,,НАР,
plaaf_130-Ⅱ_rocket=130-II,,НАР,Китайская авиационная неуправляемая ракета класса «воздух-поверхность» производства корпорации NORINCO.
plaaf_90-Ⅰ_rocket=90-I,,НАР,Китайская авиационная неуправляемая ракета класса «воздух-поверхность» производства корпорации NORINCO.

# ---------- Torpedos ---------
pla_yu-11_air=Ю-11,,Противолодочная торпеда,Ю-11 — китайская малогабаритная торпеда, принятая на вооружение в 2010-х годах в качестве основного противолодочного оружия крупных кораблей ВМС НОАК. По сравнению с предшественницей Ю-7 она оснащена водомётным движителем, менее шумна и, возможно, способна действовать на глубинах более 600 м.

# ------------------ CIWS -----------------
pla_cal_30mm=30мм,,Снаряд,Снаряд калибра 30 мм.
