[---------- General Data ----------]
[General]
UnitType=Aircraft

DefaultCameraDistance=1
MinCameraDistanceForeAft=0.36
MinCameraDistanceBroadside=0.36
CameraPivotHeight=0.0

#Taxi values
GroundedPitchAngle=-1  // 这个角度是降落时地面的俯仰角（x）
GroundPivot=0,-0.0265,0.018816 // 主轮之间的点，起飞落地抬轮的参考点

Pilot=usn_pilot_a-7
Pilot1Positions=0,0.010982,0.099698        // 飞行员位置
EjectChance=0.6                        
        // 弹射机会

[AI]
Role=Fighter,Bomber                      //脚本
// 目前种类有：Fighter、Bomber、HeavyBomber、SEAD、Recon、EW、ESM、Transport、MPA、AEW、ASW、ASuW、Attack、Airliner

[SensorData]
#Visual
VisualIdentificationRange=5.7       // Biggest range in nm at which this unit can be visually identified
IRSignature=SemiSmall
# Radar related (RCS => radar cross section)
RCS=SemiSmall

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_fr_m2k

[---------- Flight Model ----------]
[Engine]
EngineIntakeArea=0.6              //Pi* r * r where r is engine radius, in meters

[FlightModel]
PitchGain=0.25                         // Vertical manuverability
VelocityGain=0.1136                   // Acceleration
HeadingGain=2.1                       // Horizontal manuverability
YawRateLimit=130                      // in degrees per second

BankGain=1.5                           // Roll change speed
#MaxRollForHeading=65.0                // bank limit in normal flight
MaxRollRate=82                      // in degrees per second

ThrustGain=0.352                      // Thrust change speed
SpeedBrakeFractionGain=10            // Speed brakes deploy speed

SpeedDeltaPerAltitudeChange=0.0885

[Performance]
#Dimensions
WingSpan=9.1                       //meters
#Parameters
MaxG=9                                // Mostly for horizontal turns

MaxClimbRate=285                      //Meters per second
EmptyMass=7500                    // in kg
MaxFuel=3950                       // in kg, internal tanks only

PerEngineMaxThrust=64000              //Newtons
PerEngineMaxAfterburnerThrust=95000  //Newtons
EngineCount=1
EngineWarmUp=15

Ceiling=55000.0                       // ceiling in feet
CruiseAltitude= ????                  //in feet
#"Engine" efficiency at 0ft, 37000 ft, 65000 ft. Always 1 for cruise altitude
AltitudeEfficiency=0.5,0.5,0.25       // Defines fuel consumption with altitude

#Governing of max speed
MaxSpeedAtSeaLevel=670                //in knots, Defines max speed at altitude curve
StallSpeed=105                      //in knots
MachLimit=2.2                         //for 37000ft, Defines max speed at altitude curve

#SpeedAndRange   MachNumbers or knots, Specified units or multiplier (except Cruise range)
RangeUnits=Miles                      // Can be: Km. Any other value = nmi. Defines measurment units of ranges of SpeedAndRange values

SpeedAndRange_Landing=0.2,0.4        // Landing
SpeedAndRange_Loiter=0.4,0.6          // Loiter
SpeedAndRange_Cruise=0.86,960        // Cruise
SpeedAndRange_Max=1.2,0.8             // Attack/Fast/High/Max without AB
SpeedAndRange_Afterburner=1.6,0.2     // AB max

Altitudes=200,1000,3000,6000,10000,20000  // in feet

[---------- Main Systems ----------]
[FlightControls]
NumberOfAilerons=2
Aileron1_Model=flap_l
Aileron1_MinAngle=-20.0
Aileron1_MaxAngle=20.0
Aileron1_RotationAxis=X

Aileron2_Model=flap_r
Aileron2_MinAngle=-20.0
Aileron2_MaxAngle=20.0
Aileron2_RotationAxis=X

NumberOfElevons=2
Elevon1_Model=flap_l
Elevon1_MinAngle=-20.0
Elevon1_MaxAngle=20.0
Elevon1_RotationAxis=X

Elevon2_Model=flap_r
Elevon2_MinAngle=-20.0
Elevon2_MaxAngle=20.0
Elevon2_RotationAxis=X

NumberOfRudders=1
Rudder1_Model=Rudder
Rudder1_MinAngle=-30.0
Rudder1_MaxAngle=30.0
Rudder2_RotationAxis=Z



AfterBurnerSubModel=Afterburner    // optional entry
MaxAfterBurnerIntensity=0.2
AfterBurnerFadeTime=0.5

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=3

[SensorSystem1] #Cockpit
# Cockpit
Type=Visual
SystemName=Eyes
Mount=Dummy
ViewArcs=-170,170|-20,91
ModuleType=Sensor

[SensorSystem2] #Radar
Type=Radar
SystemName=Thomson-RDI
Mount=Dummy
ModuleType=Sensor

[SensorSystem3] #RWR
Type=ESM
SystemName=AircraftRWR
Mount=Dummy
ModuleType=Sensor

[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=4
AvailableLoadouts=AirToAir,Strike

[AerialRefueling]
ReceiverSystems=ProbeAndDrogue

[WeaponSystem1] #Hardpoint
Type=Hardpoint
SystemName=Hardpoint
AssociatedSensors=SensorSystem2
NumberOfStations=9

Station1=-0.048387,-0.008042,-0.039972    //Left Wing Outer
Station2=0.048387,-0.008042,-0.039972     //Right Wing Outer
Station3=-0.034106,-0.008028,-0.030025        //Left Wing Inner
Station4=0.034106,-0.008028,-0.030025        //Right Wing Inner
Station5=0,0,0        //Center
Station6=0.011266,-0.007794,0.016386        //Bomb
Station7=-0.011266,-0.007794,0.016386  
Station8=0.012546,-0.006966,-0.047483
Station9=-0.012546,-0.006966,-0.047483


FiringArcs=-5,5

ModuleType=Weapon

Station1Rotation=3,0,0
Station2Rotation=3,0,0
Station3Rotation=3,0,0
Station4Rotation=3,0,0
Station5Rotation=3,0,0
Station6Rotation=0,0,9.19781
Station7Rotation=0,0,-9.19781
Station8Rotation=4,0,9.19781
Station9Rotation=4,0,-9.19781

Tank_1200Positions=0,-0.011824,-0.028161

Tank_1700Positions=0,-0.001736,0.001025

SAMP21Positions=0,-0.0007,-0,001

[WeaponSystem2] #Gun
Type=CIWS
SystemName=DEFA_553
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=0.004689,-0.00393,0.020153
IsMountRotatable=True
#Containers
ContainerBase=Dummy
Gun=Dummy
AreContainersRotatable=True
#Angles
FiringArcs=-3,3
ElevationArc=-3,3
#Loading
Ammunition=fr_cal_30mm
#Effects
#Other
IsOffensive=True
ModuleType=Weapon

[WeaponSystem3] #Gun
Type=CIWS
SystemName=DEFA_553
#Sensors
#Animations
#Mount
Mount=Dummy
MountPosition=-0.004689,-0.00393,0.020153
IsMountRotatable=True
#Containers
ContainerBase=Dummy
Gun=Dummy
AreContainersRotatable=True
#Angles
FiringArcs=-3,3
ElevationArc=-3,3
#Loading
Ammunition=fr_cal_30mm
#Effects
#Other
IsOffensive=True
ModuleType=Weapon

[WeaponSystem4] #Chaff
Type=Chaff
SystemName=US_AIR_CHAFF_DISP
#Sensors
#Animations
#Mount
Mount=Dummy
#MountPosition=0,-0.01,-0.016
#Containers
ContainerBase=Dummy
#Angles
#Loading
AssociatedMagazine=WeaponMagazineChaff
#Effects
NumberOfEffects=4
DelayBetweenLaunches=0.1
#Other
WorksStandalone=True
ModuleType=Weapon

[--------------------------- Loadouts ---------------------------]
#--------------- Standart --------------
[WeaponSystem1Empty]
SubModelsToHide=pyl_outer,pyl_inneer,pyl_center,pyl_bomb_abdomen,pyl_bomb_inneer,pyl_outer_2

[WeaponSystem1Ferry]
SubModelsToHide=pyl_outer,pyl_bomb_abdomen,pyl_bomb_inneer

Station3=fr_m2k_tank_1700|Tank_1700
Station4=fr_m2k_tank_1700|Tank_1700
Station5=fr_m2k_tank_1200|Tank_1200

[WeaponSystem1Default]
ReadyUpTime=15              // in minutes. Time that plane will spend refueling and rearming before takeoff.
SubModelsToHide=pyl_bomb_abdomen,pyl_bomb_inneer,pyl_inneer

Station1=fr_r550-2
Station2=fr_r550-2
Station3=fr_super-530d
Station4=fr_super-530d
Station5=fr_m2k_tank_1200|Tank_1200
#--------------- Anti-Air --------------
[WeaponSystem1AirToAir]
ReadyUpTime=15              // in minutes. Time that plane will spend refueling and rearming before takeoff.
SubModelsToHide=pyl_bomb_abdomen,pyl_bomb_inneer,pyl_inneer
Station1=fr_r550-2
Station2=fr_r550-2
Station3=fr_super-530d
Station4=fr_super-530d
Station5=fr_m2k_tank_1200|Tank_1200

#--------------- Anti-Surface --------------
[WeaponSystem1Strike]
SubModelsToHide=pyl_out_mica,pyl_aam_center,damoncles,pyl_outer_2,pyl_as30,pyl_bomb_abdomen,pyl_outer_2
Station1=fr_r550-2
Station2=fr_r550-2
Station3=usn_mk-82 
Station4=usn_mk-82 
Station5=fr_m2k_tank_1200|Tank_1200
Station6=
Station7=
Station8=
Station9=


[---------- WeaponMagazines ----------]
############################################################
# Weapon Magazine Systems
############################################################

[WeaponMagazineChaff]
NumberOfAmmunitionTypes=1
Ammunition1_Count=20
Ammunition1=wp_aircraft_chaff
ModuleType=WeaponMagazine

[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/aircraft/m2k/
ResourcesRoot=m2k.obj
ResourcesMesh=hull
ResourcesMaterial=m2k_mat.ini
############################################################
NumberOfDamageModels=1
DamageModel1=hull_dmg
DamageModelMaterial1=m2k_mat.ini
DamageModelLostWingSide1=Left
############################################################
[Submodels]
#---------- General ----------
General_1=Afterburner
General_2=windshield
General_3=canopy
General_4=canopy_glass
General_5=pilot
seats=seats

#---------- Left Wing ----------
LeftWing_1=flap_l

#---------- Right Wing ----------
RightWing_1=flap_r

#---------- Tail ----------
Tail_1=Rudder

#---------- Nose Gear ----------
NoseGear_1=nose_gear
NoseGear_2=gear_nose_door1
NoseGear_3=gear_nose_door_2
NoseGear_4=gear_nose_door_l
NoseGear_5=gear_nose_door_r

#---------- Left Gear ----------
LeftGear_1=gear_l
LeftGear_2=gear_l_door1
LeftGear_3=gear_l_door2

#---------- Right Gear ----------
RightGear_1=gear_r
RightGear_2=gear_r_door1
RightGear_3=gear_r_door2

#---------- Modex ----------

#---------- Weapons ----------
Weapons_1=pyl_outer
Weapons_2=pyl_inneer
Weapons_3=pyl_center
Weapons_4=pyl_bomb_abdomen
Weapons_5=pyl_bomb_inneer
Weapons_6=pyl_outer_2

#--------- Composite hanger ---------
############################################################
#---------- General ----------
############################################################

[Afterburner]
Mesh=Afterburner
ResourcesMaterialFolder=aircraft/materials/
Material=afterburner_mat
Position=0,0,0
Rotation=0,0,0
CastShadows=False

[windshield]
Mesh=windshield
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass

[canopy]
Mesh=canopy
Material=m2k_mat.ini
Position=0,0.017857,0.033027
Rotation=0,0,0

[canopy_glass]
Mesh=canopy_glass
ResourcesMaterialFolder=aircraft/materials/
Material=cockpit_glass
Parent=canopy

[pilot]
Mesh=pilot
ResourcesMaterialFolder=characters/materials/
Material=usn_pilot_a_mat

[seats]
Mesh=seats
Material=m2k_mat.ini

############################################################
#---------- Left Wing ----------
############################################################
[flap_l]
Mesh=flap_l
Material=m2k_mat.ini
Position=-0.033285,0.00025,-0.06042

############################################################
#---------- Right Wing ----------
############################################################
[flap_r]
Mesh=flap_r
Material=m2k_mat.ini
Position=0.033285,0.00025,-0.06042

############################################################
#---------- Tail ----------
############################################################
[Rudder]
Mesh=Rudder
Material=m2k_mat.ini
Position=0,0.020392,-0.083599
Rotation=70,0,0

############################################################
#---------- Nose Gear ----------
############################################################
[nose_gear]
Mesh=nose_gear
Material=m2k_mat.ini
Position=0,-0.000664,0.048303

[gear_nose_door1]
Mesh=gear_nose_door1
Material=m2k_mat.ini
Position=0.002948,-0.004398,0.033849
Rotation=-1.5,0,0

[gear_nose_door_2]
Mesh=gear_nose_door_2
Material=m2k_mat.ini
Position=0,-0.004691,0.053071

[gear_nose_door_l]
Mesh=gear_nose_door_l
Material=m2k_mat.ini
Position=-0.002948,-0.00416,0.046378
Rotation=-1,0,0

[gear_nose_door_r]
Mesh=gear_nose_door_r
Material=m2k_mat.ini
Position=0.002948,-0.00416,0.046378
Rotation=-1,0,0

############################################################
#---------- Left Gear ----------
############################################################
[gear_l]
Mesh=gear_l
Material=m2k_mat.ini
Position=-0.025186,0.000891,-0.026239

[gear_l_door1]
Mesh=gear_l_door1
Material=m2k_mat.ini
Position=-0.003243,-0.004847,-0.015534

[gear_l_door2]
Mesh=gear_l_door2
Material=m2k_mat.ini
Position=-0.028113,-0.001798,-0.025039
Rotation=1,0.026146,-0.000546

############################################################
#---------- Right Gear ----------
############################################################
[gear_r]
Mesh=gear_r
Material=m2k_mat.ini
Position=0.025186,0.000891,-0.026239

[gear_r_door1]
Mesh=gear_r_door1
Material=m2k_mat.ini
Position=0.003243,-0.004847,-0.015534

[gear_r_door2]
Mesh=gear_r_door2
Material=m2k_mat.ini
Position=0.028113,-0.001798,-0.025039
Rotation=1.1,-0.017458,0.000352

############################################################
#---------- Weapons ----------
############################################################

[pyl_outer]
Mesh=pyl_outer
Material=m2k_mat.ini

[pyl_outer_2]
Mesh=pyl_outer_2
Material=m2k_mat.ini

[pyl_inneer]
Mesh=pyl_inneer
Material=m2k_mat.ini

[pyl_center]
Mesh=pyl_center
Material=m2k_mat.ini

[pyl_bomb_abdomen]
Mesh=pyl_bomb_abdomen
Material=m2k_mat.ini

[pyl_bomb_inneer]
Mesh=pyl_bomb_inneer
Material=m2k_mat.ini

############################################################
#N/A
[---------- Effects ----------]
[Particles]
ShotDownFireEffect=effects/aircraft_kill_effects/usaf_f-15c_kill
ShotDownFireEffectPosition=0,0,0
HitWaterEffect=effects/splashes/emitters/splash_bomb
HitGroundEffect=effects/explosions/emitters/aircraft_hit_ground
HitAirEffectClass=LargeMissileExplosions
ExhaustSmoke=aircraft/particles/usaf_f-15c_smokeemitter
TipVortexPosition=0.096,0.004,0.03
TipVortex=effects/aircraft/emitters/tipvortex
LeftWingVortexPosition=0,-0.01,0.02
LeftWingVortex=effects/aircraft/emitters/wingvortex_f-15_left
RightWingVortexPosition=0,-0.01,0.02
RightWingVortex=effects/aircraft/emitters/wingvortex_f-15_right
ShockConePosition=0,-0.01,0.02
ShockCone=effects/aircraft/emitters/shockcone

[Sounds]
############################################################
# Sounds
############################################################
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=3
# Front
EngineAudioClip=audio/aircraft/TF30
EngineAudioPosition=0,0,0
EngineAudioRollOff=Logarithmic
EngineAudioDistance=1,20
EngineAudioPitchRange=1.0,2.4
EngineAudioVolumeRange=0.1,0.5
# Rear
ExhaustAudioClip=audio/aircraft/jet_rear_1
ExhaustAudioPosition=0,0,0
ExhaustAudioRollOff=Logarithmic
ExhaustAudioDistance=1,20
ExhaustAudioPitchRange=0.6,1.0
ExhaustAudioVolumeRange=0.75,1.0
# Far
FarAudioClip=audio/aircraft/jet_far_1
FarAudioPosition=0,0,0
FarAudioRollOff=Logarithmic
FarAudioDistance=5,20
FarAudioPitch=1.0
FarAudioVolume=1.0
FarAudioFadeRange=0.0,0.15	      // nautical miles min/max
# Afterburner
AfterburnerAudioClip=audio/aircraft/afterburner_f-15
AfterburnerAudioPosition=0,0,0
AfterburnerAudioRollOff=Logarithmic
AfterburnerAudioDistance=1,20
AfterburnerAudioPitch=1.0
AfterburnerAudioVolume=1.0
# Gears
#GearsAudioClip=audio/aircraft/gears
GearsAudioClip=audio/aircraft/LandingGearRetraction_v1
GearsAudioPosition=0,0,0
GearsAudioRollOff=Logarithmic
GearsAudioDistance=1,20
GearsAudioPitch=1.0
GearsAudioVolume=1.0
# Flaps
#FlapsAudioClip=audio/aircraft/flaps
FlapsAudioClip=audio/aircraft/LandingGearRetraction_v1
FlapsAudioPosition=0,0,0
FlapsAudioRollOff=Logarithmic
FlapsAudioDistance=1,20
FlapsAudioPitch=1.0
FlapsAudioVolume=1.0

//Front Sound = audio/aircraft/JE_Front_3 v=0.25, p=1.2
//Rear	Sound = audio/aircraft/JE_Burner_2
//Far	Sound = audio/aircraft/JetExhaustLoop p=0.75
//Afterburner = audio/aircraft/AfterburnerLarge_v1 p=0.75

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
# creates the hit boxes for this object
NumberOfColliders=3
Collider1=coll_body
Collider2=coll_body2
Collider3=coll_wings

[coll_body]
Collider=Box
Position=0,0,0.062
Rotation=0,0,0
Scale=0.023,0.028,0.18

[coll_body2]
Collider=Box
Position=0,-0.01,-0.01
Rotation=0,0,0
Scale=0.05,0.02,0.16

[coll_wings]
Collider=Box
Position=0,0,-0.013
Rotation=0,0,0
Scale=0.17,0.007,0.058