[Animations]
NumberOfAnimations=100
Animation1=MoveDownElevator1
Animation2=MoveDownElevator2
Animation3=MoveUpElevator1
Animation4=MoveUpElevator2
Animation5=OpenHangarDoors
Animation6=CloseHangarDoors
Animation7=DeflectorFrontUp
Animation8=DeflectorFrontDown
Animation9=DeflectorBackUp
Animation10=DeflectorBackDown

# IVM animations (8 IVMs, Hide/Show)
Animation11=IVM1_Hide
Animation12=IVM1_Show
Animation13=IVM2_Hide
Animation14=IVM2_Show
Animation15=IVM3_Hide
Animation16=IVM3_Show
Animation17=IVM4_Hide
Animation18=IVM4_Show
Animation19=IVM5_Hide
Animation20=IVM5_Show
Animation21=IVM6_Hide
Animation22=IVM6_Show
Animation23=IVM7_Hide
Animation24=IVM7_Show
Animation25=IVM8_Hide
Animation26=IVM8_Show

# F8 animations (4 F8s, Hide/Show)
Animation27=F8_1_Hide
Animation28=F8_1_Show
Animation29=F8_2_Hide
Animation30=F8_2_Show
Animation31=F8_3_Hide
Animation32=F8_3_Show
Animation33=F8_4_Hide
Animation34=F8_4_Show

# Alizé animations (6 Alizés, Hide/Show)
Animation35=Alize_1_Hide
Animation36=Alize_1_Show
Animation37=Alize_2_Hide
Animation38=Alize_2_Show
Animation39=Alize_3_Hide
Animation40=Alize_3_Show
Animation41=Alize_4_Hide
Animation42=Alize_4_Show
Animation43=Alize_5_Hide
Animation44=Alize_5_Show
Animation45=Alize_6_Hide
Animation46=Alize_6_Show

# IVP animations (2 IVPs, Hide/Show)
Animation47=IVP1_Hide
Animation48=IVP1_Show
Animation49=IVP2_Hide
Animation50=IVP2_Show

# Frelon Animations
Animation51=FRELON_1_Hide
Animation52=FRELON_1_Show


# Aquilons animations (6 Aquilons, Hide/Show)
Animation53=Aquilon_1_Hide
Animation54=Aquilon_1_Show
Animation55=Aquilon_2_Hide
Animation56=Aquilon_2_Show
Animation57=Aquilon_3_Hide
Animation58=Aquilon_3_Show
Animation59=Aquilon_4_Hide
Animation60=Aquilon_4_Show
Animation61=Aquilon_5_Hide
Animation62=Aquilon_5_Show
Animation63=Aquilon_6_Hide
Animation64=Aquilon_6_Show

# Alouette Animations
Animation65=ALOUETTE_1_Hide
Animation66=ALOUETTE_1_Show
#-----------------------------------------------------------

[IVM1_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=IVMAircraft_1
[IVM1_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=IVMAircraft_1

[IVM2_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=IVMAircraft_2
[IVM2_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=IVMAircraft_2

[IVM3_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=IVMAircraft_3
[IVM3_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=IVMAircraft_3

[IVM4_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=IVMAircraft_4
[IVM4_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=IVMAircraft_4

[IVM5_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=IVMAircraft_5
[IVM5_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=IVMAircraft_5

[IVM6_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=IVMAircraft_6
[IVM6_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=IVMAircraft_6

[IVM7_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=IVMAircraft_7
[IVM7_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=IVMAircraft_7

[IVM8_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=IVMAircraft_8
[IVM8_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=IVMAircraft_8

#-----------------------------------------------------------

[F8_1_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_F8
Sequence1_Model=F8Aircraft_1
[F8_1_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_F8
Sequence1_Model=F8Aircraft_1

[F8_2_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_F8
Sequence1_Model=F8Aircraft_2
[F8_2_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_F8
Sequence1_Model=F8Aircraft_2

[F8_3_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_F8
Sequence1_Model=F8Aircraft_3
[F8_3_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_F8
Sequence1_Model=F8Aircraft_3

[F8_4_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_F8
Sequence1_Model=F8Aircraft_4
[F8_4_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_F8
Sequence1_Model=F8Aircraft_4

#-----------------------------------------------------------
[Alize_1_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Alize
Sequence1_Model=AlizeAircraft_1
[Alize_1_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Alize
Sequence1_Model=AlizeAircraft_1

[Alize_2_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Alize
Sequence1_Model=AlizeAircraft_2
[Alize_2_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Alize
Sequence1_Model=AlizeAircraft_2

[Alize_3_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Alize
Sequence1_Model=AlizeAircraft_3
[Alize_3_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Alize
Sequence1_Model=AlizeAircraft_3

[Alize_4_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Alize
Sequence1_Model=AlizeAircraft_4
[Alize_4_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Alize
Sequence1_Model=AlizeAircraft_4

[Alize_5_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Alize
Sequence1_Model=AlizeAircraft_5
[Alize_5_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Alize
Sequence1_Model=AlizeAircraft_5

[Alize_6_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Alize
Sequence1_Model=AlizeAircraft_6
[Alize_6_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Alize
Sequence1_Model=AlizeAircraft_6

#-----------------------------------------------------------

[Aquilon_1_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Aquilon
Sequence1_Model=AQUILONAircraft_1
[Aquilon_1_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Aquilon
Sequence1_Model=AQUILONAircraft_1

[Aquilon_2_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Aquilon
Sequence1_Model=AQUILONAircraft_2
[Aquilon_2_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Aquilon
Sequence1_Model=AQUILONAircraft_2

[Aquilon_3_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Aquilon
Sequence1_Model=AQUILONAircraft_3
[Aquilon_3_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Aquilon
Sequence1_Model=AQUILONAircraft_3

[Aquilon_4_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Aquilon
Sequence1_Model=AQUILONAircraft_4
[Aquilon_4_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Aquilon
Sequence1_Model=AQUILONAircraft_4

[Aquilon_5_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Aquilon
Sequence1_Model=AQUILONAircraft_5
[Aquilon_5_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Aquilon
Sequence1_Model=AQUILONAircraft_5

[Aquilon_6_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_Aquilon
Sequence1_Model=AQUILONAircraft_6
[Aquilon_6_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_Aquilon
Sequence1_Model=AQUILONAircraft_6


#-----------------------------------------------------------

[IVP1_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=IVPAircraft_1
[IVP1_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=IVPAircraft_1

[IVP2_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=IVPAircraft_2
[IVP2_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=IVPAircraft_2

#-----------------------------------------------------------

[FRELON_1_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=FRELON_Aircraft_1
[FRELON_1_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=FRELON_Aircraft_1

#-----------------------------------------------------------

[ALOUETTE_1_Hide]
NumberOfSequencesToPlay=1
Sequence1=Hide_IVM
Sequence1_Model=ALOUETTE_Fuselage
[ALOUETTE_1_Show]
NumberOfSequencesToPlay=1
Sequence1=Show_IVM
Sequence1_Model=ALOUETTE_Fuselage

#-----------------------------------------------------------
[MoveDownElevator1]
NumberOfSequencesToPlay=4
Sequence1=ElevatorMoveDownSequence
Sequence1_Model=Elevator_Front
Sequence2=ElevatorMoveDownSequence
Sequence2_Model=Elevator_Front_Deck
Sequence3=ElevatorMoveDownSequence
Sequence3_Model=Elevator_Front_Underside
Sequence4=RailingsUp
Sequence4_Model=Railings1

[MoveDownElevator2]
NumberOfSequencesToPlay=9
Sequence1=ElevatorMoveDownSequence
Sequence1_Model=Elevator_Back
Sequence2=ElevatorMoveDownSequence
Sequence2_Model=Elevator_Back_Deck
Sequence3=ElevatorMoveDownSequence
Sequence3_Model=Elevator_Back_Underside
Sequence4=ElevatorMoveDownSequence
Sequence4_Model=Elevator_Back_Net
Sequence5=RailingsUp
Sequence5_Model=Railings2
Sequence6=Open_Hangar_Doors_1
Sequence6_Model=Hangar_Door1
Sequence7=Open_Hangar_Doors_2
Sequence7_Model=Hangar_Door2
Sequence8=Open_Hangar_Doors_3
Sequence8_Model=Hangar_Door3
Sequence9=Open_Hangar_Doors_4
Sequence9_Model=Hangar_Door4

[MoveUpElevator1]
NumberOfSequencesToPlay=4
Sequence1=ElevatorMoveUpSequence
Sequence1_Model=Elevator_Front
Sequence2=ElevatorMoveUpSequence
Sequence2_Model=Elevator_Front_Deck
Sequence3=ElevatorMoveUpSequence
Sequence3_Model=Elevator_Front_Underside
Sequence4=RailingsDown
Sequence4_Model=Railings1

[MoveUpElevator2]
NumberOfSequencesToPlay=9
Sequence1=ElevatorMoveUpSequence
Sequence1_Model=Elevator_Back
Sequence2=ElevatorMoveUpSequence
Sequence2_Model=Elevator_Back_Deck
Sequence3=ElevatorMoveUpSequence
Sequence3_Model=Elevator_Back_Underside
Sequence4=ElevatorMoveUpSequence
Sequence4_Model=Elevator_Back_Net
Sequence5=RailingsDown
Sequence5_Model=Railings2
Sequence6=Close_Hangar_Doors_1
Sequence6_Model=Hangar_Door1
Sequence7=Close_Hangar_Doors_2
Sequence7_Model=Hangar_Door2
Sequence8=Close_Hangar_Doors_3
Sequence8_Model=Hangar_Door3
Sequence9=Close_Hangar_Doors_4
Sequence9_Model=Hangar_Door4

[DeflectorFrontUp]
NumberOfSequencesToPlay=1
Sequence1=DeflectorUp
Sequence1_Model=Deflector_Front

[DeflectorBackUp]
NumberOfSequencesToPlay=1
Sequence1=DeflectorUp
Sequence1_Model=Deflector_Back

[DeflectorFrontDown]
NumberOfSequencesToPlay=1
Sequence1=DeflectorDown
Sequence1_Model=Deflector_Front

[DeflectorBackDown]
NumberOfSequencesToPlay=1
Sequence1=DeflectorDown
Sequence1_Model=Deflector_Back

#[OpenHangarDoors]
#NumberOfSequencesToPlay=4
#Sequence1=Open_Hangar_Doors_1
#Sequence1_Model=Hangar_Door1
#Sequence2=Open_Hangar_Doors_2
#Sequence2_Model=Hangar_Door2
#Sequence3=Open_Hangar_Doors_3
#Sequence3_Model=Hangar_Door3
#Sequence4=Open_Hangar_Doors_4
#Sequence4_Model=Hangar_Door4

#[CloseHangarDoors]
#NumberOfSequencesToPlay=4
#Sequence1=Close_Hangar_Doors_1
#Sequence1_Model=Hangar_Door1
#Sequence2=Close_Hangar_Doors_2
#Sequence2_Model=Hangar_Door2
#Sequence3=Close_Hangar_Doors_3
#Sequence3_Model=Hangar_Door3
#Sequence4=Close_Hangar_Doors_4
#Sequence4_Model=Hangar_Door4

[------------------------------ Sequences ------------------------------]
[Hide_IVM]
NumberOfSteps=1
Time1=0
PositionY1=-10
Smoothness1=EaseInOut
[Show_IVM]
NumberOfSteps=1
Time1=0
PositionY1=0.26911
Smoothness1=EaseInOut

[Hide_F8]
NumberOfSteps=1
Time1=0
PositionY1=-10
Smoothness1=EaseInOut
[Show_F8]
NumberOfSteps=1
Time1=0
PositionY1=0.263551
Smoothness1=EaseInOut

[Hide_Alize]
NumberOfSteps=1
Time1=0
PositionY1=-10
Smoothness1=EaseInOut
[Show_Alize]
NumberOfSteps=1
Time1=0
PositionY1=0.241749
Smoothness1=EaseInOut

[Hide_Aquilon]
NumberOfSteps=1
Time1=0
PositionY1=-10
Smoothness1=EaseInOut
[Show_Aquilon]
NumberOfSteps=1
Time1=0
PositionY1=0.257651 
Smoothness1=EaseInOut

#----------------------------------------------------------------------------------

[ElevatorMoveDownSequence]
NumberOfSteps=2
Time1=2                // time in seconds for the start
PositionY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=12                // time in seconds - here for the end
PositionY2=-0.125681
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as its the last entry

[ElevatorMoveUpSequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionY1=-0.125681
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=10                // time in seconds - here for the end
PositionY2=0
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as its the last entry

#----------------------------------------------------------------------------------

[RailingsUp]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=2                // time in seconds - here for the end
PositionY2=0.01378 
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as its the last entry

[RailingsDown]
NumberOfSteps=2
Time1=10                // time in seconds for the start
PositionY1=0.01378 
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=12               // time in seconds - here for the end
PositionY2=0
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as its the last entry

#----------------------------------------------------------------------------------


[Open_Hangar_Doors_1]
NumberOfSteps=2
Time1=2                // time in seconds for the start
PositionZ1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=12
PositionZ2=0.057824
Smoothness2=EaseInOut

[Close_Hangar_Doors_1]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionZ1=0.057824
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=0
Smoothness2=EaseInOut


#---------------------------------------------------------


[Open_Hangar_Doors_2]
NumberOfSteps=2
Time1=2                // time in seconds for the start
PositionZ1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=12
PositionZ2=0.119713
Smoothness2=EaseInOut

[Close_Hangar_Doors_2]
NumberOfSteps=2
Time1=0               // time in seconds for the start
PositionZ1=0.119713
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=0
Smoothness2=EaseInOut


#-----------------------------------------------------------

[Open_Hangar_Doors_3]
NumberOfSteps=2
Time1=2               // time in seconds for the start
PositionZ1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=12
PositionZ2=-0.119713
Smoothness2=EaseInOut

[Close_Hangar_Doors_3]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionZ1=-0.119713
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=0
Smoothness2=EaseInOut

#----------------------------------------------------------

[Open_Hangar_Doors_4]
NumberOfSteps=2
Time1=2                // time in seconds for the start
PositionZ1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=12
PositionZ2=-0.057824
Smoothness2=EaseInOut

[Close_Hangar_Doors_4]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionZ1=-0.057824
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=0
Smoothness2=EaseInOut

#-------------------------------------------------------------

[DeflectorUp]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationX1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=3                // time in seconds - here for the end
RotationX2=60
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as its the last entry

[DeflectorDown]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationX1=60
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=3                // time in seconds - here for the end
RotationX2=0
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as its the last entry