#!alias vessels/usn_ffg_oliver_hazard_perry_longhull.ini

[---------- FlightDeck Definitions ----------]
[AirGroup]
usn_sh-2f=Default,0
usn_sh-60b=Default,2

[FlightDeck]
AircraftCapacity=2
AircraftSupported=Helicopters
UnsupportedAircraft=usn_ch-46,usaf_hh-3,usn_qh-50c,usn_qh-50d

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=11

#---------- Air and Air&Surface search radars ----------
[SensorSystem2] #SPS-49
#Mounted on mast between bridge and main mast
Type=Radar
SystemName=SPS-49V5
Mount=SPS_49
Collider=coll_sps49

[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=8
AvailableLoadouts=Late
Late_SensorsToRemove=9
Late_SubModelsToHide=Spotlights

[---------- WeaponMagazines ----------]
############################################################
# Weapon Magazine Systems
############################################################

[WeaponMagazineMK13]
NumberOfAmmunitionTypes=2
Ammunition1=usn_rgm-84d
Ammunition1_Count=6
Ammunition2=usn_rim-66e
Ammunition2_Count=34
Collider=coll_mk13_magazine
ModuleType=MediumMagazine

[WeaponMagazineTorpedo]
NumberOfAmmunitionTypes=1
Ammunition1_Count=16
Ammunition1=usn_mk50_ship
Collider=coll_torpedo_magazine
ModuleType=SmallMagazine

[WeaponMagazineCIWS]
NumberOfAmmunitionTypes=1
Ammunition1_Count=20000
Ammunition1=usn_cal_20mm_apds
Collider=coll_ciws_magazine
ModuleType=SmallMagazine

[NoisemakerMagazine]
NumberOfAmmunitionTypes=1
Ammunition1=usn_adc_mk2_noisemaker
Ammunition1_Count=20
ModuleType=Inert

