[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=8

[Default]
ResourcesHullnumberFolder=assets/materials/hullnumbers/
HullnumberTexture=usn_lhd_1.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=2015|

CustomAirGroup=True
usmc_ah-1w_late=Squadron7,4
usmc_uh-1y=Squadron7,3
usmc_mv-22b=Squadron2,12
usmc_f-35b=Squadron1,6
#usn_mh-60s=Squadron3,2

[Variant1] #Wasp
ResourcesHullnumberFolder=assets/materials/hullnumbers/
HullnumberTexture=usn_lhd_1.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=2015|

CustomAirGroup=True
usmc_ah-1w_late=Squadron7,4
usmc_uh-1y=Squadron7,3
usmc_mv-22b=Squadron2,12
usmc_f-35b=Squadron1,6
#usn_mh-60s=Squadron3,2

[Variant2] #Essex
ResourcesHullnumberFolder=assets/materials/hullnumbers/
HullnumberTexture=usn_lhd_2.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=2015|

CustomAirGroup=True
usmc_ah-1w_late=Squadron6,4
usmc_uh-1y=Squadron6,3
usmc_mv-22b=Squadron2,12
usmc_f-35b=Squadron1,6
#usn_mh-60s=Squadron3,22

[Variant3] #Kearsarge
ResourcesHullnumberFolder=assets/materials/hullnumbers/
HullnumberTexture=usn_lhd_3.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=2015|

CustomAirGroup=True
usmc_ah-1w_late=Squadron1,4
usmc_uh-1y=Squadron1,3
usmc_mv-22b=Squadron2,12
usmc_f-35b=Squadron1,6
#usn_mh-60s=Squadron3,2

[Variant4] #Boxer
ResourcesHullnumberFolder=assets/materials/hullnumbers/
HullnumberTexture=usn_lhd_4.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=2015|

CustomAirGroup=True
usmc_ah-1w_late=Squadron5,4
usmc_uh-1y=Squadron5,3
usmc_mv-22b=Squadron2,12
usmc_f-35b=Squadron1,6
#usn_mh-60s=Squadron3,2

[Variant5] #Bataan
ResourcesHullnumberFolder=assets/materials/hullnumbers/
HullnumberTexture=usn_lhd_5.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=2015|

CustomAirGroup=True
usmc_ah-1w_late=Squadron4,4
usmc_uh-1y=Squadron4,3
usmc_mv-22b=Squadron2,12
usmc_f-35b=Squadron1,6
#usn_mh-60s=Squadron3,22

[Variant6] #Bonhomme Richard
ResourcesHullnumberFolder=assets/materials/hullnumbers/
HullnumberTexture=usn_lhd_6.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=2015|2021

CustomAirGroup=True
usmc_ah-1w_late=Squadron8,4
usmc_uh-1y=Squadron8,3
usmc_mv-22b=Squadron2,12
usmc_f-35b=Squadron1,6
#usn_mh-60s=Squadron3,2

[Variant7] #Iwo Jima
ResourcesHullnumberFolder=assets/materials/hullnumbers/
HullnumberTexture=usn_lhd_7.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=2015|

CustomAirGroup=True
usmc_ah-1w_late=Squadron4,4
usmc_uh-1y=Squadron4,3
usmc_mv-22b=Squadron2,12
usmc_f-35b=Squadron1,6
#usn_mh-60s=Squadron3,2

[Variant8] #Makin Island
ResourcesHullnumberFolder=assets/materials/hullnumbers/
HullnumberTexture=usn_lhd_8.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=2015|

CustomAirGroup=True
usmc_ah-1w_late=Squadron3,4
usmc_uh-1y=Squadron3,3
usmc_mv-22b=Squadron2,12
usmc_f-35b=Squadron1,6
#usn_mh-60s=Squadron3,2