[Language_en]
Name=Moloti's Armed Merchantmen
Description=A pack of merchant vessels with limited armament for all your merchant cruiser needs. Fundamentally not a serious add-on.
[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept a higher PATCH.
;Would recommend this as a default for starters.
ApproximateVersion=0.8.0