[ ========================================= General ========================================== ]
[General]
DataLinkUpdateRate=1             // every x seconds there will be an update for the overall sensor image for the minimap
PassiveSensorUpdateRate=1.0        // every x seconds the passive contacts will be re-evaluated
LostPassiveContactTimeToDisable=5  // time in seconds after which a lost passive contact bearing line will be greyed out
LostContactTimeToRemove=30         // time in seconds after which a lost contact will be removed from the map

[ ---------------------------- Sonars ----------------------------- ]
[MGK-600] #MGK-600 Irtush-Amfora
#Users: wp_ssn_yasen
Kind=Sonar
HasDataLink=False       // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=5.0   // TODO in degrees
RangeResolution=130.0   // TODO defines the minimum range where two targets behind can be recognized as two; in meters
ActiveRange=50          // in km
PassiveRange=105         // in km
ActiveGain=40
Gain=48                 // in db, gain of the sensor
OutputPower=230         // Active sensor output power in dB, unused for passive ones
Type=Hull				//Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF
IsTowedSonar=False
ModuleType=SonarSensor
SignalProcessing=8
NarrowBandCapable=True
MaxConvergenceZones=1

[MGK-540]
#Users: wp_ssn_akula
Kind=Sonar
HasDataLink=True                     // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=5.0                // TODO in degrees
RangeResolution=150.0                // TODO defines the minimum range where two targets behind can be recognized as two; in meters
ActiveRange=35                       // in km
PassiveRange=65                      // in km
ActiveGain=40                        // in db, gain of the active sensor
Gain=45                              // in db, gain of the passive sensor
OutputPower=230                      // Active sensor output power in dB, unused for passive ones
Type=Hull                            //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF                    // TODO ????
ModuleType=SonarSensor
SignalProcessing=6
NarrowBandCapable=True
MaxConvergenceZones=1

[ ---------------------------- Towed Arrays ----------------------------- ]
[MGK-600_TA]
#Users: wp_ssn_yasen
Kind=Sonar
HasDataLink=False                     // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=6.0                // TODO in degrees
RangeResolution=150.0                // TODO defines the minimum range where two targets behind can be recognized as two; in meters
PassiveRange=155                      // in km
Gain=52                              // in db, gain of the sensor
Type=Towed                           //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF                    // TODO ????
ModuleType=SonarSensor
SignalProcessing=8
NarrowBandCapable=True
MaxConvergenceZones=2

[MGK-540_TA]
#Users: wp_ssn_akula
Kind=Sonar
HasDataLink=True                     // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=6.0                // TODO in degrees
RangeResolution=150.0                // TODO defines the minimum range where two targets behind can be recognized as two; in meters
PassiveRange=110                      // in km
Gain=48                              // in db, gain of the sensor
Type=Towed                           //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF                    // TODO ????
ModuleType=SonarSensor
SignalProcessing=6
NarrowBandCapable=True
MaxConvergenceZones=2
