[General]
UnitType=LandUnit
LandUnitSubType=MobileUnit

DefaultCameraDistance=0.8
MinCameraDistanceForeAft=0.4
MinCameraDistanceBroadside=0.4
CameraPivotHeight=0.04

GroundOffset=0
AutoFlatten=False
MaskVegetation=True

Length=6.5                     // in meters
Beam=3.2                       // in meters
Range=243                      // in miles

# Hull armor: None, Minor, Moderate, Heavy
ArmorType=Minor
DamagePoints=5  //systems damage contribution substracted from this when systems destroyed, when becomes less than zero, the whole unit is considered being destroyed

[Physics]
HorsePower=465
Mass=13                      // in tons

MaxForwardVelocity=45        // in knots
MaxBackwardVelocity=7.5          // in knots
Braking=12                     // knots/sec
TurnRate=35                    // in degrees per second

[AI]
UnitScoreValue=1               // value for calculation of mission score
Role=Gun

[ControlSystem]
Collider=coll_hitbox  // makes unit destroyable
Integrity=5

[SensorData]
#Visual
VisualIdentificationRange=2.5  // Camouflaged  (x0.5)
IRSignature=Small
# Radar related (RCS => radar cross section)
RCS=Small

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_usa_ifv_bradley

[---------- Sensor Systems ----------]
############################################################
# Sensor Systems
############################################################
[SensorSystems]
NumberOfSensorSystems=2
#---------- Visual ----------
[SensorSystem1] #AdvancedOptics
Type=Visual
SystemName=AdvancedOptics
MountPosition=0,0.04,0


[---------- Weapon Systems ----------]
############################################################
# Weapon Systems
############################################################
[WeaponSystems]
NumberOfWeaponSystems=2

[WeaponSystem1]  #2A28
Type=Gun
SystemName=2A28
#Sensors
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
ContainerBase=Gun
NumberOfGuns=1
Gun1=Barrel
AreContainersRotatable=True
#Angles
ElevationArc=-4,30
RestAngles=0
#Loading
AssociatedMagazine=WeaponMagazineGun
#Effects
#Other
MaxVelocityToFire=15
VIDIncrease=5  // In miles. Flat base VID increace when firing.
SharesMountWith=WeaponSystem2  //List of systems

[WeaponSystem2]  #AT-3
Type=Missile
SystemName=AT-3_BMP-1
#Sensors
#Animations
#Mount
Mount=Turret
IsMountRotatable=True
#Containers
NumberOfContainers=1
Container1=Gun
#Angles
FixVerticalLaunchAngle=2
RestAngles=0,0
LoadAngles=Any
#Loading
AssociatedMagazine=WeaponMagazineAT-3
PreloadAmmunition=True           // REQUIRED!!! for non-unloading launchers with magazine, like MK29 and ASROC
#Effects
#Other
DisplayWeaponsOnSystem=True
VIDIncrease=8  // In miles. Flat base VID increace when firing.
SharesMountWith=WeaponSystem1


[---------- WeaponMagazines ----------]
[WeaponMagazineAT-3]
NumberOfAmmunitionTypes=1
Ammunition1=wp_9m14
Ammunition1_Count=4
ModuleType=SmallMagazine

[WeaponMagazineGun]
NumberOfAmmunitionTypes=2
Ammunition1=wp_pg-15v
Ammunition1_Count=25
Ammunition2=wp_og-15v
Ammunition2_Count=15
ModuleType=SmallMagazine

[Models]
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/models/land_units/bmp1/
ResourcesRoot=bmp1.obj
ResourcesMesh=hull
ResourcesMaterial=bmp1_mat.ini
############################################################

[Submodels]
Turret=Turret
Gun=Gun
Barrel=Barrel

[Turret]
Mesh=turret
Material=bmp1_mat.ini
Position=0,0.0266,0

[Gun]
Mesh=gun
Material=bmp1_mat.ini
Parent=Turret
Position=0,0.0002,0.01199
Rotation=-7,0,0

[Barrel]
Mesh=barrel
Material=bmp1_mat.ini
Parent=Gun
Position=0,0,0
Rotation=7,0,0

[Sounds]
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=1
AmbientAudioClip=audio/ships/Ship-Turbine-Small
AmbientAudioPosition=0,0,0
AmbientAudioRollOff=Logarithmic
AmbientAudioDistance=1,20
AmbientAudioPitchRange=1.0,1.6
AmbientAudioVolume=1.0
AmbientAudioAudibility=Above  // layer of sound audibility: Above, Below, AboveAndBelow

[Particles]
SmallFireEffectClass=SmallShipFire
SmallFireEffectPosition=0,0,0
ModerateFireEffectClass=ModerateShipFire
ModerateFireEffectPosition=0,0,0
SevereFireEffectClass=SevereShipFire
SevereFireEffectPosition=0,0,0
SecondaryExplosionEffect=effects/explosions/emitters/missile_hit_ship
SecondaryExplosionEffectPosition=0,0,0

[---------- Colliders ----------]
[Colliders]
UseKinematicCollision=False
NumberOfMeshColliders=0
NumberOfColliders=2

Collider1=coll_hitbox
Collider2=coll_collider

[coll_hitbox]
Collider=Box
Position=0,0.0197,0
Rotation=0,0,0
Scale=0.045,0.04,0.1

[coll_collider]
Collider=Box
Position=0,0.0028,-0.0023
Rotation=0,0,0
Scale=0.03,0.005,0.05
Layer=Default
