[AmmunitionNames]
# ------------------ AAM ------------------

# ------------------ SAM ------------------
rok_saam-400k= K-SAAM, south korea sam

rok_ssm-700k= rok_ssm-700k, south korea anti ship missile (KVLS)

rok_ssm-750k= rok_ssm-750k, south korea anti ground missile (KVLS)

rok_k-sam-II= SAM-II, south korea SM-2 ver.

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

ko_bilyong_130mm= Bilyong, Anti ship Missile

ko_Hycore= Hycore, Anti ship Missile

ko_Antiship_2= ASM-II,Anti ship, Ground Missile

ko_Antiship_2_ship= Haeseong_5,Anti ship Missile

rn_sea_skua=Sea Skua,,ASM,The Sea Skua is a British lightweight short range air to surface missile.

#-----------Land Strike only missiles---------

rok_hyunmoo_4_2= Hyunmoo, south korean Land Strike Missile (KVLS-II)

# ---------- Anti-sub Missiles ----------

# ------------------ RBU ------------------

# ---------- Torpedoes ----------

rok_k-745= rok_k-745, south korea terpedo

rok_k-745A1= rok_k-745A1, Asroc terpedo

rok_k-745-k-asroc= rok_k-745-k-asroc,  asroc missile

# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

ko_cal_20mm= 20mm, Guns

# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# ------------------ Depth Charges ------------------
rn_mk_11=Mk 11,250LB,Depth Charge,A British 250lb depth charge designed for use by aircraft.

# ----------------- Fueltanks ----------------