[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=2

[Default]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
#HullnumberTexture=iran_81
ResourcesLiveryFolder=ships/Tapi/
LiveryTexture=tha_fs_tapi_tx.png
SpecularTexture=tha_fs_tapi_spec.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_thailand.png
Nation=Thailand
ServiceDate=1971

[Variant1]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=iran_81
ResourcesLiveryFolder=ships/Tapi/
LiveryTexture=tha_fs_tapi_tx.png
SpecularTexture=tha_fs_tapi_spec.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_thailand.png
Nation=Thailand
ServiceDate=1971

[Variant2]
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=iran_82
ResourcesLiveryFolder=ships/Tapi/
LiveryTexture=tha_fs_tapi_tx.png
SpecularTexture=tha_fs_tapi_spec.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_thailand.png
Nation=Thailand
ServiceDate=1974