[Language_en]
Name=The Royal Navy
Description=[The Royal Navy v0.4.18] Step back into the tense waters of the Cold War with this ship mod pack, bringing the might of the Royal Navy to Sea Power: Naval Combat in the Missile Age. From guided missile destroyers to nimble frigates, this mod recreates Britain’s seaborne power projection during a time when every sonar ping and radar blip could spark global conflict. Command a fleet forged in the shadow of the Iron Curtain and test your mettle in a high-stakes maritime chess match.

Special Thanks and credit go to:
L963
Cookiesaurus
BunterGoesHard
Longbow
Britishguy
Brothermunro
MrChiaow
Hoovercopter
AllTheKingsMen
Plasm@n
Saelll451
IcEm4n
And Petrouvis

[Compatibility]
ApproximateVersion=0.8.2
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.