[Animations]
NumberOfAnimations=12

Animation1=Canopy_Extend
Animation2=Canopy_Retract
Animation3=Wings_Fold
Animation4=Wings_Extend
Animation5=Flaps_Takeoff
Animation6=Flaps_Takeoff_Retract
Animation7=Flaps_Landing
Animation8=Flaps_Landing_Retract
Animation9=Gear_Extend
Animation10=Gear_Retract
Animation11=Hook_Deploy
Animation12=Hook_Retrieve

[Canopy_Extend]
NumberOfSequencesToPlay=3
Sequence1=Canopy_Open_1
Sequence1_Model=Hatch_frame

[Canopy_Retract]
NumberOfSequencesToPlay=3
Sequence1=Canopy_Close_1
Sequence1_Model=Hatch_frame

[Wings_Fold]
NumberOfSequencesToPlay=4
Sequence1=Left_Wing_Fold_1
Sequence1_Model=Wing_left_1
Sequence2=Left_Wing_Fold_2
Sequence2_Model=Wing_left_2
Sequence3=Right_Wing_Fold_1
Sequence3_Model=Wing_right_1
Sequence4=Right_Wing_Fold_2
Sequence4_Model=Wing_right_2

[Wings_Extend]
NumberOfSequencesToPlay=4
Sequence1=Left_Wing_Spread_1
Sequence1_Model=Wing_left_1
Sequence2=Left_Wing_Spread_2
Sequence2_Model=Wing_left_2
Sequence3=Right_Wing_Spread_1
Sequence3_Model=Wing_right_1
Sequence4=Right_Wing_Spread_2
Sequence4_Model=Wing_right_2

[Flaps_Takeoff]
NumberOfSequencesToPlay=4
Sequence1=Flap_Takeoff_l_1
Sequence1_Model=Flap_l_1
Sequence2=Flap_Takeoff_l_2
Sequence2_Model=Flap_l_2
Sequence3=Flap_Takeoff_r_1
Sequence3_Model=Flap_r_1
Sequence4=Flap_Takeoff_r_2
Sequence4_Model=Flap_r_2

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=4
Sequence1=Flap_Takeoff_Retract_l_1
Sequence1_Model=Flap_l_1
Sequence2=Flap_Takeoff_Retract_l_2
Sequence2_Model=Flap_l_2
Sequence3=Flap_Takeoff_Retract_r_1
Sequence3_Model=Flap_r_1
Sequence4=Flap_Takeoff_Retract_r_2
Sequence4_Model=Flap_r_2

[Flaps_Landing]
NumberOfSequencesToPlay=4
Sequence1=Flap_Landing_l_1
Sequence1_Model=Flap_l_1
Sequence2=Flap_Landing_l_2
Sequence2_Model=Flap_l_2
Sequence3=Flap_Landing_r_1
Sequence3_Model=Flap_r_1
Sequence4=Flap_Landing_r_2
Sequence4_Model=Flap_r_2

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=4
Sequence1=Flap_Landing_Retract_l_1
Sequence1_Model=Flap_l_1
Sequence2=Flap_Landing_Retract_l_2
Sequence2_Model=Flap_l_2
Sequence3=Flap_Landing_Retract_r_1
Sequence3_Model=Flap_r_1
Sequence4=Flap_Landing_Retract_r_2
Sequence4_Model=Flap_r_2

[Gear_Extend]
NumberOfSequencesToPlay=12
Sequence1=Front_Gear_Door_1_Open
Sequence1_Model=Front_gear_door_left
Sequence2=Front_Gear_Door_2_Open
Sequence2_Model=Front_gear_door_right
Sequence3=Front_gear_Extend
Sequence3_Model=Front_gear
Sequence4=Front_gear_struts_Extend
Sequence4_Model=Front_gear_struts
Sequence5=Main_Gear_Extend_l
Sequence5_Model=Main_gear_left
Sequence6=Strut_1_left_Extend
Sequence6_Model=Strut_1_left
Sequence7=Strut_2_left_Extend
Sequence7_Model=Strut_2_left
Sequence8=Gear_door_left_Extend
Sequence8_Model=Gear_door_left
Sequence9=Main_Gear_Extend_r
Sequence9_Model=Main_gear_right
Sequence10=Strut_1_right_Extend
Sequence10_Model=Strut_1_right
Sequence11=Strut_2_right_Extend
Sequence11_Model=Strut_2_right
Sequence12=Gear_door_right_Extend
Sequence12_Model=Gear_door_right

[Gear_Retract]
NumberOfSequencesToPlay=14
Sequence1=Front_Gear_Door_1_Retract
Sequence1_Model=Front_gear_door_left
Sequence2=Front_Gear_Door_2_Retract
Sequence2_Model=Front_gear_door_right
Sequence3=Front_gear_Retract
Sequence3_Model=Front_gear
Sequence4=Front_gear_struts_Retract
Sequence4_Model=Front_gear_struts
Sequence5=Main_Gear_Retract_l
Sequence5_Model=Main_gear_left
Sequence6=Strut_1_left_Retract
Sequence6_Model=Strut_1_left
Sequence7=Strut_2_left_Retract
Sequence7_Model=Strut_2_left
Sequence8=Gear_door_left_Retract
Sequence8_Model=Gear_door_left
Sequence9=Main_Gear_Retract_r
Sequence9_Model=Main_gear_right
Sequence10=Strut_1_right_Retract
Sequence10_Model=Strut_1_right
Sequence11=Strut_2_right_Retract
Sequence11_Model=Strut_2_right
Sequence12=Gear_door_right_Retract
Sequence12_Model=Gear_door_right

[Hook_Deploy]
NumberOfSequencesToPlay=1
Sequence1=Hook_Extend
Sequence1_Model=Arrestor_Hook

[Hook_Retrieve]
NumberOfSequencesToPlay=1
Sequence1=Hook_Retract
Sequence1_Model=Arrestor_Hook

[Radar_Deploy]
NumberOfSequencesToPlay=1
Sequence1=Radar_Extend
Sequence1_Model=Radar_dome

[Radar_Retrieve]
NumberOfSequencesToPlay=1
Sequence1=Radar_Retract
Sequence1_Model=Radar_dome
[------------------------------ Sequences ------------------------------]
[Canopy_Open_1]
NumberOfSteps=2
Time1=0 
PositionZ1=0.04215279763513816
PositionY1=0.0161272183380479
Smoothness1=EaseInOut
Time2=5 
PositionZ2=0.032
PositionY2=0.0161272183380479
Smoothness2=EaseInOut

[Canopy_Close_1]
NumberOfSteps=2
Time1=0 
PositionZ1=0.032
PositionY1=0.0161272183380479
Smoothness1=EaseInOut
Time2=5 
PositionZ2=0.04215279763513816
PositionY2=0.0161272183380479
Smoothness2=EaseInOut

#------------------------------ Wing Fold/Unfold ------------------------------#

[Left_Wing_Fold_1]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=15 
RotationZ2=-145
Smoothness2=EaseInOut

[Left_Wing_Spread_1]
NumberOfSteps=2
Time1=0 
RotationZ1=-145
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
Smoothness2=EaseInOut

[Left_Wing_Fold_2]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=15 
RotationZ2=145
Smoothness2=EaseInOut

[Left_Wing_Spread_2]
NumberOfSteps=2
Time1=0 
RotationZ1=145
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
Smoothness2=EaseInOut

[Right_Wing_Fold_1]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=15 
RotationZ2=145
Smoothness2=EaseInOut

[Right_Wing_Spread_1]
NumberOfSteps=2
Time1=0 
RotationZ1=145
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
Smoothness2=EaseInOut

[Right_Wing_Fold_2]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=15 
RotationZ2=-145
Smoothness2=EaseInOut

[Right_Wing_Spread_2]
NumberOfSteps=2
Time1=0 
RotationZ1=-145
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
Smoothness2=EaseInOut

#------------------------------Flaps takeoff ------------------------------#

[Flap_Takeoff_l_1]
NumberOfSteps=2
Time1=0 
RotationX1=6
RotationZ1=-3.5
PositionZ1=-0.0087
PositionY1=-0.004
Smoothness1=EaseInOut
Time2=10
RotationX2=-20
RotationZ2=0
PositionZ2=-0.021
PositionY2=-0.0035
Smoothness2=EaseInOut

[Flap_Takeoff_Retract_l_1]
NumberOfSteps=2
Time1=0 
RotationX1=-20
RotationZ1=0
PositionZ1=-0.021
PositionY1=-0.0035
Smoothness1=EaseInOut
Time2=10
RotationX2=6
RotationZ2=-3.5
PositionZ2=-0.0087
PositionY2=-0.004
Smoothness2=EaseInOut

[Flap_Takeoff_l_2]
NumberOfSteps=2
Time1=0 
RotationX1=0
RotationZ1=5.3413123439281
PositionZ1=-0.009293206766365114
PositionY1=-0.00866248031722869
Smoothness1=EaseInOut
Time2=10
RotationX2=-27
RotationZ2=10
PositionZ2=-0.022
PositionY2=-0.0086
Smoothness2=EaseInOut

[Flap_Takeoff_Retract_l_2]
NumberOfSteps=2
Time1=0 
RotationX1=-27
RotationZ1=10
PositionZ1=-0.022
PositionY1=-0.0086
Smoothness1=EaseInOut
Time2=10
RotationX2=0
RotationZ2=5.3413123439281
PositionZ2=-0.009293206766365114
PositionY2=-0.00866248031722869
Smoothness2=EaseInOut

[Flap_Takeoff_r_1]
NumberOfSteps=2
Time1=0 
RotationX1=6
RotationZ1=3.5
PositionZ1=-0.0087
PositionY1=-0.004
Smoothness1=EaseInOut
Time2=10
RotationX2=-20
RotationZ2=0
PositionZ2=-0.021
PositionY2=-0.0035
Smoothness2=EaseInOut

[Flap_Takeoff_Retract_r_1]
NumberOfSteps=2
Time1=0 
RotationX1=-20
RotationZ1=0
PositionZ1=-0.021
PositionY1=-0.0035
Smoothness1=EaseInOut
Time2=10
RotationX2=6
RotationZ2=3.5
PositionZ2=-0.0087
PositionY2=-0.004
Smoothness2=EaseInOut

[Flap_Takeoff_r_2]
NumberOfSteps=2
Time1=0 
RotationX1=0
RotationZ1=-5.3413123439281
PositionZ1=-0.009293206766365114
PositionY1=-0.00866248031722869
Smoothness1=EaseInOut
Time2=10
RotationX2=-27
RotationZ2=-10
PositionZ2=-0.022
PositionY2=-0.0086
Smoothness2=EaseInOut

[Flap_Takeoff_Retract_r_2]
NumberOfSteps=2
Time1=0 
RotationX1=-27
RotationZ1=-10
PositionZ1=-0.022
PositionY1=-0.0086
Smoothness1=EaseInOut
Time2=10
RotationX2=0
RotationZ2=-5.3413123439281
PositionZ2=-0.009293206766365114
PositionY2=-0.00866248031722869
Smoothness2=EaseInOut

#------------------------------Flaps landing------------------------------#

[Flap_Landing_l_1]
NumberOfSteps=2
Time1=0 
RotationX1=6
RotationZ1=-3.5
PositionZ1=-0.0087
PositionY1=-0.004
Smoothness1=EaseInOut
Time2=10
RotationX2=-30
RotationZ2=0
PositionZ2=-0.021
PositionY2=-0.0035
Smoothness2=EaseInOut

[Flap_Landing_Retract_l_1]
NumberOfSteps=2
Time1=0 
RotationX1=-30
RotationZ1=0
PositionZ1=-0.021
PositionY1=-0.0035
Smoothness1=EaseInOut
Time2=10
RotationX2=6
RotationZ2=-3.5
PositionZ2=-0.0087
PositionY2=-0.004
Smoothness2=EaseInOut

[Flap_Landing_l_2]
NumberOfSteps=2
Time1=0 
RotationX1=0
RotationZ1=5.3413123439281
PositionZ1=-0.009293206766365114
PositionY1=-0.00866248031722869
Smoothness1=EaseInOut
Time2=10
RotationX2=-35
RotationZ2=11
PositionZ2=-0.022
PositionY2=-0.0086
Smoothness2=EaseInOut

[Flap_Landing_Retract_l_2]
NumberOfSteps=2
Time1=0 
RotationX1=-35
RotationZ1=11
PositionZ1=-0.022
PositionY1=-0.0086
Smoothness1=EaseInOut
Time2=10
RotationX2=0
RotationZ2=5.3413123439281
PositionZ2=-0.009293206766365114
PositionY2=-0.00866248031722869
Smoothness2=EaseInOut

[Flap_Landing_r_1]
NumberOfSteps=2
Time1=0 
RotationX1=6
RotationZ1=0
PositionZ1=-0.0087
PositionY1=-0.004
Smoothness1=EaseInOut
Time2=10
RotationX2=-30
RotationZ2=0
PositionZ2=-0.021
PositionY2=-0.0035
Smoothness2=EaseInOut

[Flap_Landing_Retract_r_1]
NumberOfSteps=2
Time1=0 
RotationX1=-30
RotationZ1=3.5
PositionZ1=-0.021
PositionY1=-0.0035
Smoothness1=EaseInOut
Time2=10
RotationX2=6
RotationZ2=3.5
PositionZ2=-0.0087
PositionY2=-0.004
Smoothness2=EaseInOut

[Flap_Landing_r_2]
NumberOfSteps=2
Time1=0 
RotationX1=0
RotationZ1=-5.3413123439281
PositionZ1=-0.009293206766365114
PositionY1=-0.00866248031722869
Smoothness1=EaseInOut
Time2=10
RotationX2=-35
RotationZ2=-11
PositionZ2=-0.022
PositionY2=-0.0086
Smoothness2=EaseInOut

[Flap_Landing_Retract_r_2]
NumberOfSteps=2
Time1=0 
RotationX1=-35
RotationZ1=-11
PositionZ1=-0.022
PositionY1=-0.0086
Smoothness1=EaseInOut
Time2=10
RotationX2=0
RotationZ2=-5.3413123439281
PositionZ2=-0.009293206766365114
PositionY2=-0.00866248031722869
Smoothness2=EaseInOut

#------------------------------Hook deploy/retract ------------------------------#

[Hook_Extend]
NumberOfSteps=2
Time1=0 
RotationX1=9
Smoothness1=EaseInOut
Time2=5 
RotationX2=-60
Smoothness2=EaseInOut

[Hook_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-60
Smoothness1=EaseInOut
Time2=5 
RotationX2=9
Smoothness2=EaseInOut

#------------------------------Gear deploy/retract ------------------------------#
#------------------------------Front Gear ------------------------------#
[Front_gear_Extend]
NumberOfSteps=2
Time1=2
RotationX1=90
Smoothness1=EaseInOut
Time2=15
RotationX2=0
Smoothness2=EaseInOut

[Front_gear_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=15
RotationX2=90
Smoothness2=EaseInOut

[Front_Gear_Door_1_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=7
RotationZ2=-80
Smoothness2=EaseInOut

[Front_Gear_Door_1_Retract]
NumberOfSteps=2
Time1=10
RotationZ1=-80
Smoothness1=EaseInOut
Time2=15
RotationZ2=0
Smoothness2=EaseInOut

[Front_Gear_Door_2_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=7
RotationZ2=80
Smoothness2=EaseInOut

[Front_Gear_Door_2_Retract]
NumberOfSteps=2
Time1=10
RotationZ1=80
Smoothness1=EaseInOut
Time2=15
RotationZ2=0
Smoothness2=EaseInOut

[Front_gear_struts_Extend]
NumberOfSteps=2
Time1=0 
RotationX1=-90
Smoothness1=EaseInOut
Time2=15
RotationX2=0
Smoothness2=EaseInOut

[Front_gear_struts_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=15
RotationX2=-90
Smoothness2=EaseInOut
#------------------------------Main Gear Left ------------------------------#
[Main_Gear_Extend_l]
NumberOfSteps=2
Time1=3
RotationZ1=93
RotationY1=0
Smoothness1=EaseInOut
Time2=15
RotationZ2=0
RotationY2=-2
Smoothness2=EaseInOut

[Main_Gear_Retract_l]
NumberOfSteps=2
Time1=0 
RotationZ1=0
RotationY1=-2
Smoothness1=EaseInOut
Time2=15 
RotationZ2=93
RotationY2=0
Smoothness2=EaseInOut

[Strut_1_left_Extend]
NumberOfSteps=2
Time1=10
RotationZ1=40
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
Smoothness2=EaseInOut

[Strut_1_left_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=40
Smoothness2=EaseInOut

[Gear_door_left_Extend]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=15 
RotationZ2=-85
Smoothness2=EaseInOut

[Gear_door_left_Retract]
NumberOfSteps=2
Time1=0
RotationZ1=-85
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
Smoothness2=EaseInOut

#------------------------------Main Gear Right ------------------------------#
[Main_Gear_Extend_r]
NumberOfSteps=2
Time1=3
RotationZ1=-93
RotationY1=0
Smoothness1=EaseInOut
Time2=15
RotationZ2=0
RotationY2=2
Smoothness2=EaseInOut

[Main_Gear_Retract_r]
NumberOfSteps=2
Time1=0 
RotationZ1=0
RotationY2=-2
Smoothness1=EaseInOut
Time2=15 
RotationZ2=-93
RotationY2=0
Smoothness2=EaseInOut

[Strut_1_right_Extend]
NumberOfSteps=2
Time1=10
RotationZ1=-40
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
Smoothness2=EaseInOut

[Strut_1_right_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=-40
Smoothness2=EaseInOut

[Gear_door_right_Extend]
NumberOfSteps=2
Time1=0
RotationZ1=0
RotationX1=0
Smoothness1=EaseInOut
Time2=15 
RotationZ2=85
RotationX2=5
Smoothness2=EaseInOut

[Gear_door_right_Retract]
NumberOfSteps=2
Time1=0
RotationZ1=85
RotationX1=5
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
RotationX2=0
Smoothness2=EaseInOut