[AmmunitionNames]
# ------------------ AAM ------------------
# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------


# ---------- Anti-ship Missiles ----------
wp_ss-n-26a=P-800,缟玛瑙,反水面,P-800缟玛瑙（3M55，SS-N-26）是苏联的高性能超音速防区外反舰武器。它在概念上与3M82白蛉和3M45花岗岩类似，是新一代反舰导弹中的轻型型号。较小的尺寸使其可装备于飞机、导弹艇以及较老的舰艇和潜艇等小型平台。就其尺寸而言，缟玛瑙威力极强：它采用由P-700花岗岩的“花岗岩-电子”导引头小型化而来的导引头，在高空和海平面均能高速飞行，再加上新一代欺骗式干扰机、末段机动和辅助对地攻击能力，使其成为一款真正令人畏惧的武器。

wp_ss-n-27a=3M54K,口径,反水面,口径3M54K（SS-N-27A）是俄罗斯的远程亚音速反舰巡航导弹，其弹头为末段高速分离的“飞镖”，最高速度接近3马赫，即使对现代防空系统也构成极大威胁。若任其进入末段，它可算是最危险的反舰导弹威胁之一。在末段之前，该弹的特性与其他亚音速巡航导弹相同，若能及时发现并拦截，则不难对付。


#-----------Land Strike only missiles---------
wp_rsm-56=RSM-56,圆锤,潜射弹道导弹,RSM-56圆锤（北约代号：SS-N-30/SS-NX-32）是为俄罗斯海军研制的潜射弹道导弹，部署于新型955型北风之神级弹道导弹核潜艇。

wp_r-39=R-39,SS-N-20鲟鱼,潜射弹道导弹,R-39（北约代号：SS-N-20“鲟鱼”）是苏联的潜射弹道导弹，装备941型鲨鱼级（台风级）弹道导弹潜艇。这是一种大型三级固体燃料导弹，携带分导式多弹头。

# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------

# --------------- Torpedoes ---------------
wp_fizik-2=物理学家-2,匣子,鱼雷,“匣子”（物理学家-2）是俄罗斯的深水自导鱼雷，2017年起在俄罗斯海军服役，接替UGST（物理学家-1）。“匣子”采用线导，最高航速约50节，最大工作深度超过500米。

# ------------------ Bombs -----------------

wp_r-29rmu=R-29RMU
# ---------------- Sonobuoys ---------------


# ------------------ FFAR -----------------


# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------


# ----------- Noisemakers/Chaff -----------


# ----------------- Decoys ----------------

# ----------------- Special ----------------


# ----------------- Fueltanks ----------------
