[ ========================================= General ========================================== ]



############################################################
# RCS values
############################################################


##### Possible frequency bands (ITU => ECM):
# VHF-Band  => A-Band    100...300MHz
# UHF-Band  => B/C-Band: 300...1000MHz
# L-Band    => D-Band:     1...2GHz
# S-Band    => E/F-Band:   2...4GHz
# C-Band    => G-Band:     4...8GHz
# X-Band    => H/I-Band:   8...10GHz
# Ku-Band   => J-Band:    10...20GHz
# K-Band    => K-Band:    20...30GHz
# Ka-Band   => K-Band:    30...40GHz
#####

#Range Resolution = Rres = c/(2*PRF) where C = 3x10E8 and PRF = Pulse repetition frequency

############################################################
# IR Signature values
############################################################


[ =========================================== Test =========================================== ]
[ ========================================= Generic ========================================== ]
[ ------------------------ Visual/Infared ------------------------- ]
#For simplification LookDown mode works only for Air units or against Land Units.
#This means that elevated Land Unit will not have LookDown penalty while observing Vessels or Submarines (or Air units)

[---------- Aircraft Radars ----------]

[---------- Containers ----------]

[ ---------------------------- Sonars ----------------------------- ]
[---------- Surface ships ----------]
[FishFinderSonar]
#Generic low capability sonar. I used a Simrad SY50 as a reference point for some stats.
Kind=Sonar
HasDataLink=False                    // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=1.0                // TODO in degrees
RangeResolution=30.0                 // TODO defines the minimum range where two targets behind can be recognized as two; in meters
ActiveRange=2                        // in km
PassiveRange=4                       // in km
ActiveGain=10                        // in db, gain of the active sensor
Gain=10                              // in db, gain of the sensor
OutputPower=210                      // Active sensor output power in dB, unused for passive ones
Type=Hull                            //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF                    // TODO ????
ModuleType=SonarSensor

[NavSonar]
#Generic low capability sonar. Reminds me of Cold Waters Navigation Sonar.
Kind=Sonar
HasDataLink=False                    // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=1.0                // TODO in degrees
RangeResolution=30.0                 // TODO defines the minimum range where two targets behind can be recognized as two; in meters
ActiveRange=2                        // in km
PassiveRange=3                       // in km
ActiveGain=10                        // in db, gain of the active sensor
Gain=10                              // in db, gain of the sensor
OutputPower=210                      // Active sensor output power in dB, unused for passive ones
Type=Hull                            //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=MF                    // TODO ????
ModuleType=SonarSensor

[MineDetectorSonar]
#Generic low capability sonar. Meant to go on minesweepers or smth.
Kind=Sonar
HasDataLink=False                    // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=1.0                // TODO in degrees
RangeResolution=30.0                 // TODO defines the minimum range where two targets behind can be recognized as two; in meters
ActiveRange=2                        // in km
PassiveRange=2                       // in km
ActiveGain=10                       // in db, gain of the active sensor
Gain=10                              // in db, gain of the sensor
OutputPower=210                      // Active sensor output power in dB, unused for passive ones
Type=Hull                            //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=HF                    // TODO ????
ModuleType=SonarSensor

[---------------------------------------- ESM ----------------------------------------]
[ ---------- RWR ---------- ]

[[ ---------- Targeting ---------- ]


[ ---------- ELINT ---------- ]



[ ------------------------------ ECM ------------------------------ ]




[---------------------------------------- MAD ----------------------------------------]
[ASWTrawlerMAD]
#Users: civ_fv_aswtrawler
Kind=MAD
HasDataLink=True                     // true means the sensor data will be used for the entire task force via data link, false local use only
MaxDetectionRange=3.0                //in nm


[============================================ China ===========================================]
[ ---------------------------- Radars ----------------------------- ]
[---------- Surface ships ----------]
[---Air/Air&Surface---]

[---Surface only---]


[---Fire Control---] + search radars linked to FC radars






[---------- Submarines ----------]
[---Surface---]

[ ---------------------------- Sonars ----------------------------- ]
[---------- Surface ships ----------]







[---------- Submarines ----------]

[ ------------------------------ ESM ------------------------------ ]

[ ------------------------------ ECM ------------------------------ ]


[============================================ France ===========================================]
############################################################
# France
############################################################
[ ---------------------------- Radars ----------------------------- ]
[---------- Submarines ----------]
[---Surface---]
[ ---------------------------- Sonars ----------------------------- ]
[---------- Submarines ----------]

[ ------------------------------ ESM ------------------------------ ]


[ ------------------------------ ECM ------------------------------ ]


[============================================ Israel ===========================================]
############################################################
# Israel
############################################################
[ ---------------------------- Radars ----------------------------- ]
[---------- Surface ships ----------]
[---Air/Air&Surface---]


[---Surface only---]
[---Fire Control---] + search radars linked to FC radars


#SAM
#ASM
#Guns
#CIWS
[ ------------------------------ ESM ------------------------------ ]


[ ------------------------------ ECM ------------------------------ ]


[============================================ Japan ===========================================]
############################################################
# Japan
############################################################
[ ---------------------------- Radars ----------------------------- ]
[---------- Surface ships ----------]
[---Air/Air&Surface---]


[---Surface only---]


[---Fire Control---] + search radars linked to FC radars
#Guns


[---------- Submarines ----------]



[ ---------------------------- Sonars ----------------------------- ]
[---------- Ships ----------]


[---------- Submarines ----------]


[ ------------------------------ ESM ------------------------------ ]


[ ------------------------------ ECM ------------------------------ ]


[======================================== United States ========================================]
[ ------------------------ Visual/Infared ------------------------- ]


[ ---------------------------- Radars ----------------------------- ]
[---------- Surface ships ----------]
[---Air/Air&Surface---]

[---Surface only---]

[---Fire Control---] + search radars linked to FC radars
#SAM

#ASM

#Guns

#CIWS
[---------- Submarines ----------]


[ ------------------------ Aircraft Radars ------------------------- ]
[---------- Land units ----------]
[---Air/Air&Surface---]

[---Fire Control---] + search radars linked to FC radars


[ ---------------------------- Sonars ----------------------------- ]


[ASWTrawlerTowedArray] #Need setup
#Users: Anti-Sub Trawlers...I think
Kind=Sonar
HasDataLink=True                     // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=5.0                // TODO in degrees
RangeResolution=130.0                // TODO defines the minimum range where two targets behind can be recognized as two; in meters
#ActiveRange=15
PassiveRange=15                      // in km
Gain=22                              // in db, gain of the sensor
#OutputPower=220
Type=Towed                           //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF                    // TODO ????
ModuleType=SonarSensor

[---------- Submarines ----------]

[---------- Towed sonars ----------]

[---------- Dipping sonars ----------]


[---------- Sonobuoys ----------]
[---------------------------------------- ESM ----------------------------------------]

[ ------------------------------ ECM ------------------------------ ]
[---------------------------------------- MAD ----------------------------------------]
[---------------------------------------- Laser Designator ---------------------------]

[======================================== Soviet Union ========================================]
[ ------------------------ Visual/Infared ------------------------- ]

[ ---------------------------- Radars ----------------------------- ]
[---------- Surface ships ----------]
[---Air/Air&Surface---]




[---Surface only---]


[---Fire Control---] + search radars linked to FC radars
#SAM

#ASM

#Guns

#CIWS



[---------- Submarines ----------]

[---------- Land units ----------]
[---Air/Air&Surface---]

[---Surface only---]



[---Fire Control---] + search radars linked to FC radars
#SAM



[ ------------------------ Aircraft Radars ------------------------- ]
[---Air/Air&Surface---]
[[---Surface only---]

[ ---------------------------- Sonars ----------------------------- ]
[---------- Surface ships ----------]
[----- Towed/VDS -----]

[---------- Submarines ----------]

# -------------------- Towed --------------------

[---------- Aircraft ----------]
[---------- Sonobuoys ----------]
[ ------------------------ Visual/Infared ------------------------- ]
[---------------------------------------- ESM ----------------------------------------]
[ ---------- RWR ---------- ]
[ ---------- ELINT ---------- ]

[ ------------------------------ ECM ------------------------------ ]
[ ---------- DECM ---------- ]
[ ---------- OECM/Universal ---------- ]
[---------------------------------------- MAD ----------------------------------------]

[---------------------------------------- Laser Designator ---------------------------]

[======================================== Royal Navy ========================================]
[ ---------------------------- Radars ----------------------------- ]
[---------- Surface ships ----------]
[---Air/Air&Surface---]

[---Surface only---]
[---Fire Control---] + search radars linked to FC radars
#SAM
#ASM
#Guns
#CIWS
[---------- Submarines ----------]
[ ------------------------ Aircraft Radars ------------------------- ]
[ ---------------------------- Sonars ----------------------------- ]
[---------- Surface ships ----------]

[----- Towed/VDS -----]

[---------- Submarines ----------]
# -------------------- Hull --------------------
# -------------------- Towed --------------------
[---------- Aircraft ----------]
[---------- Sonobuoys ----------]
[---------------------------------------- ESM ----------------------------------------]

[ ------------------------------ ECM ------------------------------ ]
