

#######################   THAILAND   ##############################################

[tha_pb_m21]
Type=PB,Patrol Boat
Default=M21-class,M21
DefaultDescription=A class of fast patrol boats built for coastal defence and rapid response, the M21-class provides the Royal Thai Navy with a nimble and flexible platform for inshore operations. Lightly armed but capable of high speed, they are well-suited to interception, patrol, and maritime security tasks, operating effectively in the confined waters of the Gulf of Thailand.
Variant1=Tor.228,M21
Variant2=Tor.229,M21
Variant3=Tor.230,M21
Variant4=Tor.232,M21
Variant5=Tor.233,M21
Variant6=Tor.234,M21
Variant7=Tor.235,M21
Variant8=Tor.236,M21
Variant9=Tor.237,M21
Variant10=Tor.261,M21
Variant11=Tor.262,M21
Variant12=Tor.263,M21
Variant13=Tor.264,M21
Variant14=Tor.265,M21
Variant15=Tor.266,M21
Variant16=Tor.267,M21
Variant17=Tor.268,M21
Variant18=Tor.269,M21
Variant19=Tor.270,M21
Variant20=Tor.271,M21
Variant21=Tor.272,M21
Variant22=Tor.273,M21

[tha_pt_sattahip]
Type=PB,Patrol Boat
Default=Sattahip-class,Sattahip
DefaultDescription=The Sattahip-class entered Thai service in the early 1980s to strengthen coastal security. Modestly armed with a medium gun and light weapons, these vessels were designed for endurance and reliability rather than speed, making them well-suited for routine patrol, surveillance, and maritime security duties in the Gulf of Thailand.
Variant1=HTMS Sattahip 521,Sattahip 
Variant2=HTMS Klongyai 522,Klongyai 
Variant3=HTMS Takbai 523,Takbai 
Variant4=HTMS Katang 524,Katang 
Variant5=HTMS Thepa 525,Thepa
Variant6=HTMS Thai Muang 526,Thai Muang 


[tha_pt_hua_hin]
Type=PB,Patrol Boat
Default=Hua Hin-class,Hua Hin
DefaultDescription=The Hua Hin class is a series of three patrol gunboats operated by the Royal Thai Navy (RTN). Designed for surveillance of Thailand's Exclusive Economic Zone (EEZ) and maritime law enforcement, these vessels were commissioned between 2002 and 2004. They are considered large patrol boats or offshore patrol vessels (OPV) based on a modified Khamronsin-class design.
Variant1=HTMS Hua Hin 541,Hua Hin
Variant2=HTMS Klaeng 542,Klaeng
Variant3=HTMS Si Racha 543,Si Racha


[tha_pt_chonburi]
Type=PB,Patrol Boat
Default=Chonburi-class,Chonburi
DefaultDescription=The Chonburi class patrol craft were built by the Italian shipyard, Cantiere Navale Breda, and were designed to be fast and maneuverable, these ships were armed with a variety of weapons, including two 76 mm guns, one 40 mm/70 caliber gun, and two 12.7 mm machine guns.
Variant1=HTMS Chonburi 331,Chonburi 
Variant2=HTMS Songkla 332,Songkla


[tha_ptg_prabrarapak]
Type=PTG,Missile Boat
Default=Prabrarapak-class,Prabrarapak
DefaultDescription=The Prabparapak-class is a group of three missile-armed fast attack craft (FAC) operated by the Royal Thai Navy. Built in the 1970s by Singapore Shipbuilding & Engineering, they are based on the Sea Wolf class design from Singapore.
Variant1=HTMS Prabrarapak 311,Prabrarapak
Variant2=HTMS Hanhak Sattru 312,Hanhak Sattru
Variant3=HTMS Suphairin 313,Suphairin


[tha_ptg_ratcharit]
Type=PTG,Missile Boat
Default=Ratcharit-class,Ratcharit
DefaultDescription=The Ratcharit class consists of three fast attack missile craft (FAC-M) that served in the Royal Thai Navy (RTN) for over 40 years. Built in Italy by Cantiere Navale Breda, these 270-ton vessels were designed to provide potent anti-surface strike capabilities in coastal waters using MM38 Exocet missiles.
Variant1=HTMS Ratcharit 321,Ratcharit
Variant2=HTMS Witthayakom 322,Witthayakom
Variant3=HTMS Udomet 323,Udomet


[tha_fs_tapi]
Type=FS,Corvette
Default=Tapi-class,Tapi
DefaultDescription=The Tapi-class corvettes marked a major step forward in the Royal Thai Navy’s evolution from coastal defence to a more capable, multi-role maritime force.
Built in the United States in the early 1970s, these ships were based on a patrol frigate design and tailored for Thailand’s growing need to secure its Exclusive Economic Zone and maintain a sustained presence in the Gulf of Thailand.
Variant1=HTMS Tapi 431,Tapi
Variant2=HTMS Khirirat 432,Khirirat


[tha_fs_khamronsin]
Type=FS,Corvette
Default=Khamronsin-class,Khamronsin
DefaultDescription=The Khamronsin-class corvettes are three corvettes constructed for the Royal Thai Navy in the late 1980s. Based on a British design, all three ships were built in Thailand. A fourth vessel, constructed to a modified design, was built for the Thai Police and was the first to enter service in 1992. The three Khamrosin-class corvettes commissioned in 1992 and remain in service.
Variant1=HTMS Kamronsin 531,Kamronsin
Variant2=HTMS Thayanchon 532,Thayanchon
Variant3=HTMS Longlom 533,Longlom

[tha_fs_ratanakosin]
Type=FS,Corvette
Default=Ratanakosin-class,Ratanakosin
DefaultDescription=The Ratanakosin-class corvettes are a class of two corvettes based on the Saudi Arabian Badr-class design that were built for the Royal Thai Navy in the 1980s. Constructed by Tacoma Boatbuilding Company in the United States, a third was planned to be built in Thailand but was canceled before construction could begin. The Ratanakosin class is used as flagships for squadrons of fast attack craft.
Variant1=HTMS Ratanakosin 441,Ratanakosin
Variant2=HTMS Sukhothai 442,Sukhothai


[tha_ff_cannon]
Type=FF,Frigate
Default=Cannon-class,Cannon
DefaultDescription=Forming the backbone of the Royal Thai Navy in the 1960s, these ex-American escorts—drawn from the Cannon-class destroyer escort and Tacoma-class patrol frigate—provided Thailand with its first true multi-role surface combatants.
Variant1=HTMS Pin Klao,Pin Klao
Variant2=HTMS Prasae,Prasae
Variant3=HTMS Tachin,Tachin


[tha_ff_makut_rajakumarn]
Type=FF,Frigate
Default=Makut Rajakumarn-class,Makut Rajakumarn
DefaultDescription=HTMS Makut Rajakumarn is a frigate operated by the Royal Thai Navy. The ship was built by Yarrow Shipbuilders in Glasgow, Scotland 1971. The ship entered service in 1973 and was modernised in 1988.
Variant1=HTMS Makut Rajakumarn 433,Makut Rajakumarn


[tha_ff_makut_rajakumarn_88]
Type=FF,Frigate
Default=Makut Rajakumarn-class,Makut Rajakumarn
DefaultDescription=HTMS Makut Rajakumarn is a frigate operated by the Royal Thai Navy. The ship was built by Yarrow Shipbuilders in Glasgow, Scotland 1971. The ship re-entered service in 1988 after being modernised and is currently in service as a training ship.
Variant1=HTMS Makut Rajakumarn 433,Makut Rajakumarn


[tha_ff_knox_84]
Type=FF,Frigate
Default=Phutthayotfa Chulalok-class,Phutthayotfa Chulalok
DefaultDescription=In the Royal Thai Navy (RTN), the Knox-class frigates—locally designated as the Phutthayotfa Chulalok-class—served as the fleet's primary anti-submarine warfare (ASW) backbone for over two decades. It carried the AB-212 helicopter, which required the hangar to be enlarged.
Variant1=HTMS Phutthaloetla Naphalai FFG 461,Phutthaloetla Naphalai
Variant2=HTMS Phutthayotfa Chulalok FFG 462,Phutthayotfa Chulalok


[tha_ff_053HT]
Type=FF,Frigate
Default=Chao Phraya-class,Chao Phraya
DefaultDescription=Chao Phraya is the lead ship of her class of frigates for the Royal Thai Navy, a variant of the Chinese-built Type 053H2 frigate.
Variant1=HTMS Chao Phraya 455,Chao Phraya
Variant2=HTMS Bangpakong 456,Bangpakong


[tha_ff_053HT_H]
Type=FF,Frigate
Default=Chao Phraya-class,Chao Phraya
DefaultDescription=A sub variant of the Chao Phraya-class, the ship was armed at launch with one 100 mm/56 Type 79 twin-barreled gun and four 37 mm Type 76 twin-barreled guns. For anti-submarine warfare, the ship was equipped with two Type 86 anti-submarine rocket launchers and a helicopter deck at the rear.
Variant1=HTMS Kraburi 457,Kraburi
Variant2=HTMS Saiburi 458,Saiburi


[tha_ffg_naresuan]
Type=FFG,Frigate
Default=Naresuan-class,Naresuan
DefaultDescription=The Naresuan-class frigate is an enlarged modified version of the Chinese-made Type 053 frigate with Western weaponry, cooperatively designed by the Royal Thai Navy and built in China.
Variant1=HTMS Naresuan 421,Naresuan
Variant2=HTMS Taksin 422,Taksin


[tha_cvl_chakri_naruebet]
Type=CVL,Light Carrier
Default=Chakri Naruebet-class,Chakri Naruebet
DefaultDescription=HTMS Chakri Naruebet (911) is the flagship of the Royal Thai Navy, and Thailand's first and only aircraft carrier, although the RTN refers to her as an "Offshore Patrol Helicopter Carrier". Based on the Spanish Navy's Príncipe de Asturias design and constructed by Spanish shipbuilder Bazán, Chakri Naruebet was ordered in 1992, laid down in 1994, launched in 1996, and commissioned into the RTN in 1997. The ship is the smallest functioning aircraft carrier in the world (currently only operates helicopters and drones).
Variant1=HTMS Chakri Naruebet 911,Chakri Naruebet

[tha_aor_chula]
Type=AKL,Fleet Auxiliary
Default=Chula-class,Chula
DefaultDescription=The Chula class (often referred to as the Jula class or Jula II-class) consists of small auxiliary tankers designed for coastal oiler duties within the Royal Thai Navy. The lead ship, HTMS Chula (831), has been a long-serving asset but is currently approaching the end of its operational life.
Variant1=HTMS Chula 831,Chula
Variant2=HMTS Matra 836,Matra

[tha_lst_sichang]
Type=LST,Landing Ship
Default=Sichang class,Sichang
DefaultDescription=The Sichang class (Type PS700) is a group of two medium tank landing ships (LST) operated by the Royal Thai Navy. Based on a French design, these vessels transport marines, vehicles, and heavy equipment directly onto shores during beach landings or humanitarian missions.
Variant1=HTMS Sichang 721,Sichang
Variant2=HTMS Surin 722,Surin
