[AmmunitionNames]
# ------------------ AAM ------------------
# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------
# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

# ---------- Anti-sub  Missilies ----------
ods_emad=Emad,emad_launcher,Ballistic Missiles,Originally named EMAD , Emad is an Iranian-designed, liquid-fuel, medium-range ballistic missile (MRBM), a derivative of the Shahab-3
# ------------------ RBU ------------------
# --------------- Torpedoes ---------------
# ------------------ Bombs -----------------
# ---------------- Sonobuoys ---------------
# ------------------ FFAR -----------------
# ------------------ MLRS -----------------
# ------------------ Guns -----------------
# ------------------ CIWS -----------------
# ----------- Noisemakers/Chaff -----------
# ----------------- Decoys ----------------
# ----------------- Special ----------------
# ----------------- Fueltanks ----------------
