[General]
SerialnumberReferences=Numbers_Modex
EmblemReference=Emblem_A
NationFlagReference=Flag1
NumberOfSquadrons=1

[Default]
ResourcesSerialnumberFolder=
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=assets/models/aircraft/h6kn/Emblem/
EmblemTexture=h6kn_modex_a.png
ResourcesLiveryFolder=assets/models/aircraft/h6kn/textures
LiveryTexture=pla_h6kn_MainTex.png
SpecularTexture=pla_h6kn_SpecTex.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_china
# nations are referenced in the layout.ini file:
Nation=China
ServiceDate=2018

[Squadron1]
ResourcesSerialnumberFolder=assets/models/aircraft/h6kn/numbers/
SerialNumberPrefix=
SerialnumberTextures=h6_41270.png,h6_41271.png,h6_41272.png,h6_41273.png,h6_41274.png,h6_41275.png,h6_41276.png,h6_41277.png,h6_41278.png,h6_41279.png
ResourcesEmblemFolder=assets/models/aircraft/h6kn/Emblem/
EmblemTexture=h6kn_modex_a.png
ResourcesLiveryFolder=assets/models/aircraft/h6kn/textures
LiveryTexture=pla_h6kn_MainTex.png
SpecularTexture=pla_h6kn_SpecTex.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_china
# nations are referenced in the layout.ini file:
Nation=China