[---------- General Data ----------]

#------------ 生成弹药的侧视图
[General]
UnitType=Aircraft
HideIn=Encyclopedia,Signatures
DefaultCameraDistance=1
MinCameraDistanceForeAft=0.36
MinCameraDistanceBroadside=0.36
CameraPivotHeight=0.0

#Taxi values
GroundedPitchAngle=-1  // 这个角度是降落时地面的俯仰角（x）
GroundPivot=0,-0.0265,0.018816 // 主轮之间的点，起飞落地抬轮的参考点

Pilot1=wp_pilot_a                      // 飞行员调用，在ammunition里
Pilot1Positions=0,0.010982,0.099698        // 飞行员位置
EjectChance=0.6                        
        // 弹射机会

[AI]
Role=Fighter                     //脚本
// 目前种类有：Fighter、Bomber、HeavyBomber、SEAD、Recon、EW、ESM、Transport、MPA、AEW、ASW、ASuW、Attack、Airliner

[SensorData]
#Visual
VisualIdentificationRange=5.7       // Biggest range in nm at which this unit can be visually identified
IRSignature=SemiSmall
# Radar related (RCS => radar cross section)
RCS=10

[Animations]
NumberOfAnimationReferences=1
AnimationFile_1=animations_plaaf_j-7Ⅱ

[---------- Flight Model ----------]
[Engine]
EngineIntakeArea=0.6

[FlightModel]
PitchGain=0.25                        // Vertical manuverability
VelocityGain=0.1136                   // Acceleration
HeadingGain=2                         // Horizontal manuverability
YawRateLimit=130                      // in degrees per second

BankGain=1.5                          // Roll change speed
#MaxRollForHeading=55.0                // bank limit in normal flight
MaxRollRate=230.0                      // in degrees per second
MaxPitchRate=25

ThrustGain=0.352                      // Thrust change speed
SpeedBrakeFractionGain=10            // Speed brakes deploy speed

SpeedDeltaPerAltitudeChange=0.0885

[Performance]
#Dimensions
WingSpan=8.32                         //meters
#Parameters
MaxG=8.7                             // Mostly for horizontal turns

MaxClimbRate=195                      //Meters per second
EmptyMass=5292                      // in kg, dry empty weight
MaxFuel=1926                       // in kg, internal

PerEngineMaxThrust=46000              //Newtons
EngineCount=2
EngineWarmUp=15

Ceiling=60000                         // ceiling in feet
CruiseAltitude=36000                //in feet
#"Engine" efficiency at 0ft, 37000 ft, 65000 ft. Always 1 for cruise altitude
AltitudeEfficiency=0.5,0.5,0.25       // Defines fuel consumption with altitude

#Governing of max speed
MaxSpeedAtSeaLevel=670                //in knots, Defines max speed at altitude curve
StallSpeed=102                     //in knots
MachLimit=1.78                         //for 37000ft, Defines max speed at altitude curve

#SpeedAndRange   MachNumbers or knots, Specified units or multiplier (except Cruise range)
RangeUnits=Miles                      // Can be: Km. Any other value = nmi. Defines measurment units of ranges of SpeedAndRange values

SpeedAndRange_Landing=0.25,0.4        // Landing
SpeedAndRange_Loiter=0.4,0.6         // Loiter
SpeedAndRange_Cruise=0.86,925         // Cruise
SpeedAndRange_Max=1.2,0.8             // Attack/Fast/High/Max without AB
SpeedAndRange_Afterburner=1.6,0.2     // AB max

Altitudes=200,1000,3000,6000,10000,20000  // in feet
[---------- Main Systems ----------]
[FlightControls]
NumberOfAilerons=2
Aileron1_Model=aileron_l
Aileron1_MinAngle=-20.0
Aileron1_MaxAngle=20.0
Aileron1_RotationAxis=X

Aileron2_Model=aileron_r
Aileron2_MinAngle=-20.0
Aileron2_MaxAngle=20.0
Aileron2_RotationAxis=X

NumberOfElevons=2
Elevon1_Model=elevator_l
Elevon1_MinAngle=-20.0
Elevon1_MaxAngle=20.0
Elevon1_RotationAxis=X

Elevon2_Model=elevator_r
Elevon2_MinAngle=-20.0
Elevon2_MaxAngle=20.0
Elevon2_RotationAxis=X

NumberOfRudders=1
Rudder1_Model=rudder
Rudder1_MinAngle=-30.0
Rudder1_MaxAngle=30.0

[---------- Sensor Systems ----------]
[SensorSystems]
NumberOfSensorSystems=3

[SensorSystem1] #Cockpit
# Cockpit
Type=Visual
SystemName=Eyes
Mount=Dummy
ViewArcs=-170,170|-20,91
ModuleType=Sensor

[SensorSystem2] #Type_266
Type=Radar
SystemName=Type_266
Mount=Dummy
ModuleType=Sensor

#---------- ESM ----------
[SensorSystem3] #RWR
Type=ESM
SystemName=AircraftRWR
Mount=Dummy
ModuleType=Sensor

[---------- Weapon Systems ----------]
[WeaponSystems]
NumberOfWeaponSystems=3
AvailableLoadouts=Default

[WeaponSystem1] #Hardpoint
Type=Hardpoint
SystemName=Hardpoint
NumberOfStations=1

Station1=-0,0,0    //Left Wing pylon

ModuleType=Weapon

[--------------------------- Loadouts ---------------------------]
#--------------- Standart --------------
[WeaponSystem1Empty]

[WeaponSystem1Ferry]

[WeaponSystem1Default]
Station1=plan_yu-12_ship
	
[--------------------------- Mesh definitions ---------------------------]
[Models]
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=assets/pyl/
ResourcesRoot=clean_pyl.obj
ResourcesMesh=hull

############################################################
NumberOfDamageModels=1
DamageModel1=hull_d1
############################################################
[Submodels]
############################################################
#---------- Modex ----------


############################################################
#N/A
[---------- Effects ----------]
[Particles]
ShotDownFireEffect=effects/aircraft_kill_effects/usaf_f-15c_kill
ShotDownFireEffectPosition=0,0,0
HitWaterEffect=effects/splashes/emitters/splash_bomb
HitGroundEffect=effects/explosions/emitters/aircraft_hit_ground
HitAirEffectClass=LargeMissileExplosions
ExhaustSmoke=aircraft/particles/usaf_f-15c_smokeemitter
TipVortexPosition=0.096,0.004,0.03
TipVortex=effects/aircraft/emitters/tipvortex
LeftWingVortexPosition=0,-0.01,0.02
LeftWingVortex=effects/aircraft/emitters/wingvortex_f-15_left
RightWingVortexPosition=0,-0.01,0.02
RightWingVortex=effects/aircraft/emitters/wingvortex_f-15_right
ShockConePosition=0,-0.01,0.02
ShockCone=effects/aircraft/emitters/shockcone

[Sounds]
############################################################
# Sounds
############################################################
# possible sound modes:
# 1: simple
# 2: near/far
# 3: near/far with aspect
SoundMode=3
# Front
EngineAudioClip=audio/aircraft/TF30
EngineAudioPosition=0,0,0
EngineAudioRollOff=Logarithmic
EngineAudioDistance=1,20
EngineAudioPitchRange=1.0,2.4
EngineAudioVolumeRange=0.1,0.5
# Rear
ExhaustAudioClip=audio/aircraft/jet_rear_1
ExhaustAudioPosition=0,0,0
ExhaustAudioRollOff=Logarithmic
ExhaustAudioDistance=1,20
ExhaustAudioPitchRange=0.6,1.0
ExhaustAudioVolumeRange=0.75,1.0
# Far
FarAudioClip=audio/aircraft/jet_far_1
FarAudioPosition=0,0,0
FarAudioRollOff=Logarithmic
FarAudioDistance=5,20
FarAudioPitch=1.0
FarAudioVolume=1.0
FarAudioFadeRange=0.0,0.15	      // nautical miles min/max
# Afterburner
AfterburnerAudioClip=audio/aircraft/afterburner_f-15
AfterburnerAudioPosition=0,0,0
AfterburnerAudioRollOff=Logarithmic
AfterburnerAudioDistance=1,20
AfterburnerAudioPitch=1.0
AfterburnerAudioVolume=1.0
# Gears
#GearsAudioClip=audio/aircraft/gears
GearsAudioClip=audio/aircraft/LandingGearRetraction_v1
GearsAudioPosition=0,0,0
GearsAudioRollOff=Logarithmic
GearsAudioDistance=1,20
GearsAudioPitch=1.0
GearsAudioVolume=1.0
# Flaps
#FlapsAudioClip=audio/aircraft/flaps
FlapsAudioClip=audio/aircraft/LandingGearRetraction_v1
FlapsAudioPosition=0,0,0
FlapsAudioRollOff=Logarithmic
FlapsAudioDistance=1,20
FlapsAudioPitch=1.0
FlapsAudioVolume=1.0

//Front Sound = audio/aircraft/JE_Front_3 v=0.25, p=1.2
//Rear	Sound = audio/aircraft/JE_Burner_2
//Far	Sound = audio/aircraft/JetExhaustLoop p=0.75
//Afterburner = audio/aircraft/AfterburnerLarge_v1 p=0.75

[---------- Colliders ----------]
############################################################
# Colliders definition
############################################################
[Colliders]
# creates the hit boxes for this object
NumberOfColliders=3
Collider1=coll_body
Collider2=coll_body2
Collider3=coll_wings

[coll_body]
Collider=Box
Position=0,0,0.062
Rotation=0,0,0
Scale=0.023,0.028,0.18

[coll_body2]
Collider=Box
Position=0,-0.01,-0.01
Rotation=0,0,0
Scale=0.05,0.02,0.16

[coll_wings]
Collider=Box
Position=0,0,-0.013
Rotation=0,0,0
Scale=0.17,0.007,0.058