[ ========================================= General ========================================== ]





[r-500ecm]
#Users: wp_taifun_ew
Kind=ECM
Frequencies=UHF-Band,L-Band,S-Band,C-Band,X-Band,Ku-Band //radar frequency bands the ECM suite can jam
Type=Universal                      // can be Defensive, Offensive, Universal
PeakPower=20.0                      // output peak power in kW, more power increase effectivness of offensive ECM jammers
MaxRange=5.0                       // max range in km
Gain=15.0                            // Offensive ECM jammer gain in db, more -> better
JamConeViewArcs=360               // For offensive and universal systems. Defines the cone along axis between a radar and the ECM system. Targets inside this cone is "covered" by jamming
JamChance=0.45   