[AmmunitionNames]
# ------------------ AAM ------------------

# ------------------ SAM ------------------

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

wp_9m14=AT-3,Sagger,ATGM,
wp_9m113=AT-5,Spandrel,ATGM,
uk_milan-1=MILAN-1,,ATGM

# ---------- Anti-sub  Missilies ----------

# ------------------ RBU ------------------

# --------------- Torpedoes ---------------

# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

wp_3ubr8=3UBR8,,AP
wp_pg-15v=PG-15V,HEAT,
wp_og-15v=OG-15V,HE,
uk_cal_30x170_apds-t=30mm APDS-T,AP,
brd_cal_dm63=DM63,APDS,
# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# Depth charge

# ----------------- Fueltanks ----------------


