[Animations]
NumberOfAnimations=16

Animation1=Wings_Fold
Animation2=Wings_Extend
Animation3=Flaps_Takeoff
Animation4=Flaps_Takeoff_Retract
Animation5=Flaps_Landing
Animation6=Flaps_Landing_Retract
Animation7=Gear_Extend
Animation8=Gear_Retract
Animation11=Hook_Deploy
Animation12=Hook_Retrieve
Animation13=Canopy_Extend
Animation14=Canopy_Retract

[Canopy_Extend]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Open
Sequence1_Model=Canopy

[Canopy_Retract]
NumberOfSequencesToPlay=1
Sequence1=Canopy_Close
Sequence1_Model=Canopy

[Wings_Fold]
NumberOfSequencesToPlay=2
Sequence1=Left_Wing_Fold
Sequence1_Model=tip_l
Sequence2=Right_Wing_Fold
Sequence2_Model=tip_r

[Wings_Extend]
NumberOfSequencesToPlay=2
Sequence1=Left_Wing_Spread
Sequence1_Model=tip_l
Sequence2=Right_Wing_Spread
Sequence2_Model=tip_r


[Flaps_Takeoff]
NumberOfSequencesToPlay=7
Sequence1=Flap_Takeoff
Sequence1_Model=flap_l
Sequence2=Flap_Takeoff
Sequence2_Model=flap_r
Sequence3=Wing_Takeoff
Sequence3_Model=wing

Sequence4=Slat_deploy
Sequence4_Model=slat_l
Sequence5=Slat_deploy
Sequence5_Model=slat_r
Sequence6=Slat_deploy
Sequence6_Model=tip_slat_l
Sequence7=Slat_deploy
Sequence7_Model=tip_slat_r


[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=7
Sequence1=Flap_Takeoff_Retract
Sequence1_Model=flap_l
Sequence2=Flap_Takeoff_Retract
Sequence2_Model=flap_r
Sequence3=Wing_Takeoff_Retract
Sequence3_Model=wing

Sequence4=Slat_retract
Sequence4_Model=slat_l
Sequence5=Slat_retract
Sequence5_Model=slat_r
Sequence6=Slat_retract
Sequence6_Model=tip_slat_l
Sequence7=Slat_retract
Sequence7_Model=tip_slat_r

[Flaps_Landing]
NumberOfSequencesToPlay=7
Sequence1=Flap_Takeoff
Sequence1_Model=flap_l
Sequence2=Flap_Takeoff
Sequence2_Model=flap_r
Sequence3=Wing_Takeoff
Sequence3_Model=wing

Sequence4=Slat_deploy
Sequence4_Model=slat_l
Sequence5=Slat_deploy
Sequence5_Model=slat_r
Sequence6=Slat_deploy
Sequence6_Model=tip_slat_l
Sequence7=Slat_deploy
Sequence7_Model=tip_slat_r

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=7
Sequence1=Flap_Takeoff_Retract
Sequence1_Model=flap_l
Sequence2=Flap_Takeoff_Retract
Sequence2_Model=flap_r
Sequence3=Wing_Takeoff_Retract
Sequence3_Model=wing

Sequence4=Slat_retract
Sequence4_Model=slat_l
Sequence5=Slat_retract
Sequence5_Model=slat_r
Sequence6=Slat_retract
Sequence6_Model=tip_slat_l
Sequence7=Slat_retract
Sequence7_Model=tip_slat_r

[Gear_Extend]
NumberOfSequencesToPlay=20
Sequence1=Nose_Gear_Down
Sequence1_Model=nose_gear_up
Sequence2=Nose_Gear_Down
Sequence2_Model=nose_gear
Sequence3=Nose_Gear_Hatch_L_Down
Sequence3_Model=nose_gear_hatch_l
Sequence4=Nose_Gear_Hatch_R_Down
Sequence4_Model=nose_gear_hatch_r
Sequence5=Nose_Gear_Hatch_F_Down
Sequence5_Model=nose_gear_hatch_f
Sequence6=gear_up_Down
Sequence6_Model=gear_up
Sequence7=gear_r_Down
Sequence7_Model=gear_r
Sequence8=gear_l_Down
Sequence8_Model=gear_l

Sequence11=right_hatch_u_Down
Sequence11_Model=main_door_r
Sequence12=right_hatch_d_Down
Sequence12_Model=main_door_rd
Sequence13=right_hatch_a_Down
Sequence13_Model=main_door_ra
Sequence14=left_hatch_u_Down
Sequence14_Model=main_door_l
Sequence15=left_hatch_d_Down
Sequence15_Model=main_door_ld
Sequence16=left_hatch_a_Down
Sequence16_Model=main_door_la



[Gear_Retract]
NumberOfSequencesToPlay=20
Sequence1=Nose_Gear_Up
Sequence1_Model=nose_gear_up
Sequence2=Nose_Gear_Up
Sequence2_Model=nose_gear
Sequence3=Nose_Gear_Hatch_L_Up
Sequence3_Model=nose_gear_hatch_l
Sequence4=Nose_Gear_Hatch_R_Up
Sequence4_Model=nose_gear_hatch_r
Sequence5=Nose_Gear_Hatch_F_Up
Sequence5_Model=nose_gear_hatch_f
Sequence6=gear_up_Up
Sequence6_Model=gear_up
Sequence7=gear_r_Up
Sequence7_Model=gear_r
Sequence8=gear_l_Up
Sequence8_Model=gear_l

Sequence11=right_hatch_u_Up
Sequence11_Model=main_door_r
Sequence12=right_hatch_d_Up
Sequence12_Model=main_door_rd
Sequence13=right_hatch_a_Up
Sequence13_Model=main_door_ra
Sequence14=left_hatch_u_Up
Sequence14_Model=main_door_l
Sequence15=left_hatch_d_Up
Sequence15_Model=main_door_ld
Sequence16=left_hatch_a_Up
Sequence16_Model=main_door_la

[Hook_Deploy]
NumberOfSequencesToPlay=1
Sequence1=Hook_Extend
Sequence1_Model=hook


[Hook_Retrieve]
NumberOfSequencesToPlay=1
Sequence1=Hook_Retract
Sequence1_Model=hook

####################### Sequences ############################
[Canopy_Open]
NumberOfSteps=2
Step1=0|x,y,z|0,y,z|EaseInOut
Step2=5|x,y,z|-60,y,z|EaseInOut

[Canopy_Close]
NumberOfSteps=2
Step1=0|x,y,z|-60,y,z|EaseInOut
Step2=5|x,y,z|0,y,z|EaseInOut


[Left_Wing_Fold]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=10 
RotationZ2=-90
Smoothness2=EaseInOut

[Left_Wing_Spread]
NumberOfSteps=2
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=10 
RotationZ2=0
Smoothness2=EaseInOut

[Right_Wing_Fold]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=10 
RotationZ2=90
Smoothness2=EaseInOut

[Right_Wing_Spread]
NumberOfSteps=2
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=10 
RotationZ2=0
Smoothness2=EaseInOut

[Wing_Takeoff]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=1
RotationX2=-8
Smoothness2=EaseInOut

[Flap_Takeoff]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=1
RotationX2=-30
Smoothness2=EaseInOut

[Slat_deploy]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=1
RotationZ2=30
Smoothness2=EaseInOut

[Slat_retract]
NumberOfSteps=2
Time1=0 
RotationZ1=30
Smoothness1=EaseInOut
Time2=1
RotationZ2=0
Smoothness2=EaseInOut


[Wing_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-8	
Smoothness1=EaseInOut
Time2=1 
RotationX2=0
Smoothness2=EaseInOut

[Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-30	
Smoothness1=EaseInOut
Time2=1 
RotationX2=0
Smoothness2=EaseInOut

[Flap_Landing]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=2
RotationX2=-8
Smoothness2=EaseInOut

[Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-8	
Smoothness1=EaseInOut
Time2=2 
RotationX2=0
Smoothness2=EaseInOut

[Nose_Gear_Down]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=2 
RotationX1=0
Smoothness2=EaseInOut
Time2=5
RotationX2=-47.5

[Nose_Gear_Up]
NumberOfSteps=2
Time1=0
RotationX1=-47.5
Smoothness1=EaseInOut
Time2=3
RotationX2=0
Smoothness2=EaseInOut

[Nose_Gear_Hatch_L_Down]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=0
RotationZ1=0
Smoothness2=EaseInOut
Time2=2
RotationZ2=-90

[Nose_Gear_Hatch_L_Up]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=3
RotationZ1=-90
Smoothness2=EaseInOut
Time2=5
RotationZ2=0

[Nose_Gear_Hatch_R_Down]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=0
RotationZ1=0
Smoothness2=EaseInOut
Time2=2
RotationZ2=90

[Nose_Gear_Hatch_R_Up]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=3
RotationZ1=90
Smoothness2=EaseInOut
Time2=5
RotationZ2=0

[Nose_Gear_Hatch_F_Down]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=0
RotationX1=0
Smoothness2=EaseInOut
Time2=2
RotationX2=-90

[Nose_Gear_Hatch_F_Up]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=3
RotationX1=-90
Smoothness2=EaseInOut
Time2=5
RotationX2=0

[gear_up_Down]
NumberOfSteps=2
Time1=0.5
RotationX1=0
Smoothness1=EaseInOut
Time2=6
RotationX2=50
Smoothness2=EaseInOut

[gear_up_Up]
NumberOfSteps=2
Time1=0
RotationX1=50
Smoothness1=EaseInOut
Time2=5.5
RotationX2=0
Smoothness2=EaseInOut

[gear_r_Down]
NumberOfSteps=2
Time1=0.5
RotationY1=0
Smoothness1=EaseInOut
Time2=6
RotationY2=62
Smoothness2=EaseInOut

[gear_r_Up]
NumberOfSteps=2
Time1=0
RotationY1=62
Smoothness1=EaseInOut
Time2=5.5
RotationY2=0
Smoothness2=EaseInOut

[gear_l_Down]
NumberOfSteps=2
Time1=0.5
RotationY1=0
Smoothness1=EaseInOut
Time2=6
RotationY2=-62
Smoothness2=EaseInOut

[gear_l_Up]
NumberOfSteps=2
Time1=0
RotationY1=-62
Smoothness1=EaseInOut
Time2=5.5
RotationY2=0
Smoothness2=EaseInOut

[right_hatch_u_Down]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=0
RotationZ1=0
Smoothness2=EaseInOut
Time2=4
RotationZ2=70

[right_hatch_u_Up]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=3
RotationZ1=70
Smoothness2=EaseInOut
Time2=7
RotationZ2=0

[right_hatch_d_Down]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=0
RotationZ1=0
Smoothness2=EaseInOut
Time2=4
RotationZ2=-90

[right_hatch_d_Up]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=3
RotationZ1=-90
Smoothness2=EaseInOut
Time2=7
RotationZ2=0

[right_hatch_a_Down]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=0
RotationZ1=0
Smoothness2=EaseInOut
Time2=4
RotationZ2=-90

[right_hatch_a_Up]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=3
RotationZ1=-70
Smoothness2=EaseInOut
Time2=7
RotationZ2=0

[left_hatch_u_Down]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=0
RotationZ1=0
Smoothness2=EaseInOut
Time2=4
RotationZ2=-70

[left_hatch_u_Up]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=3
RotationZ1=-70
Smoothness2=EaseInOut
Time2=7
RotationZ2=0

[left_hatch_d_Down]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=0
RotationZ1=0
Smoothness2=EaseInOut
Time2=4
RotationZ2=90

[left_hatch_d_Up]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=3
RotationZ1=90
Smoothness2=EaseInOut
Time2=7
RotationZ2=0

[left_hatch_a_Down]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=0
RotationZ1=0
Smoothness2=EaseInOut
Time2=4
RotationZ2=70

[left_hatch_a_Up]
NumberOfSteps=2
Smoothness1=EaseInOut
Time1=3
RotationZ1=70
Smoothness2=EaseInOut
Time2=7
RotationZ2=0

[Hook_Extend]
NumberOfSteps=3
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=2 
RotationX2=0
Smoothness2=EaseInOut
Time3=5 
RotationX3=-45
Smoothness3=EaseInOut

[Hook_Retract]
NumberOfSteps=3
Time1=0 
RotationX1=-45
Smoothness1=EaseInOut
Time2=2 
RotationX2=-45
Smoothness2=EaseInOut
Time3=5 
RotationX3=0
Smoothness3=EaseInOut

