[General]
Type=Container                       // can be Projectile, Missile, RBU, ASROC, Torpedo,AerialRocket,MLRS
Mass=136                                    // in kg. Used for aircraft. Container mass. Weapon mass is read from weapon ini

[Ammunition]
Ammunition=rn_rp_3_sap

NumberOfAttachments=4
AttachmentPosition1=0.00635,0,-0.001
AttachmentPosition2=0.002,0,-0.001
AttachmentPosition3=0.00635,-0.0022,0.0022
AttachmentPosition4=0.002,-0.002,0.0022

SalvoFireAmount=8                       // number of shots fired

[---------- Mesh definitions----------]
############################################################
# Main Model with collider
############################################################
[Models]
############################################################
# AssetBundle related
############################################################
AssetBundleMeshes=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMaterials=/AssetBundles/StandaloneWindows/aircraft
AssetBundleMesh=usn_rim-7
AssetBundleDamagedMesh=
AssetBundleMaterial=usn_rim-7_mat
AssetBundleMeshHullCollider=usn_rim-7_coll
############################################################
############################################################
# Internal Resources folder related
############################################################
ResourcesFolder=aircraft/fr_aquilon_202/
ResourcesRoot=fr_aquilon_202.obj
ResourcesMesh=Rocket_pylons_l
ResourcesMaterial=fr_aquilon_202_mat.ini
