[============================== Cargo Groups ==============================]
[CargoVariants]

# ++++++++++++++++++++++++++++++ Military Vehicles ++++++++++++++++++++++++++++++
# --------------------------------- NATO ---------------------------------
#  ----------US Army Cargo and Vehicles ----------
1968MilitaryCargo_USN_Slot_1x2=cargo_wp_1x2_3,cargo_wp_1x2_4,cargo_wp_1x2_1

1968MilitaryCargo_USN_Slot_2x1=cargo_usn_2x1_1,cargo_usn_2x1_2,cargo_usn_2x1_3,cargo_usn_2x1_7,cargo_usn_2x1_8,cargo_usn_2x1_9,cargo_usn_2x1_10

1968MilitaryCargo_vehicle_Slot_2x1=cargo_usn_2x1_3,cargo_usn_2x1_10,cargo_wp_2x1_3,cargo_wp_2x1_10

1968MilitaryCargo_USN_Slot_2x2=cargo_usn_2x2_1,cargo_usn_2x2_5,cargo_usn_2x2_8,cargo_usn_2x2_9,cargo_usn_2x2_11,cargo_wp_2x2_6,cargo_wp_2x2_5,cargo_wp_2x2_7,cargo_wp_2x2_9,cargo_wp_2x2_11,cargo_wp_2x2_3,cargo_usn_2x3_1,cargo_usn_2x3_3,cargo_usn_2x3_5,cargo_usn_2x3_8

1968MilitaryCargo_USN_Slot_2x3=cargo_usn_2x3_1,cargo_usn_2x3_3,cargo_usn_2x3_5,cargo_usn_2x3_8,cargo_usn_2x3_10,cargo_usn_2x3_12

MilitaryCargo_USN_Slot_2x4=cargo_usn_2x4_1,cargo_usn_2x4_2,cargo_usn_2x4_3,cargo_usn_2x4_4,cargo_usn_2x4_5,cargo_usn_2x4_7,cargo_usn_2x4_8,cargo_usn_2x4_9,cargo_usn_2x4_10

# ++++++++++++++++++++++++++++++ USN Amphibious ++++++++++++++++++++++++++++++
USN_LCM_Slot=cargo_usn_lcm8

[============================== Cargo Variants ==============================]

[ ++++++++++++++++++++++++++++  USN Amphibious +++++++++++++++++++++++++++ ]
[cargo_usn_lcm8]
ResourcesMeshFolder=ships/usn_lcm8/
RootMesh=usn_lcm8
Mesh=usn_lcm8
ResourcesMaterialFolder=ships/usn_lcm8/
Material=usn_lcm8_mat


[ ++++++++++++++++++++++++++++++ Commandos ++++++++++++++++++++++++++++++ ]
[---------------------------------NATO----------------------------------]
[cargo_usn_seals]
ResourcesMeshFolder=ships/assault_raft/
RootMesh=assault_raft
Mesh=assault_raft_crew_us
ResourcesMaterialFolder=ships/assault_raft/
Material=usn_seals_mat
HideWithActiveDamageModel=False

ModuleType=Inert

[cargo_usn_car-15]
ResourcesMeshFolder=ships/assault_raft/
RootMesh=assault_raft
Mesh=assault_raft_rifles_us
ResourcesMaterialFolder=ships/assault_raft/
Material=usn_car-15
HideWithActiveDamageModel=False

ModuleType=Inert


[ ++++++++++++++++++++++++++++++ Crews ++++++++++++++++++++++++++++++ ]
[---------------------------------NATO----------------------------------]
[cargo_open_raft_crew_us]
ResourcesMeshFolder=ships/life_raft_open/
RootMesh=life_raft_open
Mesh=life_raft_open_crew_us
ResourcesMaterialFolder=ships/materials/
Material=usn_crew
HideWithActiveDamageModel=False
ModuleType=Inert

[cargo_single_raft_crew_us]
ResourcesMeshFolder=ships/one_man_raft/
RootMesh=one_man_raft
Mesh=one_man_raft_pilot_us
ResourcesMaterialFolder=characters/materials/
Material=usn_pilot_c_mat
HideWithActiveDamageModel=False
ModuleType=Inert

[cargo_single_raft_crew_potus]
ResourcesMeshFolder=aircraft/emitters/
RootMesh=usaf_potus_pod
Mesh=potus_escapepod_potus
ResourcesMaterialFolder=characters/materials/
Material=usa_president_mat
HideWithActiveDamageModel=False
ModuleType=Inert
