[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=4

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
Nation=Brazil
ServiceDate=1989|2008

[Variant1] # D-27 Pará
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=bra_D-27.png
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/usn_ff_garcia/
LiveryTexture=usn_ff_garcia_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
Nation=Brazil
ServiceDate=1989|2008
#CustomAirGroup=True
#ran_as350=Default,1

[Variant2] # D-28 Paraná
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=bra_D-28.png
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/usn_ff_garcia/
LiveryTexture=usn_ff_garcia_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
Nation=Brazil
ServiceDate=1989|2002
#CustomAirGroup=True
#ran_as350=Default,1

[Variant3] # D-29 Paraíba
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=bra_D-29.png
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/usn_ff_garcia/
LiveryTexture=usn_ff_garcia_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
Nation=Brazil
ServiceDate=1989|2004
#CustomAirGroup=True
#ran_as350=Default,1

[Variant4] # D-30 Pernambuco
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=bra_D-30.png
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=
ResourcesLiveryFolder=ships/usn_ff_garcia/
LiveryTexture=usn_ff_garcia_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
Nation=Brazil
ServiceDate=1989|2004
#CustomAirGroup=True
#ran_as350=Default,1


