[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=6

[Default]   #Niterói F40 A/S
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=bra_F40.png
ResourcesEmblemFolder=ships/materials/hullnumbers/
EmblemTexture=bra_F40.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
# nations are referenced in the layout.ini file:
Nation=Brazil
LoadoutVariant=ASW
ResourcesLiveryFolder=ships/bra_ffg_niteroi/Textures/
LiveryTexture=bra_ffg_niteroi_mat_MainTex.png
SpecularTexture=bra_ffg_niteroi_mat_SpecMap.png

ServiceDate=1976|


[Variant1]  #Niterói F40 A/S
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=bra_F40.png
ResourcesEmblemFolder=ships/materials/hullnumbers/
EmblemTexture=bra_F40.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
# nations are referenced in the layout.ini file:
Nation=Brazil
LoadoutVariant=ASW
ResourcesLiveryFolder=ships/bra_ffg_niteroi/Textures/
LiveryTexture=bra_ffg_niteroi_mat_MainTex.png
SpecularTexture=bra_ffg_niteroi_mat_SpecMap.png

ServiceDate=1976|2019

[Variant2]  #Defensora F41 A/S
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=bra_F41.png
ResourcesEmblemFolder=ships/materials/hullnumbers/
EmblemTexture=bra_F41.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
# nations are referenced in the layout.ini file:
Nation=Brazil
LoadoutVariant=ASW
ResourcesLiveryFolder=ships/bra_ffg_niteroi/Textures/
LiveryTexture=bra_ffg_niteroi_mat_MainTex.png
SpecularTexture=bra_ffg_niteroi_mat_SpecMap.png

ServiceDate=1977|

[Variant3]  #Constituição F42 E/G
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=bra_F42.png
ResourcesEmblemFolder=ships/materials/hullnumbers/
EmblemTexture=bra_F42.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
# nations are referenced in the layout.ini file:
Nation=Brazil
LoadoutVariant=Escort
ResourcesLiveryFolder=ships/bra_ffg_niteroi/Textures/
LiveryTexture=bra_ffg_liberal_mat_MainTex.png
SpecularTexture=bra_ffg_liberal_mat_SpecMap.png

ServiceDate=1978|

[Variant4]  #Liberal F43 E/G
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=bra_F43.png
ResourcesEmblemFolder=ships/materials/hullnumbers/
EmblemTexture=bra_F43.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
# nations are referenced in the layout.ini file:
Nation=Brazil
LoadoutVariant=Escort
ResourcesLiveryFolder=ships/bra_ffg_niteroi/Textures/
LiveryTexture=bra_ffg_liberal_mat_MainTex.png
SpecularTexture=bra_ffg_liberal_mat_SpecMap.png

ServiceDate=1978|

[Variant5]  #Independência F44 A/S
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=bra_F44.png
ResourcesEmblemFolder=ships/materials/hullnumbers/
EmblemTexture=bra_F44.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
# nations are referenced in the layout.ini file:
Nation=Brazil
LoadoutVariant=ASW
ResourcesLiveryFolder=ships/bra_ffg_niteroi/Textures/
LiveryTexture=bra_ffg_niteroi_mat_MainTex.png
SpecularTexture=bra_ffg_niteroi_mat_SpecMap.png

ServiceDate=1979|

[Variant6] #União F45 A/S
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=bra_F45.png
ResourcesEmblemFolder=ships/materials/hullnumbers/
EmblemTexture=bra_F45.png
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_brazil
# nations are referenced in the layout.ini file:
Nation=Brazil
LoadoutVariant=ASW
ResourcesLiveryFolder=ships/bra_ffg_niteroi/Textures/
LiveryTexture=bra_ffg_niteroi_mat_MainTex.png
SpecularTexture=bra_ffg_niteroi_mat_SpecMap.png

ServiceDate=1980|
