[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag19
NumberOfSquadrons=3

[Default]
Nation=Australia

[Squadron1]#empty
ResourcesSerialnumberFolder=
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/A4/Variant1/
LiveryTexture=A4_Remake_Paintshop_DefaultMaterial_AlbedoTransparency.png
ResourcesFlagFolder=
FlagTexture=flag_australia
# nations are referenced in the layout.ini file:
Nation=Australia

[Squadron2]#empty
ResourcesSerialnumberFolder=
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/A4/Variant2/
LiveryTexture=A4_Remake_Paintshop_DefaultMaterial_AlbedoTransparency.png
ResourcesFlagFolder=
FlagTexture=flag_australia
# nations are referenced in the layout.ini file:
Nation=Australia

[Squadron3]#empty
ResourcesSerialnumberFolder=
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/A4/Variant2/
LiveryTexture=A4_Remake_Paintshop_DefaultMaterial_AlbedoTransparency.png
ResourcesFlagFolder=
FlagTexture=flag_australia
# nations are referenced in the layout.ini file:
Nation=Australia


