[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag19
NumberOfSquadrons=2

[Default]
ResourcesSerialnumberFolder=
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/ran_A4/RAN_Camo_3/
LiveryTexture=A4_Skyhawk_late_paint_DefaultMaterial_AlbedoTransparency.png
SpecularTexture=A4_Skyhawk_late_paint_DefaultMaterial_SpecularSmoothness.png
ResourcesFlagFolder=
FlagTexture=flag_australia
# nations are referenced in the layout.ini file:
Nation=Australia
ServiceDate=1979|1984

[Squadron1]#empty
ResourcesSerialnumberFolder=
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/ran_A4/RAN_Camo_3/
LiveryTexture=A4_Skyhawk_late_paint_DefaultMaterial_AlbedoTransparency.png
SpecularTexture=A4_Skyhawk_late_paint_DefaultMaterial_SpecularSmoothness.png
ResourcesFlagFolder=
FlagTexture=flag_australia
# nations are referenced in the layout.ini file:
Nation=Australia

[Squadron2]#empty
ResourcesSerialnumberFolder=
SerialNumberPrefix=
SerialnumberTextures=
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft/ran_A4/Variant1/
LiveryTexture=A4_Skyhawk_paint_DefaultMaterial_AlbedoTransparency.png
SpecularTexture=A4_Skyhawk_paint_DefaultMaterial_SpecularSmoothness.png
ResourcesFlagFolder=
FlagTexture=flag_australia
# nations are referenced in the layout.ini file:
Nation=Australia

