[Animations]
NumberOfAnimations=8
Animation1=Flaps_Takeoff
Animation2=Flaps_Takeoff_Retract
Animation3=Flaps_Landing
Animation4=Flaps_Landing_Retract
Animation5=Gear_Extend
Animation6=Gear_Retract
Animation7=Bay_Open
Animation8=Bay_Close
[Flaps_Takeoff]
NumberOfSequencesToPlay=4
Sequence1=Flap_Takeoff_A
Sequence1_Model=Left_Flap_A
Sequence2=Flap_Takeoff_A
Sequence2_Model=Right_Flap_A
Sequence3=Flap_Takeoff_B
Sequence3_Model=Left_Flap_B
Sequence4=Flap_Takeoff_B
Sequence4_Model=Right_Flap_B
[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=4
Sequence1=Flap_Takeoff_Retract_A
Sequence1_Model=Left_Flap_A
Sequence2=Flap_Takeoff_Retract_A
Sequence2_Model=Right_Flap_A
Sequence3=Flap_Takeoff_Retract_B
Sequence3_Model=Left_Flap_B
Sequence4=Flap_Takeoff_Retract_B
Sequence4_Model=Right_Flap_B
[Flaps_Landing]
NumberOfSequencesToPlay=4
Sequence1=Flap_Landing_A
Sequence1_Model=Left_Flap_A
Sequence2=Flap_Landing_A
Sequence2_Model=Right_Flap_A
Sequence3=Flap_Landing_B
Sequence3_Model=Left_Flap_B
Sequence4=Flap_Landing_B
Sequence4_Model=Right_Flap_B
[Flaps_Landing_Retract]
NumberOfSequencesToPlay=4
Sequence1=Flap_Landing_Retract_A
Sequence1_Model=Left_Flap_A
Sequence2=Flap_Landing_Retract_A
Sequence2_Model=Right_Flap_A
Sequence3=Flap_Landing_Retract_B
Sequence3_Model=Left_Flap_B
Sequence4=Flap_Landing_Retract_B
Sequence4_Model=Right_Flap_B
[Gear_Extend]
NumberOfSequencesToPlay=27
Sequence1=Nose_Gear_Extend
Sequence1_Model=Nose_Gear
Sequence2=Nose_Gear_Strut_Extend
Sequence2_Model=Nose_Gear_Strut
Sequence3=H_Gear_Door_Front_Open
Sequence3_Model=Nose_Gear_Door_H
Sequence4=N_Gear_Door_Left_Open
Sequence4_Model=Nose_Gear_Door_L
Sequence5=N_Gear_Door_Right_Open
Sequence5_Model=Nose_Gear_Door_R
Sequence6=Main_Gear_Extend
Sequence6_Model=Left_Gear
Sequence7=Main_Gear_Truck_Extend
Sequence7_Model=Left_Gear_Truck
Sequence8=Main_Gear_Actuator_Extend
Sequence8_Model=Left_Gear_Actuator
Sequence9=Main_Gear_Piston_Extend
Sequence9_Model=Left_Gear_Piston
Sequence10=Main_Gear_Strut_Extend
Sequence10_Model=Left_Gear_Strut
Sequence11=Main_Gear_Extend
Sequence11_Model=Right_Gear
Sequence12=Main_Gear_Truck_Extend
Sequence12_Model=Right_Gear_Truck
Sequence13=Main_Gear_Piston_Extend
Sequence13_Model=Right_Gear_Piston
Sequence14=Main_Gear_Actuator_Extend
Sequence14_Model=Right_Gear_Actuator
Sequence15=Main_Gear_Strut_Extend
Sequence15_Model=Right_Gear_Strut
Sequence16=Gear_Door_Open_A1
Sequence16_Model=Left_Gear_Door_A1
Sequence17=Gear_Door_Open_A2
Sequence17_Model=Left_Gear_Door_A2
Sequence18=Gear_Door_Open_B1
Sequence18_Model=Left_Gear_Door_B1
Sequence19=Gear_Door_Open_B2
Sequence19_Model=Left_Gear_Door_B2
Sequence20=Gear_Door_Open_C1
Sequence20_Model=Left_Gear_Door_C1
Sequence21=Gear_Door_Open_C2
Sequence21_Model=Left_Gear_Door_C2
Sequence22=Gear_Door_Open_A1
Sequence22_Model=Right_Gear_Door_A1
Sequence23=Gear_Door_Open_A2
Sequence23_Model=Right_Gear_Door_A2
Sequence24=Gear_Door_Open_B1
Sequence24_Model=Right_Gear_Door_B1
Sequence25=Gear_Door_Open_B2
Sequence25_Model=Right_Gear_Door_B2
Sequence26=Gear_Door_Open_C1
Sequence26_Model=Right_Gear_Door_C1
Sequence27=Gear_Door_Open_C2
Sequence27_Model=Right_Gear_Door_C2
[Gear_Retract]
NumberOfSequencesToPlay=27
Sequence1=Nose_Gear_Retract
Sequence1_Model=Nose_Gear
Sequence2=Nose_Gear_Strut_Retract
Sequence2_Model=Nose_Gear_Strut
Sequence3=H_Gear_Door_Front_Close
Sequence3_Model=Nose_Gear_Door_H
Sequence4=N_Gear_Door_Left_Close
Sequence4_Model=Nose_Gear_Door_L
Sequence5=N_Gear_Door_Right_Close
Sequence5_Model=Nose_Gear_Door_R
Sequence6=Main_Gear_Retract
Sequence6_Model=Left_Gear
Sequence7=Main_Gear_Truck_Retract
Sequence7_Model=Left_Gear_Truck
Sequence8=Main_Gear_Actuator_Retract
Sequence8_Model=Left_Gear_Actuator
Sequence9=Main_Gear_Piston_Retract
Sequence9_Model=Left_Gear_Piston
Sequence10=Main_Gear_Strut_Retract
Sequence10_Model=Left_Gear_Strut
Sequence11=Main_Gear_Retract
Sequence11_Model=Right_Gear
Sequence12=Main_Gear_Truck_Retract
Sequence12_Model=Right_Gear_Truck
Sequence13=Main_Gear_Piston_Retract
Sequence13_Model=Right_Gear_Piston
Sequence14=Main_Gear_Actuator_Retract
Sequence14_Model=Right_Gear_Actuator
Sequence15=Main_Gear_Strut_Retract
Sequence15_Model=Right_Gear_Strut
Sequence16=Gear_Door_Close_A1
Sequence16_Model=Left_Gear_Door_A1
Sequence17=Gear_Door_Close_A2
Sequence17_Model=Left_Gear_Door_A2
Sequence18=Gear_Door_Close_B1
Sequence18_Model=Left_Gear_Door_B1
Sequence19=Gear_Door_Close_B2
Sequence19_Model=Left_Gear_Door_B2
Sequence20=Gear_Door_Close_C1
Sequence20_Model=Left_Gear_Door_C1
Sequence21=Gear_Door_Close_C2
Sequence21_Model=Left_Gear_Door_C2
Sequence22=Gear_Door_Close_A1
Sequence22_Model=Right_Gear_Door_A1
Sequence23=Gear_Door_Close_A2
Sequence23_Model=Right_Gear_Door_A2
Sequence24=Gear_Door_Close_B1
Sequence24_Model=Right_Gear_Door_B1
Sequence25=Gear_Door_Close_B2
Sequence25_Model=Right_Gear_Door_B2
Sequence26=Gear_Door_Close_C1
Sequence26_Model=Right_Gear_Door_C1
Sequence27=Gear_Door_Close_C2
Sequence27_Model=Right_Gear_Door_C2
[Bay_Open]
NumberOfSequencesToPlay=4
Sequence1=Bay_Door_L_Open
Sequence1_Model=Bay_Door_L1
Sequence2=Bay_Door_L_Open
Sequence2_Model=Bay_Door_L2
Sequence3=Bay_Door_R_Open
Sequence3_Model=Bay_Door_R1
Sequence4=Bay_Door_R_Open
Sequence4_Model=Bay_Door_R2
[Bay_Close]
NumberOfSequencesToPlay=4
Sequence1=Bay_Door_L_Close
Sequence1_Model=Bay_Door_L1
Sequence2=Bay_Door_L_Close
Sequence2_Model=Bay_Door_L2
Sequence3=Bay_Door_R_Close
Sequence3_Model=Bay_Door_R1
Sequence4=Bay_Door_R_Close
Sequence4_Model=Bay_Door_R2
[------------------------------ Sequences ------------------------------]
#--------------------Wing Flap Animations--------------------#
[Flap_Takeoff_A]
NumberOfSteps=2
Time1=0 
RotationZ1=5.3
Smoothness1=EaseInOut
Time2=3 
RotationZ2=-15.3
Smoothness2=EaseInOut
[Flap_Takeoff_B]
NumberOfSteps=2
Time1=0 
RotationZ1=9.7
Smoothness1=EaseInOut
Time2=3 
RotationZ2=-15.3
Smoothness2=EaseInOut
[Flap_Takeoff_Retract_A]
NumberOfSteps=2
Time1=0 
RotationZ1=-15.3
Smoothness1=EaseInOut
Time2=3 
RotationZ2=5.3
Smoothness2=EaseInOut
[Flap_Takeoff_Retract_B]
NumberOfSteps=2
Time1=0 
RotationZ1=-15.3
Smoothness1=EaseInOut
Time2=3 
RotationZ2=9.7
Smoothness2=EaseInOut
[Flap_Landing_A]
NumberOfSteps=2
Time1=0 
RotationZ1=5.3
Smoothness1=EaseInOut
Time2=3 
RotationZ2=-10.3
Smoothness2=EaseInOut
[Flap_Landing_B]
NumberOfSteps=2
Time1=0 
RotationZ1=9.7
Smoothness1=EaseInOut
Time2=3 
RotationZ2=-10.3
Smoothness2=EaseInOut
[Flap_Landing_Retract_A]
NumberOfSteps=2
Time1=0 
RotationZ1=-10.3
Smoothness1=EaseInOut
Time2=3 
RotationZ2=5.3
Smoothness2=EaseInOut
[Flap_Landing_Retract_B]
NumberOfSteps=2
Time1=0 
RotationZ1=-10.3
Smoothness1=EaseInOut
Time2=3 
RotationZ2=9.7
Smoothness2=EaseInOut
#--------------------Nose_Gear Animations--------------------#
[Nose_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=2
RotationZ2=90
Smoothness2=EaseInOut
Time3=4
RotationZ3=0
Smoothness3=EaseInOut
[Nose_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=0
Smoothness2=EaseInOut
Time3=4
RotationZ3=90
Smoothness3=EaseInOut
[Nose_Gear_Strut_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-95
Smoothness1=EaseInOut
Time2=2
RotationZ2=-95
Smoothness2=EaseInOut
Time3=4
RotationZ3=0
Smoothness3=EaseInOut
[Nose_Gear_Strut_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=0
Smoothness2=EaseInOut
Time3=4
RotationZ3=-95
Smoothness3=EaseInOut
[N_Gear_Door_Left_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=-90
Smoothness2=EaseInOut
[N_Gear_Door_Right_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=90
Smoothness2=EaseInOut

[N_Gear_Door_Left_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=5.5
RotationZ2=-90
Smoothness2=EaseInOut
Time3=7.5
RotationZ3=0
Smoothness3=EaseInOut
[N_Gear_Door_Right_Close]
NumberOfSteps=3
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=5.5
RotationZ2=90
Smoothness2=EaseInOut
Time3=7.5
RotationZ3=0
Smoothness3=EaseInOut
[H_Gear_Door_Front_Open]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=3.5
RotationX2=-50
Smoothness2=EaseInOut
[H_Gear_Door_Front_Close]
NumberOfSteps=2
Time1=0 
RotationX1=-50
Smoothness1=EaseInOut
Time2=3.5
RotationX2=0
Smoothness2=EaseInOut
#--------------------LR_Gear Animations--------------------#
[Main_Gear_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=89
Smoothness1=EaseInOut
Time2=2 
RotationZ2=89
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut
[Main_Gear_Truck_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=2 
RotationZ2=90
Smoothness2=EaseInOut
Time3=4 
RotationZ3=0
Smoothness3=EaseInOut
[Main_Gear_Piston_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-115
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-115
Smoothness2=EaseInOut
Time3=3 
RotationZ3=0
Smoothness3=EaseInOut
[Main_Gear_Actuator_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=160
Smoothness1=EaseInOut
Time2=2 
RotationZ2=160
Smoothness2=EaseInOut
Time3=3 
RotationZ3=0
Smoothness3=EaseInOut
[Main_Gear_Strut_Extend]
NumberOfSteps=3
Time1=0 
RotationZ1=-25
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-25
Smoothness2=EaseInOut
Time3=4 
RotationZ3=0
Smoothness3=EaseInOut

[Main_Gear_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=5 
RotationZ3=89
Smoothness3=EaseInOut

[Main_Gear_Truck_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=4
RotationZ3=90
Smoothness3=EaseInOut

[Main_Gear_Piston_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=3 
RotationZ3=-115
Smoothness3=EaseInOut

[Main_Gear_Actuator_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=3 
RotationZ3=160
Smoothness3=EaseInOut

[Main_Gear_Strut_Retract]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=0
Smoothness2=EaseInOut
Time3=4 
RotationZ3=-25
Smoothness3=EaseInOut
#--------------------LR_Gear Door Animations--------------------#
[Gear_Door_Open_A1]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=-45
Smoothness2=EaseInOut
[Gear_Door_Close_A1]
NumberOfSteps=3
Time1=0 
RotationZ1=-45
Smoothness1=EaseInOut
Time2=4.5
RotationZ2=-45
Smoothness2=EaseInOut
Time3=7.5
RotationZ3=0
Smoothness3=EaseInOut
[Gear_Door_Open_A2]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=45
Smoothness2=EaseInOut
[Gear_Door_Close_A2]
NumberOfSteps=3
Time1=0 
RotationZ1=45
Smoothness1=EaseInOut
Time2=4.5
RotationZ2=45
Smoothness2=EaseInOut
Time3=7.5
RotationZ3=0
Smoothness3=EaseInOut
[Gear_Door_Open_B1]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=-45
Smoothness2=EaseInOut
Time3=5.5
RotationZ3=-45
Smoothness3=EaseInOut
Time4=7.5
RotationZ4=0
Smoothness4=EaseInOut
[Gear_Door_Close_B1]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=-45
Smoothness2=EaseInOut
Time3=5.5
RotationZ3=-45
Smoothness3=EaseInOut
Time4=7.5
RotationZ4=0
Smoothness4=EaseInOut
[Gear_Door_Open_B2]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=45
Smoothness2=EaseInOut
Time3=5.5
RotationZ3=45
Smoothness3=EaseInOut
Time4=7.5
RotationZ4=0
Smoothness4=EaseInOut
[Gear_Door_Close_B2]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=45
Smoothness2=EaseInOut
Time3=5.5
RotationZ3=45
Smoothness3=EaseInOut
Time4=7.5
RotationZ4=0
Smoothness4=EaseInOut
[Gear_Door_Open_C1]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=-45
Smoothness2=EaseInOut
Time3=5.5
RotationZ3=-45
Smoothness3=EaseInOut
Time4=7.5
RotationZ4=0
Smoothness4=EaseInOut
[Gear_Door_Close_C1]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=-45
Smoothness2=EaseInOut
Time3=5.5
RotationZ3=-45
Smoothness3=EaseInOut
Time4=7.5
RotationZ4=0
Smoothness4=EaseInOut
[Gear_Door_Open_C2]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=45
Smoothness2=EaseInOut
Time3=5.5
RotationZ3=45
Smoothness3=EaseInOut
Time4=7.5
RotationZ4=0
Smoothness4=EaseInOut
[Gear_Door_Close_C2]
NumberOfSteps=4
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=45
Smoothness2=EaseInOut
Time3=5.5
RotationZ3=45
Smoothness3=EaseInOut
Time4=7.5
RotationZ4=0
Smoothness4=EaseInOut
#--------------------Bay Door--------------------#
[Bay_Door_L_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=-55
Smoothness2=EaseInOut
[Bay_Door_L_Close]
NumberOfSteps=2
Time1=0 
RotationZ1=-55
Smoothness1=EaseInOut
Time2=2
RotationZ2=0
Smoothness2=EaseInOut
[Bay_Door_R_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=55
Smoothness2=EaseInOut
[Bay_Door_R_Close]
NumberOfSteps=2
Time1=0 
RotationZ1=55
Smoothness1=EaseInOut
Time2=2
RotationZ2=0
Smoothness2=EaseInOut