[AmmunitionNames]
# ------------------ AAM ------------------

# ------------------ SAM ------------------

PN_fr_mica_em=VL Mica (EM) Ship to Air Ver

PN_fr_mica_ir=VL Mica (IR) Ship to Air Ver

# ---------- Anti-radar Missiles ---------

# ---------- Anti-ship Missiles ----------

#-----------Land Strike only missiles---------

# ---------- Anti-sub Missiles ----------

# ------------------ RBU ------------------

# ---------- Torpedoes ----------

# ------------------ Bombs -----------------

# ---------------- Sonobuoys ---------------

# ------------------ FFAR -----------------

# ------------------ MLRS -----------------

# ------------------ Guns -----------------

# ------------------ CIWS -----------------

# ----------- Noisemakers/Chaff -----------

# ----------------- Decoys ----------------

# ----------------- Special ----------------

# ------------------ Depth Charges ------------------

# ----------------- Fueltanks ----------------