[Animations]
NumberOfAnimations=4
Animation1=VDS_Extend
Animation2=VDS_Retract
Animation3=HangarOpenAnim
Animation4=HangarCloseAnim

[HangarOpenAnim]
NumberOfSequencesToPlay=4
Sequence1=HangarOpenDoor1AnimSequence
Sequence1_Model=Hangar_Door_A
Sequence2=HangarOpenDoor2AnimSequence
Sequence2_Model=Hangar_Door_B
Sequence3=HangarOpenDoor3AnimSequence
Sequence3_Model=Hangar_Door_C
Sequence4=HangarOpenDoor4AnimSequence
Sequence4_Model=Hangar_Door_D

[HangarCloseAnim]
NumberOfSequencesToPlay=4
Sequence1=HangarCloseDoor1AnimSequence
Sequence1_Model=Hangar_Door_A
Sequence2=HangarCloseDoor2AnimSequence
Sequence2_Model=Hangar_Door_B
Sequence3=HangarCloseDoor3AnimSequence
Sequence3_Model=Hangar_Door_C
Sequence4=HangarCloseDoor4AnimSequence
Sequence4_Model=Hangar_Door_D

[VDS_Extend]
NumberOfSequencesToPlay=7

Sequence1=Winch_Reel_Out
Sequence1_Model=VDS_Winch
Sequence2=Actuator_Extend
Sequence2_Model=VDS_Actuator_1
Sequence3=Actuator_Extend
Sequence3_Model=VDS_Actuator_2
Sequence4=Cradle_Extend
Sequence4_Model=VDS_Cradle
Sequence5=Cable_1_Extend
Sequence5_Model=VDS_Cable_1
Sequence6=Cable_2_Extend
Sequence6_Model=VDS_Cable_2
Sequence7=Cable_3_Extend
Sequence7_Model=VDS_Cable_3

[VDS_Retract]
NumberOfSequencesToPlay=7

Sequence1=Winch_Reel_In
Sequence1_Model=VDS_Winch
Sequence2=Actuator_Retract
Sequence2_Model=VDS_Actuator_1
Sequence3=Actuator_Retract
Sequence3_Model=VDS_Actuator_2
Sequence4=Cradle_Retract
Sequence4_Model=VDS_Cradle
Sequence5=Cable_1_Retract
Sequence5_Model=VDS_Cable_1
Sequence6=Cable_2_Retract
Sequence6_Model=VDS_Cable_2
Sequence7=Cable_3_Retract
Sequence7_Model=VDS_Cable_3

[------------------------------ Sequences ------------------------------]
#Open Doors
[HangarOpenDoor1AnimSequence]
NumberOfSteps=3
#Step<i>=Time|Position|Rotation|SmoothnessType
#Step<i>=0|None|0,0,0|Linear
Step1=0|x,0.07,z|0,y,z|Linear
Step2=11.5|x,0.115,z|0,y,z|Linear
Step3=12.5|x,0.13,z|90,y,z|Linear

[HangarOpenDoor2AnimSequence]
NumberOfSteps=3

Step1=0|x,0.084,z|0,y,z|Linear
Step2=10|x,0.115,z|0,y,z|Linear
Step3=11|x,0.13,z|90,y,z|Linear

[HangarOpenDoor3AnimSequence]
NumberOfSteps=3

Step1=0|x,0.097,z|0,y,z|Linear
Step2=8|x,0.115,z|0,y,z|Linear
Step3=9|x,0.13,z|90,y,z|Linear

[HangarOpenDoor4AnimSequence]
NumberOfSteps=3

Step1=0|x,0.111,z|0,y,z|Linear
Step2=6|x,0.115,z|0,y,z|Linear
Step3=8|x,0.13,|90|Linear

#Close Doors
[HangarCloseDoor1AnimSequence]
NumberOfSteps=3

Step1=0|x,0.13,z|90,y,z|Linear
Step2=1|x,0.12,z|0,y,z|Linear
Step3=12.5|x,0.07,z|0,y,z|Linear

[HangarCloseDoor2AnimSequence]
NumberOfSteps=3

Step1=0|x,0.13,z|90,y,z|Linear
Step2=1|x,0.121,z|0,y,z|Linear
Step3=11|x,0.084,z|0,y,z|Linear

[HangarCloseDoor3AnimSequence]
NumberOfSteps=3

Step1=0|x,0.13,z|90,y,z|Linear
Step2=1|x,0.12,z|0,y,z|Linear
Step3=9|x,0.097,z|0,y,z|Linear

[HangarCloseDoor4AnimSequence]
NumberOfSteps=3

Step1=0|x,0.13,z|90,y,z|Linear
Step2=1|x,0.121,z|0,y,z|Linear
Step3=6|x,0.111,z|0,y,z|Linear

############################################################
# Deploy VDS
############################################################

[Winch_Reel_Out]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationZ1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=5               // time in seconds - here for the end
RotationZ2=1200
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Actuator_Extend]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationZ1=-45
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=5               // time in seconds - here for the end
RotationZ2=45
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Cradle_Extend]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationZ1=45
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=5                // time in seconds - here for the end
RotationZ2=-45
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Cable_1_Extend]
NumberOfSteps=7
Time1=0
RotationX1=38
Smoothness1=Linear
Time2=1.25
RotationX2=36
Smoothness2=Linear
Time3=2.5
RotationX3=30
Smoothness3=Linear
Time4=3
RotationX4=24
Smoothness4=Linear
Time5=3.5
RotationX5=20
Smoothness5=Linear
Time6=4.5
RotationX6=13.5
Smoothness6=Linear
Time7=5
RotationX7=12.5
Smoothness7=Linear


[Cable_2_Extend]
NumberOfSteps=2
Time1=0
PositionZ1=0
RotationX1=0
Smoothness1=Linear
Time2=5
PositionZ2=0.043
RotationX2=0
Smoothness2=EaseInOut

[Cable_3_Extend]
NumberOfSteps=2
Time1=0
PositionZ1=0
Smoothness1=Linear
Time2=5
PositionZ2=0.043
Smoothness2=Linear

############################################################
# Retract VDS
############################################################

[Winch_Reel_In]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationZ1=1200
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=5               // time in seconds - here for the end
RotationZ2=0
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Actuator_Retract]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationZ1=45
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=5               // time in seconds - here for the end
RotationZ2=-45
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Cradle_Retract]
NumberOfSteps=2
Time1=0                // time in seconds for the start
RotationZ1=-45
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step
Time2=5                // time in seconds - here for the end
RotationZ2=45
Smoothness2=EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Cable_1_Retract]
NumberOfSteps=7
Time1=0
RotationX1=12.5
Smoothness1=Linear
Time2=0.5
RotationX2=13.5
Smoothness2=Linear
Time3=1.5
RotationX3=20
Smoothness3=EaseInOut
Time4=2
RotationX4=24
Smoothness4=Linear
Time5=2.5
RotationX5=30
Smoothness5=EaseInOut
Time6=3.75
RotationX6=36
Smoothness6=EaseInOut
Time7=5
RotationX7=38
Smoothness7=EaseInOut


[Cable_2_Retract]
NumberOfSteps=2
Time1=0
PositionZ1=0.043
RotationX1=0
Smoothness1=Linear
Time2=5
PositionZ2=0
RotationX2=0
Smoothness2=EaseInOut

[Cable_3_Retract]
NumberOfSteps=2
Time1=0
PositionZ1=0.043
Smoothness1=EaseInOut
Time2=5
PositionZ2=0
Smoothness2=EaseInOut

[------------------------------ FlightDeck Taxi Sequences ------------------------------]


[Elevator2LaunchPoint3Sequence]
#FixMe
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=0.042
PositionY1=0.1676
PositionZ1=-1.07
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=-1.28
Smoothness2=Linear  //EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[Elevator1LaunchPoint4Sequence]
#FixMe
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=-0.1245
PositionY1=0.1676
PositionZ1=-0.61
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=14
PositionZ2=-0.98
Smoothness2=Linear  //EaseInOut  // can be: Linear, EaseInOut - is not used here as it's the last entry

[RecoveryPoint1Elevator1Sequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=-0.1245
PositionY1=0.1676
PositionZ1=-0.98
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=14
PositionZ2=-0.61
Smoothness2=EaseInOut

[RecoveryPoint2Elevator2Sequence]
NumberOfSteps=2
Time1=0                // time in seconds for the start
PositionX1=0.042
PositionY1=0.1676
PositionZ1=-1.28
RotationY1=0
Smoothness1=EaseInOut  // can be: Linear, EaseInOut - transition to the next step

Time2=10
PositionZ2=-1.07
Smoothness2=EaseInOut
