#!alias vessels/usn_msc_adjutant.ini
# ver. 20260826
#

[Submodels]
SubModel13=Hullnumber

[Crew]
Material=nato_crew
HideWithActiveDamageModel=True

[Gun_Mount_1]
HideWithActiveDamageModel=True

[Gunner]
ResourcesMeshFolder=ships/ir_pt_parvin/
RootMesh=ir_pt_parvin
Mesh=ir_pt_parvin_gambo_gunner
ResourcesMaterialFolder=ships/materials/
Material=nato_crew
Position=0,-0.0226,0.002
Rotation=20,0,0

[Hullnumber]
ResourcesMeshFolder=ships/ae_msc_jucar/
RootMesh=ae_msc_jucar_hullnumbers.obj
Mesh=Hullnumbers
ResourcesMaterialFolder=ships/materials/hullnumbers/
Material=hullnumber

