[Main]
Duration=10000
Loop=False
Prewarm=False
StartDelay=0
StartLifetime=10000
StartSpeed=0
StartSize=1
StartRotation=0
FlipRotation=0
StartColor=1,1,1,1
GravityModifier=0
SimulationSpace=Local
SimulationSpeed=1
UnscaledTime=False
ScalingMode=Local
PlayOnAwake=True
EmitterVelocityMode=Transform
CustomVelocity=0,0,0
MaxParticles=1000
StopAction=None
CullingMode=AlwaysSimulate
RingBufferMode=Disabled
RingBufferLoopRange=0,1

[Emission]
RateOverTime=0
RateOverDistance=0
Bursts=0:1:1:1:0.01

[Shape]
ShapeType=Sphere
Radius=0
Angle=0
Length=0
Arc=360
Position=0,0,0
Rotation=0,0,0
Scale=2,2,2
AlignToDirection=False

[SizeOverLifetime]
SeparateAxes=True
X=1
Y=1
Z=1

[Renderer]
RenderMode=Mesh
NormalDirection=1
Material=aircraft/materials/afterburner_mat
CameraScale=0
SpeedScale=0
LengthScale=2
FreeformStretching=False
RotateWithStretch=True
MeshDistribution=UniformRandom
SortMode=None
SortingFudge=0
MinParticleSize=0
MaxParticleSize=0.5
Alignment=Local
Flip=0,0,0
AllowRoll=True
MaskInteraction=None
ShadowCastingMode=Off
ReceiveShadows=False
ShadowBias=0
MotionVectorGenerationMode=Object
SortingLayerID=0
SortingOrder=0
LightProbeUsage=Off
ReflectionProbeUsage=Off
MeshCount=1
Mesh0=assets\europack\models\exhaust.obj,eu_missile_exhaust

;[SubEmitters]
;Count=1
;SubEmitter0=effects/weapons/emitters/exhaust_flame_aam_fire.ini
;SubEmitter0_Position=0,0,-0.06
;SubEmitter0_Rotation=0,0,0
;SubEmitter0_Scale=1,1,1
;SubEmitter0_Type=Birth
;SubEmitter0_Properties=InheritNothing
;SubEmitter0_Probability=1
