[Animations]
NumberOfAnimations=8

Animation1=Flaps_Takeoff
Animation2=Flaps_Takeoff_Retract
Animation3=Flaps_Landing
Animation4=Flaps_Landing_Retract
Animation5=Gear_Extend
Animation6=Gear_Retract
Animation7=Bays_Open
Animation8=Bays_Close

[Flaps_Takeoff]
NumberOfSequencesToPlay=6
Sequence1=Flap_Takeoff
Sequence1_Model=Engine_flaps_r
Sequence2=Flap_Takeoff
Sequence2_Model=Engine_flaps_l
Sequence3=Flap_Takeoff
Sequence3_Model=Flaps_1_l
Sequence4=Flap_Takeoff
Sequence4_Model=Flaps_2_l
Sequence5=Flap_Takeoff
Sequence5_Model=Flaps_1_r
Sequence6=Flap_Takeoff
Sequence6_Model=Flaps_2_r

[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=6
Sequence1=Flap_Takeoff_Retract
Sequence1_Model=Engine_flaps_r
Sequence2=Flap_Takeoff_Retract
Sequence2_Model=Engine_flaps_l
Sequence3=Flap_Takeoff_Retract
Sequence3_Model=Flaps_1_l
Sequence4=Flap_Takeoff_Retract
Sequence4_Model=Flaps_2_l
Sequence5=Flap_Takeoff_Retract
Sequence5_Model=Flaps_1_r
Sequence6=Flap_Takeoff_Retract
Sequence6_Model=Flaps_2_r

[Flaps_Landing]
NumberOfSequencesToPlay=6
Sequence1=Flap_Landing
Sequence1_Model=Engine_flaps_r
Sequence2=Flap_Landing
Sequence2_Model=Engine_flaps_l
Sequence3=Flap_Landing
Sequence3_Model=Flaps_1_l
Sequence4=Flap_Landing
Sequence4_Model=Flaps_2_l
Sequence5=Flap_Landing
Sequence5_Model=Flaps_1_r
Sequence6=Flap_Landing
Sequence6_Model=Flaps_2_r

[Flaps_Landing_Retract]
NumberOfSequencesToPlay=6
Sequence1=Flap_Landing_Retract
Sequence1_Model=Engine_flaps_r
Sequence2=Flap_Landing_Retract
Sequence2_Model=Engine_flaps_l
Sequence3=Flap_Landing_Retract
Sequence3_Model=Flaps_1_l
Sequence4=Flap_Landing_Retract
Sequence4_Model=Flaps_2_l
Sequence5=Flap_Landing_Retract
Sequence5_Model=Flaps_1_r
Sequence6=Flap_Landing_Retract
Sequence6_Model=Flaps_2_r

[Gear_Extend]
NumberOfSequencesToPlay=11
Sequence1=Front_Gear_Door_1_Open
Sequence1_Model=Nose_Gear_Door_L
Sequence2=Front_Gear_Door_2_Open
Sequence2_Model=Nose_Gear_Door_R
Sequence3=Front_gear_Extend
Sequence3_Model=Front_Gear
Sequence4=Main_Gear_Extend_l
Sequence4_Model=Main_gear_l
Sequence5=Strut_1_left_Extend
Sequence5_Model=Actuator_l
Sequence6=Gear_door_left_1_Extend
Sequence6_Model=Main_Gear_Door_L_1
Sequence7=Gear_door_left_2_Extend
Sequence7_Model=Main_Gear_Door_L_2
Sequence8=Main_Gear_Extend_r
Sequence8_Model=Main_gear_r
Sequence9=Strut_1_right_Extend
Sequence9_Model=Actuator_r
Sequence10=Gear_door_right_1_Extend
Sequence10_Model=Main_Gear_Door_R_1
Sequence11=Gear_door_right_2_Extend
Sequence11_Model=Main_Gear_Door_R_2

[Gear_Retract]
NumberOfSequencesToPlay=11
Sequence1=Front_Gear_Door_1_Retract
Sequence1_Model=Nose_Gear_Door_L
Sequence2=Front_Gear_Door_2_Retract
Sequence2_Model=Nose_Gear_Door_R
Sequence3=Front_gear_Retract
Sequence3_Model=Front_Gear
Sequence4=Main_Gear_Retract_l
Sequence4_Model=Main_gear_l
Sequence5=Strut_1_left_Retract
Sequence5_Model=Actuator_l
Sequence6=Gear_door_left_1_Retract
Sequence6_Model=Main_Gear_Door_L_1
Sequence7=Gear_door_left_2_Retract
Sequence7_Model=Main_Gear_Door_L_2
Sequence8=Main_Gear_Retract_r
Sequence8_Model=Main_gear_r
Sequence9=Strut_1_right_Retract
Sequence9_Model=Actuator_r
Sequence10=Gear_door_right_1_Retract
Sequence10_Model=Main_Gear_Door_R_1
Sequence11=Gear_door_right_2_Retract
Sequence11_Model=Main_Gear_Door_R_2

[Bays_Open]
NumberOfSequencesToPlay=2
Sequence1=Bay_Door_Left_Open
Sequence1_Model=Bomb_bay_l
Sequence2=Bay_Door_Right_Open
Sequence2_Model=Bomb_bay_r

[Bays_Close]
NumberOfSequencesToPlay=2
Sequence1=Bay_Door_Left_Close
Sequence1_Model=Bomb_bay_l
Sequence2=Bay_Door_Right_Close
Sequence2_Model=Bomb_bay_r
[------------------------------ Sequences ------------------------------]
#------------------------------Flaps deploy/retract ------------------------------#

[Flap_Takeoff]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=10
RotationX2=-20
Smoothness2=EaseInOut

[Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-20
Smoothness1=EaseInOut
Time2=10
RotationX2=0
Smoothness2=EaseInOut

[Flap_Landing]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=10
RotationX2=-35
Smoothness2=EaseInOut

[Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-35
Smoothness1=EaseInOut
Time2=10
RotationX2=0
Smoothness2=EaseInOut

#------------------------------Hook deploy/retract ------------------------------#
#------------------------------Radar deploy/retract ------------------------------#
#------------------------------Gear deploy/retract ------------------------------#
#------------------------------Front Gear ------------------------------#
[Front_Gear_Door_1_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
PositionX1=0
Smoothness1=EaseInOut
Time2=8
RotationZ2=18
PositionX2=-0.002
Smoothness2=EaseInOut

[Front_Gear_Door_1_Retract]
NumberOfSteps=2
Time1=5
RotationZ1=18
PositionX1=-0.002
Smoothness1=EaseInOut
Time2=13
RotationZ2=0
PositionX2=0
Smoothness2=EaseInOut

[Front_Gear_Door_2_Open]
NumberOfSteps=2
Time1=0 
RotationZ1=0
PositionX1=0
Smoothness1=EaseInOut
Time2=8
RotationZ2=-18
PositionX2=0.002
Smoothness2=EaseInOut

[Front_Gear_Door_2_Retract]
NumberOfSteps=2
Time1=5
RotationZ1=-18
PositionX1=0.002
Smoothness1=EaseInOut
Time2=13
RotationZ2=0
PositionX2=0
Smoothness2=EaseInOut

[Front_gear_Extend]
NumberOfSteps=2
Time1=5 
RotationX1=0
Smoothness1=EaseInOut
Time2=15
RotationX2=-90
Smoothness2=EaseInOut

[Front_gear_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-90
Smoothness1=EaseInOut
Time2=10
RotationX2=0
Smoothness2=EaseInOut

#------------------------------Main Gear Left ------------------------------#
[Main_Gear_Extend_l]
NumberOfSteps=2
Time1=3
RotationZ1=-7
Smoothness1=EaseInOut
Time2=15
RotationZ2=90
Smoothness2=EaseInOut

[Main_Gear_Retract_l]
NumberOfSteps=2
Time1=0 
RotationZ1=90
Smoothness1=EaseInOut
Time2=15 
RotationZ2=-7
Smoothness2=EaseInOut

[Strut_1_left_Extend]
NumberOfSteps=2
Time1=2
RotationZ1=0
Smoothness1=EaseInOut
Time2=15 
RotationZ2=-145
Smoothness2=EaseInOut

[Strut_1_left_Retract]
NumberOfSteps=2
Time1=2 
RotationZ1=-145
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
Smoothness2=EaseInOut

[Gear_door_left_1_Extend]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=15 
RotationZ2=95
Smoothness2=EaseInOut

[Gear_door_left_1_Retract]
NumberOfSteps=2
Time1=0
RotationZ1=95
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
Smoothness2=EaseInOut

[Gear_door_left_2_Extend]
NumberOfSteps=3
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=7 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=16 
RotationZ3=0
Smoothness3=EaseInOut

[Gear_door_left_2_Retract]
NumberOfSteps=3
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=-90
Smoothness2=EaseInOut
Time3=20 
RotationZ3=0
Smoothness3=EaseInOut
#------------------------------Main Gear Right ------------------------------#
[Main_Gear_Extend_r]
NumberOfSteps=2
Time1=3
RotationZ1=7
Smoothness1=EaseInOut
Time2=15
RotationZ2=-90
Smoothness2=EaseInOut

[Main_Gear_Retract_r]
NumberOfSteps=2
Time1=0 
RotationZ1=-90
Smoothness1=EaseInOut
Time2=15 
RotationZ2=7
Smoothness2=EaseInOut

[Strut_1_right_Extend]
NumberOfSteps=2
Time1=2
RotationZ1=0
Smoothness1=EaseInOut
Time2=15 
RotationZ2=145
Smoothness2=EaseInOut

[Strut_1_right_Retract]
NumberOfSteps=2
Time1=2 
RotationZ1=145
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
Smoothness2=EaseInOut

[Gear_door_right_1_Extend]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=15 
RotationZ2=-95
Smoothness2=EaseInOut

[Gear_door_right_1_Retract]
NumberOfSteps=2
Time1=0
RotationZ1=-95
Smoothness1=EaseInOut
Time2=15 
RotationZ2=0
Smoothness2=EaseInOut

[Gear_door_right_2_Extend]
NumberOfSteps=3
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=7 
RotationZ2=90
Smoothness2=EaseInOut
Time3=16 
RotationZ3=0
Smoothness3=EaseInOut

[Gear_door_right_2_Retract]
NumberOfSteps=3
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=90
Smoothness2=EaseInOut
Time3=20 
RotationZ3=0
Smoothness3=EaseInOut
#------------------------------Main Gear Right ------------------------------#
[Bay_Door_Left_Open]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=-75
Smoothness2=EaseInOut

[Bay_Door_Left_Close]
NumberOfSteps=2
Time1=0
RotationZ1=-75
Smoothness1=EaseInOut
Time2=5 
RotationZ2=0
Smoothness2=EaseInOut

[Bay_Door_Right_Open]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=75
Smoothness2=EaseInOut

[Bay_Door_Right_Close]
NumberOfSteps=2
Time1=0
RotationZ1=75
Smoothness1=EaseInOut
Time2=5 
RotationZ2=0
Smoothness2=EaseInOut