[Animations]
NumberOfAnimations=8

Animation1=Flaps_Takeoff
Animation2=Flaps_Takeoff_Retract
Animation3=Flaps_Landing
Animation4=Flaps_Landing_Retract
Animation5=Gear_Extend
Animation6=Gear_Retract
Animation7=Boom_Extend
Animation8=Boom_Retract

[Flaps_Takeoff]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff
Sequence1_Model=Flaps_Left
Sequence2=Flap_Takeoff
Sequence2_Model=Flaps_Right


[Flaps_Takeoff_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Takeoff_Retract
Sequence1_Model=Flaps_Left
Sequence2=Flap_Takeoff_Retract
Sequence2_Model=Flaps_Right

[Flaps_Landing]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing
Sequence1_Model=Flaps_Left
Sequence2=Flap_Landing
Sequence2_Model=Flaps_Right


[Flaps_Landing_Retract]
NumberOfSequencesToPlay=2
Sequence1=Flap_Landing_Retract
Sequence1_Model=Flaps_Left
Sequence2=Flap_Landing_Retract
Sequence2_Model=Flaps_Right

[Gear_Extend]
NumberOfSequencesToPlay=13
Sequence1=Main_Strut_Extend_1
Sequence1_Model=Landing_Strut_Base_1
Sequence2=Landing_Strut_rotate_1
Sequence2_Model=Landing_Strut_1
Sequence3=Landing_Main_rotate_1
Sequence3_Model=Landing_Main_1

Sequence4=Main_Strut_Extend_2
Sequence4_Model=Landing_Strut_Base_2
Sequence5=Landing_Strut_rotate_2
Sequence5_Model=Landing_Strut_2
Sequence6=Landing_Main_rotate_2
Sequence6_Model=Landing_Main_2

Sequence7=Front_Gear_Rotate_1
Sequence7_Model=Front_Gear_Strut
Sequence8=Front_Gear_Door_Rotate_1
Sequence8_Model=Front_Gear_Door_1
Sequence9=Front_Gear_Door_Rotate_2
Sequence9_Model=Front_Gear_Door_2

Sequence10=Gear_Door_extend_1
Sequence10_Model=Gear_Door_1A
Sequence11=Gear_Door_extend_2
Sequence11_Model=Gear_Door_2A

Sequence12=Gear_Door_Engine_extend_1
Sequence12_Model=Gear_Door_1D
Sequence13=Gear_Door_Engine_extend_2
Sequence13_Model=Gear_Door_2D

[Gear_Retract]
NumberOfSequencesToPlay=13
Sequence1=Main_Strut_Retract_1
Sequence1_Model=Landing_Strut_Base_1
Sequence2=Landing_Strut_retract_1
Sequence2_Model=Landing_Strut_1
Sequence3=Landing_Main_retract_1
Sequence3_Model=Landing_Main_1

Sequence4=Main_Strut_Retract_2
Sequence4_Model=Landing_Strut_Base_2
Sequence5=Landing_Strut_retract_2
Sequence5_Model=Landing_Strut_2
Sequence6=Landing_Main_retract_2
Sequence6_Model=Landing_Main_2

Sequence7=Front_Gear_Retract_1
Sequence7_Model=Front_Gear_Strut
Sequence8=Front_Gear_Door_Retract_1
Sequence8_Model=Front_Gear_Door_1
Sequence9=Front_Gear_Door_Retract_2
Sequence9_Model=Front_Gear_Door_2

Sequence10=Gear_Door_Retract_1
Sequence10_Model=Gear_Door_1A
Sequence11=Gear_Door_Retract_2
Sequence11_Model=Gear_Door_2A

Sequence12=Gear_Door_Engine_Retract_1
Sequence12_Model=Gear_Door_1D
Sequence13=Gear_Door_Engine_Retract_2
Sequence13_Model=Gear_Door_2D

[Boom_Extend]
NumberOfSequencesToPlay=1
Sequence1=MAD_Boom_Extend
Sequence1_Model=MAD

[Boom_Retract]
NumberOfSequencesToPlay=1
Sequence1=MAD_Boom_Retract
Sequence1_Model=MAD

***************************************************
[Flap_Takeoff]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=5 
RotationX2=-15
Smoothness2=EaseInOut

[Flap_Takeoff_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-15
Smoothness1=EaseInOut
Time2=5 
RotationX2=0
Smoothness2=EaseInOut

[Flap_Landing]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=10 
RotationX2=-25
Smoothness2=EaseInOut

[Flap_Landing_Retract]
NumberOfSteps=2
Time1=0 
RotationX1=-25
Smoothness1=EaseInOut
Time2=10 
RotationX2=0
Smoothness2=EaseInOut

[MAD_Boom_Extend]
NumberOfSteps=2
Time1=0
PositionZ1=-0.075
RotationZ1=0
Smoothness1=EaseInOut
Time2=6
PositionZ2=-0.12
Smoothness2=EaseInOut

[MAD_Boom_Retract]
NumberOfSteps=2
Time1=0
PositionZ1=-0.12
RotationZ1=0
Smoothness1=EaseInOut
Time2=6
PositionZ2=-0.075
Smoothness2=EaseInOut

************************************************************
#Gear Struts Extension#

###Right Side Gear Assembly###

[Main_Strut_Extend_1]
NumberOfSteps=3
Time1=0 
RotationZ1=-110
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-10
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Landing_Strut_rotate_1]
NumberOfSteps=3
Time1=0 
RotationZ1=110
Smoothness1=EaseInOut
Time2=2 
RotationZ2=10
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Landing_Main_rotate_1]
NumberOfSteps=2
Time1=0 
RotationZ1=85
Smoothness1=EaseInOut
Time2=2.5 
RotationZ2=0
Smoothness2=EaseInOut

###Left Side Gear Assembly###
[Main_Strut_Extend_2]
NumberOfSteps=3
Time1=0 
RotationZ1=110
Smoothness1=EaseInOut
Time2=2 
RotationZ2=10
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Landing_Strut_rotate_2]
NumberOfSteps=3
Time1=0 
RotationZ1=-110
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-10
Smoothness2=EaseInOut
Time3=5 
RotationZ3=0
Smoothness3=EaseInOut

[Landing_Main_rotate_2]
NumberOfSteps=2
Time1=0 
RotationZ1=-85
Smoothness1=EaseInOut
Time2=2.5
RotationZ2=0
Smoothness2=EaseInOut

###Front Gear Assembly###
[Front_Gear_Rotate_1]
NumberOfSteps=2
Time1=0 
RotationX1=90
Smoothness1=EaseInOut
Time2=5
RotationX2=0
Smoothness2=EaseInOut

[Front_Gear_Door_Rotate_1]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=3
RotationZ2=-60
Smoothness2=EaseInOut

[Front_Gear_Door_Rotate_2]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=3
RotationZ2=60
Smoothness2=EaseInOut

[Gear_Door_extend_1]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=1.5
RotationZ2=100
Smoothness2=EaseInOut

[Gear_Door_extend_2]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=1.5
RotationZ2=-100
Smoothness2=EaseInOut

[Gear_Door_Engine_extend_1]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=1.5
RotationZ2=-110
Smoothness2=EaseInOut

[Gear_Door_Engine_extend_2]
NumberOfSteps=2
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=1.5
RotationZ2=110
Smoothness2=EaseInOut

*******************************************
#Gear Struts Retraction#
[Main_Strut_Retract_1]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-10
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-110
Smoothness3=EaseInOut

[Landing_Strut_retract_1]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=10
Smoothness2=EaseInOut
Time3=5 
RotationZ3=110
Smoothness3=EaseInOut

[Landing_Main_retract_1]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2
RotationZ2=30
Smoothness2=EaseInOut
Time3=5 
RotationZ3=85
Smoothness3=EaseInOut

###Left Side Gear Assembly###
[Main_Strut_Retract_2]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=10
Smoothness2=EaseInOut
Time3=5 
RotationZ3=110
Smoothness3=EaseInOut

[Landing_Strut_retract_2]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-10
Smoothness2=EaseInOut
Time3=5 
RotationZ3=-110
Smoothness3=EaseInOut

[Landing_Main_retract_2]
NumberOfSteps=3
Time1=0 
RotationZ1=0
Smoothness1=EaseInOut
Time2=2 
RotationZ2=-30
Smoothness2=EaseInOut
Time3=5
RotationZ3=-85
Smoothness3=EaseInOut

###Front Gear Assembly###
[Front_Gear_Retract_1]
NumberOfSteps=2
Time1=0 
RotationX1=0
Smoothness1=EaseInOut
Time2=5
RotationX2=90
Smoothness2=EaseInOut

[Front_Gear_Door_Retract_1]
NumberOfSteps=2
Time1=3 
RotationZ1=-60
Smoothness1=EaseInOut
Time2=8
RotationZ2=0
Smoothness2=EaseInOut

[Front_Gear_Door_Retract_2]
NumberOfSteps=2
Time1=3 
RotationZ1=60
Smoothness1=EaseInOut
Time2=8
RotationZ2=0
Smoothness2=EaseInOut

[Gear_Door_Retract_1]
NumberOfSteps=2
Time1=2
RotationZ1=100
Smoothness1=EaseInOut
Time2=8
RotationZ2=0
Smoothness2=EaseInOut

[Gear_Door_Retract_2]
NumberOfSteps=2
Time1=2
RotationZ1=-100
Smoothness1=EaseInOut
Time2=8
RotationZ2=0
Smoothness2=EaseInOut

[Gear_Door_Engine_Retract_1]
NumberOfSteps=2
Time1=6
RotationZ1=-110
Smoothness1=EaseInOut
Time2=8
RotationZ2=0
Smoothness2=EaseInOut

[Gear_Door_Engine_Retract_2]
NumberOfSteps=2
Time1=6
RotationZ1=110
Smoothness1=EaseInOut
Time2=8
RotationZ2=0
Smoothness2=EaseInOut


