[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
AllVariantsAreOfSameNation=False //Speeds up nation sorting. Only needed if there is more then 1 nation variants. Default is 'true'
NumberOfVariants=2

[Default]  #UK
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_australia
Nation=Australia
ServiceDate=1950|1961

[Variant1] #UK
#Scrapped in 1978.
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=ran_59.png
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_australia
Nation=Australia
ServiceDate=1951|1961

[Variant2] #UK
#Scrapped in 1978.
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=ran_37.png
#ResourcesEmblemFolder=ships/materials/emblem/
#EmblemTexture=ae-26
#ResourcesLiveryFolder=ships/rn_dd_c-class/
#LiveryTexture=usn_ae_kilauea_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_australia
Nation=Australia
ServiceDate=1950|1960

