[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
#AllVariantsAreOfSameNation=False //Speeds up nation sorting. Only needed if there is more then 1 nation variants. Default is 'true'
NumberOfVariants=21

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet
ServiceDate=1952

[Variant1]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet

[Variant2]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet

[Variant3]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet

[Variant4]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet

[Variant5]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet

[Variant6]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet

[Variant7]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet

[Variant8]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet

[Variant9]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_soviet
Nation=Soviet

#Indonesia

[Variant10] #Poland
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia

[Variant11] #Syria
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia

[Variant12] #North Vietnam
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia

[Variant13] #DDR
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia

[Variant14] #Egypt
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia

[Variant15] #Cuba
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia

[Variant16] #Poland
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia

[Variant17] #Syria
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia

[Variant18] #Syria
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia

[Variant19] #Syria
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia

[Variant20] #Syria
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia

[Variant21] #Syria
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_indonesia
Nation=Indonesia