#Dot: This file begs for refactor...
[LanguageResources]
Unknown=Unknown Group
SG_ESM=ESM
SG_ESM_Mast=ESM Mast
[SystemNames]
# ***********************************************************************************************
#                                          Main SYSTEMS
# ***********************************************************************************************
CIC=CIC
Bridge=Bridge
MainPowerSystem=Engine
Engine=Engine

Propulsion=Propulsion
PropulsionSystem1=Propulsion
PropulsionSystem2=Propulsion
PropulsionSystem3=Propulsion
PropulsionSystem4=Propulsion

Rudder=Rudder
RudderSystem1=Rudder
RudderSystem2=Rudder
RudderSystem3=Rudder
RudderSystem4=Rudder

BowPlanes=Bow Planes
DepthRudderSystem1=Bow Planes
SternPlanes=Stern Planes
DepthRudderSystem2=Stern Planes

Pumps=Pumps
Hangar=Hangar
FlightDeck=Flight Deck

# ***********************************************************************************************
#                                          Sensor SYSTEMS
# ***********************************************************************************************
#======================================== Generic ========================================
#---------------------------------------- Visual ----------------------------------------
#---------------------------------------- Radar ----------------------------------------
SurfaceSearchRadar=SurfaceSearchRadar
#---------- Surface ships ----------
#---Air/Air&Surface---
SA-Radar=SA-Radar|The SA Radar is a World war 2 early radar used for basic surface and air detection.
LW08=LW08|The JUPITER/LW 08 2D-early warning radar performs long-range air surveillance on board medium and heavy-tonnage ships. JUPITER/LW 08 operates in D-Band, and is available with a cost-effective fully solid-state transmitter. The antenna is mounted on a lightweight hydraulically stabilised platform (roll and pitch).
DA-05=DA-05|The DA-05 is Dutch 2D-early warning radar able to spot Air and Surface targets up to a range of 237 kilometers,it operates in the S-Band
LW-02=LW-02|The LW-02 is a long range air surveillance radar operating in the L band.
Type277Q=Type 277Q|The Type 277 was a surface search and secondary aircraft early warning radar used by the Royal Navy and allies during World War II and the post-war era. It was a major update of the earlier Type 271 radar, offering much more power, better signal processing, new displays, and new antennas with greatly improved performance and much simpler mounting requirements.
Type 1022=Type 1022|The Type 1022 is a long-range frequency synthesiser-driven Traveling-wave tube (TWT) radar with pulse-to-pulse coherence. It was developed as a replacement for the Royal Navy’s Type 965 surveillance radar. Long-range performance is aided by the use of a high mean-power TWT in the transmitter.
Type_965=Type 965|The Type 965 was a VHF band long-range early warning suveillance radar, designed primarily to be fitted in destroyers and frigates. Type 965 used the AKE-2 “double-bedstead” antenna.
Type 978=Type 978|Type 978 was operating in X band surface warning and navigation radar for British destroyers and frigates. This radar replaced the earlier Type 277Q. Later it was also replaced by Type 1006.
Type_993=Type 993|Type 993 is a short-range, general-purpose radar fitted in several older frigate classes. The Type 993 is used for air and surface search, and for target designation. Its antenna is a "quarter cheese," a shape that resembles a quarter of a cheese wheel; this configuration prevents the feed horn from obstructing the main radar beam. 
Type 984=Type 984|Type 984 radar was a British radar system introduced in the mid-1950s. It was a rotating mechanically stabilized 3D S band radar, measuring longitudinal position, latitudinal position, as well as target altitude
SA-Radar=SA-Radar|The SA Radar is a World war 2 early radar used for basic surface and air detection.
LW08=LW08|The JUPITER/LW 08 2D-early warning radar performs long-rangeair surveillance on board medium and heavy-tonnage ships. JUPITER/LW 08 operates in D band, and is available with a cost-effective fully solid-state transmitter. The antenna is mounted on a lightweight hydraulically stabilised platform (roll and pitch).
DA-05=DA-05|The DA-05 is Dutch 2D-early warning radar able to spot Air and Surface targets up to a range of 237 kilometers,it operates in the S-Band
ELM-2228S_AMDR=ELTA ELM-2228S AMDR|The ELTA ELM-2228S AMDR (Automatic Missile Detection Radar) is designed to detect sea-skimming missiles, generate automatic threat alerts and provide an automatic, track-while-scan (more than 100 targets simultaneously) air and surface surveillance capability. It operates in S-Band and X-Band.
SPS-49(V)5=SPS-49(V)5|A late Cold War upgrade of the baseline SPS-49, this version provided enhanced range performance and reliability over earlier models. Used widely by U.S. and allied navies in the 1980s and early 1990s as a key 2D long-range air search radar.
SPS-49A(V)1=SPS-49A(V)1|An enhanced mid-1990s variant of the long-range 2D air search radar. It introduced Doppler-based target velocity tracking and improved clutter rejection, offering better performance against sea-skimming and low-RCS threats. Commonly fitted during NTU upgrades to legacy ships.
#---Surface only---
ZW06=ZW06|A surface search and navigation radar operating in the X band with a range of 22km.
Type_1002=Type 1002|The Type 1002 is an X-band submarine navigation radar.
Type_1003=Type 1003|The Type 1003 is an improved version of the Type 1002 X-band submarine navigation radar.
ZW06=ZW06|A surface search and navigation radar operating in the X band with a range of 22km.
eu_smart-smk2=SMART-S Mk. 2|The SMART-S (Signaal Multibeam Acquisition Radar for Targeting) is an all-weather 3-D target indication and surveillance radar system intended for all types of naval vessels from fast patrol boats upwards. The SMART system operates in F band

#---Fire Control---

STIR 180=STIR 180|The STIR 180 is a medium to long range weapon fire control radar operating on the X and K band with a max range of 58 kilometers
STIR 240=STIR 240|The STIR 240 is a medium to long range weapon fire control radar operating on the X and K band with a max range of 512 kilometers
Type 903=type 903|4-Inch guns Fire Control Radar
Type_ELM_2221FCS=EL/M-2221GM|Elta EL/M-2221GM fire control radar
STIR 180=STIR 180|The STIR 180 is a medium to long range weapon fire control radar operating on the X and K band with a max range of 36 kilometers
STIR 240=STIR 240|The STIR 240 is a medium to long range weapon fire control radar operating on the X and K band with a max range of 512 kilometers
Type_M44=Type M44|The Hollandse Signaalapparaten M-44 is a naval fire control system and radar/optical director developed in the Netherlands during the Cold War. This equipment was specifically designed to automate, guide, and control the firing of short-range anti-aircraft missiles and anti-aircraft guns.

Local_GFCR=Gun radar
#---------- Submarines ----------
Calypso III=Calypso III|A 70S radar designed for submarine use aboard submarines thanks to its high water pressure recistance.It is relatively short range with only 37 kilometers range.

#---------------------------------------- Aircraft radar ----------------------------------------
Sea Spray=Sea Spray|The Sea Spray Radar APS-705 is a 1970s surface search radar developed for Anti Submarine Warfare,SAR and other maritime missions.Mainly used by helicopters in the ventral or dorsal configuration
Ferranti Blue Fox=Ferranti Blue Fox|The Ferranti Blue Fox was a British multi-role airborne radar designed and built for the Royal Navy by Ferranti Defence Systems in the late 1970's.
Ferranti Blue Parrot=Ferranti Blue Parrot|The Ferranti Blue Parrot was a British surface search radar designed and built for the Royal Navy by Ferranti Defence Systems in the late 1970's.
GEC AI.18 Radar=GEC AI.18 Radar|The AI.18 was a British made Air Interception radar designed to be used by two seater aircraft,it was mainly used by Royal Navy and Air Force fighters and interceptors in the 1970s'.
ASV-19A=ASV-19A|The ASV-19A was a British made surface search radar used by maritime patrol aircraft in the 1970's.
ASV-21=ASV-21|The ASV-21 was a British made surface search radar used by maritime patrol aircraft in the 1970's.It was an upgraded variant of the ASV-19A with more range and accuracy.
ASV-21D=ASV-21D|The ASV-21D was a British made surface search radar used by maritime patrol aircraft in the 1970's.
AN/APS-88=AN/APS-88|Long range surface detection radar used for detecting naval targets at long ranges,mainly used by maritime patrol aircraft
Thorn EMI Searchwater=Thorn EMI Searchwater|Searchwater was a maritime surveillance radar developed by Thorn EMI under project P1149.
Thorn EMI Skymaster=Thorn EMI Skymaster|Skymaster was a british made airborne radar designed to be used on aerial early warning and control platforms like the Nimrod AEW.3 .It had significant range for both aerial and surface targets but was difficult to operate.
ECKO_290=ECKO 290|The ECKO 290 was an aerial weather radar with limited plane spotting capabilities.
FLIR=FLIR|Advanced optics for day and night engagements
EL/M 2022-A=EL/M 2022-A|The ELTA ELM-2022 is designed to provide a cost-effective force multiplier solution for maritime surveillance EEZ-patrol, surface and littoral warfare, search and rescue, drug interdiction and prevention of illegal immigration and terrorist activities, coastguard and fisheries patrol, and image intelligence operations.
EL/M-2032=EL/M-2032|The ELTA ELM-2032 is an Israeli multimode fire control radar for multi-missions fighters. It uses a mechanically tilted slotted waveguide antenna. It is designed for air-to-air, air-to-ground and air-to-sea missions. It has been fitted to F-16s, V/STOL Sea Harriers, F-5E/F Tiger light fighters, F-4 Phantom, Kfir C10s, and Jaguar strike fighters around the world; and was picked for South Korea’s TA-50 and India Tejas lightweight fighters.
AN/APY-2=AN/APY-2|Northrop Grumman AN/APY-2 is a development of APY-1 pulse Doppler radar system installed on E-3 AWACS aircraft. It features the ability to detect and track targets over the horizon and/or flying at low altitude. Plus the ability to incorporates a complete maritime surveillance capability. 
#---------- Containers ----------
#---------------------------------------- Sonar ----------------------------------------

#Ship
Thales-SpherionB=Thales Spherion-B|The Thales Spherion is a medium-frequency hull-mounted sonar providing improved active and passive detection for modern surface combatants. Features digital beamforming and advanced signal processing for enhanced target classification and tracking in littoral and open-water environments. It was installed in the Adelaide-class FFGs.
#Submarine
#Towed
#Dipping
AQS-13E=AQS-13E|The AN/AQS-13 series is a helicopter dipping sonar aboard carrier-based helicopters, and the most widely-used dipping sonar in the west.
#Sonobuoys
Jezebel_Sonar=Jezebel_Sonar|

#---------------------------------------- ESM ----------------------------------------
NS-9003_ESM=Elisra NS-9003|The Elisra NS-9003 is an advanced naval Electronic Support Measures (ESM) and Radar Warning Receiver (RWR) system. Its primary mission is to detect, intercept, classify, and precisely locate enemy radar emissions before the host ship is targeted or compromised.
C-Pearl_ESM=C-Pearl-DV|The Rafael C-Pearl-DV is a modern digital electronic support measures (ESM) suite providing wideband detection, accurate emitter classification, and high-precision bearing data. Fully integrated into the ship’s combat system and data links, replacing legacy SLQ-32(V) systems during FFG upgrades.
EW-1017=Loral EW-1017 Yellow Gate|The Loral EW-1017 "Yellow Gate" system is a classic and historic Electronic Support Measures (ESM) system that played a crucial role in the British Air Force (RAF). At its core, the Yellow Gate used the architecture and processors of a Radar Warning Receiver (RWR), but the software and libraries were extensively reprogrammed to convert it into a broadband tactical ESM search system.
#---------------------------------------- ECM ----------------------------------------
#---------------------------------------- MAD ----------------------------------------
#---------------------------------------- Laser Designator ---------------------------
# ***********************************************************************************************
#                                          WEAPON SYSTEMS
# ***********************************************************************************************
Hardpoint=Hardpoint
BombBay=Bomb Bay
VesselChaff=Chaff
# ------------------ ASM -----------------
Exocet_quadMM40=MM40|Exocet MM40|Quad launcher variant for MM-40 Missile.
# --------------- Torpedoes ---------------
MTLS=MTLS|324mm Magazine torpedo launch system| The Magazine Torpedo Launch System is a lightweight torpedo launch system commonly used in the Type 23 frigates. The system employs a modular, internally installed design that protects the tubes and crew within the hull, and deploys the ejectors through pneumatic doors only at the moment of firing. The tubes are integrated directly into the ship's torpedo magazine.
# --------------- SAM ---------------
SeaWolf_VLS=GWS VLS|Seawolf-VLS|VLS variant of the GWS25.
# ***********************************************************************************************
#                                          Magazine SYSTEMS
# ***********************************************************************************************
# ------------------ SAM ------------------
SAM_Magazine=SAM Magazine
# ---------- Anti-ship Missilies ----------
# ---------- Anti-sub  Missilies ----------
# ------------------ RBU ------------------
# --------------- Torpedoes ---------------
TorpedoMagazine=Torpedo magazine
TorpedoMagazine_400mm=Torpedo magazine
TorpedoMagazine_533mm=Torpedo magazine
TorpedoMagazine_650mm=Torpedo magazine

# ------------------ Guns -----------------


# ------------------ CIWS -----------------
CIWS_Magazine=CIWS Magazine
# ----------- Noisemakers/Chaff -----------

NoisemakerMagazine=Noisemaker Magazine
# ***********************************************************************************************
#                                          OTHER SYSTEMS
# ***********************************************************************************************
Cargo=Cargo
