#!alias ammunition/b-2_lrasm.ini
[---------- Guidance ----------]
[Guidance]
#========================================= Launch stats ============================================================
MaxLaunchRange=550.0                   // Maximum launch range in nautical miles