#!/usr/bin/env python3
"""Render both load-order views from the order the PC installer actually uses."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INSTALLED_STATUSES = {"active", "deprecated", "wip"}


def main():
    catalog = json.loads((ROOT / "data/mod-catalog.json").read_text(encoding="utf-8"))
    mods = {m["workshop_id"]: m for m in catalog["mods"]
            if m.get("status") in INSTALLED_STATUSES}
    tokens = [line.strip() for line in (ROOT / "data/load-order.tokens.txt")
              .read_text(encoding="utf-8-sig").splitlines()
              if line.strip() and not line.lstrip().startswith("#")]
    if len(tokens) != len(set(tokens)):
        raise SystemExit("Duplicate load-order tokens")
    if not tokens or tokens[0] != "SEST_Integration":
        raise SystemExit("SEST_Integration must be first")
    if set(tokens[1:]) != set(mods):
        raise SystemExit(f"Load order/catalog mismatch: missing={sorted(set(mods) - set(tokens[1:]))}; "
                         f"unexpected={sorted(set(tokens[1:]) - set(mods))}")

    lines = ["# Full load order", "",
             f"{len(mods)} locally observed Workshop mods plus SEST Integration "
             f"({len(tokens)} entries; {len(catalog['local_packs'])} SEST source packs consolidated).", "",
             "Generated by `tools/generate_load_order.py` from `data/load-order.tokens.txt` "
             "and `data/mod-catalog.json`. Edit those inputs, then regenerate both this page "
             "and `data/load-order.preview.txt`.", "",
             "Higher entries win file conflicts. SEST Integration must stay first. "
             "This is the reconciled PC inventory, not a live Steam account subscription count. "
             "See `workshop-inventory-20260916.md` for evidence and snapshot limitations.", ""]
    preview = ["# Mod Manager order preview — data/load-order.tokens.txt",
               "# Generated by tools/generate_load_order.py; names from the catalog.", ""]
    for n, token in enumerate(tokens, 1):
        mod = mods.get(token)
        name = mod["title"] if mod else "SEST Integration Pack"
        note = mod.get("load_order", "") if mod else "Must stay above every Workshop mod."
        lines.append(f"{n}. **{name}** (`{token}`)" + (f" — {note}" if note else ""))
        preview.append(f"{n:4}. {token:<17} {name}")
    (ROOT / "docs/load-order-full.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (ROOT / "data/load-order.preview.txt").write_text("\n".join(preview) + "\n", encoding="utf-8")
    print(f"Generated both load-order views: {len(tokens)} entries")


if __name__ == "__main__":
    main()
