[Language_en]
Name=Ultimate Missile Workshop
Description=MUST BE ABOVE ALL IN MODLIST	This mod will rework many mod and systems missiles with kinematic mechanic and general balance
[Language_ru]
Name=Ultimate Missile Workshop
Description=ДОЛЖЕН БЫТЬ ВЫШЕ ВСЕХ В СПИСКЕ	Этот мод изменяет параметры многих модовых ракет и систем под механику кинематики и создание общего баланса
[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.7.10