[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=1

[Default]
Nation=Australia
ResourcesLiveryFolder=aircraft/AH1G/
LiveryTexture=Aussie_CobraAH1G.png
SpecularTexture=Aussie_CobraAH1G_spec.png
# nations are referenced in the layout.ini file:
Nation=Australia
ServiceDate=1971|1981

[Squadron1] #No. 9 Squadron RAAF
ResourcesSerialnumberFolder=aircraft/usmc_ah-1t/modex/
SerialNumberPrefix=
SerialnumberTextures=730,731,732,733,734,735,736
#ResourcesEmblemFolder=aircraft/usmc_ah-1t/
EmblemTexture=
ResourcesLiveryFolder=aircraft/AH1G/
LiveryTexture=Aussie_CobraAH1G.png
SpecularTexture=Aussie_CobraAH1G_spec.png
# nations are referenced in the layout.ini file:
Nation=Australia