[General]
SerialnumberReferences=Serial
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=3

[Default]
#ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
#SerialnumberTextures=modex_tni_au.png
ResourcesLiveryFolder=aircraft/iaf_tu-16/
LiveryTexture=iaf_tu-16.png
FlagTexture=flag_indonesia.png
# nations are referenced in the layout.ini file:
Nation=Indonesia
ServiceDate=1961|1970

[Squadron1]
#ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
#SerialnumberTextures=modex_tni_au.png
ResourcesLiveryFolder=aircraft/iaf_tu-16/
LiveryTexture=iaf_tu-16.png
FlagTexture=flag_indonesia.png
# nations are referenced in the layout.ini file:
Nation=Indonesia
ServiceDate=1961|1970

[Squadron2]
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=wp_num_black_001,wp_num_black_002,wp_num_black_003,wp_num_black_004,wp_num_black_005,wp_num_black_006,wp_num_black_007,wp_num_black_008,wp_num_black_009,wp_num_black_010,wp_num_black_011,wp_num_black_012,wp_num_black_013,wp_num_black_014,wp_num_black_015,wp_num_black_016,wp_num_black_017,wp_num_black_018,wp_num_black_019,wp_num_black_020
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft\wp_tu-16\eaf_camo\
LiveryTexture=wp_tu-16_tx
SpecularTexture=wp_tu-16_spec
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Egypt
ServiceDate=1962|1975

[Squadron3]
ResourcesSerialnumberFolder=aircraft/materials/numbers/
SerialNumberPrefix=
SerialnumberTextures=wp_num_blue_001,wp_num_blue_002,wp_num_blue_003,wp_num_blue_004,wp_num_blue_005,wp_num_blue_006,wp_num_blue_007,wp_num_blue_008,wp_num_blue_009,wp_num_blue_010,wp_num_blue_011,wp_num_blue_012,wp_num_blue_013,wp_num_blue_014,wp_num_blue_015,wp_num_blue_016
ResourcesEmblemFolder=
EmblemTexture=
ResourcesLiveryFolder=aircraft\wp_tu-16\nmf\
LiveryTexture=wp_tu-16_tx
SpecularTexture=wp_tu-16_spec
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=Soviet
ServiceDate=1955|1972

