[General]
SerialnumberReferences=
EmblemReference=Emblem
NationFlagReference=Flag19
NumberOfSquadrons=1

[Default]
Nation=NewZealand
ServiceDate=1966|1998

[Squadron1]#HMS Leander
ResourcesFlagFolder=
FlagTexture=
# nations are referenced in the layout.ini file:
Nation=NewZealand