; SolidRocket_MediumLarge - native Sea Power INI; 1 m = 0.0148809375 units
[Main]
Duration=40
Loop=False
Prewarm=False
StartDelay=0
StartLifetime=0.23
StartSpeed=0
StartSize=0.0065476125|0.00922618125
StartRotation=0|6.283185
StartColor=1,0.85,0.63,0.09
GravityModifier=0
SimulationSpace=Local
SimulationSpeed=1
ScalingMode=Shape
PlayOnAwake=True
EmitterVelocityMode=Custom
CustomVelocity=0,0,0
MaxParticles=48
StopAction=None
CullingMode=AlwaysSimulate

[Emission]
RateOverTime=160
RateOverDistance=0

[Shape]
ShapeType=Circle
Radius=0.00017857125
Arc=360
ArcMode=Random
Position=0,0,0
Rotation=0,0,0
Scale=1,1,1
AlignToDirection=False

[VelocityOverLifetime]
X=0
Y=0
Z=-0.238095
Space=Local
SpeedModifier=1

[ColorOverLifetime]
Color=gradient(0:1,1,1,0/0.12:1,1,1,1/0.55:1,1,1,0.7/1:1,1,1,0)

[SizeOverLifetime]
SeparateAxes=False
Size=curve(0:0.55/0.5:1/1:1.2)

[Renderer]
RenderMode=Billboard
Material=effects/particle materials/aerial_explosion 2
SortMode=Distance
SortingFudge=0
MinParticleSize=0
MaxParticleSize=1
Alignment=View
ShadowCastingMode=Off
ReceiveShadows=False
LightProbeUsage=Off
ReflectionProbeUsage=Off

[Noise]
Strength=0.000372023438
Frequency=1
OctaveCount=1
ScrollSpeed=0.25
Damping=True
Quality=Low

[TextureSheetAnimation]
Mode=Grid
NumTilesX=8
NumTilesY=6
Animation=WholeSheet
RowMode=Custom
RowIndex=0
TimeMode=Lifetime
StartFrame=0
Cycles=1
FrameOverTime=curve(0:0/1:0.7)
