; SolidRocket_MediumLarge - native Sea Power INI; 1 m = 0.0148809375 units
[Main]
Duration=44
Loop=False
Prewarm=False
StartDelay=0
StartLifetime=10|14
StartSpeed=0
StartSize=0.029761875|0.0446428125
StartRotation=0|6.283185
StartColor=1,1,1,0.35
GravityModifier=0
SimulationSpace=World
SimulationSpeed=1
ScalingMode=Shape
PlayOnAwake=True
EmitterVelocityMode=Transform
CustomVelocity=0,0,0
MaxParticles=10000
StopAction=None
CullingMode=AlwaysSimulate

[Emission]
RateOverTime=700
RateOverDistance=0

[Shape]
ShapeType=Box
Radius=0
Arc=360
ArcMode=Random
Position=0,0,-0.29761875
Rotation=0,0,0
Scale=0.0017857125,0.0017857125,0.5952375
AlignToDirection=False

[VelocityOverLifetime]
X=0
Y=0
Z=-0.00223214062
Space=Local
SpeedModifier=1

[ColorOverLifetime]
Color=gradient(0:1,1,1,0.3/0.002:1,1,1,0.65/0.03:1,1,1,1/0.6:1,1,1,0.5/1:1,1,1,0)

[SizeOverLifetime]
SeparateAxes=False
Size=curve(0:1/0.015:2/0.15:5/0.6:10/1:16)

[Renderer]
RenderMode=Billboard
Material=effects/weapons/materials/fx_boostersmoke2
SortMode=Distance
SortingFudge=0
MinParticleSize=0
MaxParticleSize=1
Alignment=View
ShadowCastingMode=Off
ReceiveShadows=False
LightProbeUsage=Off
ReflectionProbeUsage=Off

[Noise]
Strength=0.0029761875
Frequency=1
OctaveCount=2
ScrollSpeed=0.25
Damping=True
Quality=Low

[TextureSheetAnimation]
Mode=Grid
NumTilesX=8
NumTilesY=16
Animation=WholeSheet
RowMode=Custom
RowIndex=0
TimeMode=Lifetime
StartFrame=0
Cycles=1
FrameOverTime=curve(0:0.46/0.5:0.7/1:0.95)

[SmokeTrail]
SpacingMeters=2.5
