[Shader]
Path=Marmoset/Occlusion/Bumped Specular IBL

#[Properties]
_Color=Color,{*}808080ff
_SpecColor=Color,{*}ffffffff
_SpecInt=Float,1.0
_Shininess=Float,6.5
_Fresnel=Float,0.75

[Textures]
_MainTex=aircraft/Wessex/Variant1/Wessex_paintshop_DefaultMaterial_AlbedoTransparency.png
_SpecTex=aircraft/Wessex/Variant1/Wessex_paintshop_DefaultMaterial_SpecularSmoothness.png
_BumpMap=aircraft/Wessex/Variant1/Wessex_paintshop_DefaultMaterial_Normal.png
