[LoadoutNames]
# ------------- F-35A Weapon Systems ------------- #
# ------------- Empty/Ferry ------------- #
Ferry=Ferry                                // Maximum fueltanks, no weapons, except guns and chaff

# ------------- Air to Air loadouts ------------- #
AirToAir=Air to Air                        // Standard Air to Air loadout for the type
AirToAirStealth=Air-to-air (Internal Only)

# ------------- Air to Surface loadouts ------------- #
Strike=Strike                              // Dumb bombs in 1 salvo
StrikeStealth=Close Air Support (Internal Only)
# StrikePrecision=Strike GBU-53 Precision
StrikeLongRange=Strike Long Range          // Same as Strike but less weapons, more fuel
StrikeLongRangeStealth=Joint Strike Missile (Internal Only)

# ------------- Air to Surface Ship loadouts ------------- #
AntiShip=Anti Ship                         // Most vague loadout. Can include anything from dumb bombs to medium-range missilies
AntiShipHeavy=Anti Ship Heavy              // Designed to mark heavy anti-ship bombers like Tu-22 and Tu-16 and small planes with most weapons

#--------------- SEST RAAF F-35A JATM ----------------
Intercept260Stealth=SEST Intercept Stealth (AIM-260)
Intercept260=SEST Intercept (6x AIM-260 int)
Intercept260Beast=SEST Intercept Beast (10x AIM-260)
Malice424=SEST Intercept MALICE (2x AIM-424 int)
