[weeb_aesa_radar]
#Users: the f-2a :pekohappy:
Kind=Radar
Type=DirectedSearch                    // Classes can be "DirectedSearch", "Search", "Targeting"
HasDataLink=True                      // true means the sensor data will be used for the entire task force via data link, false local use only
Role=AirAndSurface                     // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate                        // Can be "Illuminate", "RadioCommand"
TargetChannels=1                       // if applicable number of targets it can track simultaneously
WeaponChannels=2                       // if applicable number of weapons (missiles) it can guide simultaneously
CanDetectLandTargets=True              // True means the radar can see ground objects
ViewArcs=-60,60|-60,60                 // pair of values left to | is horisontal left-right angles of vision, second pair is down-up vertical angles
LookDownMultiplier=0.75                // multiplier that applies to max radar range when target is projected on terrain/sea background, default is 1.0
MinRange=0.1                           // min range in km
MaxRange=185.2                         // max range in km
MinAltitude=0                          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=30480                      // max altitude in meters, relevant for air, unused for surface
RangeResolution=10.0                   // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=0.8                          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=55.0                              // gain in dB on the sensor
Frequency=X-Band                       // frequency band
PeakPower=10                         // output peak power in kW

[spaam-4]
#J/APG-1 guidance mode for AAM-4
#Users: jp_f-2a :pekopleased:
Kind=Radar
Type=Targeting         // Classes can be "DirectedSearch", "Search", "Targeting"
HasDataLink=False      // true means the sensor data will be used for the entire task force via data link, false local use only
Role=Air               // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=10       // if applicable number of targets it can track simultaneously
WeaponChannels=10       // if applicable number of weapons (missiles) it can guide simultaneously
CanDetectLandTargets=True              // True means the radar can see ground objects
ViewArcs=-60,60|-60,60                 // pair of values left to | is horisontal left-right angles of vision, second pair is down-up vertical angles
LookDownMultiplier=0.75                // multiplier that applies to max radar range when target is projected on terrain/sea background, default is 1.0
MinRange=0.1                           // min range in km
MaxRange=185.2                         // max range in km
MinAltitude=0                          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=30480                      // max altitude in meters, relevant for air, unused for surface
RangeResolution=10.0                   // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=0.8                          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=55.0                              // gain in dB on the sensor
Frequency=X-Band                       // frequency band
PeakPower=10                         // output peak power in kW

[burger_aesa_radar]
#Users: the burger f-2a >250yearsyoung.png
Kind=Radar
Type=DirectedSearch                    // Classes can be "DirectedSearch", "Search", "Targeting"
HasDataLink=True                      // true means the sensor data will be used for the entire task force via data link, false local use only
Role=AirAndSurface                     // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate                        // Can be "Illuminate", "RadioCommand"
TargetChannels=1                       // if applicable number of targets it can track simultaneously
WeaponChannels=2                       // if applicable number of weapons (missiles) it can guide simultaneously
CanDetectLandTargets=True              // True means the radar can see ground objects
ViewArcs=-60,60|-60,60                 // pair of values left to | is horisontal left-right angles of vision, second pair is down-up vertical angles
LookDownMultiplier=0.75                // multiplier that applies to max radar range when target is projected on terrain/sea background, default is 1.0
MinRange=0.1                           // min range in km
MaxRange=185.2                         // max range in km
MinAltitude=0                          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=30480                      // max altitude in meters, relevant for air, unused for surface
RangeResolution=10.0                   // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=0.8                          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=55.0                              // gain in dB on the sensor
Frequency=X-Band                       // frequency band
PeakPower=10                         // output peak power in kW

[spamraam]
#AN/APG-80 guidance mode for AMRAAM
#Users: usaf_f-2a :umariamerinya:
Kind=Radar
Type=Targeting         // Classes can be "DirectedSearch", "Search", "Targeting"
HasDataLink=False      // true means the sensor data will be used for the entire task force via data link, false local use only
Role=Air               // Role can be "Surface", "Air", "AirAndSurface"
Mode=Illuminate        // Can be "Illuminate", "RadioCommand"
TargetChannels=10       // if applicable number of targets it can track simultaneously
WeaponChannels=10       // if applicable number of weapons (missiles) it can guide simultaneously
CanDetectLandTargets=True              // True means the radar can see ground objects
ViewArcs=-60,60|-60,60                 // pair of values left to | is horisontal left-right angles of vision, second pair is down-up vertical angles
LookDownMultiplier=0.75                // multiplier that applies to max radar range when target is projected on terrain/sea background, default is 1.0
MinRange=0.1                           // min range in km
MaxRange=185.2                         // max range in km
MinAltitude=0                          // min altitude in meters, relevant for air, unused for surface
MaxAltitude=30480                      // max altitude in meters, relevant for air, unused for surface
RangeResolution=10.0                   // defines the minimum range where two targets behind can be recognized as two; in meters
BeamWidth=0.8                          // defines the beam width in degrees for BearingResolution >= 2*Dist*sin(BeamWidth/2)
Gain=55.0                              // gain in dB on the sensor
Frequency=X-Band                       // frequency band
PeakPower=10  