[General]
# R-17 Elbrus (SS-1C Scud-B)
# Users: a lot
Type=Missile                           // can be Projectile, Missile, Torpedo
TargetType=ASuW                         // can be AAW, ASuW, ASW
LandAttackCapability=All  // can be  All, Installation, Mobile, ShoreTargetsOnly

Mass=5385                              // in kg. Used for aircraft
AmmoPoints=16155                        // For Supply System. Defines "price" of ammunition based on mass, volume, complexity and availability

#Determines if this weapon has "early service" with low availability, must be earlier than 'FOCDate' and is usually the first production year (LRIP) or first year this weapon was deployed in service, specify ONLY this date in the case of prototype systems that never became fully operable
#IOCDate=19XX						   // Year, shows in Unit Reference. If set, defines if the weapon is able to be used in combat before it is fully operational (before FOCDate)

#Specifies the first year this weapon is widely deployed, and when it becomes fully operational without serious availability/operability concerns
FOCDate=1964						   // Year, shows in Unit Reference, defines first year this weapon is commonly available to be selected. Default/unset: always available


DefaultCameraDistance=0.6
MinCameraDistanceForeAft=0.29
MinCameraDistanceBroadside=0.29
CameraPivotHeight=0.0

DecalClass=SAMImpacts  // referenced in effects/decals.ini

FrontalArea=0.8901
SideArea=9.96
BottomArea=9.96
[SensorData]
#Visual
VisualIdentificationRange=4  // at what range in nm this unit can be visually identified
IRSignature=Large
# Radar related (RCS => radar cross section)
RCS=10
# Sonar related
# Transient
TransientRCS=Large                    // Transient visibility on the radar
TransientVisualIdentificationRange=5  // Transient can be visually detected at this distance in nmi
TransientBaseNoise=200                // In db

[---------- Warhead Data ----------]
#Warhead Types:
#0 = Blast Fragmentation
#1 = Armor Piercing
#2 = HEAT
#3 = Illumination
#4 = Cluster
#5 = Runway Cratering

# Fuze Types: 0 = Impact Fuze, 1 = Proximity Fuze
[WarheadData]
WarheadType=0
Power=100
ImpactSize=150                    // Impact size, can be small, medium, large, verylarge
Penetration=Always                    // can be minor, moderate, heavy, always
[---------- Guidance ----------]
# Guidance Types:
# 0 = None
# 1 = IR Homing
# 2 = Semi-Active Radar Homing
# 3 = Active Radar Homing
# 4 = Anti-Radiation Homing
# 5 = Laser-Homing
# 6 = TV-Homing
# 7 = Active Sonar Homing
# 8 = Passive Sonar Homing
# 9 = Wake Homing
[Guidance]
GuidanceType=0
MidCourseCorrection=0                  // 0 = None, 1 = Radio Command, 2 = Wire Guided, 3 = Datalink midcourse (used with SARH or ARH)
InitialFlightPhaseDuration=10.0         // time in seconds where the missile moves straight on without guiding
#======================================== Flight Profile ===========================================================
#flight phase 1: loft-----------------------------------------------------------------------------------------------------------------
#1st stage of missile flight - high altitude
MaxLoftAngle=90.0                      // Climb angle for initial loft
MaxLoftAlt=280000.0                     // in feet. Maximum altitude for lofting
#flight phase 2: sea skimming---------------------------------------------------------------------------------------------------------
#2nd stage of missile flight - low altitude
#flight phase 3: final flight phase (e.g. terminal popup)------------------------------------------------------------------------------
#Pop-Up. Missile climbs to higher altitude before activating the seeker. Or in some cases going even lower
#flight phase 4: terminal approach------------------------------------------------------------------------------------------------------
#Last stage - missile activates seeker and locks on target
TerminalApproachDist=0.1              // in N. miles. Recommended to set this distance slightly less than the seeker range. For SAM better set it to max value, 1000 miles is enough
#=========================================  Kinematics  ============================================================
ApplyKinematics=True                   // If we should use full kinematics rules. If this is true, we will only use kinematics 
#for acceleration, instead of calculating acceleration time based on the max velocity. MaxVelocity is still used, since missile stalls at 1/4 max velocity or 500 knots, whichever is less
MaxVelocity=2500.0                     // Maximum speed in knots
MaxTurnRate=5.0                       // Maximum turnrate in degrees per second
MaxTurnG=10                       // Maximum G-limit of missile turns
AccelerationTime=5                  // Burn time for initial booster burn
Acceleration=1.8                      // Gs of acceleration in initial burn
SustainerAccelerationTime=90            // Time of sustainer burn. -1 if there is no sustainer burn
SustainerAcceleration=1.8               // Acceleration of sustainer burn. -1 if there is no sustainer
TypicalTargetAlt=0					// Sets the estimated target altitude (in feet) at which the missile will reach maximum firing range. Use 0 if the target is a surface unit. Default: 50000
TypicalFiringAlt=0				// Sets the estimated firing altitude (in feet) at which the missile will reach maximum firing range. Use 0 for a surface launch missile. Default: 50000
TypicalLaunchVelocity=0				// Sets the estimated firing speed (in knots) at which the missile will reach maximum firing range. Use 0 for a surface launch missile. Default: 1000
DragCoefficient=0.5               // Drag coefficient. 0 for no drag, 1 for default drag, more for more drag. Defaults to -1, where we calculate it based on missile max range
VelocityBleed=0.8                      // Missile will eventually slowdown to MaxVelocity*VelocityBleed at the end of its lifetime
MaxFlightTime=420               // How long until missile entirely fails, acts as a hard limit based on batteries, etc. Default: unlimited
LiftFactor=0.0001				// default is 0.005, defines the extra drag at high altitudes/low speeds due to the increase AOA from lift loss, lower values improve lift characteristics and are less impacted by altitude
OptimizeLoftAlt=False
BallisticLoft=True
TimeLimited=True
TerminalLoft=True
#========================================= Launch stats ============================================================
MinLaunchRange=81.0                    // Minimum launch range in nautical miles
MaxLaunchRange=162.0                   // Maximum launch range in nautical miles
WarheadReliability=0.97                // Chance that warhead will detonate upon hit
#========================================     Seeker     ===========================================================
CircularErrorRadiusInstallation=450     // Circular error vs 'Installation' land units
#Homing
#Misc Guidance Properties
#InsDrift=1							   // In degrees per minute of unguided flight. Shifts the weapon's nose by this amount per minute whenever the missile is not being actively guided (RC, Wire, tracking a target with its seeker)
# cass: meant for making missiles drift when they lose their target, blocked for now due to unresolved issues
#ECCM
#Search params for torpedoes
#SelfDestruct
SelfDestructDelay=600.0                  // delay in seconds for self destruction
SelfDestructAfterTargetGone=False      // in case the target is destroyed and therefor lost, shall the missile be destroyed too?

[---------- Mesh definitions----------]
[Models]
ResourcesFolder=ground objects/wp_scud_tel/
ResourcesRoot=wp_scud_tel
ResourcesMesh=wp_ss-1c
ResourcesMeshForLaunch=wp_ss-1c_onrail
ResourcesMeshSwitchTime=0  // time in seconds after launch to switch from launch mesh to main mesh
ResourcesMaterial=wp_scud_mat
############################################################
[---------- Effects ----------]
# Effects are referenced in /effects/effects.ini when using an effects class
# e.g. either:
# BoosterEffect=effects/weapons/emitters/submarine_torpedo_launch
# or
# BoosterEffectClass=BoosterEffects  // this will be referenced in effects.ini

# possible values (optionally with suffix "Class")
# BoosterEffect, InFligheEffect, UnderwaterTrail, ParachuteEffect, TorpedoSurfaceSplash, HitWaterSplash
# DebrisTrail, DebrisSplash, SmallFireEffect, ModerateFireEffect, SevereFireEffect,
# HitAirExplosion, HitShipExplosion, HitObjectExplosion, HitGroundExplosion, HitDefaultExplosion
[Particles]
DudExplosionClass=SmallFlakExplosions
BoosterEffect=effects/weapons/emitters/sam_medium_effect
BoosterEffectPosition=0,0,-0.070
InFlightEffectClass=DefaultMissileInflightEffect
InFlightEffectPosition=0,0,-0.025
InFlightEffectStartTime=2.0  // in seconds, after that the Inflight Effect will be played if available

SustainerEffect=effects/weapons/emitters/missile_sustainer_large_effect
SustainerEffectPosition=0,0,-0.065
SustainerEffectStartTime=2

HitDefaultExplosion=effects/explosions/emitters/ballistic_missile_hit
HitShipExplosion=effects/explosions/emitters/ballistic_missile_hit
HitAirExplosionClass=LargeMissileExplosions

HitWaterSplashClass=LargeWaterSplashes
HitGroundExplosion=effects/explosions/emitters/ballistic_missile_hit

[---------- Colliders ----------]
[Colliders]
# creates the hit box for this object
Collider=col_main

[col_main]
Collider=Box
Position=0,0,0
Rotation=0,0,0
Scale=0.005,0.005,0.043
