[---------- Dipping sonars ----------]
[HQS-103]
#Users: SH-60J
Kind=Sonar
IsActiveOnly=False                   // True means no passive detection
HasDataLink=True                     // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=8.0                // TODO in degrees
RangeResolution=180.0                // TODO defines the minimum range where two targets behind can be recognized as two; in meters
Gain=32                              // in db, gain of the sensor
ActiveRange=12                       // in km
PassiveRange=14                      // in km
ActiveGain=16                        // in db, gain of the active sensor
OutputPower=216                      // Active sensor output power in dB, unused for passive ones
Type=Dipping                         //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=MF                    // TODO ????
SignalProcessing=1
MaxConvergenceZones=0				// maximum number of CZs this sonar can detect out to, 0 if incapable of using CZ/BB effects


[HQS-104]
#Users: SH-60K
Kind=Sonar
IsActiveOnly=False                   // True means no passive detection
HasDataLink=True                     // true means the sensor data will be used for the entire task force via data link, false local use only
AngularResolution=5.0                // TODO in degrees
RangeResolution=50.0                // TODO defines the minimum range where two targets behind can be recognized as two; in meters
Gain=40                              // in db, gain of the sensor
ActiveRange=25                       // in km
PassiveRange=24                      // in km
ActiveGain=20                        // in db, gain of the active sensor
OutputPower=220                      // Active sensor output power in dB, unused for passive ones
Type=Dipping                         //Hull: hull mounted sonar, Towed: towed passive sonar, VDS: variable depth active sonar, Dipping: dipping sonar
SonarFrequency=LF                    // TODO ????
SignalProcessing=7
MaxConvergenceZones=0				// maximum number of CZs this sonar can detect out to, 0 if incapable of using CZ/BB effects
