[General]
SerialnumberReferences=Modex,Modex_2,Modex_4
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfSquadrons=5

[Default]
Nation=France

[Squadron1]     #11F
Nation=France
ResourcesSerialnumberFolder=assets/models/aircraft/Etendard/numbers/SUE/white
SerialNumberPrefix=
SerialnumberTextures=8.png,71.png,18.png,7.png,35.png,47.png,19.png,10.png,61.png,15.png,25.png,5.png
ResourcesEmblemFolder=assets/models/aircraft/Etendard/emblems
EmblemTexture=11F.png
FueltankTextures=fr_tank_625c_etendard,assets/models/aircraft/Etendard/textures/11F.png|fr_tank_625l_etendard,assets/models/aircraft/Etendard/textures/11F.png|fr_tank_625c_etendard,assets/models/aircraft/Etendard/textures/11F.png

[Squadron2]     #14F
Nation=France
ResourcesSerialnumberFolder=assets/models/aircraft/Etendard/numbers/SUE/white
SerialNumberPrefix=
SerialnumberTextures=40.png,22.png,17.png,41.png,33.png,51.png,16.png,32.png,58.png,37.png,44.png,27.png,20.png,70.png
ResourcesEmblemFolder=assets/models/aircraft/Etendard/emblems
EmblemTexture=14F.png
#FueltankTextures=fr_tank_625c_etendard,assets/models/aircraft/Etendard/textures/SUE_14F_1.png|fr_tank_625l_etendard,assets/models/aircraft/Etendard/textures/SUE_14F_1.png|fr_tank_625c_etendard,assets/models/aircraft/Etendard/textures/SUE_14F_1.png


[Squadron3]     #17F
Nation=France
ResourcesSerialnumberFolder=assets/models/aircraft/Etendard/numbers/SUE/white
SerialNumberPrefix=
SerialnumberTextures=9.png,55.png,1.png,14.png,62.png,46.png,49.png,39.png
ResourcesEmblemFolder=assets/models/aircraft/Etendard/emblems
EmblemTexture=17F.png
FueltankTextures=fr_tank_625c_etendard,assets/models/aircraft/Etendard/textures/17F.png|fr_tank_625l_etendard,assets/models/aircraft/Etendard/textures/17F.png|fr_tank_625c_etendard,assets/models/aircraft/Etendard/textures/17F.png

[Squadron4]     #Argentina
Nation=Argentina
ResourcesSerialnumberFolder=assets/models/aircraft/Etendard/numbers/SUE/ARA
SerialNumberPrefix=
SerialnumberTextures=212.png,215.png,210.png,208.png,220.png,219.png,213.png,221.png,207.png,209.png,222.png,217.png,214.png,216.png,218.png,206.png,211.png
ResourcesEmblemFolder=assets/models/aircraft/Etendard/emblems
EmblemTexture=EA32.png
ResourcesLiveryFolder=assets/models/aircraft/Etendard/textures
LiveryTexture=SUE_EA32_1.png
#FueltankTextures=fr_tank_625c_etendard,assets/models/aircraft/Etendard/textures/SUE_EA32_1.png|fr_tank_625l_etendard,assets/models/aircraft/Etendard/textures/SUE_EA32_1.png|fr_tank_625c_etendard,assets/models/aircraft/Etendard/textures/SUE_EA32_1.png

[Squadron5]     #Iraq
Nation=Iraq
ResourcesSerialnumberFolder=assets/models/aircraft/Etendard/numbers/SUE/white
SerialNumberPrefix=
SerialnumberTextures=7447.png,7445.png,7449.png,7446.png,7448.png
ResourcesEmblemFolder=assets/models/aircraft/Etendard/emblems
EmblemTexture=
ResourcesLiveryFolder=assets/models/aircraft/Etendard/textures
LiveryTexture=SUE_82Sqn_1.png
#FueltankTextures=fr_tank_625c_etendard,assets/models/aircraft/Etendard/textures/SUE_82Sqn_1.png|fr_tank_625l_etendard,assets/models/aircraft/Etendard/textures/SUE_82Sqn_1.png|fr_tank_625c_etendard,assets/models/aircraft/Etendard/textures/SUE_82Sqn_1.png
