[Language_cn]
Name=飞机与直升机的真实照片
Description=将所有原版与部分模组的飞机与直升机百科图片换成真实的照片。

[Language_en]
Name=Real photos of airplanes and helicopters
Description=Replace all the original and partial modular aircraft and helicopter encyclopedia pictures with real photos.

[Language_ru]
Name=Реальные фотографии самолётов и вертолётов
Description=Заменить все изображения в энциклопедии самолётов и вертолётов оригинальных моделей и некоторых модулей на реальные фотографии.

[Language_ja]
Name=飛行機とヘリコプターの実際の写真
Description=すべてのオリジナルおよび一部のモジュールに含まれる航空機とヘリコプターの百科事典画像を、実際の写真に置き換える。

[Language_fr]
Name=Photos réelles d'avions et d'hélicoptères
Description=Remplacer toutes les images d'encyclopédie des avions et hélicoptères originales ainsi que certaines modules par des photos réelles.

[Language_ko]
Name=비행기와 헬리콥터의 실제 사진
Description=모든 원본과 일부 모듈의 항공기 및 헬리콥터 백과사전 이미지를 실제 사진으로 대체한다.

[Language_de]
Name=Echte Fotos von Flugzeugen und Hubschraubern
Description=Alle Original- und Teile der Modul-Aufnahmen von Flugzeugen und Hubschraubern durch echte Fotos ersetzen.

[Language_es]
Name=Fotos reales de aviones y helicópteros
Description=Cambiar las imágenes de la enciclopedia de aviones y helicópteros, tanto de la versión original como de algunos módulos, por fotografías reales.

[Language_vn]
Name=Hình ảnh thực tế của máy bay và trực thăng
Description=Thay thế tất cả hình ảnh bách khoa toàn thư về máy bay và trực thăng nguyên bản cùng một số mô-đun bằng những bức ảnh thực tế.

[Compatibility]
;ApproximateVersion is the second check and will override all statements below. This checks MAJOR and MINOR match but will accept higher PATCH.
;Would recommend this as a default case for starters.
ApproximateVersion=0.8.0