[AmmunitionNames]

# ---------- Air To Air Missile ---------


# ---------- Anti-radar Missiles ---------


# ---------- Anti-ship Missiles ----------


#-----------Land Strike only missiles---------


#-----------Bombs---------


#-----------Torpedoes---------

usn_mk48_mod8_adcap=MK 48 Mod 8 ADCAP,TI-1,ASW/ASuW Torpedo,The MK 48 Mod 8 is a planned upgrade to the MK 48 ADCAP heavyweight torpedo, featuring APB 6 (Advanced Processor Build 6) software and TI-1 (Technology Insertion 1) hardware improvements. 

# ----------------- Special ----------------

# ----------------- Fueltanks ----------------


-------------------------------------------------------------------------------------------